# Código para generar imágenes con Stable Diffusion 3.5 y Stable Diffusion 3.

El siguiente cuaderno sirve para generar las imágenes necesarias para posteriormente evaluar su generación y para deducir la casa presente en la imagen. Es decir, este código genera las imágenes tras haber generado el RAG la respuesta del usuario. 

Como los medios que tenemos son limitados, en principio no podemos escribir un código con el pipeline completo: escribir pregunta, recibir respuesta y recibir imagen. Como los modelos que utilizamos no caben en la memoria de la A100 de Google Colab, vamos a generar las imágenes en un este cuaderno utilizando las respuesta del RAG, también previamente generadas en otro cuaderno para la asignatura de NLP. De esta forma, el proceso más pesado (el generar las imagenes) se hará una vez, y luego seguiremos con el resto del proyecto.


Como bien sabemos, la idea es generar imágenes haciendo uso de SD-3.5 XL. El prompt utilizado se basará en la respuesta recibida por parte del RAG. No obstante, no todo el mundo dispone que la suscripción de Googla Colab Pro Plus, y por lo tanto, no todo el mundo tiene a mano un GPU A100 con 80 GB de VRAM en el que meter el modelo de SD-3.5 XL. Por eso mismo, a fin de ver la viabildiad del proyecto con menos recursos, se van a generar imágenes con modelos SD más antiguos que requieren de menos recursos. Posteriormente, en otro notebook, evaluaremos que tan buenas son las imágenes de los diferentes modelos.

## ¿Cómo generaremos los prompts para generar imágenes?

Para generar las imágenes, necesitamos un prompt. El problema, es que el prompt que genere la imagen tiene que generarse de forma automática basandose en la respuesta del RAG, pues no tendría sentido que el usuario preguntase algo sobre el libro y luego tuviese que ecribir el prompt para genarar la imagen. Teniendo esto en cuenta, veamos algunos detalles importantes:

- En principal modelo generador será Stable Diffusion 3.5 XL. Este modelo está optimizado para trabajar con 256 tokens como máximo, pero acepta también hasta 512.
- Se hicieron pruebas en otro código y se vió que, según el tokenizer de SD 3.5 XL, un token ocupa de media 3.8 caracteres. Esta información será vital a la hora de crear los promtps.
- En la parte de NLP, se generaron 100 respuestas a 100 preguntas planteadas sobre el libro. El resultado final fue un .json en el cual tenemos varias columnas, entre ellas, evidemente, la pregunta y la respuesta del RAG. Esto será vital para poder generar los prompts.
- En el primer notebook entregado, se ha generado un .json con los chunks de los resúmenes que mejor contestan a las preguntas del RAG. También serán importantes a la hora de generar los prompts.
- De las 100 preguntas, se han elegido, por parte de Javier, 50. Estas son las pregunta que el integrante del grupo considera que son "dibujables", en base a su conocimiento de Juego de Tronos.

Teniendo todo esto en cuenta, veamos como se han generado los prompts:

- Para cada pregunta, se han generado tres prompts diferentes, a fin de hacer pruebas:

    - Los primeros prompts buscan tener 500 caracteres. Estos prompts serán los más cortos, pensando en SD3. Estos prompts se generarán usando la pregunta y la respuesta del RAG.
    - Otros prompts tendrán 1000 caracteres, a fin de ajustarse a los 256 tokens de SD 3.5 XL. Como en el caso anterior, estos prompts también se generan usando la pregunta y la respuesta del RAG.
    - Los últimos prompts tendrán 1960 caracteres, a fin de ajustarse a los 512 tokens de SD 3.5 XL. Estos prompt se generarán usando la pregunta, la respuesta, y el chunk de resumen, a fin de tener mejor contexto.

Estos tres tipos de Prompts los ha generado el integrante del grupo Juan, haciendo uso del clúster de GPUs de Tecnalia, empresa en la que actualmente está haciendo sus práctica. El metodo seguido ha sido el siguiente:

- Ha descargado el modelo de Gemma 4 de 31B de parámetros, el más reciente de Google. 
- Le ha pasado un prompt muy detallado al Gemma, diciendole que tiene que crear los prompts siguiendo una pautas y usando como contexto la pregunta, la respuesta, y en el último caso, el resumen de la escena. 
- Gemma ha devuelto todos los prompts, que se han guardado en un .json. Este código utilizará dicho .json.

Los detalles de este proceso están en el cuaderno dedicado a eso.

Una vez sabemos como se generar los prompts, veamos como generaremos las imágenes:

## ¿Cómo se generarán las imágenes?

Vamos a hacerlo de forma automática, es decir, que se le de a Run en el código y nos genere todas las imágenes que queremos. La idea es generar las 50 imágenes usando la primera tanda de prompts, las siguiente 50 con la siguiente, y así sucesivamenta hasta tener 300 imágenes (6 por pregunta, 3 por modelo).

In [1]:
# ============================================================
# INSTALL
# ============================================================

# Limpieza de posibles restos de Pillow/PIL mezclados
!pip uninstall -y pillow pillow-simd PIL > /dev/null 2>&1

# Reinstalación limpia de Pillow
!pip install -q --no-cache-dir --force-reinstall "pillow==11.3.0"

# Librerías principales
!pip install -q -U \
    diffusers \
    transformers \
    accelerate \
    safetensors \
    sentencepiece \
    protobuf \
    pandas \
    tqdm \
    huggingface_hub

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 303.4 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gradio 5.50.0 requires pandas<3.0,>=1.0, but you have pandas 3.0.2 which is incompatible.

In [2]:
# ============================================================
# DRIVE + HUGGING FACE LOGIN
# ============================================================
from google.colab import drive
drive.mount('/content/drive')

# Opción 1:
# Si quieres, pega aquí tu token de Hugging Face.
# Si ya estás logueado o no hace falta, déjalo en None.
HF_TOKEN = "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"
# HF_TOKEN = "hf_xxxxxxxxxxxxxxxxxxxxxxxxx"

if HF_TOKEN:
    from huggingface_hub import login
    login(HF_TOKEN)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
# ============================================================
# IMPORTS
# ============================================================
import gc
import json
import time
import traceback
from pathlib import Path
from typing import Any, Dict, List

import pandas as pd
import torch
from tqdm.auto import tqdm
from PIL import Image

from diffusers import StableDiffusion3Pipeline

Flax classes are deprecated and will be removed in Diffusers v1.0.0. We recommend migrating to PyTorch classes or pinning your version of Diffusers.
Flax classes are deprecated and will be removed in Diffusers v1.0.0. We recommend migrating to PyTorch classes or pinning your version of Diffusers.

In [4]:
# ============================================================
# CONFIG
# ============================================================

# ---------- Input ----------
PROMPTS_DIR = Path("/content/drive/MyDrive/Proyecto NLP y DL/Imagen_Generacion/prompts_sd3")

DATASETS = [
    {
        "file_name": "prueba_500chars_sd3.jsonl",
        "prompt_col": "prompt_sd3_large",
        "max_sequence_length": {
            "sd35_large": 256,
            "sd3_medium": 256,
        },
    },
    {
        "file_name": "prueba_1013chars_sd3_inicial.jsonl",
        "prompt_col": "prompt_sd3_large",
        "max_sequence_length": {
            "sd35_large": 256,
            "sd3_medium": 256,
        },
    },
    {
        "file_name": "prueba_1960chars_sd3_conResumen.jsonl",
        "prompt_col": "prompt_sd3_large",
        "max_sequence_length": {
            "sd35_large": 512,
            "sd3_medium": 512,
        },
    },
]

# ---------- Output ----------
OUTPUT_ROOT = Path("/content/drive/MyDrive/Proyecto NLP y DL/Imagen_Generacion/generated_images_sd3")

# ---------- Models ----------
MODELS = {
    # Cambia este model_id si en tu notebook actual usas otro distinto
    "sd35_large": {
        "model_id": "stabilityai/stable-diffusion-3.5-large",
        "folder_name": "sd35_large",
    },
    "sd3_medium": {
        "model_id": "stabilityai/stable-diffusion-3-medium-diffusers",
        "folder_name": "sd3_medium",
    },
}

# ---------- Generation params ----------
GEN_CONFIG = {
    "height": 1024,
    "width": 1024,
    "num_inference_steps": 28,
    "guidance_scale": 7.0,
    "negative_prompt": None,
    "base_seed": 1234,
    "num_images_per_prompt": 1,
}

# ---------- Runtime ----------
SKIP_IF_IMAGE_EXISTS = True
USE_CPU_OFFLOAD = True   # recomendado en Colab para ahorrar VRAM
TORCH_DTYPE = torch.float16

# ---------- Order ----------
MODEL_EXECUTION_ORDER = ["sd35_large", "sd3_medium"]

print("Configuración cargada.")
print("PROMPTS_DIR:", PROMPTS_DIR)
print("OUTPUT_ROOT:", OUTPUT_ROOT)

Configuración cargada.
PROMPTS_DIR: /content/drive/MyDrive/Proyecto NLP y DL/Imagen_Generacion/prompts_sd3
OUTPUT_ROOT: /content/drive/MyDrive/Proyecto NLP y DL/Imagen_Generacion/generated_images_sd3

In [5]:
# ============================================================
# HELPERS
# ============================================================

def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)

def clear_memory() -> None:
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
        try:
            torch.cuda.ipc_collect()
        except Exception:
            pass

def to_jsonable(value: Any) -> Any:
    if pd.isna(value):
        return None
    if isinstance(value, Path):
        return str(value)
    if hasattr(value, "item"):
        try:
            return value.item()
        except Exception:
            pass
    return value

def save_json(data: Any, path: Path) -> None:
    ensure_dir(path.parent)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

def safe_name(text: Any, max_len: int = 80) -> str:
    text = str(text)
    cleaned = []
    for ch in text:
        if ch.isalnum() or ch in ("-", "_"):
            cleaned.append(ch)
        else:
            cleaned.append("_")
    cleaned = "".join(cleaned).strip("_")
    cleaned = cleaned[:max_len]
    return cleaned if cleaned else "item"

def load_jsonl(path: Path) -> pd.DataFrame:
    return pd.read_json(path, lines=True)

def build_output_paths(model_alias: str, dataset_file_name: str) -> Dict[str, Path]:
    dataset_stem = Path(dataset_file_name).stem
    base_dir = OUTPUT_ROOT / MODELS[model_alias]["folder_name"] / dataset_stem
    images_dir = base_dir / "images"
    metadata_path = base_dir / "metadata.json"

    ensure_dir(images_dir)

    return {
        "base_dir": base_dir,
        "images_dir": images_dir,
        "metadata_path": metadata_path,
    }

def load_pipeline(model_id: str) -> StableDiffusion3Pipeline:
    print(f"\nCargando modelo: {model_id}")
    start = time.time()

    pipe = StableDiffusion3Pipeline.from_pretrained(
        model_id,
        torch_dtype=TORCH_DTYPE,
    )

    if torch.cuda.is_available():
        if USE_CPU_OFFLOAD:
            pipe.enable_model_cpu_offload()
        else:
            pipe = pipe.to("cuda")

    # Esto ayuda un poco con memoria
    pipe.enable_attention_slicing()

    elapsed = time.time() - start
    print(f"Modelo cargado en {elapsed:.2f} s")
    return pipe

def unload_pipeline(pipe: StableDiffusion3Pipeline) -> None:
    try:
        del pipe
    except Exception:
        pass
    clear_memory()

def generate_one_image(
    pipe: StableDiffusion3Pipeline,
    prompt: str,
    seed: int,
    max_sequence_length: int,
) -> Image.Image:
    device = "cuda" if torch.cuda.is_available() else "cpu"
    generator = torch.Generator(device=device).manual_seed(seed)

    result = pipe(
        prompt=prompt,
        negative_prompt=GEN_CONFIG["negative_prompt"],
        num_inference_steps=GEN_CONFIG["num_inference_steps"],
        guidance_scale=GEN_CONFIG["guidance_scale"],
        height=GEN_CONFIG["height"],
        width=GEN_CONFIG["width"],
        num_images_per_prompt=GEN_CONFIG["num_images_per_prompt"],
        max_sequence_length=max_sequence_length,
        generator=generator,
    )

    return result.images[0]

def generate_dataset(
    pipe: StableDiffusion3Pipeline,
    model_alias: str,
    dataset_cfg: Dict[str, Any],
) -> Dict[str, Any]:
    dataset_path = PROMPTS_DIR / dataset_cfg["file_name"]
    prompt_col = dataset_cfg["prompt_col"]
    max_sequence_length = dataset_cfg["max_sequence_length"][model_alias]

    if not dataset_path.exists():
        raise FileNotFoundError(f"No existe el archivo: {dataset_path}")

    output_paths = build_output_paths(model_alias, dataset_cfg["file_name"])
    images_dir = output_paths["images_dir"]
    metadata_path = output_paths["metadata_path"]

    print("\n" + "=" * 80)
    print(f"Modelo: {model_alias}")
    print(f"Dataset: {dataset_cfg['file_name']}")
    print(f"Prompt column: {prompt_col}")
    print(f"max_sequence_length: {max_sequence_length}")
    print(f"Output dir: {images_dir}")
    print("=" * 80)

    df = load_jsonl(dataset_path)
    print(f"Filas cargadas: {len(df)}")

    if prompt_col not in df.columns:
        raise ValueError(f"La columna '{prompt_col}' no existe en {dataset_path.name}")

    records = []
    ok_count = 0
    error_count = 0
    skipped_count = 0

    for idx, row in tqdm(df.iterrows(), total=len(df), desc=f"{model_alias} | {dataset_cfg['file_name']}"):
        row_dict = {col: to_jsonable(row[col]) for col in df.columns}

        row_id = row_dict.get("id", idx)
        prompt = row_dict.get(prompt_col, None)
        seed = GEN_CONFIG["base_seed"] + int(idx)

        image_name = f"{idx:04d}_{safe_name(row_id)}.png"
        image_path = images_dir / image_name

        record = {
            "id": row_id,
            "row_index": int(idx),
            "source_file": dataset_cfg["file_name"],
            "model_alias": model_alias,
            "model_id": MODELS[model_alias]["model_id"],
            "prompt_column": prompt_col,
            "prompt": prompt,
            "max_sequence_length": max_sequence_length,
            "seed": seed,
            "image_path": str(image_path),
            "status": None,
            "error": None,
            "row_data": row_dict,
        }

        if not isinstance(prompt, str) or not prompt.strip():
            record["status"] = "error"
            record["error"] = "Prompt vacío o no válido"
            records.append(record)
            error_count += 1
            continue

        if SKIP_IF_IMAGE_EXISTS and image_path.exists():
            record["status"] = "skipped_existing"
            records.append(record)
            skipped_count += 1
            continue

        try:
            image = generate_one_image(
                pipe=pipe,
                prompt=prompt,
                seed=seed,
                max_sequence_length=max_sequence_length,
            )
            image.save(image_path)
            record["status"] = "ok"
            ok_count += 1

        except Exception as e:
            record["status"] = "error"
            record["error"] = "{}: {}".format(type(e).__name__, str(e))
            error_count += 1
            print(f"\nError en fila {idx} (id={row_id}): {record['error']}")
            print(traceback.format_exc())

            # Intentar liberar algo de memoria y seguir
            clear_memory()

        records.append(record)

    metadata = {
        "source_file": dataset_cfg["file_name"],
        "model_alias": model_alias,
        "model_id": MODELS[model_alias]["model_id"],
        "prompt_column": prompt_col,
        "max_sequence_length": max_sequence_length,
        "generation_config": {
            "height": GEN_CONFIG["height"],
            "width": GEN_CONFIG["width"],
            "num_inference_steps": GEN_CONFIG["num_inference_steps"],
            "guidance_scale": GEN_CONFIG["guidance_scale"],
            "negative_prompt": GEN_CONFIG["negative_prompt"],
            "base_seed": GEN_CONFIG["base_seed"],
            "num_images_per_prompt": GEN_CONFIG["num_images_per_prompt"],
        },
        "summary": {
            "total_rows": int(len(df)),
            "ok": int(ok_count),
            "errors": int(error_count),
            "skipped_existing": int(skipped_count),
        },
        "records": records,
    }

    save_json(metadata, metadata_path)
    print("\nMetadata guardado en:", metadata_path)
    print("Resumen:", metadata["summary"])

    return {
        "model_alias": model_alias,
        "model_id": MODELS[model_alias]["model_id"],
        "source_file": dataset_cfg["file_name"],
        "total_rows": int(len(df)),
        "ok": int(ok_count),
        "errors": int(error_count),
        "skipped_existing": int(skipped_count),
        "metadata_path": str(metadata_path),
    }

In [6]:
# ============================================================
# MAIN RUNNER
# ============================================================

def run_all_generations() -> List[Dict[str, Any]]:
    ensure_dir(OUTPUT_ROOT)

    overall_summary = []

    for model_alias in MODEL_EXECUTION_ORDER:
        model_id = MODELS[model_alias]["model_id"]
        print("\n" + "#" * 100)
        print(f"INICIANDO BLOQUE DE MODELO: {model_alias}")
        print(f"MODEL ID: {model_id}")
        print("#" * 100)

        pipe = None
        try:
            pipe = load_pipeline(model_id)

            for dataset_cfg in DATASETS:
                result = generate_dataset(
                    pipe=pipe,
                    model_alias=model_alias,
                    dataset_cfg=dataset_cfg,
                )
                overall_summary.append(result)

        finally:
            print(f"\nLiberando modelo: {model_alias}")
            if pipe is not None:
                unload_pipeline(pipe)

    summary_path = OUTPUT_ROOT / "run_summary.json"
    save_json(overall_summary, summary_path)

    print("\n" + "=" * 100)
    print("GENERACIÓN COMPLETA")
    print("Resumen guardado en:", summary_path)
    print("=" * 100)

    return overall_summary

In [7]:
# ============================================================
# EXECUTE ALL
# ============================================================

summary = run_all_generations()
pd.DataFrame(summary)

####################################################################################################
INICIANDO BLOQUE DE MODELO: sd35_large
MODEL ID: stabilityai/stable-diffusion-3.5-large
####################################################################################################

Cargando modelo: stabilityai/stable-diffusion-3.5-large

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:103: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(

model_index.json:   0%|          | 0.00/706 [00:00<?, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 28 files:   0%|          | 0/28 [00:00<?, ?it/s]

Loading pipeline components...:   0%|          | 0/9 [00:00<?, ?it/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/219 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/517 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

Modelo cargado en 88.15 s

================================================================================
Modelo: sd35_large
Dataset: prueba_500chars_sd3.jsonl
Prompt column: prompt_sd3_large
max_sequence_length: 256
Output dir: /content/drive/MyDrive/Proyecto NLP y DL/Imagen_Generacion/generated_images_sd3/sd35_large/prueba_500chars_sd3/images
================================================================================
Filas cargadas: 50

sd35_large | prueba_500chars_sd3.jsonl:   0%|          | 0/50 [00:00<?, ?it/s]

[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (113 > 77). Running this sequence through the model will result in indexing errors
[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer CLIPTokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["'s throat . around him , his sons and guards stand in tense silence , their heavy furs and boiled leather cloaks dusted with frost under a bleak , oppressive grey sky ."]
[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (113 > 77). Running this sequence through the model will result in indexing errors
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["'s throat . around him , his sons and guards stand in tense silence , their heavy furs and boiled leather cloaks dusted with frost under a bleak , oppressive grey sky ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', mud - stained furs and boiled leather . pale , wintry light filters through a grey sky , casting a cold , somber mood over the gritty , snowy wilderness .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', mud - stained furs and boiled leather . pale , wintry light filters through a grey sky , casting a cold , somber mood over the gritty , snowy wilderness .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['eyes watching silently . a cold wind stirs the crimson leaves , while the stark , grey atmosphere emphasizes the heavy silence of mourning .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['eyes watching silently . a cold wind stirs the crimson leaves , while the stark , grey atmosphere emphasizes the heavy silence of mourning .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', harsh shadows across the granite columns and the silent stone kings . the air is thick with damp dust and ancient grief .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', harsh shadows across the granite columns and the silent stone kings . the air is thick with damp dust and ancient grief .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', his expression etched with hesitation . cold northern light filters through high stone arches , casting long shadows across the rough - hewn floor .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', his expression etched with hesitation . cold northern light filters through high stone arches , casting long shadows across the rough - hewn floor .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['draped in stark , baratheon , and lannister banners . warm , flickering torchlight cuts through the haze of roasted meat and hearth - smoke .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['draped in stark , baratheon , and lannister banners . warm , flickering torchlight cuts through the haze of roasted meat and hearth - smoke .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['goblet of wine . warm , flickering torchlight casts deep shadows across their faces , highlighting the grit and tension of this whispered , cruel piece of advice .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['goblet of wine . warm , flickering torchlight casts deep shadows across their faces , highlighting the grit and tension of this whispered , cruel piece of advice .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['oppressive shadows across the floor . his eyes are hard , reflecting a man stepping into a nest of vipers to uncover a deadly secret .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['oppressive shadows across the floor . his eyes are hard , reflecting a man stepping into a nest of vipers to uncover a deadly secret .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', eager eyes . they wear heavy grey wools and rough furs . cold northern light filters through a narrow slit window , casting long , moody shadows .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', eager eyes . they wear heavy grey wools and rough furs . cold northern light filters through a narrow slit window , casting long , moody shadows .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['pale light filters through the dust , casting long shadows . bran slips , his small fingers losing grip on the rough granite as he begins to fall .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['pale light filters through the dust , casting long shadows . bran slips , his small fingers losing grip on the rough granite as he begins to fall .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["scene is set against a grey , oppressive sky ; cold wind whips bran 's linen tunic . harsh , pale light casts deep shadows across the weathered masonry ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["scene is set against a grey , oppressive sky ; cold wind whips bran 's linen tunic . harsh , pale light casts deep shadows across the weathered masonry ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['and anger . cold winter light spills from an open window , illuminating dust motes and the rough grey masonry , while a heavy , suffocating silence fills the room .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['and anger . cold winter light spills from an open window , illuminating dust motes and the rough grey masonry , while a heavy , suffocating silence fills the room .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [", draped in delicate silks , reaches out with trembling fingers to touch the animal 's velvet nose . dust dances in the warm , hazy air around them ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [", draped in delicate silks , reaches out with trembling fingers to touch the animal 's velvet nose . dust dances in the warm , hazy air around them ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['tunic of heavy velvet , while ned is clad in somber , dark grey boiled leather and thick wool . harsh torchlight casts deep , flickering shadows .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['tunic of heavy velvet , while ned is clad in somber , dark grey boiled leather and thick wool . harsh torchlight casts deep , flickering shadows .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["gritty courtyards of winterfell under a bleak , overcast sky , with harsh , cold light emphasizing the raw violence and the wolf 's thick , coarse fur ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["gritty courtyards of winterfell under a bleak , overcast sky , with harsh , cold light emphasizing the raw violence and the wolf 's thick , coarse fur ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["is heavy with dread and mystery , the cold northern air visible as a faint mist , highlighting the blade 's sinister , ancient craftsmanship ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["is heavy with dread and mystery , the cold northern air visible as a faint mist , highlighting the blade 's sinister , ancient craftsmanship ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['damp earth . nearby , arya stands breathless in mud - stained leather , while the river flows coldly under a pale , oppressive sky of grey clouds .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['damp earth . nearby , arya stands breathless in mud - stained leather , while the river flows coldly under a pale , oppressive sky of grey clouds .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['cloak drape around him as he delivers the mercy blow . the atmosphere is heavy with tragedy , lit by a pale , wintry light that casts long , somber shadows .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['cloak drape around him as he delivers the mercy blow . the atmosphere is heavy with tragedy , lit by a pale , wintry light that casts long , somber shadows .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['sentinel trees loom under a heavy , overcast sky , with soft winter light filtering through the frost , creating a cold , hushed atmosphere .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['sentinel trees loom under a heavy , overcast sky , with soft winter light filtering through the frost , creating a cold , hushed atmosphere .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['thick furs . the scene is lit by a single flickering hearth , casting long , dancing shadows and a warm , orange glow against the cold , damp grey masonry .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['thick furs . the scene is lit by a single flickering hearth , casting long , dancing shadows and a warm , orange glow against the cold , damp grey masonry .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [". dust motes dance in shafts of pale sunlight piercing the gloom , highlighting the rough grain of the wood and arya 's simple linen tunic ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [". dust motes dance in shafts of pale sunlight piercing the gloom , highlighting the rough grain of the wood and arya 's simple linen tunic ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['serene , knowing expression . the golden hour light casts a warm , amber glow over the endless horizon , highlighting the soft textures of the grass and the intimate , tender bond between the two women .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['serene , knowing expression . the golden hour light casts a warm , amber glow over the endless horizon , highlighting the soft textures of the grass and the intimate , tender bond between the two women .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', once - fine linen . around them , dothraki warriors watch in silence . harsh midday sun casts sharp shadows across the arid plains , highlighting the tension in their standoff .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', once - fine linen . around them , dothraki warriors watch in silence . harsh midday sun casts sharp shadows across the arid plains , highlighting the tension in their standoff .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['shoulders , eyes wide with quiet longing . cold , grey morning light filters through a narrow slit window , casting long , pale shadows across the damp , grit - covered floor .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['shoulders , eyes wide with quiet longing . cold , grey morning light filters through a narrow slit window , casting long , pale shadows across the damp , grit - covered floor .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['gripping a heavy hammer . his blue eyes are sullen and guarded . around them , glowing forges cast harsh , flickering light and deep shadows across grime - covered anvils and piles of raw iron .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['gripping a heavy hammer . his blue eyes are sullen and guarded . around them , glowing forges cast harsh , flickering light and deep shadows across grime - covered anvils and piles of raw iron .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [", his eyes wide with terror . harsh sunlight cuts through narrow slits in the grey walls , illuminating dust motes and the stark contrast between the warrior 's power and the boy 's fear ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [", his eyes wide with terror . harsh sunlight cuts through narrow slits in the grey walls , illuminating dust motes and the stark contrast between the warrior 's power and the boy 's fear ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['; banners flutter in the wind , and the air is thick with kicked - up dirt and the scent of crushed grass and horse sweat .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['; banners flutter in the wind , and the air is thick with kicked - up dirt and the scent of crushed grass and horse sweat .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['tables . flickering orange torchlight casts long , dancing shadows across the stone walls and mud - streaked floor , heightening the sudden tension .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['tables . flickering orange torchlight casts long , dancing shadows across the stone walls and mud - streaked floor , heightening the sudden tension .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['ted frame . he is escorted by stern guards in mud - splattered leather and steel . grey mist clings to the jagged peaks above .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['ted frame . he is escorted by stern guards in mud - splattered leather and steel . grey mist clings to the jagged peaks above .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['pierces through swirling grey clouds , casting harsh shadows across the white stone of the seven towering spires .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['pierces through swirling grey clouds , casting harsh shadows across the white stone of the seven towering spires .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['. cold mountain light floods the white marble hall , casting sharp shadows . the atmosphere is tense , smelling of ozone and cold stone and desperation .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['. cold mountain light floods the white marble hall , casting sharp shadows . the atmosphere is tense , smelling of ozone and cold stone and desperation .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['flickering torchlight casts dancing , jagged shadows across the grime - streaked walls and muddy floor , illuminating the tension of their treasonous plot .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['flickering torchlight casts dancing , jagged shadows across the grime - streaked walls and muddy floor , illuminating the tension of their treasonous plot .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["the knight 's armpit . vardis , in dented plate armor , gasps in agony . cold , pale light filters through the high arches ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["the knight 's armpit . vardis , in dented plate armor , gasps in agony . cold , pale light filters through the high arches ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['throne . the cold , thin mountain air swirls around them , while pale , stark light filters through the high arches , casting long , oppressive shadows .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['throne . the cold , thin mountain air swirls around them , while pale , stark light filters through the high arches , casting long , oppressive shadows .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['with betrayal ; the lighting is stark , with cold shafts of daylight cutting through dust motes , casting deep shadows across the stone floor .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['with betrayal ; the lighting is stark , with cold shafts of daylight cutting through dust motes , casting deep shadows across the stone floor .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['. soft , golden sunlight filters through budding willow trees , casting a hopeful , ethereal glow over the sprawling tournament grounds .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['. soft , golden sunlight filters through budding willow trees , casting a hopeful , ethereal glow over the sprawling tournament grounds .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["the flickering orange glow of braziers that cast deep , dancing shadows . drogo 's expression is stern and dismissive as he prepares for the hunt , embodying the fierce stallion who mounts the world ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["the flickering orange glow of braziers that cast deep , dancing shadows . drogo 's expression is stern and dismissive as he prepares for the hunt , embodying the fierce stallion who mounts the world ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["others struggle to strip the boy 's garments . cold , grey light filters through skeletal trees , casting a bleak , oppressive atmosphere over the struggle ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["others struggle to strip the boy 's garments . cold , grey light filters through skeletal trees , casting a bleak , oppressive atmosphere over the struggle ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['pale light filtering through narrow slits , casting long shadows across the damp floor and the distant , sightless gaze of maester aemon .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['pale light filtering through narrow slits , casting long shadows across the damp floor and the distant , sightless gaze of maester aemon .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['en . splashes of crimson blood spray across the damp forest floor . dim , filtered sunlight pierces through a canopy of ancient , oppressive grey trees .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['en . splashes of crimson blood spray across the damp forest floor . dim , filtered sunlight pierces through a canopy of ancient , oppressive grey trees .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['athered parchment , his expression torn with guilt as he carefully writes " my heir " instead of " my son ." flickering orange candlelight casts long , dancing shadows .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['athered parchment , his expression torn with guilt as he carefully writes " my heir " instead of " my son ." flickering orange candlelight casts long , dancing shadows .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['dirt . cold , grey light filters through the towering stone walls , casting long shadows over the damp cobblestones and piles of refuse in the oppressive , silent atmosphere .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['dirt . cold , grey light filters through the towering stone walls , casting long shadows over the damp cobblestones and piles of refuse in the oppressive , silent atmosphere .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['beats down , casting sharp shadows on the scorched earth , while the merchant screams , dragged through the dirt by galloping horses .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['beats down , casting sharp shadows on the scorched earth , while the merchant screams , dragged through the dirt by galloping horses .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['wintry light filters through a leaden sky , casting a cold , grim atmosphere over the mud - splattered steel of gathered spears .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['wintry light filters through a leaden sky , casting a cold , grim atmosphere over the mud - splattered steel of gathered spears .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['splattered steel plate and boiled leather . a grey , oppressive sky casts a flat light over the rushing river , enhancing the grim , tense atmosphere of a standoff .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['splattered steel plate and boiled leather . a grey , oppressive sky casts a flat light over the rushing river , enhancing the grim , tense atmosphere of a standoff .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['canopy , illuminating the swirling snowflakes and the damp , frosted earth . the atmosphere is tense , smelling of pine and winter .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['canopy , illuminating the swirling snowflakes and the damp , frosted earth . the atmosphere is tense , smelling of pine and winter .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['rigid . the air is thick with tension and the scent of dust , while the stark light casts deep , jagged shadows across the cobblestones .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['rigid . the air is thick with tension and the scent of dust , while the stark light casts deep , jagged shadows across the cobblestones .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', his eyes vacant , wearing a stained leather vest . harsh , blinding sunlight creates shimmering heat waves , casting stark , oppressive shadows across the gritty earth .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', his eyes vacant , wearing a stained leather vest . harsh , blinding sunlight creates shimmering heat waves , casting stark , oppressive shadows across the gritty earth .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['an inner heat . daenerys , skin glistening with sweat and ash , is enveloped by the searing fire , her expression one of divine transcendence and raw power .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['an inner heat . daenerys , skin glistening with sweat and ash , is enveloped by the searing fire , her expression one of divine transcendence and raw power .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', grey daylight filters through the oppressive stone walls , casting long , melancholic shadows across the room where untouched silver platters of food sit abandoned .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', grey daylight filters through the oppressive stone walls , casting long , melancholic shadows across the room where untouched silver platters of food sit abandoned .']

  0%|          | 0/28 [00:00<?, ?it/s]

Metadata guardado en: /content/drive/MyDrive/Proyecto NLP y DL/Imagen_Generacion/generated_images_sd3/sd35_large/prueba_500chars_sd3/metadata.json
Resumen: {'total_rows': 50, 'ok': 50, 'errors': 0, 'skipped_existing': 0}

================================================================================
Modelo: sd35_large
Dataset: prueba_1013chars_sd3_inicial.jsonl
Prompt column: prompt_sd3_large
max_sequence_length: 256
Output dir: /content/drive/MyDrive/Proyecto NLP y DL/Imagen_Generacion/generated_images_sd3/sd35_large/prueba_1013chars_sd3_inicial/images
================================================================================
Filas cargadas: 50

sd35_large | prueba_1013chars_sd3_inicial.jsonl:   0%|          | 0/50 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["in the blood - stained snow , its size dwarfing a pony . eddard 's weathered hand reaches beneath the creature 's jaw , pulling out a jagged , blood - soaked shard of a stag 's antler . beside him , young bran clutches a tiny , shivering direwolf pup to his chest with fierce desperation , while theon greyjoy stands nearby , his steel sword half - drawn with a cold , arrogant expression . the lighting is a bleak , oppressive winter grey , with a pale sun struggling to pierce through heavy clouds , casting soft , muted shadows across the crimson - stained white terrain and the rough , boiled leather and fur textures of the stark party 's winter attire ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["in the blood - stained snow , its size dwarfing a pony . eddard 's weathered hand reaches beneath the creature 's jaw , pulling out a jagged , blood - soaked shard of a stag 's antler . beside him , young bran clutches a tiny , shivering direwolf pup to his chest with fierce desperation , while theon greyjoy stands nearby , his steel sword half - drawn with a cold , arrogant expression . the lighting is a bleak , oppressive winter grey , with a pale sun struggling to pierce through heavy clouds , casting soft , muted shadows across the crimson - stained white terrain and the rough , boiled leather and fur textures of the stark party 's winter attire ."]
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ["massive, dark carcass of a direwolf, an enormous beast semienterred in the blood-stained snow, its size dwarfing a pony. Eddard's weathered hand reaches beneath the creature's jaw, pulling out a jagged, blood-soaked shard of a stag's antler. Beside him, young Bran clutches a tiny, shivering direwolf pup to his chest with fierce desperation, while Theon Greyjoy stands nearby, his steel sword half-drawn with a cold, arrogant expression. The lighting is a bleak, oppressive winter grey, with a pale sun struggling to pierce through heavy clouds, casting soft, muted shadows across the crimson-stained white terrain and the rough, boiled leather and fur textures of the Stark party's winter attire."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['small , shivering grey pup , his face a mask of desperate protection , while robb stands beside him with a defiant , commanding gaze . jon snow stands slightly apart , cradling a sixth , smaller pup against his chest , his expression solemn and longing . around them , grim guards in interlocking steel ringmail and heavy grey wool look on with apprehension . the ground is a harsh mixture of frozen white snow and dark , blood - stained earth . a pale , wintry light filters through a heavy overcast sky , casting a cold , muted glow over the scene , emphasizing the stark contrast between the warmth of the pups and the freezing , oppressive atmosphere of the wilderness .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['small , shivering grey pup , his face a mask of desperate protection , while robb stands beside him with a defiant , commanding gaze . jon snow stands slightly apart , cradling a sixth , smaller pup against his chest , his expression solemn and longing . around them , grim guards in interlocking steel ringmail and heavy grey wool look on with apprehension . the ground is a harsh mixture of frozen white snow and dark , blood - stained earth . a pale , wintry light filters through a heavy overcast sky , casting a cold , muted glow over the scene , emphasizing the stark contrast between the warmth of the pups and the freezing , oppressive atmosphere of the wilderness .']
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ['together in the biting cold. Young Bran clings fiercely to a small, shivering grey pup, his face a mask of desperate protection, while Robb stands beside him with a defiant, commanding gaze. Jon Snow stands slightly apart, cradling a sixth, smaller pup against his chest, his expression solemn and longing. Around them, grim guards in interlocking steel ringmail and heavy grey wool look on with apprehension. The ground is a harsh mixture of frozen white snow and dark, blood-stained earth. A pale, wintry light filters through a heavy overcast sky, casting a cold, muted glow over the scene, emphasizing the stark contrast between the warmth of the pups and the freezing, oppressive atmosphere of the wilderness.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["delivers the devastating news of jon arryn 's death . ned 's expression is one of sudden , crushing loss , his eyes clouded with memory and shock . they are positioned beside the ancient heart tree , its ghostly white bark contrasting sharply with the deep , bleeding red of its carved face and sap - filled eyes . the atmosphere is heavy and oppressive , with a thin mist clinging to the damp earth . pale , diffused northern light filters through the skeletal branches of the godswood , casting soft , muted shadows that emphasize the grim solemnity of the encounter and the sudden weight of a dying era ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["delivers the devastating news of jon arryn 's death . ned 's expression is one of sudden , crushing loss , his eyes clouded with memory and shock . they are positioned beside the ancient heart tree , its ghostly white bark contrasting sharply with the deep , bleeding red of its carved face and sap - filled eyes . the atmosphere is heavy and oppressive , with a thin mist clinging to the damp earth . pale , diffused northern light filters through the skeletal branches of the godswood , casting soft , muted shadows that emphasize the grim solemnity of the encounter and the sudden weight of a dying era ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["beside him , his expression solemn and guarded , holding a flickering oil lamp that casts long , dancing shadows across the vaulted ceiling . they are dressed in heavy , travel - worn furs and thick wools ; robert 's royal velvet is dusted with grime , while ned wears a dark , rugged cloak of boiled leather and grey wool . around them , a silent procession of ancient stark ancestors sit carved in stone , their sightless eyes watching from the gloom . the atmosphere is thick with dampness and the scent of old earth . the singular , trembling orange light of the lamp creates a stark chiaroscuro , illuminating the pale , serene face of lyanna 's statue against the suffocating darkness ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["beside him , his expression solemn and guarded , holding a flickering oil lamp that casts long , dancing shadows across the vaulted ceiling . they are dressed in heavy , travel - worn furs and thick wools ; robert 's royal velvet is dusted with grime , while ned wears a dark , rugged cloak of boiled leather and grey wool . around them , a silent procession of ancient stark ancestors sit carved in stone , their sightless eyes watching from the gloom . the atmosphere is thick with dampness and the scent of old earth . the singular , trembling orange light of the lamp creates a stark chiaroscuro , illuminating the pale , serene face of lyanna 's statue against the suffocating darkness ."]
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ["aching longing, his hand hovering near the cold granite. Ned stands beside him, his expression solemn and guarded, holding a flickering oil lamp that casts long, dancing shadows across the vaulted ceiling. They are dressed in heavy, travel-worn furs and thick wools; Robert's royal velvet is dusted with grime, while Ned wears a dark, rugged cloak of boiled leather and grey wool. Around them, a silent procession of ancient Stark ancestors sit carved in stone, their sightless eyes watching from the gloom. The atmosphere is thick with dampness and the scent of old earth. The singular, trembling orange light of the lamp creates a stark chiaroscuro, illuminating the pale, serene face of Lyanna's statue against the suffocating darkness."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['trothal of sansa stark to prince joffrey . ned stands rigid , his face a mask of solemn hesitation , dressed in heavy , charcoal - grey wool and thick furs that smell of pine and cold rain . robert wears a rich , gold - embroidered velvet doublet , now stained and rumpled , reflecting his decadent decline . the room is illuminated by the orange flicker of massive hearths , casting long , dancing shadows across the rough - hewn stone walls . the air is thick with the scent of roasting meat and peat smoke , while the oppressive chill of the north clings to the edges of the warmth , mirroring the tension of a political bond forged in the shadow of old ghosts .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['trothal of sansa stark to prince joffrey . ned stands rigid , his face a mask of solemn hesitation , dressed in heavy , charcoal - grey wool and thick furs that smell of pine and cold rain . robert wears a rich , gold - embroidered velvet doublet , now stained and rumpled , reflecting his decadent decline . the room is illuminated by the orange flicker of massive hearths , casting long , dancing shadows across the rough - hewn stone walls . the air is thick with the scent of roasting meat and peat smoke , while the oppressive chill of the north clings to the edges of the warmth , mirroring the tension of a political bond forged in the shadow of old ghosts .']
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: [', his expression a mixture of desperation and nostalgic longing as he proposes the betrothal of Sansa Stark to Prince Joffrey. Ned stands rigid, his face a mask of solemn hesitation, dressed in heavy, charcoal-grey wool and thick furs that smell of pine and cold rain. Robert wears a rich, gold-embroidered velvet doublet, now stained and rumpled, reflecting his decadent decline. The room is illuminated by the orange flicker of massive hearths, casting long, dancing shadows across the rough-hewn stone walls. The air is thick with the scent of roasting meat and peat smoke, while the oppressive chill of the North clings to the edges of the warmth, mirroring the tension of a political bond forged in the shadow of old ghosts.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['goblet of deep red summer wine . behind him , the air is thick with the scent of roasted meats and hearth smoke . in the distant , elevated background , the high table is a scene of opulent rigidity ; lord and lady stark sit beside the king and queen , surrounded by the royal children . the queen is radiant in a gown of shimmering gold silk , a jeweled emerald diadem resting upon her golden hair . massive stone walls are draped with heavy wool banners of the direwolf , stag , and lion . warm , flickering orange light from towering fireplaces casts long , dancing shadows , contrasting the golden glow of the high table with the dim , gritty atmosphere of the lower benches .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['goblet of deep red summer wine . behind him , the air is thick with the scent of roasted meats and hearth smoke . in the distant , elevated background , the high table is a scene of opulent rigidity ; lord and lady stark sit beside the king and queen , surrounded by the royal children . the queen is radiant in a gown of shimmering gold silk , a jeweled emerald diadem resting upon her golden hair . massive stone walls are draped with heavy wool banners of the direwolf , stag , and lion . warm , flickering orange light from towering fireplaces casts long , dancing shadows , contrasting the golden glow of the high table with the dim , gritty atmosphere of the lower benches .']
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ['He wears a simple, dark wool tunic of coarse weave, clutching a pewter goblet of deep red summer wine. Behind him, the air is thick with the scent of roasted meats and hearth smoke. In the distant, elevated background, the high table is a scene of opulent rigidity; Lord and Lady Stark sit beside the King and Queen, surrounded by the royal children. The Queen is radiant in a gown of shimmering gold silk, a jeweled emerald diadem resting upon her golden hair. Massive stone walls are draped with heavy wool banners of the direwolf, stag, and lion. Warm, flickering orange light from towering fireplaces casts long, dancing shadows, contrasting the golden glow of the high table with the dim, gritty atmosphere of the lower benches.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["rion leans in with a knowing , cynical smirk , his mismatched eyes gleaming with sharp intelligence . tyrion is dressed in rich , crimson velvet and gold - threaded brocade that contrasts sharply with the bleak northern surroundings . he gestures with a small , ring - adorned hand , delivering his cold advice . the background is a blur of rough - hewn stone walls and flickering wall torches that cast long , dancing shadows and a warm , orange glow across the scene . the air is thick with the scent of roasted meat and old smoke . jon 's face is a mask of suppressed hurt and simmering anger , capturing a pivotal moment of psychological cruelty ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["rion leans in with a knowing , cynical smirk , his mismatched eyes gleaming with sharp intelligence . tyrion is dressed in rich , crimson velvet and gold - threaded brocade that contrasts sharply with the bleak northern surroundings . he gestures with a small , ring - adorned hand , delivering his cold advice . the background is a blur of rough - hewn stone walls and flickering wall torches that cast long , dancing shadows and a warm , orange glow across the scene . the air is thick with the scent of roasted meat and old smoke . jon 's face is a mask of suppressed hurt and simmering anger , capturing a pivotal moment of psychological cruelty ."]
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ["y wool tunic trimmed with coarse fur. Beside him, the diminutive Tyrion leans in with a knowing, cynical smirk, his mismatched eyes gleaming with sharp intelligence. Tyrion is dressed in rich, crimson velvet and gold-threaded brocade that contrasts sharply with the bleak Northern surroundings. He gestures with a small, ring-adorned hand, delivering his cold advice. The background is a blur of rough-hewn stone walls and flickering wall torches that cast long, dancing shadows and a warm, orange glow across the scene. The air is thick with the scent of roasted meat and old smoke. Jon's face is a mask of suppressed hurt and simmering anger, capturing a pivotal moment of psychological cruelty."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['the textures coarse and weathered , smelling of pine and old snow . around him , the room is swallowed by oppressive shadows , illuminated only by the flickering , amber glow of a few dying hearth fires that cast long , dancing silhouettes against the damp masonry . his eyes are narrow and haunted , reflecting the weight of a dangerous secret . through a narrow window , a bleak , overcast sky looms , hinting at the treacherous journey south . the atmosphere is thick with tension and paranoia , a silent battle between his loyalty to robert and the suffocating realization that he is stepping into a nest of vipers .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['the textures coarse and weathered , smelling of pine and old snow . around him , the room is swallowed by oppressive shadows , illuminated only by the flickering , amber glow of a few dying hearth fires that cast long , dancing silhouettes against the damp masonry . his eyes are narrow and haunted , reflecting the weight of a dangerous secret . through a narrow window , a bleak , overcast sky looms , hinting at the treacherous journey south . the atmosphere is thick with tension and paranoia , a silent battle between his loyalty to robert and the suffocating realization that he is stepping into a nest of vipers .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', his finger pointing toward the lethal , tapered tip of the blade . arya looks up at him with wide , intense eyes , her face a mask of fierce determination . jon wears a heavy , dark wool tunic and a weathered leather jerkin , while arya is dressed in a simple , rough - spun linen dress , slightly rumpled from her struggle with packing . beside them , the white wolf ghost and the grey wolf nymeria sit alert , their fur contrasting against the cold grey granite floor . soft , pale northern light filters through a narrow embrasure , casting long , cool shadows and highlighting the metallic sheen of the sword and the gritty texture of the ancient stone walls .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', his finger pointing toward the lethal , tapered tip of the blade . arya looks up at him with wide , intense eyes , her face a mask of fierce determination . jon wears a heavy , dark wool tunic and a weathered leather jerkin , while arya is dressed in a simple , rough - spun linen dress , slightly rumpled from her struggle with packing . beside them , the white wolf ghost and the grey wolf nymeria sit alert , their fur contrasting against the cold grey granite floor . soft , pale northern light filters through a narrow embrasure , casting long , cool shadows and highlighting the metallic sheen of the sword and the gritty texture of the ancient stone walls .']
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: [", trembling hand to grip the hilt. He is mid-sentence, demonstrating the weapon's purpose, his finger pointing toward the lethal, tapered tip of the blade. Arya looks up at him with wide, intense eyes, her face a mask of fierce determination. Jon wears a heavy, dark wool tunic and a weathered leather jerkin, while Arya is dressed in a simple, rough-spun linen dress, slightly rumpled from her struggle with packing. Beside them, the white wolf Ghost and the grey wolf Nymeria sit alert, their fur contrasting against the cold grey granite floor. Soft, pale northern light filters through a narrow embrasure, casting long, cool shadows and highlighting the metallic sheen of the sword and the gritty texture of the ancient stone walls."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['golden - haired man — her mirror image — are locked in a passionate , forbidden embrace against a cold stone wall . the room is cast in deep amber shadows and stark chiaroscuro , highlighting the pale skin of the lovers . outside , the air is freezing , with a light dusting of melting snow clinging to the grey masonry . bran ’ s small fingers grip the rough , abrasive rock , his simple wool tunic damp from the mist . the tension is palpable ; the boy is frozen in a moment of devastating discovery , the vast , dizzying drop to the wet courtyard below creating a sense of vertigo and impending doom .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['golden - haired man — her mirror image — are locked in a passionate , forbidden embrace against a cold stone wall . the room is cast in deep amber shadows and stark chiaroscuro , highlighting the pale skin of the lovers . outside , the air is freezing , with a light dusting of melting snow clinging to the grey masonry . bran ’ s small fingers grip the rough , abrasive rock , his simple wool tunic damp from the mist . the tension is palpable ; the boy is frozen in a moment of devastating discovery , the vast , dizzying drop to the wet courtyard below creating a sense of vertigo and impending doom .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["uselessly at the rough , grey masonry as he tips into the void . the man wears a rich , gold - threaded doublet of heavy crimson silk , now rumpled and stained . the architecture is oppressive , featuring weathered gargoyles and damp , lichen - covered granite . below , the dizzying drop reveals a courtyard of slick , slushy snow and grey cobblestones . the lighting is a bleak , oppressive overcast daylight , casting soft but dismal shadows that emphasize the grit of the stone . a chilling atmosphere of betrayal permeates the air , with the wind whipping the boy 's simple wool tunic as he begins his fatal descent ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["uselessly at the rough , grey masonry as he tips into the void . the man wears a rich , gold - threaded doublet of heavy crimson silk , now rumpled and stained . the architecture is oppressive , featuring weathered gargoyles and damp , lichen - covered granite . below , the dizzying drop reveals a courtyard of slick , slushy snow and grey cobblestones . the lighting is a bleak , oppressive overcast daylight , casting soft but dismal shadows that emphasize the grit of the stone . a chilling atmosphere of betrayal permeates the air , with the wind whipping the boy 's simple wool tunic as he begins his fatal descent ."]
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ["is a mask of pure shock and terror, his small hands clawing uselessly at the rough, grey masonry as he tips into the void. The man wears a rich, gold-threaded doublet of heavy crimson silk, now rumpled and stained. The architecture is oppressive, featuring weathered gargoyles and damp, lichen-covered granite. Below, the dizzying drop reveals a courtyard of slick, slushy snow and grey cobblestones. The lighting is a bleak, oppressive overcast daylight, casting soft but dismal shadows that emphasize the grit of the stone. A chilling atmosphere of betrayal permeates the air, with the wind whipping the boy's simple wool tunic as he begins his fatal descent."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', simmering hatred , turns sharply toward jon snow . jon stands near the heavy oak door , his posture rigid and pained , dressed in dark , travel - worn boiled leather and a heavy wool cloak . the air is thick with resentment . catelyn ’ s eyes are narrow and cruel as she delivers her biting words , her lip curling in disdain . beside jon , the white direwolf ghost watches with piercing red eyes , sensing the hostility . pale , wintry light filters through a narrow open window , illuminating dust motes and the stark contrast between the warm hearth - glow and the freezing draft . the atmosphere is suffocating , charged with familial tragedy and unspoken malice .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', simmering hatred , turns sharply toward jon snow . jon stands near the heavy oak door , his posture rigid and pained , dressed in dark , travel - worn boiled leather and a heavy wool cloak . the air is thick with resentment . catelyn ’ s eyes are narrow and cruel as she delivers her biting words , her lip curling in disdain . beside jon , the white direwolf ghost watches with piercing red eyes , sensing the hostility . pale , wintry light filters through a narrow open window , illuminating dust motes and the stark contrast between the warm hearth - glow and the freezing draft . the atmosphere is suffocating , charged with familial tragedy and unspoken malice .']
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ['burn hair matted and disheveled, her face etched with hollow exhaustion and a cold, simmering hatred, turns sharply toward Jon Snow. Jon stands near the heavy oak door, his posture rigid and pained, dressed in dark, travel-worn boiled leather and a heavy wool cloak. The air is thick with resentment. Catelyn’s eyes are narrow and cruel as she delivers her biting words, her lip curling in disdain. Beside Jon, the white direwolf Ghost watches with piercing red eyes, sensing the hostility. Pale, wintry light filters through a narrow open window, illuminating dust motes and the stark contrast between the warm hearth-glow and the freezing draft. The atmosphere is suffocating, charged with familial tragedy and unspoken malice.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["breathtaking creature , its coat a shimmering winter - sea grey and its flowing mane like swirling silver smoke , tossing its head with youthful energy . daenerys , dressed in delicate , flowing silks of pale cream and gold , reaches out with a mixture of trepidation and wonder , her small hand nearly touching the mare 's velvet muzzle . around them , the atmosphere is thick with the heat of the afternoon , the golden light casting long , soft shadows across the stone tiles . the tension is palpable as the proud dothraki bloodriders watch in silence , their bronze ornaments glinting under a harsh , brilliant sky ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["breathtaking creature , its coat a shimmering winter - sea grey and its flowing mane like swirling silver smoke , tossing its head with youthful energy . daenerys , dressed in delicate , flowing silks of pale cream and gold , reaches out with a mixture of trepidation and wonder , her small hand nearly touching the mare 's velvet muzzle . around them , the atmosphere is thick with the heat of the afternoon , the golden light casting long , soft shadows across the stone tiles . the tension is palpable as the proud dothraki bloodriders watch in silence , their bronze ornaments glinting under a harsh , brilliant sky ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['hall . ned stark stands his ground , his face a mask of frozen grief and moral indignation , his grey eyes piercing and filled with a quiet , simmering anger . ned wears a heavy , charcoal - grey wool doublet with a thick fur mantle draped over his shoulders , while robert is clad in rich , gold - embroidered crimson velvet that contrasts with the grim atmosphere . the room is illuminated by flickering orange torchlight that casts long , dancing shadows against the damp limestone walls . the air is thick with tension and the scent of old smoke , capturing a moment of profound ideological clash between two old friends .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['hall . ned stark stands his ground , his face a mask of frozen grief and moral indignation , his grey eyes piercing and filled with a quiet , simmering anger . ned wears a heavy , charcoal - grey wool doublet with a thick fur mantle draped over his shoulders , while robert is clad in rich , gold - embroidered crimson velvet that contrasts with the grim atmosphere . the room is illuminated by flickering orange torchlight that casts long , dancing shadows against the damp limestone walls . the air is thick with tension and the scent of old smoke , capturing a moment of profound ideological clash between two old friends .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['in a silent scream of agony as blood sprays across the cold floor . nearby , catelyn stark recoils in terror and relief , her fine velvet gown torn and stained , her auburn hair disheveled . beside her , young bran stark looks on with wide , trembling eyes , his small frame shivering in a linen tunic . the atmosphere is thick with tension and the smell of iron and wet fur . harsh , flickering torchlight casts long , dancing shadows against the damp granite walls , creating a stark chiaroscuro effect that emphasizes the raw , primal power of the beast protecting the children in the oppressive gloom of the north .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['in a silent scream of agony as blood sprays across the cold floor . nearby , catelyn stark recoils in terror and relief , her fine velvet gown torn and stained , her auburn hair disheveled . beside her , young bran stark looks on with wide , trembling eyes , his small frame shivering in a linen tunic . the atmosphere is thick with tension and the smell of iron and wet fur . harsh , flickering torchlight casts long , dancing shadows against the damp granite walls , creating a stark chiaroscuro effect that emphasizes the raw , primal power of the beast protecting the children in the oppressive gloom of the north .']
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ['assassin, dressed in rough, dark wool and weathered leather, is thrown backward, his face twisted in a silent scream of agony as blood sprays across the cold floor. Nearby, Catelyn Stark recoils in terror and relief, her fine velvet gown torn and stained, her auburn hair disheveled. Beside her, young Bran Stark looks on with wide, trembling eyes, his small frame shivering in a linen tunic. The atmosphere is thick with tension and the smell of iron and wet fur. Harsh, flickering torchlight casts long, dancing shadows against the damp granite walls, creating a stark chiaroscuro effect that emphasizes the raw, primal power of the beast protecting the children in the oppressive gloom of the North.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['metal that shimmer with a sinister , iridescent quality . beside the blade , a hand in a rough wool sleeve points toward the weapon , highlighting its unnatural sharpness . the room is cold , with frost creeping along the stone walls and a single flickering torch casting long , dancing shadows and a warm , orange glow that contrasts with the oppressive grey stone . the atmosphere is thick with dread and urgency . ser rodrik stands in the background , his face etched with grim determination , wearing heavy boiled leather and a weathered cloak of thick grey fur , his eyes fixed on the deadly instrument of the attempted assassination .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['metal that shimmer with a sinister , iridescent quality . beside the blade , a hand in a rough wool sleeve points toward the weapon , highlighting its unnatural sharpness . the room is cold , with frost creeping along the stone walls and a single flickering torch casting long , dancing shadows and a warm , orange glow that contrasts with the oppressive grey stone . the atmosphere is thick with dread and urgency . ser rodrik stands in the background , his face etched with grim determination , wearing heavy boiled leather and a weathered cloak of thick grey fur , his eyes fixed on the deadly instrument of the attempted assassination .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["firmly onto joffrey 's arm . the prince 's ornate crimson and gold velvet doublet is torn , and his polished leather boots kick frantically in the air . nearby , a young arya stark , dressed in mud - splattered brown leather and rough linen , stands with a defiant , tear - streaked face , clutching a wooden stick . the ground is a mess of trampled emerald grass and damp river silt . sunlight filters through the canopy of ancient , whispering trees , creating sharp contrasts of light and shadow . the atmosphere is thick with tension , the spray of river water and the dust kicked up by the panicked horse adding a gritty , visceral realism to the sudden attack ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["firmly onto joffrey 's arm . the prince 's ornate crimson and gold velvet doublet is torn , and his polished leather boots kick frantically in the air . nearby , a young arya stark , dressed in mud - splattered brown leather and rough linen , stands with a defiant , tear - streaked face , clutching a wooden stick . the ground is a mess of trampled emerald grass and damp river silt . sunlight filters through the canopy of ancient , whispering trees , creating sharp contrasts of light and shadow . the atmosphere is thick with tension , the spray of river water and the dust kicked up by the panicked horse adding a gritty , visceral realism to the sudden attack ."]
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ["eyes, is captured mid-leap, her powerful jaws clamped firmly onto Joffrey's arm. The prince's ornate crimson and gold velvet doublet is torn, and his polished leather boots kick frantically in the air. Nearby, a young Arya Stark, dressed in mud-splattered brown leather and rough linen, stands with a defiant, tear-streaked face, clutching a wooden stick. The ground is a mess of trampled emerald grass and damp river silt. Sunlight filters through the canopy of ancient, whispering trees, creating sharp contrasts of light and shadow. The atmosphere is thick with tension, the spray of river water and the dust kicked up by the panicked horse adding a gritty, visceral realism to the sudden attack."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["grey cobblestones . ned 's expression is shattered , eyes glistening with unshed tears as he leans close to the creature , his voice a silent whisper of apology . he wears a heavy , dark grey wool doublet with thick leather fastenings and a fur - lined cloak that clings to his broad shoulders . the atmosphere is oppressive and somber , lit by the pale , filtered light of a cloudy afternoon that casts soft , muted shadows across the scene . in the background , the towering red walls of the fortress loom , cold and indifferent . the air is thick with a sense of inevitable tragedy , capturing the precise moment of a father 's heartbreaking sacrifice ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["grey cobblestones . ned 's expression is shattered , eyes glistening with unshed tears as he leans close to the creature , his voice a silent whisper of apology . he wears a heavy , dark grey wool doublet with thick leather fastenings and a fur - lined cloak that clings to his broad shoulders . the atmosphere is oppressive and somber , lit by the pale , filtered light of a cloudy afternoon that casts soft , muted shadows across the scene . in the background , the towering red walls of the fortress loom , cold and indifferent . the air is thick with a sense of inevitable tragedy , capturing the precise moment of a father 's heartbreaking sacrifice ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["gently outstretched , touching the pup 's forehead as the creature leans in with curious trust . around them , the landscape is a stark wilderness of towering , frost - covered sentinel trees and a heavy , oppressive grey sky . the air is thick with a biting chill , visible as faint puffs of breath from both boy and wolf . soft , diffused winter light filters through the canopy , casting muted shadows across the pristine snow . the scene is one of quiet wonder and destiny , capturing the raw , gritty texture of the north , from the coarse weave of bran 's cloak to the wet , cold nose of the wolf ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["gently outstretched , touching the pup 's forehead as the creature leans in with curious trust . around them , the landscape is a stark wilderness of towering , frost - covered sentinel trees and a heavy , oppressive grey sky . the air is thick with a biting chill , visible as faint puffs of breath from both boy and wolf . soft , diffused winter light filters through the canopy , casting muted shadows across the pristine snow . the scene is one of quiet wonder and destiny , capturing the raw , gritty texture of the north , from the coarse weave of bran 's cloak to the wet , cold nose of the wolf ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["a silver direwolf brooch , and his weathered leather tunic shows the wear of the north . opposite him , the atmosphere is thick with accusation . the room is illuminated by a few flickering wall torches that cast long , dancing shadows across the rough - hewn granite walls and cold floor . dust motes dance in the orange light , highlighting the stark contrast between the shimmering , otherworldly metal of the blade and the gritty , muted tones of the room . ned 's brow is furrowed , his eyes piercing as he speaks of tyrion lannister , the air heavy with the weight of a betrayal that threatens the peace of his household ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["a silver direwolf brooch , and his weathered leather tunic shows the wear of the north . opposite him , the atmosphere is thick with accusation . the room is illuminated by a few flickering wall torches that cast long , dancing shadows across the rough - hewn granite walls and cold floor . dust motes dance in the orange light , highlighting the stark contrast between the shimmering , otherworldly metal of the blade and the gritty , muted tones of the room . ned 's brow is furrowed , his eyes piercing as he speaks of tyrion lannister , the air heavy with the weight of a betrayal that threatens the peace of his household ."]
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ["ilt, gripping it tightly as he presents the evidence. His heavy grey wool cloak is fastened with a silver direwolf brooch, and his weathered leather tunic shows the wear of the North. Opposite him, the atmosphere is thick with accusation. The room is illuminated by a few flickering wall torches that cast long, dancing shadows across the rough-hewn granite walls and cold floor. Dust motes dance in the orange light, highlighting the stark contrast between the shimmering, otherworldly metal of the blade and the gritty, muted tones of the room. Ned's brow is furrowed, his eyes piercing as he speaks of Tyrion Lannister, the air heavy with the weight of a betrayal that threatens the peace of his household."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['looking small and bony , stands sideways in a precise fencing stance , her face a mask of intense concentration and nervousness . she grips a heavy wooden practice sword — weighted with lead — in her left hand , her knuckles white . syrio is mid - motion , his hand adjusting the placement of her fingers on the hilt to ensure a perfect grip . the room is bathed in pale , dusty midday light filtering through high windows , casting long , soft shadows across the cold stone floor . arya wears simple , rough - spun linen clothes , slightly rumpled , contrasting with the disciplined , rhythmic atmosphere of the lethal dance .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['looking small and bony , stands sideways in a precise fencing stance , her face a mask of intense concentration and nervousness . she grips a heavy wooden practice sword — weighted with lead — in her left hand , her knuckles white . syrio is mid - motion , his hand adjusting the placement of her fingers on the hilt to ensure a perfect grip . the room is bathed in pale , dusty midday light filtering through high windows , casting long , soft shadows across the cold stone floor . arya wears simple , rough - spun linen clothes , slightly rumpled , contrasting with the disciplined , rhythmic atmosphere of the lethal dance .']
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ['a poised, fluid grace, his expression stern yet focused, as he guides Arya in the Water Dance. Arya, looking small and bony, stands sideways in a precise fencing stance, her face a mask of intense concentration and nervousness. She grips a heavy wooden practice sword—weighted with lead—in her left hand, her knuckles white. Syrio is mid-motion, his hand adjusting the placement of her fingers on the hilt to ensure a perfect grip. The room is bathed in pale, dusty midday light filtering through high windows, casting long, soft shadows across the cold stone floor. Arya wears simple, rough-spun linen clothes, slightly rumpled, contrasting with the disciplined, rhythmic atmosphere of the lethal dance.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["of gentle realization as she softly presses her fingers against daenerys 's lower abdomen . daenerys looks down at her own belly , her violet eyes shimmering with a mixture of shock and newfound strength , her lips parted in a silent , knowing breath . the surrounding landscape is an infinite horizon of waving green grasses that mimic the motion of ocean waves under a brilliant , searing sun . the lighting is golden and hazy , casting a soft glow over their skin and highlighting the intricate textures of the woven dothraki fabrics . the atmosphere is heavy with a sense of destiny and secret power , captured in a tender , hushed exchange amidst the wild openness of the plains ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["of gentle realization as she softly presses her fingers against daenerys 's lower abdomen . daenerys looks down at her own belly , her violet eyes shimmering with a mixture of shock and newfound strength , her lips parted in a silent , knowing breath . the surrounding landscape is an infinite horizon of waving green grasses that mimic the motion of ocean waves under a brilliant , searing sun . the lighting is golden and hazy , casting a soft glow over their skin and highlighting the intricate textures of the woven dothraki fabrics . the atmosphere is heavy with a sense of destiny and secret power , captured in a tender , hushed exchange amidst the wild openness of the plains ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', stained with the red dust of the plains , while viserys is clad in a faded , once - opulent silk tunic of pale gold , now frayed and soiled . around them , the khalasar watches in tense silence ; dothraki bloodriders on powerful horses loom in the background , their leather armor and bronze ornaments glinting . the scene is bathed in the harsh , oppressive glare of a midday sun , casting short , obsidian shadows across the parched earth . a swirling haze of golden dust clings to their clothes and hair , blurring the horizon of the vast , undulating grasslands , emphasizing the raw , gritty tension of a power shift .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', stained with the red dust of the plains , while viserys is clad in a faded , once - opulent silk tunic of pale gold , now frayed and soiled . around them , the khalasar watches in tense silence ; dothraki bloodriders on powerful horses loom in the background , their leather armor and bronze ornaments glinting . the scene is bathed in the harsh , oppressive glare of a midday sun , casting short , obsidian shadows across the parched earth . a swirling haze of golden dust clings to their clothes and hair , blurring the horizon of the vast , undulating grasslands , emphasizing the raw , gritty tension of a power shift .']
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ['a travel-worn Dothraki gown of rough-spun cream linen, stained with the red dust of the plains, while Viserys is clad in a faded, once-opulent silk tunic of pale gold, now frayed and soiled. Around them, the khalasar watches in tense silence; Dothraki bloodriders on powerful horses loom in the background, their leather armor and bronze ornaments glinting. The scene is bathed in the harsh, oppressive glare of a midday sun, casting short, obsidian shadows across the parched earth. A swirling haze of golden dust clings to their clothes and hair, blurring the horizon of the vast, undulating grasslands, emphasizing the raw, gritty tension of a power shift.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["he wears a coarse , oversized tunic of rough - spun grey wool and heavy , mud - caked leather boots that sink into the damp earth of winterfell . bran clings to him , his small hands gripping the rough fabric of hodor 's shoulder , his expression one of quiet trust . they move through a dim , stone corridor of the ancient fortress , where the air is thick with cold moisture . pale , wintry light filters through narrow arrow - slits , casting long , stark shadows across the uneven cobblestones . the atmosphere is somber and hushed , illuminated by the flickering , orange glow of a distant wall torch that highlights the gritty texture of the damp granite walls ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["he wears a coarse , oversized tunic of rough - spun grey wool and heavy , mud - caked leather boots that sink into the damp earth of winterfell . bran clings to him , his small hands gripping the rough fabric of hodor 's shoulder , his expression one of quiet trust . they move through a dim , stone corridor of the ancient fortress , where the air is thick with cold moisture . pale , wintry light filters through narrow arrow - slits , casting long , stark shadows across the uneven cobblestones . the atmosphere is somber and hushed , illuminated by the flickering , orange glow of a distant wall torch that highlights the gritty texture of the damp granite walls ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['. gendry , shirtless and glistening with perspiration , pauses mid - action , his powerful arms strained as he grips a heavy iron hammer . he looks toward eddard stark with sullen , brooding blue eyes , his jaw shadowed by a coarse , emerging beard . around them , the forge glows with an intense , oppressive orange heat , casting deep , flickering shadows against the soot - stained walls . other apprentices labor in the background , pumping massive leather bellows that breathe fire into the hearths . the lighting is a stark chiaroscuro , where the blinding white - hot glow of molten steel clashes with the oppressive darkness of the stone chamber , highlighting the grime and grit of the smithy .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['. gendry , shirtless and glistening with perspiration , pauses mid - action , his powerful arms strained as he grips a heavy iron hammer . he looks toward eddard stark with sullen , brooding blue eyes , his jaw shadowed by a coarse , emerging beard . around them , the forge glows with an intense , oppressive orange heat , casting deep , flickering shadows against the soot - stained walls . other apprentices labor in the background , pumping massive leather bellows that breathe fire into the hearths . the lighting is a stark chiaroscuro , where the blinding white - hot glow of molten steel clashes with the oppressive darkness of the stone chamber , highlighting the grime and grit of the smithy .']
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ['-black, unruly hair plastered to his forehead by sweat. Gendry, shirtless and glistening with perspiration, pauses mid-action, his powerful arms strained as he grips a heavy iron hammer. He looks toward Eddard Stark with sullen, brooding blue eyes, his jaw shadowed by a coarse, emerging beard. Around them, the forge glows with an intense, oppressive orange heat, casting deep, flickering shadows against the soot-stained walls. Other apprentices labor in the background, pumping massive leather bellows that breathe fire into the hearths. The lighting is a stark chiaroscuro, where the blinding white-hot glow of molten steel clashes with the oppressive darkness of the stone chamber, highlighting the grime and grit of the smithy.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["is soft - featured and overweight , his face wet with tears of desperation , dressed in fine but ill - fitting velvet doublets of house tarly . randyll ’ s expression is one of cold disgust and disappointment , his posture rigid as he forces his son toward a waiting escort . the room is dimly lit by flickering wall torches that cast long , oppressive shadows across the grey granite floors and heavy oak furniture . cold winter light filters through narrow slits in the masonry , illuminating dust motes in the air . the atmosphere is suffocating and cruel , capturing the moment of a father 's brutal rejection as he casts his son away to the wall ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["is soft - featured and overweight , his face wet with tears of desperation , dressed in fine but ill - fitting velvet doublets of house tarly . randyll ’ s expression is one of cold disgust and disappointment , his posture rigid as he forces his son toward a waiting escort . the room is dimly lit by flickering wall torches that cast long , oppressive shadows across the grey granite floors and heavy oak furniture . cold winter light filters through narrow slits in the masonry , illuminating dust motes in the air . the atmosphere is suffocating and cruel , capturing the moment of a father 's brutal rejection as he casts his son away to the wall ."]
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: [", Samwell Tarly, who is trembling and shrinking back in terror. Sam is soft-featured and overweight, his face wet with tears of desperation, dressed in fine but ill-fitting velvet doublets of House Tarly. Randyll’s expression is one of cold disgust and disappointment, his posture rigid as he forces his son toward a waiting escort. The room is dimly lit by flickering wall torches that cast long, oppressive shadows across the grey granite floors and heavy oak furniture. Cold winter light filters through narrow slits in the masonry, illuminating dust motes in the air. The atmosphere is suffocating and cruel, capturing the moment of a father's brutal rejection as he casts his son away to the Wall."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['blue silk , embroidered with delicate golden crescents , billows violently in the wind . his face is youthful and strikingly handsome , wearing a smirk of effortless confidence . around him , the tourney grounds are a chaos of churned brown earth and scattered straw . in the background , the blurred shapes of cheering crowds and colorful pavilions create a sense of scale . the lighting is a harsh , brilliant midday sun that creates sharp highlights on the steel and deep , dramatic shadows in the folds of his cloak , emphasizing the stark contrast between his pristine beauty and the gritty , dusty reality of the arena .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['blue silk , embroidered with delicate golden crescents , billows violently in the wind . his face is youthful and strikingly handsome , wearing a smirk of effortless confidence . around him , the tourney grounds are a chaos of churned brown earth and scattered straw . in the background , the blurred shapes of cheering crowds and colorful pavilions create a sense of scale . the lighting is a harsh , brilliant midday sun that creates sharp highlights on the steel and deep , dramatic shadows in the folds of his cloak , emphasizing the stark contrast between his pristine beauty and the gritty , dusty reality of the arena .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['by two burly guards . tyrion , small in stature with mismatched eyes and a scarred face , looks up with a mixture of shock and defiant amusement , his rich crimson velvet doublet rumpled and stained with spilled ale . around them , the common room is a chaos of overturned stools and startled peasants . the air is thick with the smell of roasting meat and damp wool . harsh , flickering orange light from a massive stone hearth casts long , dancing shadows across the timbered walls , while a cold , grey rain streaks the windowpanes , blurring the desolate landscape outside .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['by two burly guards . tyrion , small in stature with mismatched eyes and a scarred face , looks up with a mixture of shock and defiant amusement , his rich crimson velvet doublet rumpled and stained with spilled ale . around them , the common room is a chaos of overturned stools and startled peasants . the air is thick with the smell of roasting meat and damp wool . harsh , flickering orange light from a massive stone hearth casts long , dancing shadows across the timbered walls , while a cold , grey rain streaks the windowpanes , blurring the desolate landscape outside .']
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ['commanding finger at Tyrion Lannister, who is being violently hauled upward from a rough-hewn wooden table by two burly guards. Tyrion, small in stature with mismatched eyes and a scarred face, looks up with a mixture of shock and defiant amusement, his rich crimson velvet doublet rumpled and stained with spilled ale. Around them, the common room is a chaos of overturned stools and startled peasants. The air is thick with the smell of roasting meat and damp wool. Harsh, flickering orange light from a massive stone hearth casts long, dancing shadows across the timbered walls, while a cold, grey rain streaks the windowpanes, blurring the desolate landscape outside.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['wears a heavy , mud - splattered woolen cloak of deep grey over a sturdy travel dress , her auburn hair damp from the relentless drizzle . surrounding them , armored men - at - arms in weathered steel ringmail and boiled leather push the captives toward the jagged , towering peaks of the arryn mountains . the atmosphere is oppressive and bleak ; a thick , slate - grey mist clings to the steep cliffs , blurring the horizon . the lighting is a dim , diffused silver , casting soft , melancholy shadows across the wet stone and sodden earth , emphasizing the isolation and the growing tension of the kidnapping .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['wears a heavy , mud - splattered woolen cloak of deep grey over a sturdy travel dress , her auburn hair damp from the relentless drizzle . surrounding them , armored men - at - arms in weathered steel ringmail and boiled leather push the captives toward the jagged , towering peaks of the arryn mountains . the atmosphere is oppressive and bleak ; a thick , slate - grey mist clings to the steep cliffs , blurring the horizon . the lighting is a dim , diffused silver , casting soft , melancholy shadows across the wet stone and sodden earth , emphasizing the isolation and the growing tension of the kidnapping .']
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ['elyn Stark rides a powerful warhorse, her expression a mask of cold, unwavering determination. She wears a heavy, mud-splattered woolen cloak of deep grey over a sturdy travel dress, her auburn hair damp from the relentless drizzle. Surrounding them, armored men-at-arms in weathered steel ringmail and boiled leather push the captives toward the jagged, towering peaks of the Arryn mountains. The atmosphere is oppressive and bleak; a thick, slate-grey mist clings to the steep cliffs, blurring the horizon. The lighting is a dim, diffused silver, casting soft, melancholy shadows across the wet stone and sodden earth, emphasizing the isolation and the growing tension of the kidnapping.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["railing tightly , knuckles white , as she gazes down at the dizzying drop of the giant 's lance . around her , the air is thin and biting , with swirling mountain mists clinging to the jagged spires that pierce the sky like daggers . the lighting is a harsh , pale morning sun filtering through a veil of freezing fog , casting long , ghostly shadows across the courtyard below . the atmosphere is one of oppressive isolation and quiet tension , where the wind howls through the open arches , whipping her hair across a face marked by the grief and paranoia of a widow ruling a secluded kingdom ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["railing tightly , knuckles white , as she gazes down at the dizzying drop of the giant 's lance . around her , the air is thin and biting , with swirling mountain mists clinging to the jagged spires that pierce the sky like daggers . the lighting is a harsh , pale morning sun filtering through a veil of freezing fog , casting long , ghostly shadows across the courtyard below . the atmosphere is one of oppressive isolation and quiet tension , where the wind howls through the open arches , whipping her hair across a face marked by the grief and paranoia of a widow ruling a secluded kingdom ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['the hilt of a well - used steel longsword . opposite him , a knight of the vale in polished , interlocking steel ringmail and a heavy blue surcoat bristles with indignation . in the background , tyrion lannister watches with a mixture of anxiety and defiance , his small frame draped in a rich but travel - worn crimson velvet doublet . the architecture is cold and imposing , with towering white marble pillars and high vaulted ceilings . pale , wintry light filters through narrow slits in the stone , casting long , stark shadows across the polished floor , while the atmosphere is thick with the oppressive silence of the court and the scent of cold stone .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['the hilt of a well - used steel longsword . opposite him , a knight of the vale in polished , interlocking steel ringmail and a heavy blue surcoat bristles with indignation . in the background , tyrion lannister watches with a mixture of anxiety and defiance , his small frame draped in a rich but travel - worn crimson velvet doublet . the architecture is cold and imposing , with towering white marble pillars and high vaulted ceilings . pale , wintry light filters through narrow slits in the stone , casting long , stark shadows across the polished floor , while the atmosphere is thick with the oppressive silence of the court and the scent of cold stone .']
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ['s weathered, salt-stained boiled leather armor and a rough linen tunic, his hand gripping the hilt of a well-used steel longsword. Opposite him, a knight of the Vale in polished, interlocking steel ringmail and a heavy blue surcoat bristles with indignation. In the background, Tyrion Lannister watches with a mixture of anxiety and defiance, his small frame draped in a rich but travel-worn crimson velvet doublet. The architecture is cold and imposing, with towering white marble pillars and high vaulted ceilings. Pale, wintry light filters through narrow slits in the stone, casting long, stark shadows across the polished floor, while the atmosphere is thick with the oppressive silence of the court and the scent of cold stone.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['two conspirators . a few paces ahead , a portly man in a short , heavy leather cloak and a dull steel helmet leans in close to his companion . beside him stands a man with a distinctive , bifurcated yellow goatee , his expression cunning and low . the air is thick with moisture and the stench of decay . a single , flickering torch held by the men casts long , dancing shadows and a harsh orange glow that cuts through the suffocating darkness , highlighting the grime on their clothes and the tension in their hushed argument . the scene is a gritty tableau of secrecy , where the cold stone walls seem to close in around the hidden girl .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['two conspirators . a few paces ahead , a portly man in a short , heavy leather cloak and a dull steel helmet leans in close to his companion . beside him stands a man with a distinctive , bifurcated yellow goatee , his expression cunning and low . the air is thick with moisture and the stench of decay . a single , flickering torch held by the men casts long , dancing shadows and a harsh orange glow that cuts through the suffocating darkness , highlighting the grime on their clothes and the tension in their hushed argument . the scene is a gritty tableau of secrecy , where the cold stone walls seem to close in around the hidden girl .']
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ['of intense alertness, her wide eyes filled with fear and curiosity as she eavesdrops on two conspirators. A few paces ahead, a portly man in a short, heavy leather cloak and a dull steel helmet leans in close to his companion. Beside him stands a man with a distinctive, bifurcated yellow goatee, his expression cunning and low. The air is thick with moisture and the stench of decay. A single, flickering torch held by the men casts long, dancing shadows and a harsh orange glow that cuts through the suffocating darkness, highlighting the grime on their clothes and the tension in their hushed argument. The scene is a gritty tableau of secrecy, where the cold stone walls seem to close in around the hidden girl.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["smeared with grey stone dust . bronn is captured mid - action , gripping his longsword with both hands , driving the blade with his full body weight deep into the gap of the knight 's armpit , piercing the interlocking steel ringmail . the scene is thick with tension ; the air is cold and thin . high above , the pale , stark light of a mountain moon filters through the open architecture , casting long , harsh shadows across the pale stone floor . bronn wears weathered , blood - stained boiled leather and rough wool , his expression one of cold professionalism , contrasting with the wide - eyed terror and agony on ser vardis 's face ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["smeared with grey stone dust . bronn is captured mid - action , gripping his longsword with both hands , driving the blade with his full body weight deep into the gap of the knight 's armpit , piercing the interlocking steel ringmail . the scene is thick with tension ; the air is cold and thin . high above , the pale , stark light of a mountain moon filters through the open architecture , casting long , harsh shadows across the pale stone floor . bronn wears weathered , blood - stained boiled leather and rough wool , his expression one of cold professionalism , contrasting with the wide - eyed terror and agony on ser vardis 's face ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['thick cloak of sky - blue wool draped over his shoulders . opposite him , the small , battered figure of tyrion lannister stands defiant , his face bruised and swollen , wearing travel - worn crimson velvet and gold brocade that is stained with the grime of the dungeons . lady lysa arryn watches from her high throne of pale moonstone , her expression a mask of cold cruelty and twisted triumph . the hall is a cavern of white marble and soaring arches , illuminated by pale , wintry light filtering through high windows , casting long , stark shadows across the polished floor . the atmosphere is thick with hostility , the air cold and breathless as the court looks on in silence .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['thick cloak of sky - blue wool draped over his shoulders . opposite him , the small , battered figure of tyrion lannister stands defiant , his face bruised and swollen , wearing travel - worn crimson velvet and gold brocade that is stained with the grime of the dungeons . lady lysa arryn watches from her high throne of pale moonstone , her expression a mask of cold cruelty and twisted triumph . the hall is a cavern of white marble and soaring arches , illuminated by pale , wintry light filtering through high windows , casting long , stark shadows across the polished floor . the atmosphere is thick with hostility , the air cold and breathless as the court looks on in silence .']
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: [', etched with the falcon of House Arryn, with a thick cloak of sky-blue wool draped over his shoulders. Opposite him, the small, battered figure of Tyrion Lannister stands defiant, his face bruised and swollen, wearing travel-worn crimson velvet and gold brocade that is stained with the grime of the dungeons. Lady Lysa Arryn watches from her high throne of pale moonstone, her expression a mask of cold cruelty and twisted triumph. The hall is a cavern of white marble and soaring arches, illuminated by pale, wintry light filtering through high windows, casting long, stark shadows across the polished floor. The atmosphere is thick with hostility, the air cold and breathless as the court looks on in silence.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['grey wool doublet with a thick fur mantle draped over his shoulders , the fabric coarse and weathered . robert , bloated and flushed with rage , leans forward in his carved throne , his gold - embroidered crimson tunic strained . between them , the air is thick with tension . the room is illuminated by flickering orange torchlight that casts long , dancing shadows against the cold stone walls and towering tapestries . dust motes dance in the singular shafts of pale light filtering through high , narrow windows . the atmosphere is suffocating and grim , capturing the exact moment ned refuses to seal the death warrant of a young princess .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['grey wool doublet with a thick fur mantle draped over his shoulders , the fabric coarse and weathered . robert , bloated and flushed with rage , leans forward in his carved throne , his gold - embroidered crimson tunic strained . between them , the air is thick with tension . the room is illuminated by flickering orange torchlight that casts long , dancing shadows against the cold stone walls and towering tapestries . dust motes dance in the singular shafts of pale light filtering through high , narrow windows . the atmosphere is suffocating and grim , capturing the exact moment ned refuses to seal the death warrant of a young princess .']
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ['he stares down King Robert Baratheon. Ned wears a heavy, charcoal-grey wool doublet with a thick fur mantle draped over his shoulders, the fabric coarse and weathered. Robert, bloated and flushed with rage, leans forward in his carved throne, his gold-embroidered crimson tunic strained. Between them, the air is thick with tension. The room is illuminated by flickering orange torchlight that casts long, dancing shadows against the cold stone walls and towering tapestries. Dust motes dance in the singular shafts of pale light filtering through high, narrow windows. The atmosphere is suffocating and grim, capturing the exact moment Ned refuses to seal the death warrant of a young princess.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['a tunic of boiled leather and rough - spun linen . in the distance , the colossal , melted towers of harrenhal loom like blackened , twisted fingers against a pale , shimmering sky . the atmosphere is thick with the scent of damp earth and blooming wildflowers . soft , golden sunlight filters through a light haze , casting a nostalgic , ethereal glow over the landscape . ned ’ s expression is one of wide - eyed wonder and anticipation , his hand gripping the leather reins . the scene captures the transition from the cold north to the deceptive warmth of the south , blending the grit of medieval travel with the haunting , surreal beauty of a fever dream .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['a tunic of boiled leather and rough - spun linen . in the distance , the colossal , melted towers of harrenhal loom like blackened , twisted fingers against a pale , shimmering sky . the atmosphere is thick with the scent of damp earth and blooming wildflowers . soft , golden sunlight filters through a light haze , casting a nostalgic , ethereal glow over the landscape . ned ’ s expression is one of wide - eyed wonder and anticipation , his hand gripping the leather reins . the scene captures the transition from the cold north to the deceptive warmth of the south , blending the grit of medieval travel with the haunting , surreal beauty of a fever dream .']
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ['ak of charcoal wool fastened by a silver wolf-head brooch, over a tunic of boiled leather and rough-spun linen. In the distance, the colossal, melted towers of Harrenhal loom like blackened, twisted fingers against a pale, shimmering sky. The atmosphere is thick with the scent of damp earth and blooming wildflowers. Soft, golden sunlight filters through a light haze, casting a nostalgic, ethereal glow over the landscape. Ned’s expression is one of wide-eyed wonder and anticipation, his hand gripping the leather reins. The scene captures the transition from the cold North to the deceptive warmth of the south, blending the grit of medieval travel with the haunting, surreal beauty of a fever dream.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["legacy . he is mid - motion , fastening a wide , ornate belt crafted from heavy medallions of hammered gold , silver , and bronze over a painted leather vest . beside him , daenerys targaryen is propped up on one elbow atop a heap of rich , textured sleeping furs , her pale skin contrasting with the dark fabrics . her expression is one of yearning and intensity as she looks up at him , pleading for the conquest of the west . the atmosphere is charged with narrative tension ; drogo 's face is stern , his lips pursed beneath a long mustache , dismissing her talk of wooden horses . harsh chiaroscuro lighting casts long , dancing shadows against the canvas walls , emphasizing the raw power of the dothraki warlord ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["legacy . he is mid - motion , fastening a wide , ornate belt crafted from heavy medallions of hammered gold , silver , and bronze over a painted leather vest . beside him , daenerys targaryen is propped up on one elbow atop a heap of rich , textured sleeping furs , her pale skin contrasting with the dark fabrics . her expression is one of yearning and intensity as she looks up at him , pleading for the conquest of the west . the atmosphere is charged with narrative tension ; drogo 's face is stern , his lips pursed beneath a long mustache , dismissing her talk of wooden horses . harsh chiaroscuro lighting casts long , dancing shadows against the canvas walls , emphasizing the raw power of the dothraki warlord ."]
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ["heavy, uncut curtain past his waist, symbolizing his undefeated legacy. He is mid-motion, fastening a wide, ornate belt crafted from heavy medallions of hammered gold, silver, and bronze over a painted leather vest. Beside him, Daenerys Targaryen is propped up on one elbow atop a heap of rich, textured sleeping furs, her pale skin contrasting with the dark fabrics. Her expression is one of yearning and intensity as she looks up at him, pleading for the conquest of the West. The atmosphere is charged with narrative tension; Drogo's face is stern, his lips pursed beneath a long mustache, dismissing her talk of wooden horses. Harsh chiaroscuro lighting casts long, dancing shadows against the canvas walls, emphasizing the raw power of the Dothraki warlord."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["wool tunic , their expressions greedy and cruel . bran 's useless legs hang limp in the stirrups , his small hands frozen and trembling . the scene is set amidst a dense , oppressive forest where ancient , gnarled roots break through a thin , fresh layer of slushy snow . a heavy , grey mist clings to the towering pines , blurring the horizon . the lighting is dim and cold , with a pale , filtered winter light casting muted tones across the damp earth and mud - splattered boots of the attackers , creating an atmosphere of sudden , suffocating dread and vulnerability ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["wool tunic , their expressions greedy and cruel . bran 's useless legs hang limp in the stirrups , his small hands frozen and trembling . the scene is set amidst a dense , oppressive forest where ancient , gnarled roots break through a thin , fresh layer of slushy snow . a heavy , grey mist clings to the towering pines , blurring the horizon . the lighting is dim and cold , with a pale , filtered winter light casting muted tones across the damp earth and mud - splattered boots of the attackers , creating an atmosphere of sudden , suffocating dread and vulnerability ."]
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ["ly yanks at the horse's bridle, while another reaches up to tear at Bran's fine wool tunic, their expressions greedy and cruel. Bran's useless legs hang limp in the stirrups, his small hands frozen and trembling. The scene is set amidst a dense, oppressive forest where ancient, gnarled roots break through a thin, fresh layer of slushy snow. A heavy, grey mist clings to the towering pines, blurring the horizon. The lighting is dim and cold, with a pale, filtered winter light casting muted tones across the damp earth and mud-splattered boots of the attackers, creating an atmosphere of sudden, suffocating dread and vulnerability."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["knowing smile , delivers the humbling news of jon 's assignment . jon 's expression is one of quiet shock , his dark eyes wide and his jaw slightly slack as he realizes he has been relegated to a servant . in the background , the blurred figures of other recruits depart , while the blind maester aemon remains a ghostly , silent presence . the atmosphere is oppressive and damp , with grey light filtering through narrow slits in the thick granite walls . a single iron torch bracket casts flickering , orange light and long , dancing shadows across the floor , highlighting the gritty texture of the frost - covered stone and the stark , bleak reality of jon 's new life ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["knowing smile , delivers the humbling news of jon 's assignment . jon 's expression is one of quiet shock , his dark eyes wide and his jaw slightly slack as he realizes he has been relegated to a servant . in the background , the blurred figures of other recruits depart , while the blind maester aemon remains a ghostly , silent presence . the atmosphere is oppressive and damp , with grey light filtering through narrow slits in the thick granite walls . a single iron torch bracket casts flickering , orange light and long , dancing shadows across the floor , highlighting the gritty texture of the frost - covered stone and the stark , bleak reality of jon 's new life ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["caked hunting tunic of deep gold and crimson velvet , now torn and drenched in dark , visceral blood . the boar 's coarse , bristly black fur is matted with dirt and forest debris . they are surrounded by a claustrophobic woodland of gnarled oaks and damp ferns under a suffocating , grey overcast sky . shafts of pale , cold light filter through the canopy , illuminating the spray of blood and the churned - up earth beneath them . the atmosphere is heavy with the scent of pine and iron , capturing a moment of raw , violent desperation as the king collapses into the wet loam , his royal dignity shattered by the beast 's primal fury ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["caked hunting tunic of deep gold and crimson velvet , now torn and drenched in dark , visceral blood . the boar 's coarse , bristly black fur is matted with dirt and forest debris . they are surrounded by a claustrophobic woodland of gnarled oaks and damp ferns under a suffocating , grey overcast sky . shafts of pale , cold light filter through the canopy , illuminating the spray of blood and the churned - up earth beneath them . the atmosphere is heavy with the scent of pine and iron , capturing a moment of raw , violent desperation as the king collapses into the wet loam , his royal dignity shattered by the beast 's primal fury ."]
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ["and agony as a tusk rips deep into his abdomen. He wears a heavy, mud-caked hunting tunic of deep gold and crimson velvet, now torn and drenched in dark, visceral blood. The boar's coarse, bristly black fur is matted with dirt and forest debris. They are surrounded by a claustrophobic woodland of gnarled oaks and damp ferns under a suffocating, grey overcast sky. Shafts of pale, cold light filter through the canopy, illuminating the spray of blood and the churned-up earth beneath them. The atmosphere is heavy with the scent of pine and iron, capturing a moment of raw, violent desperation as the king collapses into the wet loam, his royal dignity shattered by the beast's primal fury."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['and moral agony , holds a piece of rough parchment across his knee . with a trembling hand , he grips a quill , the ink glistening black . the scene captures the precise moment of betrayal and love : ned is mid - stroke , carefully scratching the words " my heir " instead of " my son joffrey ." he wears a heavy , dark grey wool tunic with a fur mantle draped over his shoulders , the fabric coarse and worn . a single flickering candle on a nearby oak table casts long , dancing shadows and a harsh orange glow , highlighting the stark contrast between the king \'s decaying flesh and the cold , determined resolve in ned \'s eyes .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['and moral agony , holds a piece of rough parchment across his knee . with a trembling hand , he grips a quill , the ink glistening black . the scene captures the precise moment of betrayal and love : ned is mid - stroke , carefully scratching the words " my heir " instead of " my son joffrey ." he wears a heavy , dark grey wool tunic with a fur mantle draped over his shoulders , the fabric coarse and worn . a single flickering candle on a nearby oak table casts long , dancing shadows and a harsh orange glow , highlighting the stark contrast between the king \'s decaying flesh and the cold , determined resolve in ned \'s eyes .']
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ['rattling breaths. Ned, his face etched with profound grief and moral agony, holds a piece of rough parchment across his knee. With a trembling hand, he grips a quill, the ink glistening black. The scene captures the precise moment of betrayal and love: Ned is mid-stroke, carefully scratching the words "my heir" instead of "my son Joffrey." He wears a heavy, dark grey wool tunic with a fur mantle draped over his shoulders, the fabric coarse and worn. A single flickering candle on a nearby oak table casts long, dancing shadows and a harsh orange glow, highlighting the stark contrast between the king\'s decaying flesh and the cold, determined resolve in Ned\'s eyes.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['to the ground , mirroring the predatory stance of a mangy , one - eared black cat that arches its back and hisses at her from the shadows . the environment is a gritty labyrinth of grey limestone walls and oppressive architecture , with piles of refuse and damp moss clinging to the corners . harsh , slanted sunlight filters down from high ramparts , creating a stark contrast of blinding light and deep , ink - black shadows . the air is thick with the smell of salt and old stone . her hands are scarred with raw scratches and half - healed scabs , highlighting her desperation and the ruggedness of her secret training in the heart of the castle .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['to the ground , mirroring the predatory stance of a mangy , one - eared black cat that arches its back and hisses at her from the shadows . the environment is a gritty labyrinth of grey limestone walls and oppressive architecture , with piles of refuse and damp moss clinging to the corners . harsh , slanted sunlight filters down from high ramparts , creating a stark contrast of blinding light and deep , ink - black shadows . the air is thick with the smell of salt and old stone . her hands are scarred with raw scratches and half - healed scabs , highlighting her desperation and the ruggedness of her secret training in the heart of the castle .']
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ['concentration and fear. She is mid-stride, crouching low to the ground, mirroring the predatory stance of a mangy, one-eared black cat that arches its back and hisses at her from the shadows. The environment is a gritty labyrinth of grey limestone walls and oppressive architecture, with piles of refuse and damp moss clinging to the corners. Harsh, slanted sunlight filters down from high ramparts, creating a stark contrast of blinding light and deep, ink-black shadows. The air is thick with the smell of salt and old stone. Her hands are scarred with raw scratches and half-healed scabs, highlighting her desperation and the ruggedness of her secret training in the heart of the castle.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["stripped naked and trembling with terror , his limbs bound with rough hemp ropes to the back of a heavy wooden wagon . the wagon 's wheels churn through the dry , golden earth , kicking up clouds of grit . dothraki bloodriders on lean horses circle the procession , their curved arakhs gleaming under a harsh , oppressive sun . the atmosphere is thick with tension and the smell of sweat and dust . stark , high - contrast lighting creates deep shadows , emphasizing the raw muscles of the warriors and the desperate , strained muscles of the condemned man as he is dragged across the unforgiving terrain ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["stripped naked and trembling with terror , his limbs bound with rough hemp ropes to the back of a heavy wooden wagon . the wagon 's wheels churn through the dry , golden earth , kicking up clouds of grit . dothraki bloodriders on lean horses circle the procession , their curved arakhs gleaming under a harsh , oppressive sun . the atmosphere is thick with tension and the smell of sweat and dust . stark , high - contrast lighting creates deep shadows , emphasizing the raw muscles of the warriors and the desperate , strained muscles of the condemned man as he is dragged across the unforgiving terrain ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['wild hair , listen intently . robb wears a heavy cloak of grey wool fastened by a silver direwolf brooch , over a tunic of boiled leather and a gambeson of quilted linen . the karstarks are draped in massive , coarse furs of bear and wolf , their steel spear - tips glinting coldly . the atmosphere is heavy with the scent of wet earth and horse musk . a pale , wintry sun struggles to pierce through a slate - grey sky , casting a flat , oppressive light over the scene , while the distant sound of a deep war drum echoes against the ancient granite walls of the fortress .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['wild hair , listen intently . robb wears a heavy cloak of grey wool fastened by a silver direwolf brooch , over a tunic of boiled leather and a gambeson of quilted linen . the karstarks are draped in massive , coarse furs of bear and wolf , their steel spear - tips glinting coldly . the atmosphere is heavy with the scent of wet earth and horse musk . a pale , wintry sun struggles to pierce through a slate - grey sky , casting a flat , oppressive light over the scene , while the distant sound of a deep war drum echoes against the ancient granite walls of the fortress .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["studded oak gates that block the crossing . robb is clad in heavy , mud - splattered steel plate armor and a thick fur cloak that catches the damp wind . beside him , catelyn stark watches with a worried , piercing gaze , her velvet gown stained by the road . the atmosphere is oppressive and grey , with a churning , slate - colored river rushing violently beneath the towering stone bridge . a cold mist clings to the jagged fortifications , while the dim , overcast light casts deep shadows across the soldiers ' grim faces , emphasizing the suffocating tension of a diplomatic deadlock on the brink of war ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["studded oak gates that block the crossing . robb is clad in heavy , mud - splattered steel plate armor and a thick fur cloak that catches the damp wind . beside him , catelyn stark watches with a worried , piercing gaze , her velvet gown stained by the road . the atmosphere is oppressive and grey , with a churning , slate - colored river rushing violently beneath the towering stone bridge . a cold mist clings to the jagged fortifications , while the dim , overcast light casts deep shadows across the soldiers ' grim faces , emphasizing the suffocating tension of a diplomatic deadlock on the brink of war ."]
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ["appearing youthful yet burdened, gestures with a clenched fist toward the massive iron-studded oak gates that block the crossing. Robb is clad in heavy, mud-splattered steel plate armor and a thick fur cloak that catches the damp wind. Beside him, Catelyn Stark watches with a worried, piercing gaze, her velvet gown stained by the road. The atmosphere is oppressive and grey, with a churning, slate-colored river rushing violently beneath the towering stone bridge. A cold mist clings to the jagged fortifications, while the dim, overcast light casts deep shadows across the soldiers' grim faces, emphasizing the suffocating tension of a diplomatic deadlock on the brink of war."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['knees in the slushy snow . she wears rugged , interlocking furs and rough - hewn hides , her clothing stained with the grime of the wilderness . stark guards in iron - studded leather armor hold her arms firmly , their breath visible in the freezing air . around them , the ancient trees are draped in a thin shroud of white snow , their skeletal branches interlocking overhead . the lighting is a cold , oppressive grey , with a pale , wintry sun struggling to pierce through the thick canopy , casting soft , muted shadows across the frozen ground and highlighting the gritty texture of the mud and ice .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['knees in the slushy snow . she wears rugged , interlocking furs and rough - hewn hides , her clothing stained with the grime of the wilderness . stark guards in iron - studded leather armor hold her arms firmly , their breath visible in the freezing air . around them , the ancient trees are draped in a thin shroud of white snow , their skeletal branches interlocking overhead . the lighting is a cold , oppressive grey , with a pale , wintry sun struggling to pierce through the thick canopy , casting soft , muted shadows across the frozen ground and highlighting the gritty texture of the mud and ice .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["els in the dirt , his face weathered and exhausted , wearing a torn , grime - streaked linen tunic and heavy leather breeches . ned 's expression is one of grim acceptance , his eyes fixed forward . beside the throne , queen cersei and a weeping sansa stark are frozen in shock , their faces pale with desperation . a gold - cloaked guardsman stands poised with a heavy steel longsword , the blade reflecting the stark light . the atmosphere is thick with tension and the smell of dust and sweat , while the surrounding crowd is a blur of muted browns and greys , creating a sharp contrast with the royal gold and the impending violence ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["els in the dirt , his face weathered and exhausted , wearing a torn , grime - streaked linen tunic and heavy leather breeches . ned 's expression is one of grim acceptance , his eyes fixed forward . beside the throne , queen cersei and a weeping sansa stark are frozen in shock , their faces pale with desperation . a gold - cloaked guardsman stands poised with a heavy steel longsword , the blade reflecting the stark light . the atmosphere is thick with tension and the smell of dust and sweat , while the surrounding crowd is a blur of muted browns and greys , creating a sharp contrast with the royal gold and the impending violence ."]
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ["glints harshly under a blinding midday sun. Before him, Ned Stark kneels in the dirt, his face weathered and exhausted, wearing a torn, grime-streaked linen tunic and heavy leather breeches. Ned's expression is one of grim acceptance, his eyes fixed forward. Beside the throne, Queen Cersei and a weeping Sansa Stark are frozen in shock, their faces pale with desperation. A gold-cloaked guardsman stands poised with a heavy steel longsword, the blade reflecting the stark light. The atmosphere is thick with tension and the smell of dust and sweat, while the surrounding crowd is a blur of muted browns and greys, creating a sharp contrast with the royal gold and the impending violence."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['his lips before her expression hardens ; with a sudden , desperate motion , she grips a heavy fabric cushion and presses it firmly over his face to stifle his breath . she wears a sweat - stained , lightweight dothraki gown of pale silk that clings to her skin in the stifling air . drogo is clad in a weathered leather vest , his chest beneath it marked by a dried , crusty poultice of blue mud and fig leaves . the lighting is a harsh , blinding midday glare that creates shimmering heat waves across the horizon , while fat , reddish blood - flies buzz in oppressive circles around them , adding a visceral sense of decay to the silent , tragic scene .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['his lips before her expression hardens ; with a sudden , desperate motion , she grips a heavy fabric cushion and presses it firmly over his face to stifle his breath . she wears a sweat - stained , lightweight dothraki gown of pale silk that clings to her skin in the stifling air . drogo is clad in a weathered leather vest , his chest beneath it marked by a dried , crusty poultice of blue mud and fig leaves . the lighting is a harsh , blinding midday glare that creates shimmering heat waves across the horizon , while fat , reddish blood - flies buzz in oppressive circles around them , adding a visceral sense of decay to the silent , tragic scene .']
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ['former self. Daenerys presses a final, lingering kiss to his lips before her expression hardens; with a sudden, desperate motion, she grips a heavy fabric cushion and presses it firmly over his face to stifle his breath. She wears a sweat-stained, lightweight Dothraki gown of pale silk that clings to her skin in the stifling air. Drogo is clad in a weathered leather vest, his chest beneath it marked by a dried, crusty poultice of blue mud and fig leaves. The lighting is a harsh, blinding midday glare that creates shimmering heat waves across the horizon, while fat, reddish blood-flies buzz in oppressive circles around them, adding a visceral sense of decay to the silent, tragic scene.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['by his head amidst his long , braided hair , and the cream - and - gold egg placed between his legs . the air is thick with the scent of burning oil and scorched earth . as the towering inferno erupts , violent orange and crimson flames roar upward , swirling in a chaotic vortex of heat . daenerys steps into the heart of the fire , her skin glistening with oil , her simple linen gown catching fire . the lighting is a stark , blinding chiaroscuro of searing gold light and deep , soot - black shadows . the atmosphere is heavy with mystical tension , capturing the exact moment of a supernatural rebirth amidst the crackling roar of the pyre .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['by his head amidst his long , braided hair , and the cream - and - gold egg placed between his legs . the air is thick with the scent of burning oil and scorched earth . as the towering inferno erupts , violent orange and crimson flames roar upward , swirling in a chaotic vortex of heat . daenerys steps into the heart of the fire , her skin glistening with oil , her simple linen gown catching fire . the lighting is a stark , blinding chiaroscuro of searing gold light and deep , soot - black shadows . the atmosphere is heavy with mystical tension , capturing the exact moment of a supernatural rebirth amidst the crackling roar of the pyre .']
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ['egg is pressed against his heart, the green egg nestled by his head amidst his long, braided hair, and the cream-and-gold egg placed between his legs. The air is thick with the scent of burning oil and scorched earth. As the towering inferno erupts, violent orange and crimson flames roar upward, swirling in a chaotic vortex of heat. Daenerys steps into the heart of the fire, her skin glistening with oil, her simple linen gown catching fire. The lighting is a stark, blinding chiaroscuro of searing gold light and deep, soot-black shadows. The atmosphere is heavy with mystical tension, capturing the exact moment of a supernatural rebirth amidst the crackling roar of the pyre.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', her knuckles white from gripping the cold masonry . her face is a mask of profound grief , eyes red - rimmed and brimming with tears , her expression flickering between utter despair and a haunting longing for release . the room is cluttered with untouched silver platters of food , casting dull reflections in the dim light . outside , the grey , forbidding walls of the red keep loom under a heavy , overcast sky . the atmosphere is suffocating and melancholic , lit only by the pale , filtered daylight of a winter afternoon , creating deep , moody shadows that emphasize her isolation and the crushing weight of her captivity .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', her knuckles white from gripping the cold masonry . her face is a mask of profound grief , eyes red - rimmed and brimming with tears , her expression flickering between utter despair and a haunting longing for release . the room is cluttered with untouched silver platters of food , casting dull reflections in the dim light . outside , the grey , forbidding walls of the red keep loom under a heavy , overcast sky . the atmosphere is suffocating and melancholic , lit only by the pale , filtered daylight of a winter afternoon , creating deep , moody shadows that emphasize her isolation and the crushing weight of her captivity .']

  0%|          | 0/28 [00:00<?, ?it/s]

Metadata guardado en: /content/drive/MyDrive/Proyecto NLP y DL/Imagen_Generacion/generated_images_sd3/sd35_large/prueba_1013chars_sd3_inicial/metadata.json
Resumen: {'total_rows': 50, 'ok': 50, 'errors': 0, 'skipped_existing': 0}

================================================================================
Modelo: sd35_large
Dataset: prueba_1960chars_sd3_conResumen.jsonl
Prompt column: prompt_sd3_large
max_sequence_length: 512
Output dir: /content/drive/MyDrive/Proyecto NLP y DL/Imagen_Generacion/generated_images_sd3/sd35_large/prueba_1960chars_sd3_conResumen/images
================================================================================
Filas cargadas: 50

sd35_large | prueba_1960chars_sd3_conResumen.jsonl:   0%|          | 0/50 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['of the worn pelt matted with frozen condensation . his face is a mask of stoic duty , though his eyes betray a flicker of heavy sorrow ; a slight furrow in his brow and a tight set to his jaw reveal the burden of the sentence he must carry out . before him kneels gared , the deserter . gared is a broken man , his salt - stained , tattered black wool cloak clinging to his shivering frame . his skin is a pallid , translucent grey , beaded with cold sweat and grime , his eyes wide with a primal , haunting terror that speaks of things seen beyond the wall . his breath emerges in jagged , frantic plumes of white steam . the tension is electric and suffocating . nearby , a young bran stark watches with wide , innocent eyes , his small hand clutching a thick wool tunic , while jon snow stands beside him , his expression stern , whispering a lesson on the necessity of looking upon death . theon greyjoy stands poised , his fingers gripping the hilt of ice — the massive greatsword of house stark . the blade is a terrifying marvel of valyrian steel , featuring smoky , rippling patterns etched into the dark metal , reflecting the dull , leaden sky . the lighting is oppressive and cold , a diffused , wintry luminescence that casts soft , smudge - like shadows across the frozen peat . the environment is framed by the skeletal , blackened branches of ancient weirwoods and jagged grey stones . as eddard raises the massive blade , the steel catches a sliver of pale light , creating a sharp , lethal contrast against the muted tones of the tundra . every detail is visceral : the crunch of frozen earth under boots , the metallic scent of the blade , and the heavy , rhythmic silence of the north .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['of the worn pelt matted with frozen condensation . his face is a mask of stoic duty , though his eyes betray a flicker of heavy sorrow ; a slight furrow in his brow and a tight set to his jaw reveal the burden of the sentence he must carry out . before him kneels gared , the deserter . gared is a broken man , his salt - stained , tattered black wool cloak clinging to his shivering frame . his skin is a pallid , translucent grey , beaded with cold sweat and grime , his eyes wide with a primal , haunting terror that speaks of things seen beyond the wall . his breath emerges in jagged , frantic plumes of white steam . the tension is electric and suffocating . nearby , a young bran stark watches with wide , innocent eyes , his small hand clutching a thick wool tunic , while jon snow stands beside him , his expression stern , whispering a lesson on the necessity of looking upon death . theon greyjoy stands poised , his fingers gripping the hilt of ice — the massive greatsword of house stark . the blade is a terrifying marvel of valyrian steel , featuring smoky , rippling patterns etched into the dark metal , reflecting the dull , leaden sky . the lighting is oppressive and cold , a diffused , wintry luminescence that casts soft , smudge - like shadows across the frozen peat . the environment is framed by the skeletal , blackened branches of ancient weirwoods and jagged grey stones . as eddard raises the massive blade , the steel catches a sliver of pale light , creating a sharp , lethal contrast against the muted tones of the tundra . every detail is visceral : the crunch of frozen earth under boots , the metallic scent of the blade , and the heavy , rhythmic silence of the north .']
[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (543 > 512). Running this sequence through the model will result in indexing errors
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ['d in heavy, charcoal-grey furs and boiled leather, the texture of the worn pelt matted with frozen condensation. His face is a mask of stoic duty, though his eyes betray a flicker of heavy sorrow; a slight furrow in his brow and a tight set to his jaw reveal the burden of the sentence he must carry out. Before him kneels Gared, the deserter. Gared is a broken man, his salt-stained, tattered black wool cloak clinging to his shivering frame. His skin is a pallid, translucent grey, beaded with cold sweat and grime, his eyes wide with a primal, haunting terror that speaks of things seen beyond the Wall. His breath emerges in jagged, frantic plumes of white steam. The tension is electric and suffocating. Nearby, a young Bran Stark watches with wide, innocent eyes, his small hand clutching a thick wool tunic, while Jon Snow stands beside him, his expression stern, whispering a lesson on the necessity of looking upon death. Theon Greyjoy stands poised, his fingers gripping the hilt of Ice—the massive greatsword of House Stark. The blade is a terrifying marvel of Valyrian steel, featuring smoky, rippling patterns etched into the dark metal, reflecting the dull, leaden sky. The lighting is oppressive and cold, a diffused, wintry luminescence that casts soft, smudge-like shadows across the frozen peat. The environment is framed by the skeletal, blackened branches of ancient weirwoods and jagged grey stones. As Eddard raises the massive blade, the steel catches a sliver of pale light, creating a sharp, lethal contrast against the muted tones of the tundra. Every detail is visceral: the crunch of frozen earth under boots, the metallic scent of the blade, and the heavy, rhythmic silence of the North.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["a nearby pony , her massive ribcage heaving one last time in a frozen stillness . embedded deep within her throat is a jagged , towering set of antlers , the bone bleached and splintered , locking her in a permanent , silent scream of agony . surrounding the beast are the stark children , their small figures dwarfed by the scale of the tragedy . robb stark , his face tight with a mixture of grief and protective instinct , cradles a tiny , shivering direwolf pup in his calloused hands , the pup 's fur a soft , smoky grey against the rough , salt - stained wool of robb 's heavy winter cloak . beside him , bran stands frozen , his wide eyes reflecting the horror and wonder of the scene , his small hand reaching out toward the mother 's coarse , frozen pelt . jon snow stands slightly apart , his expression brooding and observant , his dark eyes scanning the perimeter of the snowy clearing . the lighting is a harsh , oppressive winter grey ; a pale , filtered sun struggles to pierce through a thick veil of slate - colored clouds , casting soft , diffused shadows that blur the line between the white earth and the grey sky . tiny ice crystals dance in the frigid air , clinging to the children 's eyelashes and the woolen fibers of their tunics . the texture of the scene is visceral : the wet , glistening blood soaking into the porous snow , the rough grain of the antlers , and the contrast between the massive , cold corpse and the fragile , warm breath of the five tiny pups huddling together in a desperate pile of fur and whimpers . the atmosphere is heavy with the scent of iron and old frost , capturing a pivotal moment of innocence meeting the brutal reality of the north ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["a nearby pony , her massive ribcage heaving one last time in a frozen stillness . embedded deep within her throat is a jagged , towering set of antlers , the bone bleached and splintered , locking her in a permanent , silent scream of agony . surrounding the beast are the stark children , their small figures dwarfed by the scale of the tragedy . robb stark , his face tight with a mixture of grief and protective instinct , cradles a tiny , shivering direwolf pup in his calloused hands , the pup 's fur a soft , smoky grey against the rough , salt - stained wool of robb 's heavy winter cloak . beside him , bran stands frozen , his wide eyes reflecting the horror and wonder of the scene , his small hand reaching out toward the mother 's coarse , frozen pelt . jon snow stands slightly apart , his expression brooding and observant , his dark eyes scanning the perimeter of the snowy clearing . the lighting is a harsh , oppressive winter grey ; a pale , filtered sun struggles to pierce through a thick veil of slate - colored clouds , casting soft , diffused shadows that blur the line between the white earth and the grey sky . tiny ice crystals dance in the frigid air , clinging to the children 's eyelashes and the woolen fibers of their tunics . the texture of the scene is visceral : the wet , glistening blood soaking into the porous snow , the rough grain of the antlers , and the contrast between the massive , cold corpse and the fragile , warm breath of the five tiny pups huddling together in a desperate pile of fur and whimpers . the atmosphere is heavy with the scent of iron and old frost , capturing a pivotal moment of innocence meeting the brutal reality of the north ."]
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ["crimson blood. The wolf is monstrous in scale, dwarfing a nearby pony, her massive ribcage heaving one last time in a frozen stillness. Embedded deep within her throat is a jagged, towering set of antlers, the bone bleached and splintered, locking her in a permanent, silent scream of agony. Surrounding the beast are the Stark children, their small figures dwarfed by the scale of the tragedy. Robb Stark, his face tight with a mixture of grief and protective instinct, cradles a tiny, shivering direwolf pup in his calloused hands, the pup's fur a soft, smoky grey against the rough, salt-stained wool of Robb's heavy winter cloak. Beside him, Bran stands frozen, his wide eyes reflecting the horror and wonder of the scene, his small hand reaching out toward the mother's coarse, frozen pelt. Jon Snow stands slightly apart, his expression brooding and observant, his dark eyes scanning the perimeter of the snowy clearing. The lighting is a harsh, oppressive winter grey; a pale, filtered sun struggles to pierce through a thick veil of slate-colored clouds, casting soft, diffused shadows that blur the line between the white earth and the grey sky. Tiny ice crystals dance in the frigid air, clinging to the children's eyelashes and the woolen fibers of their tunics. The texture of the scene is visceral: the wet, glistening blood soaking into the porous snow, the rough grain of the antlers, and the contrast between the massive, cold corpse and the fragile, warm breath of the five tiny pups huddling together in a desperate pile of fur and whimpers. The atmosphere is heavy with the scent of iron and old frost, capturing a pivotal moment of innocence meeting the brutal reality of the North."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["by a pale , dying winter sun that casts long , ghostly blue shadows across the jagged , snow - covered terrain . robb stark , his face hardened by the sudden weight of leadership , cradles a small , shivering direwolf pup in his calloused hands . his fingers are red from the cold , gripping the pup 's thick , charcoal - colored fur . he is leaning toward bran , whose wide , innocent eyes are filled with a mixture of terror and wonder . bran ’ s breath forms thick white plumes in the freezing air , his small frame wrapped in heavy , salt - stained wool and thick furs that look coarse and heavy . beside them , jon snow stands slightly apart , his posture guarded , his dark eyes scanning the perimeter . his expression is one of quiet realization as he discovers the sixth pup , hidden beneath the flank of the dead mother . the pup is smaller , a ghostly white , its tiny claws digging into the frozen earth . the tension is palpable ; the contrast between the warmth of the pups and the lethal cold of the environment creates a visceral struggle for survival . the dead mother wolf lies in a gruesome heap , a massive , jagged antler protruding violently from her throat , the wound frozen in a crust of crimson ice . the texture of the antler is porous and weathered , contrasting with the sleek , blood - stained fur of the beast . in the background , theon greyjoy stands with a smirk of disdain , his hand resting on the hilt of a polished steel blade , his leather armor glistening with a thin layer of frost . the surrounding forest consists of towering , skeletal ironwood trees , their black bark peeling like burnt skin against the blinding white of the tundra ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["by a pale , dying winter sun that casts long , ghostly blue shadows across the jagged , snow - covered terrain . robb stark , his face hardened by the sudden weight of leadership , cradles a small , shivering direwolf pup in his calloused hands . his fingers are red from the cold , gripping the pup 's thick , charcoal - colored fur . he is leaning toward bran , whose wide , innocent eyes are filled with a mixture of terror and wonder . bran ’ s breath forms thick white plumes in the freezing air , his small frame wrapped in heavy , salt - stained wool and thick furs that look coarse and heavy . beside them , jon snow stands slightly apart , his posture guarded , his dark eyes scanning the perimeter . his expression is one of quiet realization as he discovers the sixth pup , hidden beneath the flank of the dead mother . the pup is smaller , a ghostly white , its tiny claws digging into the frozen earth . the tension is palpable ; the contrast between the warmth of the pups and the lethal cold of the environment creates a visceral struggle for survival . the dead mother wolf lies in a gruesome heap , a massive , jagged antler protruding violently from her throat , the wound frozen in a crust of crimson ice . the texture of the antler is porous and weathered , contrasting with the sleek , blood - stained fur of the beast . in the background , theon greyjoy stands with a smirk of disdain , his hand resting on the hilt of a polished steel blade , his leather armor glistening with a thin layer of frost . the surrounding forest consists of towering , skeletal ironwood trees , their black bark peeling like burnt skin against the blinding white of the tundra ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["ted and coarse , his eyes bloodshot yet gleaming with a desperate , nostalgic intensity . he is draped in heavy , gold - trimmed furs that seem to swallow his frame , the rich velvets stained with droplets of spilled arbor gold . opposite him , ned stark stands as a pillar of frozen granite . his posture is rigid , his grey eyes clouded with a mixture of loyalty and profound dread . a single bead of sweat tracks down his temple , contrasting with the pale , weathered skin of his face . he wears a heavy cloak of charcoal wool fastened by a silver direwolf brooch , the metal cold and matte . between them sits a massive oak table , its surface scarred by centuries of use , holding a heavy iron flagon and two mismatched goblets . the lighting is dramatic and oppressive ; a violent orange glow from the hearth casts long , dancing shadows that stretch across the rough - hewn stone walls , while a sliver of pale , wintry moonlight pierces through a narrow slit window , illuminating the swirling dust motes in the air . robert ’ s hand , thick - fingered and adorned with a heavy gold signet ring , slams onto the table , vibrating the wood . his expression is a raw plea , his mouth slightly agape , capturing the moment he demands ned become the hand of the king . the tension is palpable , a silent war between the king 's chaotic desire and the warden of the north 's stoic reluctance . in the background , the gothic arches of the room fade into a suffocating darkness , emphasizing the claustrophobic weight of the crown 's request . every texture is visceral : the coarse weave of the tapestries , the cold dampness of the stone floor , and the shimmering , oily reflection of the wine in the cup ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["ted and coarse , his eyes bloodshot yet gleaming with a desperate , nostalgic intensity . he is draped in heavy , gold - trimmed furs that seem to swallow his frame , the rich velvets stained with droplets of spilled arbor gold . opposite him , ned stark stands as a pillar of frozen granite . his posture is rigid , his grey eyes clouded with a mixture of loyalty and profound dread . a single bead of sweat tracks down his temple , contrasting with the pale , weathered skin of his face . he wears a heavy cloak of charcoal wool fastened by a silver direwolf brooch , the metal cold and matte . between them sits a massive oak table , its surface scarred by centuries of use , holding a heavy iron flagon and two mismatched goblets . the lighting is dramatic and oppressive ; a violent orange glow from the hearth casts long , dancing shadows that stretch across the rough - hewn stone walls , while a sliver of pale , wintry moonlight pierces through a narrow slit window , illuminating the swirling dust motes in the air . robert ’ s hand , thick - fingered and adorned with a heavy gold signet ring , slams onto the table , vibrating the wood . his expression is a raw plea , his mouth slightly agape , capturing the moment he demands ned become the hand of the king . the tension is palpable , a silent war between the king 's chaotic desire and the warden of the north 's stoic reluctance . in the background , the gothic arches of the room fade into a suffocating darkness , emphasizing the claustrophobic weight of the crown 's request . every texture is visceral : the coarse weave of the tapestries , the cold dampness of the stone floor , and the shimmering , oily reflection of the wine in the cup ."]
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ["deep, boozy crimson, his beard matted and coarse, his eyes bloodshot yet gleaming with a desperate, nostalgic intensity. He is draped in heavy, gold-trimmed furs that seem to swallow his frame, the rich velvets stained with droplets of spilled Arbor gold. Opposite him, Ned Stark stands as a pillar of frozen granite. His posture is rigid, his grey eyes clouded with a mixture of loyalty and profound dread. A single bead of sweat tracks down his temple, contrasting with the pale, weathered skin of his face. He wears a heavy cloak of charcoal wool fastened by a silver direwolf brooch, the metal cold and matte. Between them sits a massive oak table, its surface scarred by centuries of use, holding a heavy iron flagon and two mismatched goblets. The lighting is dramatic and oppressive; a violent orange glow from the hearth casts long, dancing shadows that stretch across the rough-hewn stone walls, while a sliver of pale, wintry moonlight pierces through a narrow slit window, illuminating the swirling dust motes in the air. Robert’s hand, thick-fingered and adorned with a heavy gold signet ring, slams onto the table, vibrating the wood. His expression is a raw plea, his mouth slightly agape, capturing the moment he demands Ned become the Hand of the King. The tension is palpable, a silent war between the King's chaotic desire and the Warden of the North's stoic reluctance. In the background, the Gothic arches of the room fade into a suffocating darkness, emphasizing the claustrophobic weight of the crown's request. Every texture is visceral: the coarse weave of the tapestries, the cold dampness of the stone floor, and the shimmering, oily reflection of the wine in the cup."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["tension . robert ’ s posture is slumped , his heavy velvet doublet stained with the grime of the road , his breathing audible in the stillness . he gazes down at the stone effigy of lyanna stark , his eyes glistening with a mixture of raw longing and a ghost of a smile . the lighting is stark and moody ; a few flickering torches cast dancing , amber light against the deep , obsidian shadows of the vaulted ceiling , creating violent contrasts that carve deep lines into the men 's weathered faces . the torchlight glints off the polished , cold marble of lyanna ’ s statue , highlighting the delicate , frozen curve of her cheek and the intricate , motionless folds of her stone gown . ned stands slightly behind the king , his shoulders rigid , his hands clasped tightly behind his back . his expression is one of quiet endurance , a micro - twitch of the jaw betraying the pain of reopened wounds . the texture of the scene is visceral : the rough , salt - stained wool of ned 's cloak , the sweat - beaded skin on robert 's forehead despite the chill , and the ancient , porous limestone of the crypts , slick with condensation . dust motes dance in the narrow shafts of orange light . the atmosphere is heavy with the weight of dead years and unspoken secrets . robert reaches out , his calloused finger almost touching the cold stone of the statue ’ s hand , the contrast between his living , flushed skin and the pale , lifeless marble emphasizing the permanence of loss . the surrounding darkness of the crypts feels like a physical presence , pressing in on them , isolating the two men in a sanctuary of grief and memory ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["tension . robert ’ s posture is slumped , his heavy velvet doublet stained with the grime of the road , his breathing audible in the stillness . he gazes down at the stone effigy of lyanna stark , his eyes glistening with a mixture of raw longing and a ghost of a smile . the lighting is stark and moody ; a few flickering torches cast dancing , amber light against the deep , obsidian shadows of the vaulted ceiling , creating violent contrasts that carve deep lines into the men 's weathered faces . the torchlight glints off the polished , cold marble of lyanna ’ s statue , highlighting the delicate , frozen curve of her cheek and the intricate , motionless folds of her stone gown . ned stands slightly behind the king , his shoulders rigid , his hands clasped tightly behind his back . his expression is one of quiet endurance , a micro - twitch of the jaw betraying the pain of reopened wounds . the texture of the scene is visceral : the rough , salt - stained wool of ned 's cloak , the sweat - beaded skin on robert 's forehead despite the chill , and the ancient , porous limestone of the crypts , slick with condensation . dust motes dance in the narrow shafts of orange light . the atmosphere is heavy with the weight of dead years and unspoken secrets . robert reaches out , his calloused finger almost touching the cold stone of the statue ’ s hand , the contrast between his living , flushed skin and the pale , lifeless marble emphasizing the permanence of loss . the surrounding darkness of the crypts feels like a physical presence , pressing in on them , isolating the two men in a sanctuary of grief and memory ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["olith of a man . he is an exiled knight , his presence a jarring contrast of westerosi nobility and dothraki ruggedness . he wears a travel - worn tunic of coarse , salt - stained linen and a heavy leather brigandine scarred by years of desert grit . his skin is leathered and bronze from the essosi sun , with deep - set eyes reflecting a mixture of weary melancholy and sudden , piercing intrigue . opposite him stands the young daenerys targaryen , fragile and trembling , her pale skin almost translucent against the vibrant silks of her gown . her eyes are rimmed with red from recent tears , her small shoulders hunched in a posture of profound vulnerability . beside her , viserys targaryen looms , his expression a mask of arrogant desperation , his fingers twitching with a nervous , predatory energy . the tension is palpable , a silent electric current between the exiled knight and the frightened princess . jorah ’ s posture is respectful yet observant , his gaze lingering on daenerys with a protective instinct he doesn 't yet understand . in the background , the imposing figure of khal drogo stands like a bronze panther , his long , unbroken braid draped over a shoulder of corded muscle , his dark eyes scanning the room with predatory indifference . the architecture is a blend of gothic grandeur and eastern decadence : towering marble columns etched with swirling floral motifs , polished mosaic floors reflecting the violent amber glow of the afternoon sun , and heavy velvet draperies in deep crimson that cast long , jagged shadows across the scene . every texture is vivid : the cold smoothness of the marble , the rough grain of jorah 's leather gear , and the shimmering , iridescent quality of the targaryen silks ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["olith of a man . he is an exiled knight , his presence a jarring contrast of westerosi nobility and dothraki ruggedness . he wears a travel - worn tunic of coarse , salt - stained linen and a heavy leather brigandine scarred by years of desert grit . his skin is leathered and bronze from the essosi sun , with deep - set eyes reflecting a mixture of weary melancholy and sudden , piercing intrigue . opposite him stands the young daenerys targaryen , fragile and trembling , her pale skin almost translucent against the vibrant silks of her gown . her eyes are rimmed with red from recent tears , her small shoulders hunched in a posture of profound vulnerability . beside her , viserys targaryen looms , his expression a mask of arrogant desperation , his fingers twitching with a nervous , predatory energy . the tension is palpable , a silent electric current between the exiled knight and the frightened princess . jorah ’ s posture is respectful yet observant , his gaze lingering on daenerys with a protective instinct he doesn 't yet understand . in the background , the imposing figure of khal drogo stands like a bronze panther , his long , unbroken braid draped over a shoulder of corded muscle , his dark eyes scanning the room with predatory indifference . the architecture is a blend of gothic grandeur and eastern decadence : towering marble columns etched with swirling floral motifs , polished mosaic floors reflecting the violent amber glow of the afternoon sun , and heavy velvet draperies in deep crimson that cast long , jagged shadows across the scene . every texture is vivid : the cold smoothness of the marble , the rough grain of jorah 's leather gear , and the shimmering , iridescent quality of the targaryen silks ."]
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ["frame, Ser Jorah Mormont stands as a weathered monolith of a man. He is an exiled knight, his presence a jarring contrast of Westerosi nobility and Dothraki ruggedness. He wears a travel-worn tunic of coarse, salt-stained linen and a heavy leather brigandine scarred by years of desert grit. His skin is leathered and bronze from the Essosi sun, with deep-set eyes reflecting a mixture of weary melancholy and sudden, piercing intrigue. Opposite him stands the young Daenerys Targaryen, fragile and trembling, her pale skin almost translucent against the vibrant silks of her gown. Her eyes are rimmed with red from recent tears, her small shoulders hunched in a posture of profound vulnerability. Beside her, Viserys Targaryen looms, his expression a mask of arrogant desperation, his fingers twitching with a nervous, predatory energy. The tension is palpable, a silent electric current between the exiled knight and the frightened princess. Jorah’s posture is respectful yet observant, his gaze lingering on Daenerys with a protective instinct he doesn't yet understand. In the background, the imposing figure of Khal Drogo stands like a bronze panther, his long, unbroken braid draped over a shoulder of corded muscle, his dark eyes scanning the room with predatory indifference. The architecture is a blend of Gothic grandeur and Eastern decadence: towering marble columns etched with swirling floral motifs, polished mosaic floors reflecting the violent amber glow of the afternoon sun, and heavy velvet draperies in deep crimson that cast long, jagged shadows across the scene. Every texture is vivid: the cold smoothness of the marble, the rough grain of Jorah's leather gear, and the shimmering, iridescent quality of the Targaryen silks."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["blue moonlight filtering through high , narrow slits in the stone walls , creating deep , oppressive shadows . in the foreground , jon snow sits far removed from the nobility , positioned among the squires and servants at a long , rough - hewn trestle table . his posture is a mix of isolation and quiet relief ; he leans back slightly , a pewter tankard of dark ale gripped in a calloused hand . his face is etched with a subtle , melancholic detachment , his dark eyes scanning the room with a piercing , observant intensity . he wears a heavy , charcoal - grey wool tunic with a coarse , salt - stained leather jerkin , the fabric pilling at the shoulders . in the blurred mid - ground , the high table is a tableau of tension . king robert is a mountain of a man , his face flushed a violent crimson from wine , his gold - threaded velvet doublet strained across a bloated chest . beside him , queen cersei sits with a rigid , porcelain posture , her lips curled into a thin , artificial smile that doesn 't reach her cold , emerald eyes . prince joffrey exudes a sneering arrogance , his golden curls shimmering under the torchlight , while jaime lannister leans back with a predatory , effortless grace , his golden armor reflecting the firelight in sharp , blinding glints . the environment is rich with texture : the grease - slicked surfaces of the wooden tables , the heavy furs draped over stone benches , and the distant , echoing roar of a hundred voices . the air is hazy with smoke from the central hearth , blurring the edges of the gothic arches and emphasizing the suffocating social divide between the royal blood and the bastard in the shadows ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["blue moonlight filtering through high , narrow slits in the stone walls , creating deep , oppressive shadows . in the foreground , jon snow sits far removed from the nobility , positioned among the squires and servants at a long , rough - hewn trestle table . his posture is a mix of isolation and quiet relief ; he leans back slightly , a pewter tankard of dark ale gripped in a calloused hand . his face is etched with a subtle , melancholic detachment , his dark eyes scanning the room with a piercing , observant intensity . he wears a heavy , charcoal - grey wool tunic with a coarse , salt - stained leather jerkin , the fabric pilling at the shoulders . in the blurred mid - ground , the high table is a tableau of tension . king robert is a mountain of a man , his face flushed a violent crimson from wine , his gold - threaded velvet doublet strained across a bloated chest . beside him , queen cersei sits with a rigid , porcelain posture , her lips curled into a thin , artificial smile that doesn 't reach her cold , emerald eyes . prince joffrey exudes a sneering arrogance , his golden curls shimmering under the torchlight , while jaime lannister leans back with a predatory , effortless grace , his golden armor reflecting the firelight in sharp , blinding glints . the environment is rich with texture : the grease - slicked surfaces of the wooden tables , the heavy furs draped over stone benches , and the distant , echoing roar of a hundred voices . the air is hazy with smoke from the central hearth , blurring the edges of the gothic arches and emphasizing the suffocating social divide between the royal blood and the bastard in the shadows ."]
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ["ering orange torchlight and the cold, pale blue moonlight filtering through high, narrow slits in the stone walls, creating deep, oppressive shadows. In the foreground, Jon Snow sits far removed from the nobility, positioned among the squires and servants at a long, rough-hewn trestle table. His posture is a mix of isolation and quiet relief; he leans back slightly, a pewter tankard of dark ale gripped in a calloused hand. His face is etched with a subtle, melancholic detachment, his dark eyes scanning the room with a piercing, observant intensity. He wears a heavy, charcoal-grey wool tunic with a coarse, salt-stained leather jerkin, the fabric pilling at the shoulders. In the blurred mid-ground, the high table is a tableau of tension. King Robert is a mountain of a man, his face flushed a violent crimson from wine, his gold-threaded velvet doublet strained across a bloated chest. Beside him, Queen Cersei sits with a rigid, porcelain posture, her lips curled into a thin, artificial smile that doesn't reach her cold, emerald eyes. Prince Joffrey exudes a sneering arrogance, his golden curls shimmering under the torchlight, while Jaime Lannister leans back with a predatory, effortless grace, his golden armor reflecting the firelight in sharp, blinding glints. The environment is rich with texture: the grease-slicked surfaces of the wooden tables, the heavy furs draped over stone benches, and the distant, echoing roar of a hundred voices. The air is hazy with smoke from the central hearth, blurring the edges of the Gothic arches and emphasizing the suffocating social divide between the royal blood and the bastard in the shadows."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["— a secret language shared only between sisters . her eyes , wide with a mixture of dread and sudden clarity , scan the jagged ink strokes . the revelation is a poison : lysa arryn , her sister , claims that jon arryn did not die of natural causes , but was murdered by the queen and the lannisters . catelyn ’ s face is a mask of pale tension ; a single bead of sweat clings to her temple despite the cold . her posture is rigid , her shoulders hunched as if shielding the secret from the very walls . beside her , the flickering orange glow of a dying hearth casts long , dancing shadows that stretch across the rough - hewn stone floor and the heavy , dark oak furniture . the lighting is moody and oppressive , with deep amber highlights clashing against the cold , blue moonlight filtering through a narrow slit window . the textures are visceral : the coarse , salt - stained wool of catelyn 's heavy gown , the grainy texture of the ancient parchment , and the glint of a silver seal partially melted . in the background , the gothic architecture of the keep looms , with heavy vaulted ceilings and iron sconces that drip black soot . the atmosphere is heavy with an invisible weight , the silent scream of a political conspiracy that threatens to ignite a war . every line of catelyn 's expression conveys a desperate urgency ; her lips are parted , her breath visible in the freezing air , as she realizes that eddard must travel to king 's landing to uncover a truth that could destroy them all . the scene is a study in intimacy and impending doom , capturing the exact moment a private letter transforms into a catalyst for continental chaos ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["— a secret language shared only between sisters . her eyes , wide with a mixture of dread and sudden clarity , scan the jagged ink strokes . the revelation is a poison : lysa arryn , her sister , claims that jon arryn did not die of natural causes , but was murdered by the queen and the lannisters . catelyn ’ s face is a mask of pale tension ; a single bead of sweat clings to her temple despite the cold . her posture is rigid , her shoulders hunched as if shielding the secret from the very walls . beside her , the flickering orange glow of a dying hearth casts long , dancing shadows that stretch across the rough - hewn stone floor and the heavy , dark oak furniture . the lighting is moody and oppressive , with deep amber highlights clashing against the cold , blue moonlight filtering through a narrow slit window . the textures are visceral : the coarse , salt - stained wool of catelyn 's heavy gown , the grainy texture of the ancient parchment , and the glint of a silver seal partially melted . in the background , the gothic architecture of the keep looms , with heavy vaulted ceilings and iron sconces that drip black soot . the atmosphere is heavy with an invisible weight , the silent scream of a political conspiracy that threatens to ignite a war . every line of catelyn 's expression conveys a desperate urgency ; her lips are parted , her breath visible in the freezing air , as she realizes that eddard must travel to king 's landing to uncover a truth that could destroy them all . the scene is a study in intimacy and impending doom , capturing the exact moment a private letter transforms into a catalyst for continental chaos ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["and rough - hewn leather , leans in with a secretive , knowing smile , his eyes reflecting a deep , protective kinship . his posture is slightly hunched , creating a private sanctuary between them . arya , small and spirited , looks up with wide , shimmering eyes , her face a mask of sudden wonder . her fingers are stained with the dust of her haphazardly packed trunks . between them , jon presents the gift : needle . the sword is a slender , elegant sliver of high - carbon steel , its blade polished to a mirror - sheen that catches the pale , wintry light filtering through a narrow gothic window . the hilt is wrapped in fine , weathered leather , showing the subtle grain of the hide . the lighting is moody and directional ; a soft , diffused silver light from the overcast northern sky illuminates the side of their faces , while deep , velvet shadows cling to the corners of the room and the heavy oak beams of the ceiling . in the background , nymeria , the direwolf , is a blur of grey - white fur , poised like a sentinel by the heavy iron - bound door , her amber eyes watchful . every texture is visceral : the coarse weave of the stark tapestries hanging on the walls , the cold dampness of the limestone floor , and the slight glint of sweat on jon 's brow . the focus is tight on the moment the steel passes from jon 's calloused hand to arya 's small , trembling grip . the air feels heavy with the unspoken promise of protection and the looming shadow of the north , capturing a fleeting instant of childhood innocence before the onset of war ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["and rough - hewn leather , leans in with a secretive , knowing smile , his eyes reflecting a deep , protective kinship . his posture is slightly hunched , creating a private sanctuary between them . arya , small and spirited , looks up with wide , shimmering eyes , her face a mask of sudden wonder . her fingers are stained with the dust of her haphazardly packed trunks . between them , jon presents the gift : needle . the sword is a slender , elegant sliver of high - carbon steel , its blade polished to a mirror - sheen that catches the pale , wintry light filtering through a narrow gothic window . the hilt is wrapped in fine , weathered leather , showing the subtle grain of the hide . the lighting is moody and directional ; a soft , diffused silver light from the overcast northern sky illuminates the side of their faces , while deep , velvet shadows cling to the corners of the room and the heavy oak beams of the ceiling . in the background , nymeria , the direwolf , is a blur of grey - white fur , poised like a sentinel by the heavy iron - bound door , her amber eyes watchful . every texture is visceral : the coarse weave of the stark tapestries hanging on the walls , the cold dampness of the limestone floor , and the slight glint of sweat on jon 's brow . the focus is tight on the moment the steel passes from jon 's calloused hand to arya 's small , trembling grip . the air feels heavy with the unspoken promise of protection and the looming shadow of the north , capturing a fleeting instant of childhood innocence before the onset of war ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['with a bittersweet smile and eyes reflecting a deep , fraternal bond . he holds out a slender , elegant blade — needle — its polished steel gleaming with a cold , silver luster that contrasts against the rough , charcoal - grey wool of his tunic . arya ’ s expression is one of pure , wide - eyed wonder , her small hands trembling slightly as she reaches for the hilt . her skin is flushed from the cold , with a few stray smudges of dirt on her cheek , her eyes locked on the weapon with an intensity that borders on obsession . the lighting is a moody , overcast northern afternoon ; soft , diffused light filters through a heavy ceiling of slate - grey clouds , casting gentle , muted shadows that cling to the crevices of the ancient , lichen - covered granite walls . in the background , the blurred silhouettes of soldiers and horses create a sense of impending separation . the textures are visceral : the cold , biting wind whipping through arya \'s salt - stained linen dress , the coarse grain of the wooden crates she was packing , and the lethal , mirror - like smoothness of the thin blade . jon ’ s voice is a whisper , his lips barely moving as he imparts the fundamental lesson : " stick them with the pointy end ." beside them , the direwolf nymeria stands as a silent sentinel , her thick , grey - white fur ruffled by the breeze , her amber eyes vigilant , guarding the entrance to their private sanctuary . the atmosphere is heavy with the tension of a childhood ending and the silent promise of survival in a world of steel and ice .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['with a bittersweet smile and eyes reflecting a deep , fraternal bond . he holds out a slender , elegant blade — needle — its polished steel gleaming with a cold , silver luster that contrasts against the rough , charcoal - grey wool of his tunic . arya ’ s expression is one of pure , wide - eyed wonder , her small hands trembling slightly as she reaches for the hilt . her skin is flushed from the cold , with a few stray smudges of dirt on her cheek , her eyes locked on the weapon with an intensity that borders on obsession . the lighting is a moody , overcast northern afternoon ; soft , diffused light filters through a heavy ceiling of slate - grey clouds , casting gentle , muted shadows that cling to the crevices of the ancient , lichen - covered granite walls . in the background , the blurred silhouettes of soldiers and horses create a sense of impending separation . the textures are visceral : the cold , biting wind whipping through arya \'s salt - stained linen dress , the coarse grain of the wooden crates she was packing , and the lethal , mirror - like smoothness of the thin blade . jon ’ s voice is a whisper , his lips barely moving as he imparts the fundamental lesson : " stick them with the pointy end ." beside them , the direwolf nymeria stands as a silent sentinel , her thick , grey - white fur ruffled by the breeze , her amber eyes vigilant , guarding the entrance to their private sanctuary . the atmosphere is heavy with the tension of a childhood ending and the silent promise of survival in a world of steel and ice .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['ped raw , digging into the porous stone . he peers through a narrow , arched window embrasure into a dim , candle - lit chamber . inside , the lighting is a warm , flickering amber that casts dancing , elongated shadows against the damp stone walls . cersei lannister and jaime lannister are entwined in a desperate , illicit embrace . cersei ’ s skin is a pale , luminous ivory , glistening with a thin sheen of sweat ; her golden hair is a chaotic spill across her shoulders . jaime , her mirror image with a sharp , arrogant jawline and golden stubble , holds her with a possessive grip . their expressions are a volatile mix of passion and sudden , piercing panic as they realize they are being watched . the camera captures the moment of sudden violence . bran has lost his balance , his small body dangling precariously over the abyss , one hand gripping the jagged edge of the window ledge . the texture of the worn , salt - stained linen of his tunic flutters in the cold northern wind . jaime ’ s face shifts from lust to a cold , calculating desperation . he reaches out , his hand gripping bran ’ s wrist — not in a gesture of rescue , but as a prelude to a crime . the contrast is stark : the warmth of the interior chamber versus the freezing , slate - grey exterior of the tower . the air is thick with the smell of old stone and ozone . as jaime prepares to heave the boy backward into the void , the focus tightens on the micro - expression of cersei ’ s face — a mask of sheer , wide - eyed terror and ruthless necessity . the background shows the sprawling , blurred courtyard of winterfell far below , a dizzying drop of grey stone and dead grass .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['ped raw , digging into the porous stone . he peers through a narrow , arched window embrasure into a dim , candle - lit chamber . inside , the lighting is a warm , flickering amber that casts dancing , elongated shadows against the damp stone walls . cersei lannister and jaime lannister are entwined in a desperate , illicit embrace . cersei ’ s skin is a pale , luminous ivory , glistening with a thin sheen of sweat ; her golden hair is a chaotic spill across her shoulders . jaime , her mirror image with a sharp , arrogant jawline and golden stubble , holds her with a possessive grip . their expressions are a volatile mix of passion and sudden , piercing panic as they realize they are being watched . the camera captures the moment of sudden violence . bran has lost his balance , his small body dangling precariously over the abyss , one hand gripping the jagged edge of the window ledge . the texture of the worn , salt - stained linen of his tunic flutters in the cold northern wind . jaime ’ s face shifts from lust to a cold , calculating desperation . he reaches out , his hand gripping bran ’ s wrist — not in a gesture of rescue , but as a prelude to a crime . the contrast is stark : the warmth of the interior chamber versus the freezing , slate - grey exterior of the tower . the air is thick with the smell of old stone and ozone . as jaime prepares to heave the boy backward into the void , the focus tightens on the micro - expression of cersei ’ s face — a mask of sheer , wide - eyed terror and ruthless necessity . the background shows the sprawling , blurred courtyard of winterfell far below , a dizzying drop of grey stone and dead grass .']
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ['the rough, lichen-covered grey granite. His small fingers are scraped raw, digging into the porous stone. He peers through a narrow, arched window embrasure into a dim, candle-lit chamber. Inside, the lighting is a warm, flickering amber that casts dancing, elongated shadows against the damp stone walls. Cersei Lannister and Jaime Lannister are entwined in a desperate, illicit embrace. Cersei’s skin is a pale, luminous ivory, glistening with a thin sheen of sweat; her golden hair is a chaotic spill across her shoulders. Jaime, her mirror image with a sharp, arrogant jawline and golden stubble, holds her with a possessive grip. Their expressions are a volatile mix of passion and sudden, piercing panic as they realize they are being watched. The camera captures the moment of sudden violence. Bran has lost his balance, his small body dangling precariously over the abyss, one hand gripping the jagged edge of the window ledge. The texture of the worn, salt-stained linen of his tunic flutters in the cold Northern wind. Jaime’s face shifts from lust to a cold, calculating desperation. He reaches out, his hand gripping Bran’s wrist—not in a gesture of rescue, but as a prelude to a crime. The contrast is stark: the warmth of the interior chamber versus the freezing, slate-grey exterior of the tower. The air is thick with the smell of old stone and ozone. As Jaime prepares to heave the boy backward into the void, the focus tightens on the micro-expression of Cersei’s face—a mask of sheer, wide-eyed terror and ruthless necessity. The background shows the sprawling, blurred courtyard of Winterfell far below, a dizzying drop of grey stone and dead grass.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["vivid , blooming crimson welt across joffrey ’ s pale , porcelain cheek . joffrey ’ s head is snapped to the side , his mouth agape in a mixture of shock and narcissistic rage , his golden curls disheveled . his eyes are wide , glistening with unshed tears of humiliation , while his posture is stiff , trembling with the impulse to scream . tyrion ’ s expression is one of cold , disciplined disgust ; his mismatched eyes narrow , his brow furrowed in a stern reprimand . he leans in , the fabric of his rich , crimson velvet doublet contrasting with the grey , oppressive stone of the walls . the texture of the velvet is heavy and plush , catching the dim light , while tyrion 's skin is weathered , with fine lines of stress and cynicism etched around his eyes . the lighting is oppressive and moody , provided by flickering iron wall sconces that cast long , dancing shadows and a warm , amber glow that fails to penetrate the deep , charcoal gloom of the vaulted ceiling . in the background , sandor clegane looms like a mountain of scarred flesh and blackened steel , his burned face partially obscured by the flickering light , his expression one of grim , silent amusement . the environment is damp and oppressive ; moisture clings to the rough - hewn granite blocks of the hallway , and a thin mist of cold northern air swirls around their boots . the air feels thick with the scent of old stone , torch smoke , and the metallic tang of tension . every detail is visceral : the gold embroidery on joffrey 's tunic fraying slightly at the collar , the glint of a signet ring on tyrion 's finger , and the heavy , rhythmic breathing of the hound echoing through the silent , gothic passage ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["vivid , blooming crimson welt across joffrey ’ s pale , porcelain cheek . joffrey ’ s head is snapped to the side , his mouth agape in a mixture of shock and narcissistic rage , his golden curls disheveled . his eyes are wide , glistening with unshed tears of humiliation , while his posture is stiff , trembling with the impulse to scream . tyrion ’ s expression is one of cold , disciplined disgust ; his mismatched eyes narrow , his brow furrowed in a stern reprimand . he leans in , the fabric of his rich , crimson velvet doublet contrasting with the grey , oppressive stone of the walls . the texture of the velvet is heavy and plush , catching the dim light , while tyrion 's skin is weathered , with fine lines of stress and cynicism etched around his eyes . the lighting is oppressive and moody , provided by flickering iron wall sconces that cast long , dancing shadows and a warm , amber glow that fails to penetrate the deep , charcoal gloom of the vaulted ceiling . in the background , sandor clegane looms like a mountain of scarred flesh and blackened steel , his burned face partially obscured by the flickering light , his expression one of grim , silent amusement . the environment is damp and oppressive ; moisture clings to the rough - hewn granite blocks of the hallway , and a thin mist of cold northern air swirls around their boots . the air feels thick with the scent of old stone , torch smoke , and the metallic tang of tension . every detail is visceral : the gold embroidery on joffrey 's tunic fraying slightly at the collar , the glint of a signet ring on tyrion 's finger , and the heavy , rhythmic breathing of the hound echoing through the silent , gothic passage ."]
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ["violent crack of a slap that has left a vivid, blooming crimson welt across Joffrey’s pale, porcelain cheek. Joffrey’s head is snapped to the side, his mouth agape in a mixture of shock and narcissistic rage, his golden curls disheveled. His eyes are wide, glistening with unshed tears of humiliation, while his posture is stiff, trembling with the impulse to scream. Tyrion’s expression is one of cold, disciplined disgust; his mismatched eyes narrow, his brow furrowed in a stern reprimand. He leans in, the fabric of his rich, crimson velvet doublet contrasting with the grey, oppressive stone of the walls. The texture of the velvet is heavy and plush, catching the dim light, while Tyrion's skin is weathered, with fine lines of stress and cynicism etched around his eyes. The lighting is oppressive and moody, provided by flickering iron wall sconces that cast long, dancing shadows and a warm, amber glow that fails to penetrate the deep, charcoal gloom of the vaulted ceiling. In the background, Sandor Clegane looms like a mountain of scarred flesh and blackened steel, his burned face partially obscured by the flickering light, his expression one of grim, silent amusement. The environment is damp and oppressive; moisture clings to the rough-hewn granite blocks of the hallway, and a thin mist of cold Northern air swirls around their boots. The air feels thick with the scent of old stone, torch smoke, and the metallic tang of tension. Every detail is visceral: the gold embroidery on Joffrey's tunic fraying slightly at the collar, the glint of a signet ring on Tyrion's finger, and the heavy, rhythmic breathing of the Hound echoing through the silent, Gothic passage."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['sweat - beads form in the humid heat . her expression is a complex mask of trepidation and burgeoning curiosity , her violet eyes wide and reflecting the dying light . standing before her is magister illyrio , a man of immense girth and opulent excess . his face is slick with oil , his skin glistening , wearing heavy brocade robes of deep crimson and gold that look suffocatingly thick . with a slow , theatrical gesture , he presents three massive , stone - like objects resting on a velvet cushion of midnight blue . these are the dragon eggs : one a deep , mossy green with organic , crystalline ridges ; one a pale , iridescent cream that glows like a dying star ; and one a matte , obsidian black , its surface etched with ancient , smoky ripples and fossilized scales . the lighting is dramatic , with the low - hanging sun casting long , jagged silhouettes across the mosaic floor of the courtyard . to the side , viserys targaryen watches with a predatory , hungry gaze , his posture rigid , his fingers twitching with an obsessive desire for the power these eggs represent . beside him , ser jorah mormont stands like a weathered monolith , his salt - stained leather armor contrasting with the luxury of the setting , his eyes softening with a protective , hidden longing as he looks at daenerys . the environment is a blend of gothic excess and essosi opulence ; towering marble columns are entwined with flowering vines , and the air is thick with the scent of roasting meats , exotic incense , and the salty breeze of the narrow sea . the tension is palpable , a silent electricity crackling between the fragile girl and the ancient , dormant power of the stone eggs .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['sweat - beads form in the humid heat . her expression is a complex mask of trepidation and burgeoning curiosity , her violet eyes wide and reflecting the dying light . standing before her is magister illyrio , a man of immense girth and opulent excess . his face is slick with oil , his skin glistening , wearing heavy brocade robes of deep crimson and gold that look suffocatingly thick . with a slow , theatrical gesture , he presents three massive , stone - like objects resting on a velvet cushion of midnight blue . these are the dragon eggs : one a deep , mossy green with organic , crystalline ridges ; one a pale , iridescent cream that glows like a dying star ; and one a matte , obsidian black , its surface etched with ancient , smoky ripples and fossilized scales . the lighting is dramatic , with the low - hanging sun casting long , jagged silhouettes across the mosaic floor of the courtyard . to the side , viserys targaryen watches with a predatory , hungry gaze , his posture rigid , his fingers twitching with an obsessive desire for the power these eggs represent . beside him , ser jorah mormont stands like a weathered monolith , his salt - stained leather armor contrasting with the luxury of the setting , his eyes softening with a protective , hidden longing as he looks at daenerys . the environment is a blend of gothic excess and essosi opulence ; towering marble columns are entwined with flowering vines , and the air is thick with the scent of roasting meats , exotic incense , and the salty breeze of the narrow sea . the tension is palpable , a silent electricity crackling between the fragile girl and the ancient , dormant power of the stone eggs .']
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ['ber sunset, the fabric clinging to her skin where sweat-beads form in the humid heat. Her expression is a complex mask of trepidation and burgeoning curiosity, her violet eyes wide and reflecting the dying light. Standing before her is Magister Illyrio, a man of immense girth and opulent excess. His face is slick with oil, his skin glistening, wearing heavy brocade robes of deep crimson and gold that look suffocatingly thick. With a slow, theatrical gesture, he presents three massive, stone-like objects resting on a velvet cushion of midnight blue. These are the dragon eggs: one a deep, mossy green with organic, crystalline ridges; one a pale, iridescent cream that glows like a dying star; and one a matte, obsidian black, its surface etched with ancient, smoky ripples and fossilized scales. The lighting is dramatic, with the low-hanging sun casting long, jagged silhouettes across the mosaic floor of the courtyard. To the side, Viserys Targaryen watches with a predatory, hungry gaze, his posture rigid, his fingers twitching with an obsessive desire for the power these eggs represent. Beside him, Ser Jorah Mormont stands like a weathered monolith, his salt-stained leather armor contrasting with the luxury of the setting, his eyes softening with a protective, hidden longing as he looks at Daenerys. The environment is a blend of Gothic excess and Essosi opulence; towering marble columns are entwined with flowering vines, and the air is thick with the scent of roasting meats, exotic incense, and the salty breeze of the Narrow Sea. The tension is palpable, a silent electricity crackling between the fragile girl and the ancient, dormant power of the stone eggs.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["sweat and dust . he holds the lead of a magnificent young mare , a creature of ethereal beauty with a coat the color of a winter sea — a shimmering , stormy grey that catches the dying light . the horse 's mane is a wild , flowing cascade of silver smoke , whipping in the warm wind . daenerys stands before him , her expression a fragile mixture of terror and burgeoning curiosity . her skin is pale , almost translucent against the heavy , ornate silks of her bridal attire , which are embroidered with intricate gold threads that shimmer with every shallow breath she takes . her small hands tremble slightly as she looks upon the animal . the tension between them is electric ; drogo ’ s dark , piercing eyes are fixed on her , not with cruelty , but with a possessive , simmering intensity . surrounding them , the atmosphere is thick with the scent of roasted meat , pungent horse sweat , and exotic spices . in the background , the blurred figures of the bloodriders stand like statues of iron and leather , their weathered faces scarred and stern . nearby , a pile of heavy , leather - bound books provided by jorah and the iridescent , stone - like dragon eggs — one deep emerald , one cream , one obsidian black — rest upon a table of rough - hewn wood , their surfaces matte and ancient . the lighting is dramatic , with the low - hanging sun creating a high - contrast rim light around the characters , while deep , velvet shadows swallow the edges of the encampment . every texture is palpable : the coarse grain of the dothraki leather , the delicate weave of the silks , and the powerful , rippling muscles of the grey mare ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["sweat and dust . he holds the lead of a magnificent young mare , a creature of ethereal beauty with a coat the color of a winter sea — a shimmering , stormy grey that catches the dying light . the horse 's mane is a wild , flowing cascade of silver smoke , whipping in the warm wind . daenerys stands before him , her expression a fragile mixture of terror and burgeoning curiosity . her skin is pale , almost translucent against the heavy , ornate silks of her bridal attire , which are embroidered with intricate gold threads that shimmer with every shallow breath she takes . her small hands tremble slightly as she looks upon the animal . the tension between them is electric ; drogo ’ s dark , piercing eyes are fixed on her , not with cruelty , but with a possessive , simmering intensity . surrounding them , the atmosphere is thick with the scent of roasted meat , pungent horse sweat , and exotic spices . in the background , the blurred figures of the bloodriders stand like statues of iron and leather , their weathered faces scarred and stern . nearby , a pile of heavy , leather - bound books provided by jorah and the iridescent , stone - like dragon eggs — one deep emerald , one cream , one obsidian black — rest upon a table of rough - hewn wood , their surfaces matte and ancient . the lighting is dramatic , with the low - hanging sun creating a high - contrast rim light around the characters , while deep , velvet shadows swallow the edges of the encampment . every texture is palpable : the coarse grain of the dothraki leather , the delicate weave of the silks , and the powerful , rippling muscles of the grey mare ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["him , her expression one of maternal agony and exhaustion , her fingers clutching the coarse , salt - stained linen of the bedsheets . the lighting is oppressive ; dim , flickering torchlight casts dancing , jagged shadows against the rough - hewn gothic masonry , while a distant , violent orange glow from a burning tower bleeds through the narrow window , painting the room in sickly amber streaks . suddenly , the silence is shattered . a hooded assassin bursts through the heavy wooden door , his movement a blur of lethal intent . he is a shadow draped in worn , dark leather that creaks with every stride . in his grip is a dagger of valyrian steel , its blade etched with smoky , undulating ripples that seem to swallow the light . as he lunges toward the unconscious boy , catelyn throws herself forward in a desperate , instinctive shield . the blade sinks into her flesh with a sickening slide ; her eyes widen in a shock of searing pain , a single droplet of crimson blood blooming across her gown . at the apex of the violence , a blur of grey fur erupts from the corner of the room . summer , the direwolf , launches himself with primal fury . the wolf 's massive jaws snap shut with a bone - crushing sound , tearing through the assassin 's throat . blood sprays in a violent arc , splashing across the cold stone floor and the white linens of the bed . the assassin 's eyes bulge , his hands clawing uselessly at the thick , coarse fur of the beast as he is dragged backward , his muffled gurgles lost to the guttural snarls of the wolf . the scene is a visceral contrast of fragile innocence , maternal sacrifice , and raw , animalistic savagery ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["him , her expression one of maternal agony and exhaustion , her fingers clutching the coarse , salt - stained linen of the bedsheets . the lighting is oppressive ; dim , flickering torchlight casts dancing , jagged shadows against the rough - hewn gothic masonry , while a distant , violent orange glow from a burning tower bleeds through the narrow window , painting the room in sickly amber streaks . suddenly , the silence is shattered . a hooded assassin bursts through the heavy wooden door , his movement a blur of lethal intent . he is a shadow draped in worn , dark leather that creaks with every stride . in his grip is a dagger of valyrian steel , its blade etched with smoky , undulating ripples that seem to swallow the light . as he lunges toward the unconscious boy , catelyn throws herself forward in a desperate , instinctive shield . the blade sinks into her flesh with a sickening slide ; her eyes widen in a shock of searing pain , a single droplet of crimson blood blooming across her gown . at the apex of the violence , a blur of grey fur erupts from the corner of the room . summer , the direwolf , launches himself with primal fury . the wolf 's massive jaws snap shut with a bone - crushing sound , tearing through the assassin 's throat . blood sprays in a violent arc , splashing across the cold stone floor and the white linens of the bed . the assassin 's eyes bulge , his hands clawing uselessly at the thick , coarse fur of the beast as he is dragged backward , his muffled gurgles lost to the guttural snarls of the wolf . the scene is a visceral contrast of fragile innocence , maternal sacrifice , and raw , animalistic savagery ."]
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ["ic. Catelyn Stark is slumped beside him, her expression one of maternal agony and exhaustion, her fingers clutching the coarse, salt-stained linen of the bedsheets. The lighting is oppressive; dim, flickering torchlight casts dancing, jagged shadows against the rough-hewn Gothic masonry, while a distant, violent orange glow from a burning tower bleeds through the narrow window, painting the room in sickly amber streaks. Suddenly, the silence is shattered. A hooded assassin bursts through the heavy wooden door, his movement a blur of lethal intent. He is a shadow draped in worn, dark leather that creaks with every stride. In his grip is a dagger of Valyrian steel, its blade etched with smoky, undulating ripples that seem to swallow the light. As he lunges toward the unconscious boy, Catelyn throws herself forward in a desperate, instinctive shield. The blade sinks into her flesh with a sickening slide; her eyes widen in a shock of searing pain, a single droplet of crimson blood blooming across her gown. At the apex of the violence, a blur of grey fur erupts from the corner of the room. Summer, the direwolf, launches himself with primal fury. The wolf's massive jaws snap shut with a bone-crushing sound, tearing through the assassin's throat. Blood sprays in a violent arc, splashing across the cold stone floor and the white linens of the bed. The assassin's eyes bulge, his hands clawing uselessly at the thick, coarse fur of the beast as he is dragged backward, his muffled gurgles lost to the guttural snarls of the wolf. The scene is a visceral contrast of fragile innocence, maternal sacrifice, and raw, animalistic savagery."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["a mask of sheer terror and maternal agony , her breath coming in ragged gasps . a jagged wound on her arm seeps crimson , staining the fine , salt - stained linen of her gown . beside her , bran lies motionless on a heavy oak bed , his pale skin waxy and sweat - beaded , eyes closed in an unconscious stupor . the scene is frozen in a moment of violent intervention . a lean , sinister assassin , dressed in muted , charcoal - grey leathers that blend into the shadows , is being violently thrown backward . his expression is one of sudden , jarring shock , eyes wide with disbelief as his grip on a slender , rippled valyrian steel dagger slips . the blade , etched with smoky , swirling patterns , glints under the dim light . latching onto the assassin 's throat with primal ferocity is bran ’ s direwolf . the beast is a colossal shadow of grey and white fur , muscles rippling beneath a thick , coarse coat . its powerful jaws are clamped shut around the man 's neck , tearing through skin and sinew in a spray of vivid scarlet . the wolf 's eyes are amber slits of protective rage , its paws digging deep into the stone floor , claws scratching the grit . shadows stretch long and jagged across the room , cast by the dying embers of the hearth and the violent light from the window . the gothic architecture of the room — heavy vaulted ceilings and thick , oppressive pillars — frames the chaos . every texture is visceral : the rough grain of the wooden bedframe , the cold dampness of the limestone walls , and the wet , glistening gore of the assassin 's shredded throat . the atmosphere is heavy with the sudden transition from silent grief to explosive , animalistic violence ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["a mask of sheer terror and maternal agony , her breath coming in ragged gasps . a jagged wound on her arm seeps crimson , staining the fine , salt - stained linen of her gown . beside her , bran lies motionless on a heavy oak bed , his pale skin waxy and sweat - beaded , eyes closed in an unconscious stupor . the scene is frozen in a moment of violent intervention . a lean , sinister assassin , dressed in muted , charcoal - grey leathers that blend into the shadows , is being violently thrown backward . his expression is one of sudden , jarring shock , eyes wide with disbelief as his grip on a slender , rippled valyrian steel dagger slips . the blade , etched with smoky , swirling patterns , glints under the dim light . latching onto the assassin 's throat with primal ferocity is bran ’ s direwolf . the beast is a colossal shadow of grey and white fur , muscles rippling beneath a thick , coarse coat . its powerful jaws are clamped shut around the man 's neck , tearing through skin and sinew in a spray of vivid scarlet . the wolf 's eyes are amber slits of protective rage , its paws digging deep into the stone floor , claws scratching the grit . shadows stretch long and jagged across the room , cast by the dying embers of the hearth and the violent light from the window . the gothic architecture of the room — heavy vaulted ceilings and thick , oppressive pillars — frames the chaos . every texture is visceral : the rough grain of the wooden bedframe , the cold dampness of the limestone walls , and the wet , glistening gore of the assassin 's shredded throat . the atmosphere is heavy with the sudden transition from silent grief to explosive , animalistic violence ."]
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ["k is collapsed on the cold floor, her face a mask of sheer terror and maternal agony, her breath coming in ragged gasps. A jagged wound on her arm seeps crimson, staining the fine, salt-stained linen of her gown. Beside her, Bran lies motionless on a heavy oak bed, his pale skin waxy and sweat-beaded, eyes closed in an unconscious stupor. The scene is frozen in a moment of violent intervention. A lean, sinister assassin, dressed in muted, charcoal-grey leathers that blend into the shadows, is being violently thrown backward. His expression is one of sudden, jarring shock, eyes wide with disbelief as his grip on a slender, rippled Valyrian steel dagger slips. The blade, etched with smoky, swirling patterns, glints under the dim light. Latching onto the assassin's throat with primal ferocity is Bran’s direwolf. The beast is a colossal shadow of grey and white fur, muscles rippling beneath a thick, coarse coat. Its powerful jaws are clamped shut around the man's neck, tearing through skin and sinew in a spray of vivid scarlet. The wolf's eyes are amber slits of protective rage, its paws digging deep into the stone floor, claws scratching the grit. Shadows stretch long and jagged across the room, cast by the dying embers of the hearth and the violent light from the window. The Gothic architecture of the room—heavy vaulted ceilings and thick, oppressive pillars—frames the chaos. Every texture is visceral: the rough grain of the wooden bedframe, the cold dampness of the limestone walls, and the wet, glistening gore of the assassin's shredded throat. The atmosphere is heavy with the sudden transition from silent grief to explosive, animalistic violence."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [", a single streak of crimson blood blooming across her salt - stained linen gown where the blade has sliced through . opposite her , a hooded assassin looms , his posture coiled and predatory , his face obscured by a coarse , dark wool cowl that casts a deep shadow over his features . in the assassin 's grip is a slender , lethal dagger . the blade is forged from valyrian steel , characterized by its distinct , smoky ripples and dark , swirling patterns etched into the metal , shimmering with a cold , unnatural luster . the hilt is ornate , crafted from polished bone and dark leather , gripped by a hand with knuckles white from tension . the scene is violently interrupted by the sudden , explosive surge of summer , bran 's direwolf . the massive beast is a blur of grey - white fur and raw power , captured mid - leap , his jaws wide and teeth bared in a primal snarl . the wolf 's claws dig into the wooden floorboards , sending splinters flying . the composition focuses on the precise moment of impact : the wolf 's teeth sinking deep into the assassin 's throat , a spray of hot , bright blood painting the cold grey stone . lighting is dramatic and oppressive ; the room is dim , illuminated only by a flickering hearth and the distant , violent orange glow of a burning tower filtering through a narrow window , casting long , jagged silhouettes across the floor . dust motes dance in the shafts of amber light . in the background , bran lies motionless on his bed , his pale , sweat - beaded skin contrasting with the heavy , dark furs of his blankets , his expression one of haunting stillness amidst the chaos ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [", a single streak of crimson blood blooming across her salt - stained linen gown where the blade has sliced through . opposite her , a hooded assassin looms , his posture coiled and predatory , his face obscured by a coarse , dark wool cowl that casts a deep shadow over his features . in the assassin 's grip is a slender , lethal dagger . the blade is forged from valyrian steel , characterized by its distinct , smoky ripples and dark , swirling patterns etched into the metal , shimmering with a cold , unnatural luster . the hilt is ornate , crafted from polished bone and dark leather , gripped by a hand with knuckles white from tension . the scene is violently interrupted by the sudden , explosive surge of summer , bran 's direwolf . the massive beast is a blur of grey - white fur and raw power , captured mid - leap , his jaws wide and teeth bared in a primal snarl . the wolf 's claws dig into the wooden floorboards , sending splinters flying . the composition focuses on the precise moment of impact : the wolf 's teeth sinking deep into the assassin 's throat , a spray of hot , bright blood painting the cold grey stone . lighting is dramatic and oppressive ; the room is dim , illuminated only by a flickering hearth and the distant , violent orange glow of a burning tower filtering through a narrow window , casting long , jagged silhouettes across the floor . dust motes dance in the shafts of amber light . in the background , bran lies motionless on his bed , his pale , sweat - beaded skin contrasting with the heavy , dark furs of his blankets , his expression one of haunting stillness amidst the chaos ."]
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ["mask of shock, eyes wide and pupils dilated, a single streak of crimson blood blooming across her salt-stained linen gown where the blade has sliced through. Opposite her, a hooded assassin looms, his posture coiled and predatory, his face obscured by a coarse, dark wool cowl that casts a deep shadow over his features. In the assassin's grip is a slender, lethal dagger. The blade is forged from Valyrian steel, characterized by its distinct, smoky ripples and dark, swirling patterns etched into the metal, shimmering with a cold, unnatural luster. The hilt is ornate, crafted from polished bone and dark leather, gripped by a hand with knuckles white from tension. The scene is violently interrupted by the sudden, explosive surge of Summer, Bran's direwolf. The massive beast is a blur of grey-white fur and raw power, captured mid-leap, his jaws wide and teeth bared in a primal snarl. The wolf's claws dig into the wooden floorboards, sending splinters flying. The composition focuses on the precise moment of impact: the wolf's teeth sinking deep into the assassin's throat, a spray of hot, bright blood painting the cold grey stone. Lighting is dramatic and oppressive; the room is dim, illuminated only by a flickering hearth and the distant, violent orange glow of a burning tower filtering through a narrow window, casting long, jagged silhouettes across the floor. Dust motes dance in the shafts of amber light. In the background, Bran lies motionless on his bed, his pale, sweat-beaded skin contrasting with the heavy, dark furs of his blankets, his expression one of haunting stillness amidst the chaos."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["center of the frame , young arya stark stands with a fierce , protective intensity . her small frame is taut , shoulders squared , and her face is a mask of righteous fury . her skin is smudged with river silt and grime , with a single streak of mud crossing her cheek . she has just snatched ' lion 's tooth ,' joffrey ’ s ornate sword , from the ground . she grips the hilt with both hands , her knuckles white from the pressure , the blade angled defensively . the sword is a piece of arrogant craftsmanship : polished steel reflecting the grey sky , with a gold - filigreed pommel and a hilt wrapped in pristine , cream - colored leather that contrasts sharply with arya 's worn , dirt - stained linen tunic . opposite her , prince joffrey stands in a posture of wounded pride and simmering malice . he is dressed in rich , crimson velvets and gold embroidery , his clothes jarringly opulent against the wild , rugged backdrop . his lips are curled in a sneer of disbelief , his pale skin flushed with anger , and his eyes narrow with a cruel , entitled spark . between them , the butcher 's boy , mycah , cringes in terror . he is trembling , his breathing shallow , with a small , glistening bead of blood where the sword tip recently pricked his cheek . he is dressed in rough , salt - stained burlap , his posture collapsed and defeated . in the background , sansa stark watches with a look of horrified apprehension , her hands clasped tightly to her chest , her silk gown dragging in the mire . the environment is a graveyard of history , with the distant , skeletal remains of ancient battlements looming through the river mist , evoking the ghosts of the clash between robert baratheon and rhaegar targaryen ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["center of the frame , young arya stark stands with a fierce , protective intensity . her small frame is taut , shoulders squared , and her face is a mask of righteous fury . her skin is smudged with river silt and grime , with a single streak of mud crossing her cheek . she has just snatched ' lion 's tooth ,' joffrey ’ s ornate sword , from the ground . she grips the hilt with both hands , her knuckles white from the pressure , the blade angled defensively . the sword is a piece of arrogant craftsmanship : polished steel reflecting the grey sky , with a gold - filigreed pommel and a hilt wrapped in pristine , cream - colored leather that contrasts sharply with arya 's worn , dirt - stained linen tunic . opposite her , prince joffrey stands in a posture of wounded pride and simmering malice . he is dressed in rich , crimson velvets and gold embroidery , his clothes jarringly opulent against the wild , rugged backdrop . his lips are curled in a sneer of disbelief , his pale skin flushed with anger , and his eyes narrow with a cruel , entitled spark . between them , the butcher 's boy , mycah , cringes in terror . he is trembling , his breathing shallow , with a small , glistening bead of blood where the sword tip recently pricked his cheek . he is dressed in rough , salt - stained burlap , his posture collapsed and defeated . in the background , sansa stark watches with a look of horrified apprehension , her hands clasped tightly to her chest , her silk gown dragging in the mire . the environment is a graveyard of history , with the distant , skeletal remains of ancient battlements looming through the river mist , evoking the ghosts of the clash between robert baratheon and rhaegar targaryen ."]
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ["to the tall, swaying reeds. In the center of the frame, young Arya Stark stands with a fierce, protective intensity. Her small frame is taut, shoulders squared, and her face is a mask of righteous fury. Her skin is smudged with river silt and grime, with a single streak of mud crossing her cheek. She has just snatched 'Lion's Tooth,' Joffrey’s ornate sword, from the ground. She grips the hilt with both hands, her knuckles white from the pressure, the blade angled defensively. The sword is a piece of arrogant craftsmanship: polished steel reflecting the grey sky, with a gold-filigreed pommel and a hilt wrapped in pristine, cream-colored leather that contrasts sharply with Arya's worn, dirt-stained linen tunic. Opposite her, Prince Joffrey stands in a posture of wounded pride and simmering malice. He is dressed in rich, crimson velvets and gold embroidery, his clothes jarringly opulent against the wild, rugged backdrop. His lips are curled in a sneer of disbelief, his pale skin flushed with anger, and his eyes narrow with a cruel, entitled spark. Between them, the butcher's boy, Mycah, cringes in terror. He is trembling, his breathing shallow, with a small, glistening bead of blood where the sword tip recently pricked his cheek. He is dressed in rough, salt-stained burlap, his posture collapsed and defeated. In the background, Sansa Stark watches with a look of horrified apprehension, her hands clasped tightly to her chest, her silk gown dragging in the mire. The environment is a graveyard of history, with the distant, skeletal remains of ancient battlements looming through the river mist, evoking the ghosts of the clash between Robert Baratheon and Rhaegar Targaryen."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["inging to his forehead . hovering inches from his face is the three - eyed raven , a creature of unsettling intelligence . the raven 's feathers are not merely black , but a deep , iridescent void that absorbs the surrounding light , with three piercing , milky - white eyes that glow with an ancient , predatory wisdom . the bird 's beak is parted in a silent , commanding scream , its posture aggressive and urgent . the perspective is a dizzying , vertical plunge . below bran , the world unfolds like a living , breathing tapestry of gold , emerald , and slate grey . the architecture of winterfell is visible in miniature , the grey granite walls etched with frost , the godswood a splash of deep crimson leaves against a stark white snowfield . tiny , flickering figures of robb , hodor , and maester luwin move like ghosts through the courtyards . further south , the golden spires of king 's landing glint under a harsh , oppressive sun , where the figures of ned and the royal family are engulfed by creeping , ink - like shadows that coil around their ankles like serpents . to the east , the deep cerulean of the narrow sea is sliced by the sharp prow of a galley , while the distant , shimmering heat haze of the dothraki sea and the obsidian towers of asshai flicker on the horizon . to the far north , the colossal , translucent blue wall of ice looms , a jagged monolith of frozen history , with the solitary , dark silhouette of jon snow standing guard . the lighting is otherworldly ; a celestial , pale moonlight clashes with violent streaks of violet and gold nebula gas , casting long , distorted shadows across the floating fragments of the world . every texture is hyper - defined : the coarse , oily sheen of the raven 's plumage , the crystalline structure of the wall 's ice , and the fragile , trembling fabric of bran 's linen tunic ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["inging to his forehead . hovering inches from his face is the three - eyed raven , a creature of unsettling intelligence . the raven 's feathers are not merely black , but a deep , iridescent void that absorbs the surrounding light , with three piercing , milky - white eyes that glow with an ancient , predatory wisdom . the bird 's beak is parted in a silent , commanding scream , its posture aggressive and urgent . the perspective is a dizzying , vertical plunge . below bran , the world unfolds like a living , breathing tapestry of gold , emerald , and slate grey . the architecture of winterfell is visible in miniature , the grey granite walls etched with frost , the godswood a splash of deep crimson leaves against a stark white snowfield . tiny , flickering figures of robb , hodor , and maester luwin move like ghosts through the courtyards . further south , the golden spires of king 's landing glint under a harsh , oppressive sun , where the figures of ned and the royal family are engulfed by creeping , ink - like shadows that coil around their ankles like serpents . to the east , the deep cerulean of the narrow sea is sliced by the sharp prow of a galley , while the distant , shimmering heat haze of the dothraki sea and the obsidian towers of asshai flicker on the horizon . to the far north , the colossal , translucent blue wall of ice looms , a jagged monolith of frozen history , with the solitary , dark silhouette of jon snow standing guard . the lighting is otherworldly ; a celestial , pale moonlight clashes with violent streaks of violet and gold nebula gas , casting long , distorted shadows across the floating fragments of the world . every texture is hyper - defined : the coarse , oily sheen of the raven 's plumage , the crystalline structure of the wall 's ice , and the fragile , trembling fabric of bran 's linen tunic ."]
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ["awe. His skin is pale, almost translucent, with fine beads of cold sweat clinging to his forehead. Hovering inches from his face is the Three-Eyed Raven, a creature of unsettling intelligence. The raven's feathers are not merely black, but a deep, iridescent void that absorbs the surrounding light, with three piercing, milky-white eyes that glow with an ancient, predatory wisdom. The bird's beak is parted in a silent, commanding scream, its posture aggressive and urgent. The perspective is a dizzying, vertical plunge. Below Bran, the world unfolds like a living, breathing tapestry of gold, emerald, and slate grey. The architecture of Winterfell is visible in miniature, the grey granite walls etched with frost, the Godswood a splash of deep crimson leaves against a stark white snowfield. Tiny, flickering figures of Robb, Hodor, and Maester Luwin move like ghosts through the courtyards. Further south, the golden spires of King's Landing glint under a harsh, oppressive sun, where the figures of Ned and the royal family are engulfed by creeping, ink-like shadows that coil around their ankles like serpents. To the east, the deep cerulean of the Narrow Sea is sliced by the sharp prow of a galley, while the distant, shimmering heat haze of the Dothraki Sea and the obsidian towers of Asshai flicker on the horizon. To the far north, the colossal, translucent blue wall of ice looms, a jagged monolith of frozen history, with the solitary, dark silhouette of Jon Snow standing guard. The lighting is otherworldly; a celestial, pale moonlight clashes with violent streaks of violet and gold nebula gas, casting long, distorted shadows across the floating fragments of the world. Every texture is hyper-defined: the coarse, oily sheen of the raven's plumage, the crystalline structure of the Wall's ice, and the fragile, trembling fabric of Bran's linen tunic."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["strand of auburn hair clinging to her damp cheek . she wears a heavy , travel - worn cloak of deep charcoal wool , the fabric coarse and salt - stained , fastened by a simple silver brooch . beside her stands ser rodrik cassel , his presence a stark contrast of seasoned martial discipline and physical fragility . his face is raw and slightly reddened from the sea wind , notably missing his signature thick mustache — the skin above his lip is smooth and irritated , a pragmatic sacrifice to avoid the grime of his recent seasickness . he leans slightly against the salt - crusted mahogany railing , his knuckles white , his eyes scanning the horizon with a mixture of relief and apprehension . his leather brigandine is scuffed , showing the wear of a long voyage , with dull brass rivets catching the pale light . the lighting is oppressive and moody ; a heavy , overcast sky casts a diffused , cold silver light over the scene , creating deep , soft shadows in the folds of their garments . in the distance , the sprawling , jagged silhouette of king 's landing emerges through a veil of coastal mist , the red keep looming like a blood - stained monolith atop aegon 's hill . the architecture of the city is a dense , chaotic sprawl of terracotta roofs and limestone walls . the atmosphere is thick with unspoken dread . catelyn ’ s gaze is fixed on the city , her lips pressed thin , imagining the gaze of littlefinger and the dangers of the court . the deck of the ship is slick with seawater , reflecting the gloomy sky , while the rigging overhead snaps violently in the wind , adding a sense of urgency to their arrival ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["strand of auburn hair clinging to her damp cheek . she wears a heavy , travel - worn cloak of deep charcoal wool , the fabric coarse and salt - stained , fastened by a simple silver brooch . beside her stands ser rodrik cassel , his presence a stark contrast of seasoned martial discipline and physical fragility . his face is raw and slightly reddened from the sea wind , notably missing his signature thick mustache — the skin above his lip is smooth and irritated , a pragmatic sacrifice to avoid the grime of his recent seasickness . he leans slightly against the salt - crusted mahogany railing , his knuckles white , his eyes scanning the horizon with a mixture of relief and apprehension . his leather brigandine is scuffed , showing the wear of a long voyage , with dull brass rivets catching the pale light . the lighting is oppressive and moody ; a heavy , overcast sky casts a diffused , cold silver light over the scene , creating deep , soft shadows in the folds of their garments . in the distance , the sprawling , jagged silhouette of king 's landing emerges through a veil of coastal mist , the red keep looming like a blood - stained monolith atop aegon 's hill . the architecture of the city is a dense , chaotic sprawl of terracotta roofs and limestone walls . the atmosphere is thick with unspoken dread . catelyn ’ s gaze is fixed on the city , her lips pressed thin , imagining the gaze of littlefinger and the dangers of the court . the deck of the ship is slick with seawater , reflecting the gloomy sky , while the rigging overhead snaps violently in the wind , adding a sense of urgency to their arrival ."]
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ["on etched around her eyes and a single, stray strand of auburn hair clinging to her damp cheek. She wears a heavy, travel-worn cloak of deep charcoal wool, the fabric coarse and salt-stained, fastened by a simple silver brooch. Beside her stands Ser Rodrik Cassel, his presence a stark contrast of seasoned martial discipline and physical fragility. His face is raw and slightly reddened from the sea wind, notably missing his signature thick mustache—the skin above his lip is smooth and irritated, a pragmatic sacrifice to avoid the grime of his recent seasickness. He leans slightly against the salt-crusted mahogany railing, his knuckles white, his eyes scanning the horizon with a mixture of relief and apprehension. His leather brigandine is scuffed, showing the wear of a long voyage, with dull brass rivets catching the pale light. The lighting is oppressive and moody; a heavy, overcast sky casts a diffused, cold silver light over the scene, creating deep, soft shadows in the folds of their garments. In the distance, the sprawling, jagged silhouette of King's Landing emerges through a veil of coastal mist, the Red Keep looming like a blood-stained monolith atop Aegon's Hill. The architecture of the city is a dense, chaotic sprawl of terracotta roofs and limestone walls. The atmosphere is thick with unspoken dread. Catelyn’s gaze is fixed on the city, her lips pressed thin, imagining the gaze of Littlefinger and the dangers of the court. The deck of the ship is slick with seawater, reflecting the gloomy sky, while the rigging overhead snaps violently in the wind, adding a sense of urgency to their arrival."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [". he is dressed in simple , lightweight linens of a pale cream hue , the fabric clinging to his thin frame , smelling of salt and distant shores . his expression is one of playful yet piercing intensity , a slight , knowing smirk tugging at the corner of his mouth as he holds a wooden practice sword with an effortless , fluid grace . opposite him stands young arya stark , her small frame tense and vibrating with a mixture of defiance and curiosity . she wears a rough , salt - stained tunic of muted grey , her dark hair escaping a messy braid in wild strands that stick to her sweat - beaded forehead . her knuckles are white as she grips her own wooden sword , her wide , grey eyes locked onto syrio ’ s with a fierce , untamed determination . the tension between them is electric — a clash between the disciplined , rhythmic dance of braavos and the raw , unrefined spirit of the north . the surrounding architecture is oppressive ; massive , soot - stained limestone pillars rise toward a vaulted ceiling lost in deep , velvet shadows . the floor is composed of oversized , uneven flagstones , worn smooth by centuries of footsteps , reflecting the amber glow of the sun . in the background , the heavy oak doors of the small hall stand slightly ajar , casting a long , jagged silhouette across the floor . every detail is tactile : the rough grain of the practice swords , the dampness of the humid air , and the subtle ripple of syrio 's muscles as he shifts his weight , preparing to teach the girl that the sword is not a weapon , but a dance of survival ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [". he is dressed in simple , lightweight linens of a pale cream hue , the fabric clinging to his thin frame , smelling of salt and distant shores . his expression is one of playful yet piercing intensity , a slight , knowing smirk tugging at the corner of his mouth as he holds a wooden practice sword with an effortless , fluid grace . opposite him stands young arya stark , her small frame tense and vibrating with a mixture of defiance and curiosity . she wears a rough , salt - stained tunic of muted grey , her dark hair escaping a messy braid in wild strands that stick to her sweat - beaded forehead . her knuckles are white as she grips her own wooden sword , her wide , grey eyes locked onto syrio ’ s with a fierce , untamed determination . the tension between them is electric — a clash between the disciplined , rhythmic dance of braavos and the raw , unrefined spirit of the north . the surrounding architecture is oppressive ; massive , soot - stained limestone pillars rise toward a vaulted ceiling lost in deep , velvet shadows . the floor is composed of oversized , uneven flagstones , worn smooth by centuries of footsteps , reflecting the amber glow of the sun . in the background , the heavy oak doors of the small hall stand slightly ajar , casting a long , jagged silhouette across the floor . every detail is tactile : the rough grain of the practice swords , the dampness of the humid air , and the subtle ripple of syrio 's muscles as he shifts his weight , preparing to teach the girl that the sword is not a weapon , but a dance of survival ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["cream hue , the fabric clinging to his frame with salt - stained creases . his expression is one of playful yet piercing intensity , his dark eyes locked onto arya stark . arya , small and fierce , holds a blunt practice sword with white - knuckled intensity . her face is smudged with grime , a single bead of sweat tracing a path through the dust on her cheek . her posture is rigid , reflecting the clumsy strength of the west , contrasting sharply with syrio 's ethereal grace . he moves not like a soldier , but like a ripple in a pond , his wooden blade flickering in a blur of motion . the lighting is harsh and vertical , casting short , ink - black shadows that anchor the figures to the scorched earth . in the background , the gothic arches of the small hall loom , their intricate carvings weathered by centuries of salt air and neglect . the air is thick with floating motes of gold dust , illuminated by shafts of light piercing through the overhead colonnades . the tension is palpable — a clash of philosophies . syrio ’ s wooden sword barely touches arya ’ s , a series of rapid , sudden taps that mimic the flow of water , while arya lunges with heavy , desperate strikes . the texture of the scene is visceral : the rough grain of the practice swords , the coarse grit of the courtyard sand kicking up around their boots , and the shimmering heat haze distorting the distant red stone towers . syrio ’ s lips are curled in a knowing , enigmatic smile , his body coiled like a spring , embodying the water dance — a lethal , liquid elegance that makes the heavy iron of the westerosi knights seem archaic and slow ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["cream hue , the fabric clinging to his frame with salt - stained creases . his expression is one of playful yet piercing intensity , his dark eyes locked onto arya stark . arya , small and fierce , holds a blunt practice sword with white - knuckled intensity . her face is smudged with grime , a single bead of sweat tracing a path through the dust on her cheek . her posture is rigid , reflecting the clumsy strength of the west , contrasting sharply with syrio 's ethereal grace . he moves not like a soldier , but like a ripple in a pond , his wooden blade flickering in a blur of motion . the lighting is harsh and vertical , casting short , ink - black shadows that anchor the figures to the scorched earth . in the background , the gothic arches of the small hall loom , their intricate carvings weathered by centuries of salt air and neglect . the air is thick with floating motes of gold dust , illuminated by shafts of light piercing through the overhead colonnades . the tension is palpable — a clash of philosophies . syrio ’ s wooden sword barely touches arya ’ s , a series of rapid , sudden taps that mimic the flow of water , while arya lunges with heavy , desperate strikes . the texture of the scene is visceral : the rough grain of the practice swords , the coarse grit of the courtyard sand kicking up around their boots , and the shimmering heat haze distorting the distant red stone towers . syrio ’ s lips are curled in a knowing , enigmatic smile , his body coiled like a spring , embodying the water dance — a lethal , liquid elegance that makes the heavy iron of the westerosi knights seem archaic and slow ."]
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ["a poised, fluid stance. He is dressed in light, breathable linens of a pale cream hue, the fabric clinging to his frame with salt-stained creases. His expression is one of playful yet piercing intensity, his dark eyes locked onto Arya Stark. Arya, small and fierce, holds a blunt practice sword with white-knuckled intensity. Her face is smudged with grime, a single bead of sweat tracing a path through the dust on her cheek. Her posture is rigid, reflecting the clumsy strength of the West, contrasting sharply with Syrio's ethereal grace. He moves not like a soldier, but like a ripple in a pond, his wooden blade flickering in a blur of motion. The lighting is harsh and vertical, casting short, ink-black shadows that anchor the figures to the scorched earth. In the background, the Gothic arches of the Small Hall loom, their intricate carvings weathered by centuries of salt air and neglect. The air is thick with floating motes of gold dust, illuminated by shafts of light piercing through the overhead colonnades. The tension is palpable—a clash of philosophies. Syrio’s wooden sword barely touches Arya’s, a series of rapid, sudden taps that mimic the flow of water, while Arya lunges with heavy, desperate strikes. The texture of the scene is visceral: the rough grain of the practice swords, the coarse grit of the courtyard sand kicking up around their boots, and the shimmering heat haze distorting the distant red stone towers. Syrio’s lips are curled in a knowing, enigmatic smile, his body coiled like a spring, embodying the Water Dance—a lethal, liquid elegance that makes the heavy iron of the Westerosi knights seem archaic and slow."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['a captive to the quiet strength of a mother . she is dressed in worn , salt - stained linen and rough - spun silks of pale cream , the fabric clinging to her skin , damp with a fine sheen of sweat that beads on her collarbone and forehead . beside her , jhiqui leans in , her expression a mixture of reverence and knowing . the tension between them is palpable — a shared secret in a world of warriors . jhiqui ’ s hand hovers inches from daenerys ’ s abdomen , her dark eyes searching daenerys ’ s face . daenerys ’ s expression is a complex tapestry of shock and sudden , fierce clarity ; her lips are slightly parted , her silver - gold hair whipping across her face in the dry wind , some strands catching in the coarse weave of her tunic . the lighting is dramatic and directional , with the dying sun casting long , jagged silhouettes across the parched earth . a deep , amber glow illuminates the side of daenerys ’ s face , leaving the other half in a soft , velvet shadow , symbolizing her dual nature as a frightened girl and a rising queen . in the background , the blurred shapes of the khalasar are visible : the flickering orange embers of distant campfires , the silhouettes of horses with braided manes , and the distant , imposing figure of khal drogo , a mountain of muscle and leather , watching from afar . the ground is a texture of crushed yellow grass and grey dust that clings to the hem of her skirts . every detail is visceral : the cracked leather of the saddles , the glint of bronze ornaments , and the raw , organic intensity of a woman discovering a new life stirring within her amidst a wasteland of war .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['a captive to the quiet strength of a mother . she is dressed in worn , salt - stained linen and rough - spun silks of pale cream , the fabric clinging to her skin , damp with a fine sheen of sweat that beads on her collarbone and forehead . beside her , jhiqui leans in , her expression a mixture of reverence and knowing . the tension between them is palpable — a shared secret in a world of warriors . jhiqui ’ s hand hovers inches from daenerys ’ s abdomen , her dark eyes searching daenerys ’ s face . daenerys ’ s expression is a complex tapestry of shock and sudden , fierce clarity ; her lips are slightly parted , her silver - gold hair whipping across her face in the dry wind , some strands catching in the coarse weave of her tunic . the lighting is dramatic and directional , with the dying sun casting long , jagged silhouettes across the parched earth . a deep , amber glow illuminates the side of daenerys ’ s face , leaving the other half in a soft , velvet shadow , symbolizing her dual nature as a frightened girl and a rising queen . in the background , the blurred shapes of the khalasar are visible : the flickering orange embers of distant campfires , the silhouettes of horses with braided manes , and the distant , imposing figure of khal drogo , a mountain of muscle and leather , watching from afar . the ground is a texture of crushed yellow grass and grey dust that clings to the hem of her skirts . every detail is visceral : the cracked leather of the saddles , the glint of bronze ornaments , and the raw , organic intensity of a woman discovering a new life stirring within her amidst a wasteland of war .']
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ['a moment of profound, silent revelation, her posture shifting from the fragility of a captive to the quiet strength of a mother. She is dressed in worn, salt-stained linen and rough-spun silks of pale cream, the fabric clinging to her skin, damp with a fine sheen of sweat that beads on her collarbone and forehead. Beside her, Jhiqui leans in, her expression a mixture of reverence and knowing. The tension between them is palpable—a shared secret in a world of warriors. Jhiqui’s hand hovers inches from Daenerys’s abdomen, her dark eyes searching Daenerys’s face. Daenerys’s expression is a complex tapestry of shock and sudden, fierce clarity; her lips are slightly parted, her silver-gold hair whipping across her face in the dry wind, some strands catching in the coarse weave of her tunic. The lighting is dramatic and directional, with the dying sun casting long, jagged silhouettes across the parched earth. A deep, amber glow illuminates the side of Daenerys’s face, leaving the other half in a soft, velvet shadow, symbolizing her dual nature as a frightened girl and a rising queen. In the background, the blurred shapes of the khalasar are visible: the flickering orange embers of distant campfires, the silhouettes of horses with braided manes, and the distant, imposing figure of Khal Drogo, a mountain of muscle and leather, watching from afar. The ground is a texture of crushed yellow grass and grey dust that clings to the hem of her skirts. Every detail is visceral: the cracked leather of the saddles, the glint of bronze ornaments, and the raw, organic intensity of a woman discovering a new life stirring within her amidst a wasteland of war.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["grey wool and worn linen . his face is a mask of fragile defiance , eyes wide and searching , while his posture is stiff , held upright by the effort of his will . beside him , robb stark stands like a sentinel , his brow furrowed in deep suspicion , hand resting instinctively on the hilt of his sword , his gaze sharp and protective . tyrion lannister stands opposite them , a striking contrast in his rich , crimson velvet doublet with gold embroidery that catches the flickering light of nearby tallow candles . his expression is one of calculated empathy , a slight , knowing smirk playing on his lips , while his mismatched eyes glint with an intellect that borders on arrogance . he holds a piece of yellowed vellum — the blueprints for a specialized saddle — extending it toward the maester . the paper is crisp , with precise , ink - drawn diagrams of leather straps and reinforced supports . the lighting is dramatic and moody ; a single high window allows a shaft of pale , wintry sunlight to pierce the gloom , illuminating dust motes dancing in the air and casting long , jagged shadows across the uneven flagstone floor . the texture of the room is palpable : the rough - hewn granite of the walls , the polished dark oak of the furniture , and the sweat - beaded skin on bran ’ s forehead . the tension is a physical presence , a silent clash between the lannister ’ s unexpected generosity and the starks ' ingrained distrust . every micro - expression is captured — the maester ’ s squint of professional curiosity as he examines the plans , and the subtle flicker of resentment in robb 's jaw ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["grey wool and worn linen . his face is a mask of fragile defiance , eyes wide and searching , while his posture is stiff , held upright by the effort of his will . beside him , robb stark stands like a sentinel , his brow furrowed in deep suspicion , hand resting instinctively on the hilt of his sword , his gaze sharp and protective . tyrion lannister stands opposite them , a striking contrast in his rich , crimson velvet doublet with gold embroidery that catches the flickering light of nearby tallow candles . his expression is one of calculated empathy , a slight , knowing smirk playing on his lips , while his mismatched eyes glint with an intellect that borders on arrogance . he holds a piece of yellowed vellum — the blueprints for a specialized saddle — extending it toward the maester . the paper is crisp , with precise , ink - drawn diagrams of leather straps and reinforced supports . the lighting is dramatic and moody ; a single high window allows a shaft of pale , wintry sunlight to pierce the gloom , illuminating dust motes dancing in the air and casting long , jagged shadows across the uneven flagstone floor . the texture of the room is palpable : the rough - hewn granite of the walls , the polished dark oak of the furniture , and the sweat - beaded skin on bran ’ s forehead . the tension is a physical presence , a silent clash between the lannister ’ s unexpected generosity and the starks ' ingrained distrust . every micro - expression is captured — the maester ’ s squint of professional curiosity as he examines the plans , and the subtle flicker of resentment in robb 's jaw ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['parchment color , beaded with cold sweat that glitters under the flickering amber light of a dying tallow candle . his fingers , gnarled and trembling , claw desperately at the surface of a massive , leather - bound tome : " the lineages and histories of the great houses of the seven kingdoms ." the book is splayed open , its vellum pages yellowed and brittle , covered in dense , handwritten genealogical charts and ink - stained annotations that hint at a forbidden discovery . standing over him is grand maester pycelle , his posture a study in calculated indifference . pycelle ’ s heavy , velvet robes of deep crimson swallow his frail frame , the fabric thick and dusty . his long , white beard is meticulously groomed , contrasting with the predatory , calculating glint in his watery eyes . he watches arryn ’ s struggle not with urgency , but with a cold , clinical curiosity , his hands tucked hidden within his wide sleeves . the lighting is oppressive ; a single high , narrow gothic window allows a sliver of bruised purple twilight to pierce the gloom , casting a long , jagged shadow of pycelle across the dying man . the environment is cluttered with the tools of a maester : glass vials filled with iridescent liquids , bundles of dried herbs hanging from the rafters , and stacks of scrolls tied with frayed twine . the texture of the scene is visceral — the rough grain of the oak desk , the embossed gold leaf peeling off the book \'s spine , and the visible tension in arryn \'s neck tendons as he gasps for air , his eyes wide with the terror of a man who has uncovered a secret that has now become his death sentence .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['parchment color , beaded with cold sweat that glitters under the flickering amber light of a dying tallow candle . his fingers , gnarled and trembling , claw desperately at the surface of a massive , leather - bound tome : " the lineages and histories of the great houses of the seven kingdoms ." the book is splayed open , its vellum pages yellowed and brittle , covered in dense , handwritten genealogical charts and ink - stained annotations that hint at a forbidden discovery . standing over him is grand maester pycelle , his posture a study in calculated indifference . pycelle ’ s heavy , velvet robes of deep crimson swallow his frail frame , the fabric thick and dusty . his long , white beard is meticulously groomed , contrasting with the predatory , calculating glint in his watery eyes . he watches arryn ’ s struggle not with urgency , but with a cold , clinical curiosity , his hands tucked hidden within his wide sleeves . the lighting is oppressive ; a single high , narrow gothic window allows a sliver of bruised purple twilight to pierce the gloom , casting a long , jagged shadow of pycelle across the dying man . the environment is cluttered with the tools of a maester : glass vials filled with iridescent liquids , bundles of dried herbs hanging from the rafters , and stacks of scrolls tied with frayed twine . the texture of the scene is visceral — the rough grain of the oak desk , the embossed gold leaf peeling off the book \'s spine , and the visible tension in arryn \'s neck tendons as he gasps for air , his eyes wide with the terror of a man who has uncovered a secret that has now become his death sentence .']
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ['His skin is a sickly, translucent parchment color, beaded with cold sweat that glitters under the flickering amber light of a dying tallow candle. His fingers, gnarled and trembling, claw desperately at the surface of a massive, leather-bound tome: "The Lineages and Histories of the Great Houses of the Seven Kingdoms." The book is splayed open, its vellum pages yellowed and brittle, covered in dense, handwritten genealogical charts and ink-stained annotations that hint at a forbidden discovery. Standing over him is Grand Maester Pycelle, his posture a study in calculated indifference. Pycelle’s heavy, velvet robes of deep crimson swallow his frail frame, the fabric thick and dusty. His long, white beard is meticulously groomed, contrasting with the predatory, calculating glint in his watery eyes. He watches Arryn’s struggle not with urgency, but with a cold, clinical curiosity, his hands tucked hidden within his wide sleeves. The lighting is oppressive; a single high, narrow Gothic window allows a sliver of bruised purple twilight to pierce the gloom, casting a long, jagged shadow of Pycelle across the dying man. The environment is cluttered with the tools of a Maester: glass vials filled with iridescent liquids, bundles of dried herbs hanging from the rafters, and stacks of scrolls tied with frayed twine. The texture of the scene is visceral—the rough grain of the oak desk, the embossed gold leaf peeling off the book\'s spine, and the visible tension in Arryn\'s neck tendons as he gasps for air, his eyes wide with the terror of a man who has uncovered a secret that has now become his death sentence.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["cold , northern determination . beside him , ghost is a spectral presence , a massive white direwolf with piercing red eyes , his teeth bared in a silent , menacing snarl , muscles rippling beneath thick , snow - white fur . rast is recoiling into his rough , straw - filled cot , his face contorted in a mixture of sudden terror and disbelief . sweat beads on his forehead , glistening under the flickering , amber light of a distant torch that casts long , jagged silhouettes across the frost - covered stone walls . the lighting is chiaroscuro , with deep , ink - black shadows swallowing the corners of the room , emphasizing the isolation of the encounter . in the background , samwell tarly is visible , huddled in a heavy , oversized black cloak of coarse , salt - stained wool . his expression is one of fragile hope and profound vulnerability , his wide eyes reflecting the torchlight as he watches jon ’ s unexpected defense . the textures are visceral : the rough - hewn granite of the walls , the frayed edges of the black uniforms , and the cold , metallic glint of a training sword leaning against a wooden pillar . the atmosphere is heavy with the unspoken brotherhood of outcasts . jon ’ s hand rests firmly on ghost ’ s neck , the contrast between the pale fur and the dark leather of jon 's glove highlighting the bond between them . the scene is a study in power dynamics — the physical intimidation of the wolf and the moral strength of jon snow , set against the bleak , gothic austerity of the wall 's interior , where the cold seems to seep through the very image ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["cold , northern determination . beside him , ghost is a spectral presence , a massive white direwolf with piercing red eyes , his teeth bared in a silent , menacing snarl , muscles rippling beneath thick , snow - white fur . rast is recoiling into his rough , straw - filled cot , his face contorted in a mixture of sudden terror and disbelief . sweat beads on his forehead , glistening under the flickering , amber light of a distant torch that casts long , jagged silhouettes across the frost - covered stone walls . the lighting is chiaroscuro , with deep , ink - black shadows swallowing the corners of the room , emphasizing the isolation of the encounter . in the background , samwell tarly is visible , huddled in a heavy , oversized black cloak of coarse , salt - stained wool . his expression is one of fragile hope and profound vulnerability , his wide eyes reflecting the torchlight as he watches jon ’ s unexpected defense . the textures are visceral : the rough - hewn granite of the walls , the frayed edges of the black uniforms , and the cold , metallic glint of a training sword leaning against a wooden pillar . the atmosphere is heavy with the unspoken brotherhood of outcasts . jon ’ s hand rests firmly on ghost ’ s neck , the contrast between the pale fur and the dark leather of jon 's glove highlighting the bond between them . the scene is a study in power dynamics — the physical intimidation of the wolf and the moral strength of jon snow , set against the bleak , gothic austerity of the wall 's interior , where the cold seems to seep through the very image ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [", whose face is twisted in a sudden , waking mask of sheer terror . beside jon , ghost , the direwolf , is a spectral presence of blinding white fur and piercing red eyes , his massive head inches from rast ’ s throat , a low , guttural snarl vibrating through his chest . the lighting is visceral ; flickering orange torchlight casts dancing , jagged shadows against the rough - hewn granite walls , while a pale , freezing moonlight spills through a narrow arrow - slit , illuminating the frost clinging to the iron bedframes . jon ’ s expression is a study in controlled menace ; his dark brows are furrowed , and his eyes are cold , reflecting the hardness of the wall . he wears a heavy , salt - stained black cloak of thick , coarse wool with a leather strap crossing his chest . his hand rests firmly on the hilt of his sword , the pommel worn from use . rast is sprawled back against a thin , grey linen mattress , his skin beaded with cold sweat , his eyes wide and pupils dilated in panic . in the blurred background , samwell tarly is visible , huddled in a thick , oversized fur mantle that swallows his soft frame . his expression is one of profound relief and tentative hope , his eyes shimmering with unshed tears as he watches jon ’ s protective stance . the textures are tactile : the grit of the stone floor , the frayed edges of the wool blankets , and the crystalline frost forming on the edges of the room . the tension is palpable , a silent vow of brotherhood forged in the oppressive darkness of the night 's watch ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [", whose face is twisted in a sudden , waking mask of sheer terror . beside jon , ghost , the direwolf , is a spectral presence of blinding white fur and piercing red eyes , his massive head inches from rast ’ s throat , a low , guttural snarl vibrating through his chest . the lighting is visceral ; flickering orange torchlight casts dancing , jagged shadows against the rough - hewn granite walls , while a pale , freezing moonlight spills through a narrow arrow - slit , illuminating the frost clinging to the iron bedframes . jon ’ s expression is a study in controlled menace ; his dark brows are furrowed , and his eyes are cold , reflecting the hardness of the wall . he wears a heavy , salt - stained black cloak of thick , coarse wool with a leather strap crossing his chest . his hand rests firmly on the hilt of his sword , the pommel worn from use . rast is sprawled back against a thin , grey linen mattress , his skin beaded with cold sweat , his eyes wide and pupils dilated in panic . in the blurred background , samwell tarly is visible , huddled in a thick , oversized fur mantle that swallows his soft frame . his expression is one of profound relief and tentative hope , his eyes shimmering with unshed tears as he watches jon ’ s protective stance . the textures are tactile : the grit of the stone floor , the frayed edges of the wool blankets , and the crystalline frost forming on the edges of the room . the tension is palpable , a silent vow of brotherhood forged in the oppressive darkness of the night 's watch ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["yet dangerous . opposite him stands sansa stark , small and fragile , her face a mask of terrified curiosity and suppressed horror . the tension between them is electric , a collision of raw brutality and aristocratic innocence . the lighting is visceral ; a single , flickering torch on the wall casts a violent , orange glow that dances across the scene , leaving deep , cavernous shadows in the corners of the room . the light catches the sweat - beaded skin of sandor 's forehead and the glint of a half - empty wine skin clutched in his calloused , scarred hand . sandor slowly turns his head , forcing sansa to look directly at the ruin of his face . the detail is harrowing : the skin on the left side of his face is a landscape of puckered , glossy scar tissue , melted and fused into a permanent , twisted grimace . the texture is a mix of waxy , pale ridges and deep , angry crimson furrows where the flesh once bubbled . he describes the memory with a low , guttural rasp — the sensation of his brother gregor ’ s massive hand crushing his skull downward , the searing , blinding heat of the red - hot coals in the brazier , and the smell of his own burning skin . sansa ’ s expression is one of visceral shock ; her pupils are dilated , her lips slightly parted , a single tear tracing a path through the fine powder on her cheek . she wears a gown of pale , heavy silk , the fabric shimmering faintly in the torchlight , contrasting sharply with sandor 's worn , salt - stained leather armor and the rough , coarse wool of his cloak . the environment is claustrophobic , with heavy gothic arches overhead and the distant , muffled sounds of the city echoing through the cold stone corridors ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["yet dangerous . opposite him stands sansa stark , small and fragile , her face a mask of terrified curiosity and suppressed horror . the tension between them is electric , a collision of raw brutality and aristocratic innocence . the lighting is visceral ; a single , flickering torch on the wall casts a violent , orange glow that dances across the scene , leaving deep , cavernous shadows in the corners of the room . the light catches the sweat - beaded skin of sandor 's forehead and the glint of a half - empty wine skin clutched in his calloused , scarred hand . sandor slowly turns his head , forcing sansa to look directly at the ruin of his face . the detail is harrowing : the skin on the left side of his face is a landscape of puckered , glossy scar tissue , melted and fused into a permanent , twisted grimace . the texture is a mix of waxy , pale ridges and deep , angry crimson furrows where the flesh once bubbled . he describes the memory with a low , guttural rasp — the sensation of his brother gregor ’ s massive hand crushing his skull downward , the searing , blinding heat of the red - hot coals in the brazier , and the smell of his own burning skin . sansa ’ s expression is one of visceral shock ; her pupils are dilated , her lips slightly parted , a single tear tracing a path through the fine powder on her cheek . she wears a gown of pale , heavy silk , the fabric shimmering faintly in the torchlight , contrasting sharply with sandor 's worn , salt - stained leather armor and the rough , coarse wool of his cloak . the environment is claustrophobic , with heavy gothic arches overhead and the distant , muffled sounds of the city echoing through the cold stone corridors ."]
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ["drunken, bitter intensity, his posture slumped yet dangerous. Opposite him stands Sansa Stark, small and fragile, her face a mask of terrified curiosity and suppressed horror. The tension between them is electric, a collision of raw brutality and aristocratic innocence. The lighting is visceral; a single, flickering torch on the wall casts a violent, orange glow that dances across the scene, leaving deep, cavernous shadows in the corners of the room. The light catches the sweat-beaded skin of Sandor's forehead and the glint of a half-empty wine skin clutched in his calloused, scarred hand. Sandor slowly turns his head, forcing Sansa to look directly at the ruin of his face. The detail is harrowing: the skin on the left side of his face is a landscape of puckered, glossy scar tissue, melted and fused into a permanent, twisted grimace. The texture is a mix of waxy, pale ridges and deep, angry crimson furrows where the flesh once bubbled. He describes the memory with a low, guttural rasp—the sensation of his brother Gregor’s massive hand crushing his skull downward, the searing, blinding heat of the red-hot coals in the brazier, and the smell of his own burning skin. Sansa’s expression is one of visceral shock; her pupils are dilated, her lips slightly parted, a single tear tracing a path through the fine powder on her cheek. She wears a gown of pale, heavy silk, the fabric shimmering faintly in the torchlight, contrasting sharply with Sandor's worn, salt-stained leather armor and the rough, coarse wool of his cloak. The environment is claustrophobic, with heavy Gothic arches overhead and the distant, muffled sounds of the city echoing through the cold stone corridors."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["and unwavering , are locked onto tyrion lannister . she wears a heavy , travel - worn cloak of deep charcoal wool , the fabric coarse and pilled from leagues of riding , fastened by a silver brooch . tyrion is caught mid - gesture , a goblet of wine frozen in his hand , his small frame dwarfed by the looming threat around him . his expression is a complex blend of genuine shock and a flickering , calculating wit ; a single bead of sweat rolls down his temple , glistening under the flickering orange glow of the hearth . he is dressed in rich , crimson velvet that looks garish and out of place in the rustic , grime - streaked interior of the inn . surrounding them , a dozen men - at - arms erupt into motion . the sound is a synchronized metallic shriek as longswords are unsheathed from leather scabbards . the blades are polished steel , reflecting the violent , dancing flames of the fireplace , casting jagged , elongated shadows across the uneven stone floor and the rough - hewn timber beams of the ceiling . the lighting is chiaroscuro ; deep , oppressive blacks in the corners of the room contrasted with the harsh , warm amber light hitting the characters ' faces . dust motes dance in the shafts of light piercing through the grime - coated windows . the texture of the room is visceral : the greasy sheen on the wooden tables , the salt - stained linen of the peasants ' tunics , and the cold , damp grey of the stone walls . catelyn ’ s hand is clenched tight , her knuckles white , embodying the absolute authority of the north , while the air vibrates with the unspoken threat of violence and the sudden collapse of hospitality ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["and unwavering , are locked onto tyrion lannister . she wears a heavy , travel - worn cloak of deep charcoal wool , the fabric coarse and pilled from leagues of riding , fastened by a silver brooch . tyrion is caught mid - gesture , a goblet of wine frozen in his hand , his small frame dwarfed by the looming threat around him . his expression is a complex blend of genuine shock and a flickering , calculating wit ; a single bead of sweat rolls down his temple , glistening under the flickering orange glow of the hearth . he is dressed in rich , crimson velvet that looks garish and out of place in the rustic , grime - streaked interior of the inn . surrounding them , a dozen men - at - arms erupt into motion . the sound is a synchronized metallic shriek as longswords are unsheathed from leather scabbards . the blades are polished steel , reflecting the violent , dancing flames of the fireplace , casting jagged , elongated shadows across the uneven stone floor and the rough - hewn timber beams of the ceiling . the lighting is chiaroscuro ; deep , oppressive blacks in the corners of the room contrasted with the harsh , warm amber light hitting the characters ' faces . dust motes dance in the shafts of light piercing through the grime - coated windows . the texture of the room is visceral : the greasy sheen on the wooden tables , the salt - stained linen of the peasants ' tunics , and the cold , damp grey of the stone walls . catelyn ’ s hand is clenched tight , her knuckles white , embodying the absolute authority of the north , while the air vibrates with the unspoken threat of violence and the sudden collapse of hospitality ."]
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ["ing, her face a mask of cold, maternal fury. Her eyes, sharp and unwavering, are locked onto Tyrion Lannister. She wears a heavy, travel-worn cloak of deep charcoal wool, the fabric coarse and pilled from leagues of riding, fastened by a silver brooch. Tyrion is caught mid-gesture, a goblet of wine frozen in his hand, his small frame dwarfed by the looming threat around him. His expression is a complex blend of genuine shock and a flickering, calculating wit; a single bead of sweat rolls down his temple, glistening under the flickering orange glow of the hearth. He is dressed in rich, crimson velvet that looks garish and out of place in the rustic, grime-streaked interior of the inn. Surrounding them, a dozen men-at-arms erupt into motion. The sound is a synchronized metallic shriek as longswords are unsheathed from leather scabbards. The blades are polished steel, reflecting the violent, dancing flames of the fireplace, casting jagged, elongated shadows across the uneven stone floor and the rough-hewn timber beams of the ceiling. The lighting is chiaroscuro; deep, oppressive blacks in the corners of the room contrasted with the harsh, warm amber light hitting the characters' faces. Dust motes dance in the shafts of light piercing through the grime-coated windows. The texture of the room is visceral: the greasy sheen on the wooden tables, the salt-stained linen of the peasants' tunics, and the cold, damp grey of the stone walls. Catelyn’s hand is clenched tight, her knuckles white, embodying the absolute authority of the North, while the air vibrates with the unspoken threat of violence and the sudden collapse of hospitality."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["cloak of deep charcoal grey is whipped violently by a freezing gale , the fabric frayed and salt - stained from the journey . her knuckles are white as she grips the lead rope , her eyes cold and piercing , reflecting a mother 's vengeful resolve . tyrion , dwarfed by the towering limestone cliffs , stumbles on the uneven shale . his expensive crimson doublet is torn and coated in a layer of grey dust and dried mud ; the fine velvet is matted and worn . his expression is a complex mixture of intellectual defiance and genuine fear , a slight , sardonic smirk twitching at the corner of his mouth despite the sweat - beaded skin of his forehead and the bruising around his wrists where the rough hemp rope bites deep into his flesh . the lighting is oppressive : a bruised , purple - grey twilight descends , with a pale , dying sun casting long , distorted shadows that stretch like fingers across the rocky terrain . the air is thick with a swirling mist that clings to the damp , lichen - covered stone walls of the gorge . in the background , the oppressive gothic silhouette of the eyrie looms far above , a precarious spire of white stone clinging to the mountain peak , barely visible through the haze . every detail is tactile : the gritty texture of the sliding scree beneath their boots , the metallic scent of incoming snow , and the rhythmic , heavy breathing of the guards flanking them . the tension is palpable , a silent war of wills between the high - born lady and the imp , framed by the indifferent , monolithic cruelty of the westerosi highlands ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["cloak of deep charcoal grey is whipped violently by a freezing gale , the fabric frayed and salt - stained from the journey . her knuckles are white as she grips the lead rope , her eyes cold and piercing , reflecting a mother 's vengeful resolve . tyrion , dwarfed by the towering limestone cliffs , stumbles on the uneven shale . his expensive crimson doublet is torn and coated in a layer of grey dust and dried mud ; the fine velvet is matted and worn . his expression is a complex mixture of intellectual defiance and genuine fear , a slight , sardonic smirk twitching at the corner of his mouth despite the sweat - beaded skin of his forehead and the bruising around his wrists where the rough hemp rope bites deep into his flesh . the lighting is oppressive : a bruised , purple - grey twilight descends , with a pale , dying sun casting long , distorted shadows that stretch like fingers across the rocky terrain . the air is thick with a swirling mist that clings to the damp , lichen - covered stone walls of the gorge . in the background , the oppressive gothic silhouette of the eyrie looms far above , a precarious spire of white stone clinging to the mountain peak , barely visible through the haze . every detail is tactile : the gritty texture of the sliding scree beneath their boots , the metallic scent of incoming snow , and the rhythmic , heavy breathing of the guards flanking them . the tension is palpable , a silent war of wills between the high - born lady and the imp , framed by the indifferent , monolithic cruelty of the westerosi highlands ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["elements , stripped of a ceiling , allowing the oppressive , slate - grey clouds of the vale to swirl violently overhead . tyrion is huddled against the rear wall , his small frame trembling . his skin is sallow , beaded with cold sweat , and his velvet doublet is stained with grime and salt . his expression is one of raw , wide - eyed insomnia ; his pupils are dilated with the primal fear of rolling an inch too far in his sleep and plummeting to his death . standing over him is mord , the jailer , a man of grotesque cruelty . mord ’ s face is a map of pockmarks and sneers , his eyes glinting with sadistic pleasure . he holds a wooden platter of meager food , gripping it with calloused , dirt - caked fingers . the tension is electric as mord deliberately lifts the plate just out of tyrion ’ s reach , a slow , mocking gesture of power . tyrion ’ s hand is outstretched , fingers trembling , his posture desperate and diminished . the lighting is a harsh , diffused alpine glare , casting cold , blue - toned shadows that cling to the crevices of the rock . the air is thick with a visible , freezing mist that clings to the characters ' clothes . every texture is visceral : the rough , abrasive grain of the limestone , the coarse wool of mord 's tunic , and the damp , glistening moisture on the slanted floor . in the background , the dizzying drop of the mountain peaks stretches infinitely downward , a void of swirling white fog and sharp , obsidian crags , emphasizing the lethal fragility of the ledge ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["elements , stripped of a ceiling , allowing the oppressive , slate - grey clouds of the vale to swirl violently overhead . tyrion is huddled against the rear wall , his small frame trembling . his skin is sallow , beaded with cold sweat , and his velvet doublet is stained with grime and salt . his expression is one of raw , wide - eyed insomnia ; his pupils are dilated with the primal fear of rolling an inch too far in his sleep and plummeting to his death . standing over him is mord , the jailer , a man of grotesque cruelty . mord ’ s face is a map of pockmarks and sneers , his eyes glinting with sadistic pleasure . he holds a wooden platter of meager food , gripping it with calloused , dirt - caked fingers . the tension is electric as mord deliberately lifts the plate just out of tyrion ’ s reach , a slow , mocking gesture of power . tyrion ’ s hand is outstretched , fingers trembling , his posture desperate and diminished . the lighting is a harsh , diffused alpine glare , casting cold , blue - toned shadows that cling to the crevices of the rock . the air is thick with a visible , freezing mist that clings to the characters ' clothes . every texture is visceral : the rough , abrasive grain of the limestone , the coarse wool of mord 's tunic , and the damp , glistening moisture on the slanted floor . in the background , the dizzying drop of the mountain peaks stretches infinitely downward , a void of swirling white fog and sharp , obsidian crags , emphasizing the lethal fragility of the ledge ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["oppressive grey , with pale sunlight filtering through high , narrow slits , casting long , skeletal shadows across the polished stone floor . in the center of the frame , the chaos of the fight has reached its zenith . ser vardis egen , a mountain of a man encased in heavy , ornate plate armor of polished steel , is pinned helplessly beneath the massive , shattered torso of the weeping woman statue . the stone is porous and weathered , with cracks spider - webbing through the sculpture 's frozen , grieving face . vardis 's armor is scuffed and dented , the metal reflecting the dim light in dull , metallic streaks , his breathing heavy and panicked , visible as a faint mist in the chilling mountain air . standing over him is bronn , the mercenary . his posture is a contrast of lean agility and lethal intent . he wears light , worn leather brigandine and salt - stained linen that clings to his sweat - beaded skin . his face is a mask of cold , pragmatic calculation ; there is no honor in his eyes , only the professional focus of a killer . bronn grips his longsword with both hands , the steel blade shimmering with a sharp , lethal edge . he is captured in the moment of the killing blow , leaning his entire body weight forward , driving the blade downward with visceral force . the sword pierces through the gap in the armor , sliding under the knight 's arm and plunging deep into the ribs . in the background , the court watches in stunned silence . lady lysa arryn stands frozen , her face a pale mask of horror and disbelief , her fingers clutching the velvet of her gown . the atmosphere is thick with the smell of ozone , cold stone , and the metallic tang of fresh blood spilling onto the pale marble ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["oppressive grey , with pale sunlight filtering through high , narrow slits , casting long , skeletal shadows across the polished stone floor . in the center of the frame , the chaos of the fight has reached its zenith . ser vardis egen , a mountain of a man encased in heavy , ornate plate armor of polished steel , is pinned helplessly beneath the massive , shattered torso of the weeping woman statue . the stone is porous and weathered , with cracks spider - webbing through the sculpture 's frozen , grieving face . vardis 's armor is scuffed and dented , the metal reflecting the dim light in dull , metallic streaks , his breathing heavy and panicked , visible as a faint mist in the chilling mountain air . standing over him is bronn , the mercenary . his posture is a contrast of lean agility and lethal intent . he wears light , worn leather brigandine and salt - stained linen that clings to his sweat - beaded skin . his face is a mask of cold , pragmatic calculation ; there is no honor in his eyes , only the professional focus of a killer . bronn grips his longsword with both hands , the steel blade shimmering with a sharp , lethal edge . he is captured in the moment of the killing blow , leaning his entire body weight forward , driving the blade downward with visceral force . the sword pierces through the gap in the armor , sliding under the knight 's arm and plunging deep into the ribs . in the background , the court watches in stunned silence . lady lysa arryn stands frozen , her face a pale mask of horror and disbelief , her fingers clutching the velvet of her gown . the atmosphere is thick with the smell of ozone , cold stone , and the metallic tang of fresh blood spilling onto the pale marble ."]
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ["s of clouds and mountain peaks. The lighting is a cold, oppressive grey, with pale sunlight filtering through high, narrow slits, casting long, skeletal shadows across the polished stone floor. In the center of the frame, the chaos of the fight has reached its zenith. Ser Vardis Egen, a mountain of a man encased in heavy, ornate plate armor of polished steel, is pinned helplessly beneath the massive, shattered torso of the Weeping Woman statue. The stone is porous and weathered, with cracks spider-webbing through the sculpture's frozen, grieving face. Vardis's armor is scuffed and dented, the metal reflecting the dim light in dull, metallic streaks, his breathing heavy and panicked, visible as a faint mist in the chilling mountain air. Standing over him is Bronn, the mercenary. His posture is a contrast of lean agility and lethal intent. He wears light, worn leather brigandine and salt-stained linen that clings to his sweat-beaded skin. His face is a mask of cold, pragmatic calculation; there is no honor in his eyes, only the professional focus of a killer. Bronn grips his longsword with both hands, the steel blade shimmering with a sharp, lethal edge. He is captured in the moment of the killing blow, leaning his entire body weight forward, driving the blade downward with visceral force. The sword pierces through the gap in the armor, sliding under the knight's arm and plunging deep into the ribs. In the background, the court watches in stunned silence. Lady Lysa Arryn stands frozen, her face a pale mask of horror and disbelief, her fingers clutching the velvet of her gown. The atmosphere is thick with the smell of ozone, cold stone, and the metallic tang of fresh blood spilling onto the pale marble."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["the pale , oppressive light filtering through the high , narrow gothic windows . every rivet and etched groove of his cuirass is visible , catching the glint of the torchlight . opposite him , the tension is a physical weight , the silence broken only by the distant whistle of the mountain wind howling through the peaks of the vale . lysa arryn watches from her high seat , her fingers gripping the carved stone armrests until her knuckles are white . her expression is a mask of frantic desperation and maternal obsession , her eyes wide and darting , her lips pressed into a thin , trembling line . the shadows of the hall are long and jagged , stretching across the cold , grey flagstone floor which is worn smooth by centuries of footsteps . the lighting is stark and directional , a cold , wintry blue light clashing with the warm , flickering orange of the wall - mounted braziers , creating a chiaroscuro effect that deepens the hollows of the knights ' faces . ser vardis ’ s cloak , a heavy wool of deep navy , is salt - stained and frayed at the edges , contrasting with the pristine brilliance of his sword . the blade is held steady , but a single bead of sweat rolls down his temple , carving a path through the fine dust of the hall . the architecture surrounding them is oppressive ; soaring ribbed vaults and pointed arches of pale limestone that seem to lean inward , amplifying the claustrophobia of the trial . every detail , from the intricate heraldry embroidered on the banners to the microscopic cracks in the stone pillars , vibrates with the high - stakes dread of a life hanging in the balance ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["the pale , oppressive light filtering through the high , narrow gothic windows . every rivet and etched groove of his cuirass is visible , catching the glint of the torchlight . opposite him , the tension is a physical weight , the silence broken only by the distant whistle of the mountain wind howling through the peaks of the vale . lysa arryn watches from her high seat , her fingers gripping the carved stone armrests until her knuckles are white . her expression is a mask of frantic desperation and maternal obsession , her eyes wide and darting , her lips pressed into a thin , trembling line . the shadows of the hall are long and jagged , stretching across the cold , grey flagstone floor which is worn smooth by centuries of footsteps . the lighting is stark and directional , a cold , wintry blue light clashing with the warm , flickering orange of the wall - mounted braziers , creating a chiaroscuro effect that deepens the hollows of the knights ' faces . ser vardis ’ s cloak , a heavy wool of deep navy , is salt - stained and frayed at the edges , contrasting with the pristine brilliance of his sword . the blade is held steady , but a single bead of sweat rolls down his temple , carving a path through the fine dust of the hall . the architecture surrounding them is oppressive ; soaring ribbed vaults and pointed arches of pale limestone that seem to lean inward , amplifying the claustrophobia of the trial . every detail , from the intricate heraldry embroidered on the banners to the microscopic cracks in the stone pillars , vibrates with the high - stakes dread of a life hanging in the balance ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["ary work , gripping a well - used longsword with a worn leather hilt . opposite him , the opposing champion looms , clad in polished , oppressive steel that glints blindingly under the oppressive midday sun . the lighting is a harsh , vertical glare , creating deep , ink - black shadows beneath the brows and chin of the fighters , emphasizing the grit and sweat beading on bronn 's tanned skin . in the background , the towering gothic spires of the red keep loom like jagged teeth against a bleached , pale blue sky . the arena is a circle of packed ochre earth , littered with fine dust that swirls around the combatants ' boots with every subtle shift in weight . high above in the royal gallery , tyrion lannister watches with a mixture of desperation and calculated hope . his small frame is draped in heavy , crimson velvet robes that seem to swallow him , his fingers gripping the stone railing until his knuckles are white . his eyes are wide , reflecting the violent tension of the pit below , while beside him , the court nobility watches with cold , judgmental expressions , their silk garments shimmering in the heat . the air is thick with the smell of hot iron and dry earth . every detail is visceral : the etched ripples of the steel blades , the coarse weave of the linen tunics , and the micro - expressions of lethal intent on bronn 's face . the composition captures the immense scale of the architecture contrasted with the intimate , deadly proximity of the two warriors , frozen in the heartbeat before the clash ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["ary work , gripping a well - used longsword with a worn leather hilt . opposite him , the opposing champion looms , clad in polished , oppressive steel that glints blindingly under the oppressive midday sun . the lighting is a harsh , vertical glare , creating deep , ink - black shadows beneath the brows and chin of the fighters , emphasizing the grit and sweat beading on bronn 's tanned skin . in the background , the towering gothic spires of the red keep loom like jagged teeth against a bleached , pale blue sky . the arena is a circle of packed ochre earth , littered with fine dust that swirls around the combatants ' boots with every subtle shift in weight . high above in the royal gallery , tyrion lannister watches with a mixture of desperation and calculated hope . his small frame is draped in heavy , crimson velvet robes that seem to swallow him , his fingers gripping the stone railing until his knuckles are white . his eyes are wide , reflecting the violent tension of the pit below , while beside him , the court nobility watches with cold , judgmental expressions , their silk garments shimmering in the heat . the air is thick with the smell of hot iron and dry earth . every detail is visceral : the etched ripples of the steel blades , the coarse weave of the linen tunics , and the micro - expressions of lethal intent on bronn 's face . the composition captures the immense scale of the architecture contrasted with the intimate , deadly proximity of the two warriors , frozen in the heartbeat before the clash ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['young arya stark is a ghost in the dark ; her small frame is pressed tight against the cold , sweating rock , her breath held in a trembling chest . her eyes , wide and amber - dark , are fixed with intense focus on two men whispering just a few feet away . the first man is obese , his girth straining against a short , oil - slicked leather cape that smells of old sweat and cured hide . he wears a heavy steel helmet that reflects the flickering , sickly orange light of a distant torch , the metal pitted with rust and scratches . beside him stands a leaner man with a distinctive , bifurcated yellow beard that splits sharply at the chin , his expression one of predatory anticipation . the tension is palpable , a suffocating weight between them as they discuss the imminent clash between the wolf and the lion . the yellow - bearded man leans in , his voice a low , gravelly hiss , gesturing with a calloused hand as he questions why one hand of the king cannot fall if another already has . their faces are etched with malice , illuminated by a single , guttering torch that casts long , dancing silhouettes against the ribbed vaulting of the tunnel . the lighting is chiaroscuro , with violent contrasts between the deep , ink - black voids of the tunnel and the harsh , amber glow hitting the textures of the scene : the coarse weave of their woolen tunics , the glint of the steel helm , and the glistening moisture on the cavern walls . in the background , the faint , haunting silhouette of the dragon skull chamber looms , where the bleached , porous bone of ancient behemoths catches the stray light , adding a macabre , skeletal atmosphere to this nest of treason .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['young arya stark is a ghost in the dark ; her small frame is pressed tight against the cold , sweating rock , her breath held in a trembling chest . her eyes , wide and amber - dark , are fixed with intense focus on two men whispering just a few feet away . the first man is obese , his girth straining against a short , oil - slicked leather cape that smells of old sweat and cured hide . he wears a heavy steel helmet that reflects the flickering , sickly orange light of a distant torch , the metal pitted with rust and scratches . beside him stands a leaner man with a distinctive , bifurcated yellow beard that splits sharply at the chin , his expression one of predatory anticipation . the tension is palpable , a suffocating weight between them as they discuss the imminent clash between the wolf and the lion . the yellow - bearded man leans in , his voice a low , gravelly hiss , gesturing with a calloused hand as he questions why one hand of the king cannot fall if another already has . their faces are etched with malice , illuminated by a single , guttering torch that casts long , dancing silhouettes against the ribbed vaulting of the tunnel . the lighting is chiaroscuro , with violent contrasts between the deep , ink - black voids of the tunnel and the harsh , amber glow hitting the textures of the scene : the coarse weave of their woolen tunics , the glint of the steel helm , and the glistening moisture on the cavern walls . in the background , the faint , haunting silhouette of the dragon skull chamber looms , where the bleached , porous bone of ancient behemoths catches the stray light , adding a macabre , skeletal atmosphere to this nest of treason .']
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ['shadows of a narrow alcove, young Arya Stark is a ghost in the dark; her small frame is pressed tight against the cold, sweating rock, her breath held in a trembling chest. Her eyes, wide and amber-dark, are fixed with intense focus on two men whispering just a few feet away. The first man is obese, his girth straining against a short, oil-slicked leather cape that smells of old sweat and cured hide. He wears a heavy steel helmet that reflects the flickering, sickly orange light of a distant torch, the metal pitted with rust and scratches. Beside him stands a leaner man with a distinctive, bifurcated yellow beard that splits sharply at the chin, his expression one of predatory anticipation. The tension is palpable, a suffocating weight between them as they discuss the imminent clash between the Wolf and the Lion. The yellow-bearded man leans in, his voice a low, gravelly hiss, gesturing with a calloused hand as he questions why one Hand of the King cannot fall if another already has. Their faces are etched with malice, illuminated by a single, guttering torch that casts long, dancing silhouettes against the ribbed vaulting of the tunnel. The lighting is chiaroscuro, with violent contrasts between the deep, ink-black voids of the tunnel and the harsh, amber glow hitting the textures of the scene: the coarse weave of their woolen tunics, the glint of the steel helm, and the glistening moisture on the cavern walls. In the background, the faint, haunting silhouette of the dragon skull chamber looms, where the bleached, porous bone of ancient behemoths catches the stray light, adding a macabre, skeletal atmosphere to this nest of treason.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["at the edges . opposite him , a phalanx of gold cloaks — the city watch — closes in , their armor a tarnished , scratched gold that reflects the oppressive midday sun . the soldiers ' expressions are predatory , their lips curled in sneers , eyes glinting with a mixture of greed and malice . the lighting is harsh and vertical , creating deep , ink - black shadows beneath the eaves of the leaning timber - frame houses that crowd the street . shafts of blinding white light cut through the haze of floating dust and urban grime , highlighting the sweat - beaded skin on the soldiers ' foreheads and the grit embedded in the cracks of the limestone walls . ned ’ s hand rests on the pommel of his sword , the leather grip worn smooth by years of use . the tension is palpable , a vibrating silence broken only by the distant screams of the city . one guard steps forward , his breath visible as a faint mist , his hand gripping a spear with a shaft of polished ash and a tip of cold , pitted iron . the contrast is stark : ned ’ s stoic , honor - bound stillness against the jagged , aggressive energy of the city 's corruption . in the background , the red keep looms like a jagged tooth of pale red stone against a bleached , pale blue sky , its towering spires casting long , ominous shadows that seem to swallow the alleyway . every texture is visceral — the slime of the gutter , the rough grain of the wooden shutters , and the cold , metallic scent of steel and old blood hanging in the stagnant air ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["at the edges . opposite him , a phalanx of gold cloaks — the city watch — closes in , their armor a tarnished , scratched gold that reflects the oppressive midday sun . the soldiers ' expressions are predatory , their lips curled in sneers , eyes glinting with a mixture of greed and malice . the lighting is harsh and vertical , creating deep , ink - black shadows beneath the eaves of the leaning timber - frame houses that crowd the street . shafts of blinding white light cut through the haze of floating dust and urban grime , highlighting the sweat - beaded skin on the soldiers ' foreheads and the grit embedded in the cracks of the limestone walls . ned ’ s hand rests on the pommel of his sword , the leather grip worn smooth by years of use . the tension is palpable , a vibrating silence broken only by the distant screams of the city . one guard steps forward , his breath visible as a faint mist , his hand gripping a spear with a shaft of polished ash and a tip of cold , pitted iron . the contrast is stark : ned ’ s stoic , honor - bound stillness against the jagged , aggressive energy of the city 's corruption . in the background , the red keep looms like a jagged tooth of pale red stone against a bleached , pale blue sky , its towering spires casting long , ominous shadows that seem to swallow the alleyway . every texture is visceral — the slime of the gutter , the rough grain of the wooden shutters , and the cold , metallic scent of steel and old blood hanging in the stagnant air ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['sweat . in her trembling hands , she holds the massive , glistening heart of a wild stallion , still steaming in the arid heat . the organ is a deep , bruised crimson , its surface slick with thick , viscous blood that drips slowly down her wrists and stains her fingertips a dark , metallic red . her face is a mask of primal struggle ; her jaw is clenched , her eyes wide and watering from the metallic scent of raw gore , yet there is a fierce , burning determination in her gaze . beside her stands khal drogo , a towering presence of bronze skin and braided hair . his expression is initially a wall of stony indifference , his arms crossed over a chest adorned with leather and bone . however , as daenerys forces herself to consume the raw flesh , a subtle shift occurs in his micro - expressions — a softening of the brow and a glimmer of profound , unexpected pride sparking in his dark eyes . in the background , the dosh khaleen — the withered , ancient witches of the city — watch with predatory stillness . their skin is like parched parchment , draped in heavy , dust - caked silks , their eyes clouded by cataracts but sharp with judgment . they sit in the shadow of a crumbling , ancient stone archway , the gothic architecture of the city blending with the wild , untamed nature of the grasslands . the air is thick with the smell of horse sweat , dry grass , and iron . the lighting is a violent , high - contrast gold , highlighting the contrast between the raw , bloody heart and the pale , ethereal beauty of the khaleesi , capturing the exact moment of her transformation from a frightened girl into a mother of strength .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['sweat . in her trembling hands , she holds the massive , glistening heart of a wild stallion , still steaming in the arid heat . the organ is a deep , bruised crimson , its surface slick with thick , viscous blood that drips slowly down her wrists and stains her fingertips a dark , metallic red . her face is a mask of primal struggle ; her jaw is clenched , her eyes wide and watering from the metallic scent of raw gore , yet there is a fierce , burning determination in her gaze . beside her stands khal drogo , a towering presence of bronze skin and braided hair . his expression is initially a wall of stony indifference , his arms crossed over a chest adorned with leather and bone . however , as daenerys forces herself to consume the raw flesh , a subtle shift occurs in his micro - expressions — a softening of the brow and a glimmer of profound , unexpected pride sparking in his dark eyes . in the background , the dosh khaleen — the withered , ancient witches of the city — watch with predatory stillness . their skin is like parched parchment , draped in heavy , dust - caked silks , their eyes clouded by cataracts but sharp with judgment . they sit in the shadow of a crumbling , ancient stone archway , the gothic architecture of the city blending with the wild , untamed nature of the grasslands . the air is thick with the smell of horse sweat , dry grass , and iron . the lighting is a violent , high - contrast gold , highlighting the contrast between the raw , bloody heart and the pale , ethereal beauty of the khaleesi , capturing the exact moment of her transformation from a frightened girl into a mother of strength .']
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ['pale linen that clings to her skin, her forehead beaded with sweat. In her trembling hands, she holds the massive, glistening heart of a wild stallion, still steaming in the arid heat. The organ is a deep, bruised crimson, its surface slick with thick, viscous blood that drips slowly down her wrists and stains her fingertips a dark, metallic red. Her face is a mask of primal struggle; her jaw is clenched, her eyes wide and watering from the metallic scent of raw gore, yet there is a fierce, burning determination in her gaze. Beside her stands Khal Drogo, a towering presence of bronze skin and braided hair. His expression is initially a wall of stony indifference, his arms crossed over a chest adorned with leather and bone. However, as Daenerys forces herself to consume the raw flesh, a subtle shift occurs in his micro-expressions—a softening of the brow and a glimmer of profound, unexpected pride sparking in his dark eyes. In the background, the Dosh Khaleen—the withered, ancient witches of the city—watch with predatory stillness. Their skin is like parched parchment, draped in heavy, dust-caked silks, their eyes clouded by cataracts but sharp with judgment. They sit in the shadow of a crumbling, ancient stone archway, the Gothic architecture of the city blending with the wild, untamed nature of the grasslands. The air is thick with the smell of horse sweat, dry grass, and iron. The lighting is a violent, high-contrast gold, highlighting the contrast between the raw, bloody heart and the pale, ethereal beauty of the Khaleesi, capturing the exact moment of her transformation from a frightened girl into a mother of strength.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["posture broken and desperate . his face is a mask of raw terror , eyes wide and bloodshot , skin beaded with cold sweat and grime . his fine , salt - stained linen tunic is torn , exposing a bruised shoulder where his arm hangs at an unnatural angle . standing over him is khal drogo , a towering figure of bronze skin and braided hair , his expression one of cold , detached judgment . drogo holds a heavy iron pot , the metal glowing a dull , menacing red from the intense heat of the surrounding braziers . inside the pot , a belt of golden medallions has transformed into a swirling , viscous pool of molten gold , shimmering with a violent , blinding luminosity . the lighting is dominated by the fierce orange glow of the fire , casting long , jagged silhouettes across the packed dirt . the light catches the liquid gold , creating a harsh contrast against the deepening purple of the evening sky . nearby , daenerys stands motionless , her gaze unwavering and hauntingly calm , her pale skin illuminated by the flickering flames . ser jorah stands beside her , his hand gripping her shoulder , his face etched with a mixture of pity and grim necessity . the climax captures the exact moment of execution : drogo tilts the pot with a slow , deliberate motion . a thick , glowing stream of liquid gold cascades downward , striking the crown of viserys 's head . the molten metal clings to his skin , flowing like lava over his forehead and eyes , searing the flesh instantly . there is no blood , only the hiss of evaporating moisture and the blinding brilliance of the gold hardening into a grotesque , permanent mask . the texture of the cooling metal is pitted and iridescent , fusing with the charred remnants of his hair ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["posture broken and desperate . his face is a mask of raw terror , eyes wide and bloodshot , skin beaded with cold sweat and grime . his fine , salt - stained linen tunic is torn , exposing a bruised shoulder where his arm hangs at an unnatural angle . standing over him is khal drogo , a towering figure of bronze skin and braided hair , his expression one of cold , detached judgment . drogo holds a heavy iron pot , the metal glowing a dull , menacing red from the intense heat of the surrounding braziers . inside the pot , a belt of golden medallions has transformed into a swirling , viscous pool of molten gold , shimmering with a violent , blinding luminosity . the lighting is dominated by the fierce orange glow of the fire , casting long , jagged silhouettes across the packed dirt . the light catches the liquid gold , creating a harsh contrast against the deepening purple of the evening sky . nearby , daenerys stands motionless , her gaze unwavering and hauntingly calm , her pale skin illuminated by the flickering flames . ser jorah stands beside her , his hand gripping her shoulder , his face etched with a mixture of pity and grim necessity . the climax captures the exact moment of execution : drogo tilts the pot with a slow , deliberate motion . a thick , glowing stream of liquid gold cascades downward , striking the crown of viserys 's head . the molten metal clings to his skin , flowing like lava over his forehead and eyes , searing the flesh instantly . there is no blood , only the hiss of evaporating moisture and the blinding brilliance of the gold hardening into a grotesque , permanent mask . the texture of the cooling metal is pitted and iridescent , fusing with the charred remnants of his hair ."]
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ["erys Targaryen is pinned to the scorched earth, his posture broken and desperate. His face is a mask of raw terror, eyes wide and bloodshot, skin beaded with cold sweat and grime. His fine, salt-stained linen tunic is torn, exposing a bruised shoulder where his arm hangs at an unnatural angle. Standing over him is Khal Drogo, a towering figure of bronze skin and braided hair, his expression one of cold, detached judgment. Drogo holds a heavy iron pot, the metal glowing a dull, menacing red from the intense heat of the surrounding braziers. Inside the pot, a belt of golden medallions has transformed into a swirling, viscous pool of molten gold, shimmering with a violent, blinding luminosity. The lighting is dominated by the fierce orange glow of the fire, casting long, jagged silhouettes across the packed dirt. The light catches the liquid gold, creating a harsh contrast against the deepening purple of the evening sky. Nearby, Daenerys stands motionless, her gaze unwavering and hauntingly calm, her pale skin illuminated by the flickering flames. Ser Jorah stands beside her, his hand gripping her shoulder, his face etched with a mixture of pity and grim necessity. The climax captures the exact moment of execution: Drogo tilts the pot with a slow, deliberate motion. A thick, glowing stream of liquid gold cascades downward, striking the crown of Viserys's head. The molten metal clings to his skin, flowing like lava over his forehead and eyes, searing the flesh instantly. There is no blood, only the hiss of evaporating moisture and the blinding brilliance of the gold hardening into a grotesque, permanent mask. The texture of the cooling metal is pitted and iridescent, fusing with the charred remnants of his hair."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["glows against the deepening gloom . the trees ' leaves are a violent , bleeding crimson , contrasting sharply with the obsidian - black soil and the pale frost coating the gnarled roots . jon snow and samwell tarly stand side - by - side , their figures small and fragile against the towering , sentient architecture of the grove . jon ’ s posture is rigid , his jaw clenched with a solemn , ancestral weight , his dark eyes reflecting the haunting red of the leaves . his skin is weathered , beaded with cold sweat and dusted with frost . beside him , samwell is trembling , his breath emerging in heavy , ragged plumes of white vapor ; his expression is a mixture of sheer terror and desperate resolve , his oversized black cloak swallowing his frame . they are draped in the heavy , coarse wool of the night 's watch — thick , salt - stained black linen and boiled leather that looks worn and oppressive . the texture of the fabric is rough and tactile , capturing the grime of the north . facing them is the septon , his robes a muted charcoal , his face etched with deep , parchment - like wrinkles . the lighting is ethereal and directional , with the dying light of a winter sun casting long , jagged silhouettes across the snow . the red sap of the weirwood trees looks like fresh blood weeping from the carved , screaming faces in the white bark . the atmosphere is heavy with a suffocating silence , broken only by the distant , mournful howl of a wolf , emphasizing the isolation of the wall and the permanence of the oath they are swearing ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["glows against the deepening gloom . the trees ' leaves are a violent , bleeding crimson , contrasting sharply with the obsidian - black soil and the pale frost coating the gnarled roots . jon snow and samwell tarly stand side - by - side , their figures small and fragile against the towering , sentient architecture of the grove . jon ’ s posture is rigid , his jaw clenched with a solemn , ancestral weight , his dark eyes reflecting the haunting red of the leaves . his skin is weathered , beaded with cold sweat and dusted with frost . beside him , samwell is trembling , his breath emerging in heavy , ragged plumes of white vapor ; his expression is a mixture of sheer terror and desperate resolve , his oversized black cloak swallowing his frame . they are draped in the heavy , coarse wool of the night 's watch — thick , salt - stained black linen and boiled leather that looks worn and oppressive . the texture of the fabric is rough and tactile , capturing the grime of the north . facing them is the septon , his robes a muted charcoal , his face etched with deep , parchment - like wrinkles . the lighting is ethereal and directional , with the dying light of a winter sun casting long , jagged silhouettes across the snow . the red sap of the weirwood trees looks like fresh blood weeping from the carved , screaming faces in the white bark . the atmosphere is heavy with a suffocating silence , broken only by the distant , mournful howl of a wolf , emphasizing the isolation of the wall and the permanence of the oath they are swearing ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['wn oak table : a bastard sword encased in a sheath of matte black metal , intricately inlaid with thin , shimmering veins of silver . jon snow , his skin pale and beaded with a light sweat of anxiety , reaches out with his left hand . as he draws the blade , the steel sings — a low , lethal hum . the blade of longclaw is a marvel of valyrian steel , characterized by those signature smoky , rippling patterns that look like frozen currents of dark water . three deep , precise blood - grooves run the length of the steel , designed to lighten the heavy blade for both lethal thrusts and devastating cleaves . the focus tightens on the hilt : a stark , white stone pommel carved into the snarling head of a wolf , its jaws agape in a silent howl , with tiny , jagged shards of deep crimson garnet embedded as eyes that catch the flickering torchlight . the grip is wrapped in fresh , tight leather , contrasting with the ancient , otherworldly metal of the blade . the lighting is moody and directional ; a single , guttering hearth casts long , dancing shadows against the gothic arches of the room , bathing the scene in amber and deep charcoal tones . jon ’ s expression is a complex mixture of profound gratitude and haunting guilt , his brow furrowed , his eyes reflecting the glint of the steel . mormont watches him with a stern , fatherly gaze , the tension between them vibrating with the weight of a legacy passed from one warrior to another . dust motes dance in the shafts of dim light , highlighting the worn , salt - stained wool of their black cloaks .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['wn oak table : a bastard sword encased in a sheath of matte black metal , intricately inlaid with thin , shimmering veins of silver . jon snow , his skin pale and beaded with a light sweat of anxiety , reaches out with his left hand . as he draws the blade , the steel sings — a low , lethal hum . the blade of longclaw is a marvel of valyrian steel , characterized by those signature smoky , rippling patterns that look like frozen currents of dark water . three deep , precise blood - grooves run the length of the steel , designed to lighten the heavy blade for both lethal thrusts and devastating cleaves . the focus tightens on the hilt : a stark , white stone pommel carved into the snarling head of a wolf , its jaws agape in a silent howl , with tiny , jagged shards of deep crimson garnet embedded as eyes that catch the flickering torchlight . the grip is wrapped in fresh , tight leather , contrasting with the ancient , otherworldly metal of the blade . the lighting is moody and directional ; a single , guttering hearth casts long , dancing shadows against the gothic arches of the room , bathing the scene in amber and deep charcoal tones . jon ’ s expression is a complex mixture of profound gratitude and haunting guilt , his brow furrowed , his eyes reflecting the glint of the steel . mormont watches him with a stern , fatherly gaze , the tension between them vibrating with the weight of a legacy passed from one warrior to another . dust motes dance in the shafts of dim light , highlighting the worn , salt - stained wool of their black cloaks .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [", cavernous wound tears across his torso — the brutal work of a giant boar — where the skin is puckered , bruised in deep purples and sickly yellows , and seeped with dried , crusty gore . his skin is a pale , sweat - beaded parchment , clinging to his hollowed cheeks . lord eddard stark leans over him , his face a mask of grief and suppressed turmoil . ned ’ s fingers , calloused and trembling slightly , grip the edge of a heavy parchment . his grey eyes are clouded with a devastating secret , his brow furrowed in a micro - expression of agony as he looks upon his dying friend . robert ’ s hand , shaking and clumsy , reaches out to clutch ned ’ s forearm , the grip weak and desperate . in the periphery , the shadows are inhabited by vultures . grand maester pycelle stands stiffly , his long , bleached beard contrasting with the deep crimson of his robes , his eyes blinking with a calculating slowness . lord renly baratheon lingers in the dim light , his posture poised and detached , his polished leather boots reflecting the flickering orange glow of the hearth . ser barristan selmy stands like a sentinel of sorrow , his white cloak draped heavily over his shoulders , his gaze fixed on the floor in profound failure . the lighting is oppressive ; singular , guttering tallow candles cast long , dancing silhouettes against the gothic stone walls and heavy velvet tapestries . a single shaft of moonlight pierces through a high , narrow window , illuminating the floating dust motes and the cold , etched silver of the royal seal resting on a side table . the tension is a physical weight , a silent scream between the dying king 's trust and the silent betrayal of the truth ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [", cavernous wound tears across his torso — the brutal work of a giant boar — where the skin is puckered , bruised in deep purples and sickly yellows , and seeped with dried , crusty gore . his skin is a pale , sweat - beaded parchment , clinging to his hollowed cheeks . lord eddard stark leans over him , his face a mask of grief and suppressed turmoil . ned ’ s fingers , calloused and trembling slightly , grip the edge of a heavy parchment . his grey eyes are clouded with a devastating secret , his brow furrowed in a micro - expression of agony as he looks upon his dying friend . robert ’ s hand , shaking and clumsy , reaches out to clutch ned ’ s forearm , the grip weak and desperate . in the periphery , the shadows are inhabited by vultures . grand maester pycelle stands stiffly , his long , bleached beard contrasting with the deep crimson of his robes , his eyes blinking with a calculating slowness . lord renly baratheon lingers in the dim light , his posture poised and detached , his polished leather boots reflecting the flickering orange glow of the hearth . ser barristan selmy stands like a sentinel of sorrow , his white cloak draped heavily over his shoulders , his gaze fixed on the floor in profound failure . the lighting is oppressive ; singular , guttering tallow candles cast long , dancing silhouettes against the gothic stone walls and heavy velvet tapestries . a single shaft of moonlight pierces through a high , narrow window , illuminating the floating dust motes and the cold , etched silver of the royal seal resting on a side table . the tension is a physical weight , a silent scream between the dying king 's trust and the silent betrayal of the truth ."]
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ["a ruin of flesh. A jagged, cavernous wound tears across his torso—the brutal work of a giant boar—where the skin is puckered, bruised in deep purples and sickly yellows, and seeped with dried, crusty gore. His skin is a pale, sweat-beaded parchment, clinging to his hollowed cheeks. Lord Eddard Stark leans over him, his face a mask of grief and suppressed turmoil. Ned’s fingers, calloused and trembling slightly, grip the edge of a heavy parchment. His grey eyes are clouded with a devastating secret, his brow furrowed in a micro-expression of agony as he looks upon his dying friend. Robert’s hand, shaking and clumsy, reaches out to clutch Ned’s forearm, the grip weak and desperate. In the periphery, the shadows are inhabited by vultures. Grand Maester Pycelle stands stiffly, his long, bleached beard contrasting with the deep crimson of his robes, his eyes blinking with a calculating slowness. Lord Renly Baratheon lingers in the dim light, his posture poised and detached, his polished leather boots reflecting the flickering orange glow of the hearth. Ser Barristan Selmy stands like a sentinel of sorrow, his white cloak draped heavily over his shoulders, his gaze fixed on the floor in profound failure. The lighting is oppressive; singular, guttering tallow candles cast long, dancing silhouettes against the Gothic stone walls and heavy velvet tapestries. A single shaft of moonlight pierces through a high, narrow window, illuminating the floating dust motes and the cold, etched silver of the royal seal resting on a side table. The tension is a physical weight, a silent scream between the dying king's trust and the silent betrayal of the truth."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["ts of pale sunlight piercing through high , narrow gothic windows , illuminating swirling dust motes and the shimmering gold embroidery of the lannister guards ' tabards . in the center of the hall , lord eddard stark stands isolated , his face a mask of weathered nobility and sudden , crushing realization . his skin is sweat - beaded , his grey eyes wide with a mixture of betrayal and disbelief . surrounding him is a tightening ring of gold cloaks , their armor clashing with a harsh , metallic ring , their faces grim and opportunistic . janos slynt stands at the forefront , his expression one of smug , bureaucratic cruelty , his hand gesturing coldly to seal the perimeter . the tension peaks as petyr baelish leans in close to ned ’ s ear . littlefinger ’ s posture is feline and predatory , a sharp contrast to ned ’ s rigid , honorable stance . baelish holds a slender , polished steel dagger pressed firmly against the soft skin beneath ned ’ s jawline , forcing his head upward . the blade reflects a sliver of cold light , contrasting with the rich , velvet textures of baelish 's doublet . baelish ’ s lips are curled into a faint , mocking smile , his eyes gleaming with a calculated malice . in the background , queen cersei stands beside the throne , her posture regal and triumphant , her emerald green gown flowing like a river of silk over the cold granite . the massive pillars of the hall loom like silent giants , their intricate carvings obscured by deep , moody shadows , while the distant sound of steel clashing echoes as ned 's few remaining loyalists are cut down , their blood staining the pale grey flagstones in violent , spreading blooms of crimson ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["ts of pale sunlight piercing through high , narrow gothic windows , illuminating swirling dust motes and the shimmering gold embroidery of the lannister guards ' tabards . in the center of the hall , lord eddard stark stands isolated , his face a mask of weathered nobility and sudden , crushing realization . his skin is sweat - beaded , his grey eyes wide with a mixture of betrayal and disbelief . surrounding him is a tightening ring of gold cloaks , their armor clashing with a harsh , metallic ring , their faces grim and opportunistic . janos slynt stands at the forefront , his expression one of smug , bureaucratic cruelty , his hand gesturing coldly to seal the perimeter . the tension peaks as petyr baelish leans in close to ned ’ s ear . littlefinger ’ s posture is feline and predatory , a sharp contrast to ned ’ s rigid , honorable stance . baelish holds a slender , polished steel dagger pressed firmly against the soft skin beneath ned ’ s jawline , forcing his head upward . the blade reflects a sliver of cold light , contrasting with the rich , velvet textures of baelish 's doublet . baelish ’ s lips are curled into a faint , mocking smile , his eyes gleaming with a calculated malice . in the background , queen cersei stands beside the throne , her posture regal and triumphant , her emerald green gown flowing like a river of silk over the cold granite . the massive pillars of the hall loom like silent giants , their intricate carvings obscured by deep , moody shadows , while the distant sound of steel clashing echoes as ned 's few remaining loyalists are cut down , their blood staining the pale grey flagstones in violent , spreading blooms of crimson ."]
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ["the stone floor. The lighting is dramatic and cold, with shafts of pale sunlight piercing through high, narrow Gothic windows, illuminating swirling dust motes and the shimmering gold embroidery of the Lannister guards' tabards. In the center of the hall, Lord Eddard Stark stands isolated, his face a mask of weathered nobility and sudden, crushing realization. His skin is sweat-beaded, his grey eyes wide with a mixture of betrayal and disbelief. Surrounding him is a tightening ring of Gold Cloaks, their armor clashing with a harsh, metallic ring, their faces grim and opportunistic. Janos Slynt stands at the forefront, his expression one of smug, bureaucratic cruelty, his hand gesturing coldly to seal the perimeter. The tension peaks as Petyr Baelish leans in close to Ned’s ear. Littlefinger’s posture is feline and predatory, a sharp contrast to Ned’s rigid, honorable stance. Baelish holds a slender, polished steel dagger pressed firmly against the soft skin beneath Ned’s jawline, forcing his head upward. The blade reflects a sliver of cold light, contrasting with the rich, velvet textures of Baelish's doublet. Baelish’s lips are curled into a faint, mocking smile, his eyes gleaming with a calculated malice. In the background, Queen Cersei stands beside the throne, her posture regal and triumphant, her emerald green gown flowing like a river of silk over the cold granite. The massive pillars of the hall loom like silent giants, their intricate carvings obscured by deep, moody shadows, while the distant sound of steel clashing echoes as Ned's few remaining loyalists are cut down, their blood staining the pale grey flagstones in violent, spreading blooms of crimson."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["that cling to her skin , her silver - gold hair shimmering under the harsh zenith light . her expression is one of innocent curiosity , her violet eyes wide as she looks at a crystal goblet of deep , ruby - red wine held by a sweating , nervous merchant . beside her , ser jorah mormont is a pillar of weathered steel and vigilance . his posture is rigid , his hand resting instinctively on the pommel of his sword . his brow is furrowed , eyes narrowed in a piercing , suspicious gaze directed not at the princess , but at the merchant ’ s twitching fingers and darting eyes . the tension is palpable ; a silent , electric charge between the protector and the predator . the merchant , a gaunt man in salt - stained linens and greasy furs , wears a mask of forced hospitality , but a bead of sweat rolls down his temple , carving a path through the grime on his skin . as jorah steps forward , his voice a low rumble , demanding the merchant taste the vintage first , the man 's face contorts into a mask of sudden panic . the background is a blur of dothraki warriors in leather armor and ornate jewelry , their bronze skin glistening with sweat . to the side , the heavy , braided whip of jhogo is captured mid - snap , frozen in a blur of motion as it lashes out to ensnare the fleeing merchant . the architecture consists of sprawling , open - air pavilions with weathered canvas awnings that cast jagged , amber - hued shadows across the packed earth . the lighting is a violent , saturated gold , creating high contrast between the brilliant highlights of the targaryen silver and the deep , ink - black shadows of the market stalls . every texture is visceral : the grit of the sand , the shimmer of the poisoned wine , and the coarse weave of the dothraki fabrics ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["that cling to her skin , her silver - gold hair shimmering under the harsh zenith light . her expression is one of innocent curiosity , her violet eyes wide as she looks at a crystal goblet of deep , ruby - red wine held by a sweating , nervous merchant . beside her , ser jorah mormont is a pillar of weathered steel and vigilance . his posture is rigid , his hand resting instinctively on the pommel of his sword . his brow is furrowed , eyes narrowed in a piercing , suspicious gaze directed not at the princess , but at the merchant ’ s twitching fingers and darting eyes . the tension is palpable ; a silent , electric charge between the protector and the predator . the merchant , a gaunt man in salt - stained linens and greasy furs , wears a mask of forced hospitality , but a bead of sweat rolls down his temple , carving a path through the grime on his skin . as jorah steps forward , his voice a low rumble , demanding the merchant taste the vintage first , the man 's face contorts into a mask of sudden panic . the background is a blur of dothraki warriors in leather armor and ornate jewelry , their bronze skin glistening with sweat . to the side , the heavy , braided whip of jhogo is captured mid - snap , frozen in a blur of motion as it lashes out to ensnare the fleeing merchant . the architecture consists of sprawling , open - air pavilions with weathered canvas awnings that cast jagged , amber - hued shadows across the packed earth . the lighting is a violent , saturated gold , creating high contrast between the brilliant highlights of the targaryen silver and the deep , ink - black shadows of the market stalls . every texture is visceral : the grit of the sand , the shimmer of the poisoned wine , and the coarse weave of the dothraki fabrics ."]
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ["ar. She is dressed in flowing, sun-bleached silks that cling to her skin, her silver-gold hair shimmering under the harsh zenith light. Her expression is one of innocent curiosity, her violet eyes wide as she looks at a crystal goblet of deep, ruby-red wine held by a sweating, nervous merchant. Beside her, Ser Jorah Mormont is a pillar of weathered steel and vigilance. His posture is rigid, his hand resting instinctively on the pommel of his sword. His brow is furrowed, eyes narrowed in a piercing, suspicious gaze directed not at the princess, but at the merchant’s twitching fingers and darting eyes. The tension is palpable; a silent, electric charge between the protector and the predator. The merchant, a gaunt man in salt-stained linens and greasy furs, wears a mask of forced hospitality, but a bead of sweat rolls down his temple, carving a path through the grime on his skin. As Jorah steps forward, his voice a low rumble, demanding the merchant taste the vintage first, the man's face contorts into a mask of sudden panic. The background is a blur of Dothraki warriors in leather armor and ornate jewelry, their bronze skin glistening with sweat. To the side, the heavy, braided whip of Jhogo is captured mid-snap, frozen in a blur of motion as it lashes out to ensnare the fleeing merchant. The architecture consists of sprawling, open-air pavilions with weathered canvas awnings that cast jagged, amber-hued shadows across the packed earth. The lighting is a violent, saturated gold, creating high contrast between the brilliant highlights of the Targaryen silver and the deep, ink-black shadows of the market stalls. Every texture is visceral: the grit of the sand, the shimmer of the poisoned wine, and the coarse weave of the Dothraki fabrics."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [", lethal fury , his dark eyes narrowed and fixed on the trembling wretch before him . the wine merchant , stripped naked and shivering , is bound with coarse , salt - stained hemp ropes to the ornate , gilded wheel of daenerys ’ s heavy wooden carriage . the merchant 's skin is pale , slick with a mixture of cold sweat and filth , his face contorted in a silent , wide - mouthed scream of terror . beside drogo stands daenerys , her posture shifting from the fragile girl she once was to a poised khaleesi . she wears a gown of sheer , flowing cream silk that flutters in the arid breeze , the fabric clinging to her skin . her violet eyes are wide , reflecting the flickering orange glow of nearby braziers , her lips parted in a mixture of shock and newfound empowerment . the tension between them is electric ; drogo ’ s hand rests heavily on the hilt of his arakh , the curved blade ’ s steel reflecting the dying light with a sharp , silver glint . the environment is a chaotic tapestry of the great grass sea : towering , golden stalks of grass sway violently in the background , while the distant silhouettes of thousands of dothraki screamers on horseback create a jagged horizon . the lighting is dramatic and high - contrast , with the deep crimson of the setting sun casting long , distorted shadows across the dusty earth . every detail is tactile : the rough grain of the carriage 's weathered wood , the intricate leather braiding of drogo 's chest harness , and the fine , shimmering dust motes dancing in the air . the scene captures the exact moment of a vow — the air thick with the scent of horse sweat and ozone — as drogo declares his intent to cross the salt sea and conquer the seven kingdoms ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [", lethal fury , his dark eyes narrowed and fixed on the trembling wretch before him . the wine merchant , stripped naked and shivering , is bound with coarse , salt - stained hemp ropes to the ornate , gilded wheel of daenerys ’ s heavy wooden carriage . the merchant 's skin is pale , slick with a mixture of cold sweat and filth , his face contorted in a silent , wide - mouthed scream of terror . beside drogo stands daenerys , her posture shifting from the fragile girl she once was to a poised khaleesi . she wears a gown of sheer , flowing cream silk that flutters in the arid breeze , the fabric clinging to her skin . her violet eyes are wide , reflecting the flickering orange glow of nearby braziers , her lips parted in a mixture of shock and newfound empowerment . the tension between them is electric ; drogo ’ s hand rests heavily on the hilt of his arakh , the curved blade ’ s steel reflecting the dying light with a sharp , silver glint . the environment is a chaotic tapestry of the great grass sea : towering , golden stalks of grass sway violently in the background , while the distant silhouettes of thousands of dothraki screamers on horseback create a jagged horizon . the lighting is dramatic and high - contrast , with the deep crimson of the setting sun casting long , distorted shadows across the dusty earth . every detail is tactile : the rough grain of the carriage 's weathered wood , the intricate leather braiding of drogo 's chest harness , and the fine , shimmering dust motes dancing in the air . the scene captures the exact moment of a vow — the air thick with the scent of horse sweat and ozone — as drogo declares his intent to cross the salt sea and conquer the seven kingdoms ."]
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ["—cascading down his back. His expression is a mask of cold, lethal fury, his dark eyes narrowed and fixed on the trembling wretch before him. The wine merchant, stripped naked and shivering, is bound with coarse, salt-stained hemp ropes to the ornate, gilded wheel of Daenerys’s heavy wooden carriage. The merchant's skin is pale, slick with a mixture of cold sweat and filth, his face contorted in a silent, wide-mouthed scream of terror. Beside Drogo stands Daenerys, her posture shifting from the fragile girl she once was to a poised Khaleesi. She wears a gown of sheer, flowing cream silk that flutters in the arid breeze, the fabric clinging to her skin. Her violet eyes are wide, reflecting the flickering orange glow of nearby braziers, her lips parted in a mixture of shock and newfound empowerment. The tension between them is electric; Drogo’s hand rests heavily on the hilt of his arakh, the curved blade’s steel reflecting the dying light with a sharp, silver glint. The environment is a chaotic tapestry of the Great Grass Sea: towering, golden stalks of grass sway violently in the background, while the distant silhouettes of thousands of Dothraki screamers on horseback create a jagged horizon. The lighting is dramatic and high-contrast, with the deep crimson of the setting sun casting long, distorted shadows across the dusty earth. Every detail is tactile: the rough grain of the carriage's weathered wood, the intricate leather braiding of Drogo's chest harness, and the fine, shimmering dust motes dancing in the air. The scene captures the exact moment of a vow—the air thick with the scent of horse sweat and ozone—as Drogo declares his intent to cross the salt sea and conquer the Seven Kingdoms."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["ces through a high window , illuminating swirling dust motes and the frost - rimed breath of the gathered lords . at the center of the chaos , great jon umber stands as a mountain of a man , his face a mask of weathered leather and booming arrogance . his massive hand grips the hilt of a colossal greatsword , the steel singing as it is ripped from its scabbard in a blur of polished silver . he looms over robb stark , who stands rigid , his young face pale but his jaw locked in a desperate imitation of his father 's resolve . robb 's fingers clutch the hilt of his own blade , his knuckles white , sweat beading on his forehead despite the biting chill . in a sudden , explosive blur of silver - grey fur , grey wind lunges . the direwolf is a streak of primal fury , his muscles rippling beneath a thick , coarse coat . the wolf 's jaws snap shut with a sickening , wet crunch on great jon 's hand . blood , a vivid and shocking crimson , sprays across the grey stone floor , splashing against the worn , salt - stained leather of the lords ' boots . great jon 's expression shifts instantly from dominance to a wide - eyed , guttural shock , his mouth open in a silent roar of agony as two fingers are torn clean away . in the periphery , roose bolton watches with a predatory stillness , his pale , colorless eyes devoid of emotion , his posture unnervingly limp . the contrast is stark : the visceral violence of the wolf , the raw pain of the umber , and the cold , calculating silence of the bolton . the lighting casts long , jagged silhouettes across the hall , framing the scene in a chiaroscuro of power , blood , and the brutal law of the north ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["ces through a high window , illuminating swirling dust motes and the frost - rimed breath of the gathered lords . at the center of the chaos , great jon umber stands as a mountain of a man , his face a mask of weathered leather and booming arrogance . his massive hand grips the hilt of a colossal greatsword , the steel singing as it is ripped from its scabbard in a blur of polished silver . he looms over robb stark , who stands rigid , his young face pale but his jaw locked in a desperate imitation of his father 's resolve . robb 's fingers clutch the hilt of his own blade , his knuckles white , sweat beading on his forehead despite the biting chill . in a sudden , explosive blur of silver - grey fur , grey wind lunges . the direwolf is a streak of primal fury , his muscles rippling beneath a thick , coarse coat . the wolf 's jaws snap shut with a sickening , wet crunch on great jon 's hand . blood , a vivid and shocking crimson , sprays across the grey stone floor , splashing against the worn , salt - stained leather of the lords ' boots . great jon 's expression shifts instantly from dominance to a wide - eyed , guttural shock , his mouth open in a silent roar of agony as two fingers are torn clean away . in the periphery , roose bolton watches with a predatory stillness , his pale , colorless eyes devoid of emotion , his posture unnervingly limp . the contrast is stark : the visceral violence of the wolf , the raw pain of the umber , and the cold , calculating silence of the bolton . the lighting casts long , jagged silhouettes across the hall , framing the scene in a chiaroscuro of power , blood , and the brutal law of the north ."]
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ["s. A single, violent shaft of pale northern light pierces through a high window, illuminating swirling dust motes and the frost-rimed breath of the gathered lords. At the center of the chaos, Great Jon Umber stands as a mountain of a man, his face a mask of weathered leather and booming arrogance. His massive hand grips the hilt of a colossal greatsword, the steel singing as it is ripped from its scabbard in a blur of polished silver. He looms over Robb Stark, who stands rigid, his young face pale but his jaw locked in a desperate imitation of his father's resolve. Robb's fingers clutch the hilt of his own blade, his knuckles white, sweat beading on his forehead despite the biting chill. In a sudden, explosive blur of silver-grey fur, Grey Wind lunges. The direwolf is a streak of primal fury, his muscles rippling beneath a thick, coarse coat. The wolf's jaws snap shut with a sickening, wet crunch on Great Jon's hand. Blood, a vivid and shocking crimson, sprays across the grey stone floor, splashing against the worn, salt-stained leather of the lords' boots. Great Jon's expression shifts instantly from dominance to a wide-eyed, guttural shock, his mouth open in a silent roar of agony as two fingers are torn clean away. In the periphery, Roose Bolton watches with a predatory stillness, his pale, colorless eyes devoid of emotion, his posture unnervingly limp. The contrast is stark: the visceral violence of the wolf, the raw pain of the Umber, and the cold, calculating silence of the Bolton. The lighting casts long, jagged silhouettes across the hall, framing the scene in a chiaroscuro of power, blood, and the brutal law of the North."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["the heavy velvet fabric now sodden and clinging to his small frame . his face is a mask of grime and sweat , a jagged , raw wound weeping blood across his cheek , his eyes wide with a mixture of adrenaline - fueled terror and a sharp , intellectual realization of the trap . he is flanked by the rugged , feral warriors of the mountain clans ; these men are towering , wild - eyed brutes clad in cured furs and rusted chainmail , their skin weathered like old leather , shouting guttural war cries . beside tyrion , bronn stands with a predatory grace , his worn leather armor splattered with gore , a cynical , half - smirk playing on his lips as he pivots his blade to deflect a northern strike . the environment is a nightmare of gothic brutality : the ground is a churned slurry of black peat and crimson pools , littered with shattered ash - wood shields and the corpses of fallen horses . in the distance , the lannister banners — the golden lion on a field of crimson — snap violently in the wind , partially obscured by the thick , acrid smoke of burning encampments . the lighting is oppressive and cold , a diffused , pale light filtering through heavy storm clouds , creating deep , charcoal shadows in the folds of the soldiers ' cloaks . every texture is magnified : the cold glint of etched steel , the coarse weave of salt - stained linen , and the glistening , wet sheen of the mud . the tension is palpable , a snapshot of the moment tyrion realizes he and his vanguard were merely bait in his father 's cold , calculated game of war ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["the heavy velvet fabric now sodden and clinging to his small frame . his face is a mask of grime and sweat , a jagged , raw wound weeping blood across his cheek , his eyes wide with a mixture of adrenaline - fueled terror and a sharp , intellectual realization of the trap . he is flanked by the rugged , feral warriors of the mountain clans ; these men are towering , wild - eyed brutes clad in cured furs and rusted chainmail , their skin weathered like old leather , shouting guttural war cries . beside tyrion , bronn stands with a predatory grace , his worn leather armor splattered with gore , a cynical , half - smirk playing on his lips as he pivots his blade to deflect a northern strike . the environment is a nightmare of gothic brutality : the ground is a churned slurry of black peat and crimson pools , littered with shattered ash - wood shields and the corpses of fallen horses . in the distance , the lannister banners — the golden lion on a field of crimson — snap violently in the wind , partially obscured by the thick , acrid smoke of burning encampments . the lighting is oppressive and cold , a diffused , pale light filtering through heavy storm clouds , creating deep , charcoal shadows in the folds of the soldiers ' cloaks . every texture is magnified : the cold glint of etched steel , the coarse weave of salt - stained linen , and the glistening , wet sheen of the mud . the tension is palpable , a snapshot of the moment tyrion realizes he and his vanguard were merely bait in his father 's cold , calculated game of war ."]
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ["that stains his ornate, crimson-and-gold doublet, the heavy velvet fabric now sodden and clinging to his small frame. His face is a mask of grime and sweat, a jagged, raw wound weeping blood across his cheek, his eyes wide with a mixture of adrenaline-fueled terror and a sharp, intellectual realization of the trap. He is flanked by the rugged, feral warriors of the Mountain Clans; these men are towering, wild-eyed brutes clad in cured furs and rusted chainmail, their skin weathered like old leather, shouting guttural war cries. Beside Tyrion, Bronn stands with a predatory grace, his worn leather armor splattered with gore, a cynical, half-smirk playing on his lips as he pivots his blade to deflect a Northern strike. The environment is a nightmare of Gothic brutality: the ground is a churned slurry of black peat and crimson pools, littered with shattered ash-wood shields and the corpses of fallen horses. In the distance, the Lannister banners—the golden lion on a field of crimson—snap violently in the wind, partially obscured by the thick, acrid smoke of burning encampments. The lighting is oppressive and cold, a diffused, pale light filtering through heavy storm clouds, creating deep, charcoal shadows in the folds of the soldiers' cloaks. Every texture is magnified: the cold glint of etched steel, the coarse weave of salt-stained linen, and the glistening, wet sheen of the mud. The tension is palpable, a snapshot of the moment Tyrion realizes he and his vanguard were merely bait in his father's cold, calculated game of war."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["of rime ice clinging to his auburn beard and eyelashes . opposite him , osha is forced to her knees , her breath blooming in thick , white plumes in the frigid air . her expression is a volatile mix of feral defiance and calculated fear , her eyes darting between the circle of steel surrounding her . the environment is a suffocating expanse of towering sentinel trees , their bark gnarled and silver - grey , draped in heavy , sagging blankets of snow . the lighting is a cold , oppressive twilight ; a pale , filtered blue light seeps through the dense canopy , creating deep , ink - black shadows that swallow the forest floor . high - contrast lighting catches the glint of polished steel from the surrounding stark guards , whose armor is etched with the wear of travel , showing scratches and salt - stains . extreme detail is focused on the textures : the coarse , woven grain of osha 's rough - hewn furs , the intricate , hammered rivets of the soldiers ' leather bracers , and the crystalline structure of the fresh snow being crushed under heavy leather boots . a single , stray droplet of blood stains the pristine white snow near osha 's knee , a vivid , visceral crimson . the air feels heavy and damp , almost tangible , with a light flurry of snowflakes drifting slowly through the scene , some landing and melting on the sweat - beaded skin of the soldiers ' foreheads . the tension is electric , a silent war of wills played out in the oppressive silence of the north , where the only sound is the distant , haunting moan of the wind through the frozen pines ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["of rime ice clinging to his auburn beard and eyelashes . opposite him , osha is forced to her knees , her breath blooming in thick , white plumes in the frigid air . her expression is a volatile mix of feral defiance and calculated fear , her eyes darting between the circle of steel surrounding her . the environment is a suffocating expanse of towering sentinel trees , their bark gnarled and silver - grey , draped in heavy , sagging blankets of snow . the lighting is a cold , oppressive twilight ; a pale , filtered blue light seeps through the dense canopy , creating deep , ink - black shadows that swallow the forest floor . high - contrast lighting catches the glint of polished steel from the surrounding stark guards , whose armor is etched with the wear of travel , showing scratches and salt - stains . extreme detail is focused on the textures : the coarse , woven grain of osha 's rough - hewn furs , the intricate , hammered rivets of the soldiers ' leather bracers , and the crystalline structure of the fresh snow being crushed under heavy leather boots . a single , stray droplet of blood stains the pristine white snow near osha 's knee , a vivid , visceral crimson . the air feels heavy and damp , almost tangible , with a light flurry of snowflakes drifting slowly through the scene , some landing and melting on the sweat - beaded skin of the soldiers ' foreheads . the tension is electric , a silent war of wills played out in the oppressive silence of the north , where the only sound is the distant , haunting moan of the wind through the frozen pines ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["tes and the frantic movements of a macabre ritual . at the center of the scene , khal drogo lies prone and broken , his bronze skin now a sickly , pallid grey , sweat - beaded and glistening under the oppressive heat . he is partially submerged in a shallow , crimson pool of horse 's blood , the liquid reflecting the violent orange hues of the tent 's interior . mirri maz duur , the maegi , leans over him with a predatory intensity . her weathered , parchment - like skin is etched with deep wrinkles , and her eyes are wide with a terrifying , occult focus . her hands , stained dark with gore , gesture wildly as she chants , her lips curled in a sneer of arcane power . daenerys targaryen is collapsed on the dirt floor , her posture one of utter devastation . her silver - gold hair is matted with dust and sweat , clinging to her pale , tear - streaked cheeks . her eyes are wide , pupils dilated in a mixture of horror and desperate hope , her small hands clutching the coarse , salt - stained linen of her gown . beside her , ser jorah mormont stands as a battered sentinel ; his leather armor is scuffed and splattered with blood , his expression a grim mask of protective agony . his hand grips the hilt of his sword , knuckles white , as he glances warily toward the tent entrance where the shadows of terrified bloodriders flicker . the environment is a clash of textures : the rough , woven hemp of the tent walls , the slick , viscous surface of the blood - bath , and the jagged edges of ceremonial bone charms hanging from the ceiling . ethereal , ink - black shadows dance unnaturally across the canvas , twisting into distorted shapes that defy the laws of light , signaling the arrival of the dark magic of asshai ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["tes and the frantic movements of a macabre ritual . at the center of the scene , khal drogo lies prone and broken , his bronze skin now a sickly , pallid grey , sweat - beaded and glistening under the oppressive heat . he is partially submerged in a shallow , crimson pool of horse 's blood , the liquid reflecting the violent orange hues of the tent 's interior . mirri maz duur , the maegi , leans over him with a predatory intensity . her weathered , parchment - like skin is etched with deep wrinkles , and her eyes are wide with a terrifying , occult focus . her hands , stained dark with gore , gesture wildly as she chants , her lips curled in a sneer of arcane power . daenerys targaryen is collapsed on the dirt floor , her posture one of utter devastation . her silver - gold hair is matted with dust and sweat , clinging to her pale , tear - streaked cheeks . her eyes are wide , pupils dilated in a mixture of horror and desperate hope , her small hands clutching the coarse , salt - stained linen of her gown . beside her , ser jorah mormont stands as a battered sentinel ; his leather armor is scuffed and splattered with blood , his expression a grim mask of protective agony . his hand grips the hilt of his sword , knuckles white , as he glances warily toward the tent entrance where the shadows of terrified bloodriders flicker . the environment is a clash of textures : the rough , woven hemp of the tent walls , the slick , viscous surface of the blood - bath , and the jagged edges of ceremonial bone charms hanging from the ceiling . ethereal , ink - black shadows dance unnaturally across the canvas , twisting into distorted shapes that defy the laws of light , signaling the arrival of the dark magic of asshai ."]
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ["of swirling incense to illuminate floating dust motes and the frantic movements of a macabre ritual. At the center of the scene, Khal Drogo lies prone and broken, his bronze skin now a sickly, pallid grey, sweat-beaded and glistening under the oppressive heat. He is partially submerged in a shallow, crimson pool of horse's blood, the liquid reflecting the violent orange hues of the tent's interior. Mirri Maz Duur, the maegi, leans over him with a predatory intensity. Her weathered, parchment-like skin is etched with deep wrinkles, and her eyes are wide with a terrifying, occult focus. Her hands, stained dark with gore, gesture wildly as she chants, her lips curled in a sneer of arcane power. Daenerys Targaryen is collapsed on the dirt floor, her posture one of utter devastation. Her silver-gold hair is matted with dust and sweat, clinging to her pale, tear-streaked cheeks. Her eyes are wide, pupils dilated in a mixture of horror and desperate hope, her small hands clutching the coarse, salt-stained linen of her gown. Beside her, Ser Jorah Mormont stands as a battered sentinel; his leather armor is scuffed and splattered with blood, his expression a grim mask of protective agony. His hand grips the hilt of his sword, knuckles white, as he glances warily toward the tent entrance where the shadows of terrified bloodriders flicker. The environment is a clash of textures: the rough, woven hemp of the tent walls, the slick, viscous surface of the blood-bath, and the jagged edges of ceremonial bone charms hanging from the ceiling. Ethereal, ink-black shadows dance unnaturally across the canvas, twisting into distorted shapes that defy the laws of light, signaling the arrival of the dark magic of Asshai."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['the textures worn and salt - stained from the march . his auburn hair is damp with sweat , clinging to a forehead furrowed in hesitation . around him , the air vibrates with the roar of northern lords . the lighting is dramatic and directional ; massive iron braziers cast violent , dancing orange glows that carve deep , jagged shadows into the gothic arches of the hall . the flickering light catches the smoky ripples of valyrian steel and the cold glint of iron as weapons are drawn . great jon umber , a mountain of a man in rough - hewn furs and rusted mail , crashes to one knee . the sound of his heavy broadsword clattering against the cold , grey flagstones echoes like a thunderclap . the tension is palpable in the micro - expressions : the fierce , unwavering loyalty in the eyes of rickard karstark , the stern resolve of maege mormont , and the wide - eyed , hopeful desperation of the river lords . catelyn stark stands in the periphery , her face a mask of maternal terror and pride , her fingers gripping the fabric of her gown so tightly her knuckles are white . as the chorus of " the king in the north !" erupts , the sound becomes a physical force . dust motes dance in the shafts of dim light piercing through high , narrow windows . the scene is a collision of raw emotion and cold steel , capturing the exact heartbeat where a son becomes a sovereign , framed by the oppressive , ancient architecture of the tully stronghold and the suffocating heat of a hundred shouting men .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['the textures worn and salt - stained from the march . his auburn hair is damp with sweat , clinging to a forehead furrowed in hesitation . around him , the air vibrates with the roar of northern lords . the lighting is dramatic and directional ; massive iron braziers cast violent , dancing orange glows that carve deep , jagged shadows into the gothic arches of the hall . the flickering light catches the smoky ripples of valyrian steel and the cold glint of iron as weapons are drawn . great jon umber , a mountain of a man in rough - hewn furs and rusted mail , crashes to one knee . the sound of his heavy broadsword clattering against the cold , grey flagstones echoes like a thunderclap . the tension is palpable in the micro - expressions : the fierce , unwavering loyalty in the eyes of rickard karstark , the stern resolve of maege mormont , and the wide - eyed , hopeful desperation of the river lords . catelyn stark stands in the periphery , her face a mask of maternal terror and pride , her fingers gripping the fabric of her gown so tightly her knuckles are white . as the chorus of " the king in the north !" erupts , the sound becomes a physical force . dust motes dance in the shafts of dim light piercing through high , narrow windows . the scene is a collision of raw emotion and cold steel , capturing the exact heartbeat where a son becomes a sovereign , framed by the oppressive , ancient architecture of the tully stronghold and the suffocating heat of a hundred shouting men .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [", blood - red comet streaks across the charcoal sky , casting a sinister , crimson luminescence that carves deep , jagged shadows across the wasteland . daenerys targaryen emerges from the cooling white ash , her skin glistening with a mixture of sweat and soot , miraculously unburned . she is nude , her vulnerability contrasting with her newfound power . her iconic platinum hair is gone , leaving her scalp exposed and raw . she stands with a regal , primal posture , her chest heaving with slow , rhythmic breaths . clinging to her skin are three newborn dragons : one a deep , obsidian black with scales like polished onyx , another a vibrant , emerald green , and the third a shimmering cream - and - gold . their tiny , translucent wings flutter , and their needle - like claws grip her damp skin , leaving faint red marks . their eyes are slits of molten gold , blinking with ancient intelligence . surrounding the pyre , the remnants of the khalasar — gaunt elders , weeping women , and freed slaves in salt - stained , tattered linens — are frozen in collective awe . ser jorah mormont , his leather armor dusted in grey soot and his face etched with disbelief , is captured mid - motion , sinking to one knee . his expression is a complex blend of terror and religious devotion . the background is a desolate dothraki sea , the grass burnt to a crisp , under the oppressive glow of the red star . the lighting is high - contrast , with the orange glow of the remaining embers illuminating the underside of the dragons ' wings and the determined , ethereal gaze of the mother of dragons ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [", blood - red comet streaks across the charcoal sky , casting a sinister , crimson luminescence that carves deep , jagged shadows across the wasteland . daenerys targaryen emerges from the cooling white ash , her skin glistening with a mixture of sweat and soot , miraculously unburned . she is nude , her vulnerability contrasting with her newfound power . her iconic platinum hair is gone , leaving her scalp exposed and raw . she stands with a regal , primal posture , her chest heaving with slow , rhythmic breaths . clinging to her skin are three newborn dragons : one a deep , obsidian black with scales like polished onyx , another a vibrant , emerald green , and the third a shimmering cream - and - gold . their tiny , translucent wings flutter , and their needle - like claws grip her damp skin , leaving faint red marks . their eyes are slits of molten gold , blinking with ancient intelligence . surrounding the pyre , the remnants of the khalasar — gaunt elders , weeping women , and freed slaves in salt - stained , tattered linens — are frozen in collective awe . ser jorah mormont , his leather armor dusted in grey soot and his face etched with disbelief , is captured mid - motion , sinking to one knee . his expression is a complex blend of terror and religious devotion . the background is a desolate dothraki sea , the grass burnt to a crisp , under the oppressive glow of the red star . the lighting is high - contrast , with the orange glow of the remaining embers illuminating the underside of the dragons ' wings and the determined , ethereal gaze of the mother of dragons ."]
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ["e smolder, the embers glowing like dying stars in the dim, oppressive light. A violent, blood-red comet streaks across the charcoal sky, casting a sinister, crimson luminescence that carves deep, jagged shadows across the wasteland. Daenerys Targaryen emerges from the cooling white ash, her skin glistening with a mixture of sweat and soot, miraculously unburned. She is nude, her vulnerability contrasting with her newfound power. Her iconic platinum hair is gone, leaving her scalp exposed and raw. She stands with a regal, primal posture, her chest heaving with slow, rhythmic breaths. Clinging to her skin are three newborn dragons: one a deep, obsidian black with scales like polished onyx, another a vibrant, emerald green, and the third a shimmering cream-and-gold. Their tiny, translucent wings flutter, and their needle-like claws grip her damp skin, leaving faint red marks. Their eyes are slits of molten gold, blinking with ancient intelligence. Surrounding the pyre, the remnants of the khalasar—gaunt elders, weeping women, and freed slaves in salt-stained, tattered linens—are frozen in collective awe. Ser Jorah Mormont, his leather armor dusted in grey soot and his face etched with disbelief, is captured mid-motion, sinking to one knee. His expression is a complex blend of terror and religious devotion. The background is a desolate Dothraki sea, the grass burnt to a crisp, under the oppressive glow of the red star. The lighting is high-contrast, with the orange glow of the remaining embers illuminating the underside of the dragons' wings and the determined, ethereal gaze of the Mother of Dragons."]

  0%|          | 0/28 [00:00<?, ?it/s]

Metadata guardado en: /content/drive/MyDrive/Proyecto NLP y DL/Imagen_Generacion/generated_images_sd3/sd35_large/prueba_1960chars_sd3_conResumen/metadata.json
Resumen: {'total_rows': 50, 'ok': 50, 'errors': 0, 'skipped_existing': 0}

Liberando modelo: sd35_large

####################################################################################################
INICIANDO BLOQUE DE MODELO: sd3_medium
MODEL ID: stabilityai/stable-diffusion-3-medium-diffusers
####################################################################################################

Cargando modelo: stabilityai/stable-diffusion-3-medium-diffusers

model_index.json:   0%|          | 0.00/706 [00:00<?, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 26 files:   0%|          | 0/26 [00:00<?, ?it/s]

Loading pipeline components...:   0%|          | 0/9 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/219 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/517 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

Modelo cargado en 40.25 s

================================================================================
Modelo: sd3_medium
Dataset: prueba_500chars_sd3.jsonl
Prompt column: prompt_sd3_large
max_sequence_length: 256
Output dir: /content/drive/MyDrive/Proyecto NLP y DL/Imagen_Generacion/generated_images_sd3/sd3_medium/prueba_500chars_sd3/images
================================================================================
Filas cargadas: 50

sd3_medium | prueba_500chars_sd3.jsonl:   0%|          | 0/50 [00:00<?, ?it/s]

[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (113 > 77). Running this sequence through the model will result in indexing errors
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["'s throat . around him , his sons and guards stand in tense silence , their heavy furs and boiled leather cloaks dusted with frost under a bleak , oppressive grey sky ."]
[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (113 > 77). Running this sequence through the model will result in indexing errors
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["'s throat . around him , his sons and guards stand in tense silence , their heavy furs and boiled leather cloaks dusted with frost under a bleak , oppressive grey sky ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', mud - stained furs and boiled leather . pale , wintry light filters through a grey sky , casting a cold , somber mood over the gritty , snowy wilderness .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', mud - stained furs and boiled leather . pale , wintry light filters through a grey sky , casting a cold , somber mood over the gritty , snowy wilderness .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['eyes watching silently . a cold wind stirs the crimson leaves , while the stark , grey atmosphere emphasizes the heavy silence of mourning .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['eyes watching silently . a cold wind stirs the crimson leaves , while the stark , grey atmosphere emphasizes the heavy silence of mourning .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', harsh shadows across the granite columns and the silent stone kings . the air is thick with damp dust and ancient grief .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', harsh shadows across the granite columns and the silent stone kings . the air is thick with damp dust and ancient grief .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', his expression etched with hesitation . cold northern light filters through high stone arches , casting long shadows across the rough - hewn floor .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', his expression etched with hesitation . cold northern light filters through high stone arches , casting long shadows across the rough - hewn floor .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['draped in stark , baratheon , and lannister banners . warm , flickering torchlight cuts through the haze of roasted meat and hearth - smoke .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['draped in stark , baratheon , and lannister banners . warm , flickering torchlight cuts through the haze of roasted meat and hearth - smoke .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['goblet of wine . warm , flickering torchlight casts deep shadows across their faces , highlighting the grit and tension of this whispered , cruel piece of advice .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['goblet of wine . warm , flickering torchlight casts deep shadows across their faces , highlighting the grit and tension of this whispered , cruel piece of advice .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['oppressive shadows across the floor . his eyes are hard , reflecting a man stepping into a nest of vipers to uncover a deadly secret .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['oppressive shadows across the floor . his eyes are hard , reflecting a man stepping into a nest of vipers to uncover a deadly secret .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', eager eyes . they wear heavy grey wools and rough furs . cold northern light filters through a narrow slit window , casting long , moody shadows .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', eager eyes . they wear heavy grey wools and rough furs . cold northern light filters through a narrow slit window , casting long , moody shadows .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['pale light filters through the dust , casting long shadows . bran slips , his small fingers losing grip on the rough granite as he begins to fall .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['pale light filters through the dust , casting long shadows . bran slips , his small fingers losing grip on the rough granite as he begins to fall .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["scene is set against a grey , oppressive sky ; cold wind whips bran 's linen tunic . harsh , pale light casts deep shadows across the weathered masonry ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["scene is set against a grey , oppressive sky ; cold wind whips bran 's linen tunic . harsh , pale light casts deep shadows across the weathered masonry ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['and anger . cold winter light spills from an open window , illuminating dust motes and the rough grey masonry , while a heavy , suffocating silence fills the room .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['and anger . cold winter light spills from an open window , illuminating dust motes and the rough grey masonry , while a heavy , suffocating silence fills the room .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [", draped in delicate silks , reaches out with trembling fingers to touch the animal 's velvet nose . dust dances in the warm , hazy air around them ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [", draped in delicate silks , reaches out with trembling fingers to touch the animal 's velvet nose . dust dances in the warm , hazy air around them ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['tunic of heavy velvet , while ned is clad in somber , dark grey boiled leather and thick wool . harsh torchlight casts deep , flickering shadows .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['tunic of heavy velvet , while ned is clad in somber , dark grey boiled leather and thick wool . harsh torchlight casts deep , flickering shadows .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["gritty courtyards of winterfell under a bleak , overcast sky , with harsh , cold light emphasizing the raw violence and the wolf 's thick , coarse fur ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["gritty courtyards of winterfell under a bleak , overcast sky , with harsh , cold light emphasizing the raw violence and the wolf 's thick , coarse fur ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["is heavy with dread and mystery , the cold northern air visible as a faint mist , highlighting the blade 's sinister , ancient craftsmanship ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["is heavy with dread and mystery , the cold northern air visible as a faint mist , highlighting the blade 's sinister , ancient craftsmanship ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['damp earth . nearby , arya stands breathless in mud - stained leather , while the river flows coldly under a pale , oppressive sky of grey clouds .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['damp earth . nearby , arya stands breathless in mud - stained leather , while the river flows coldly under a pale , oppressive sky of grey clouds .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['cloak drape around him as he delivers the mercy blow . the atmosphere is heavy with tragedy , lit by a pale , wintry light that casts long , somber shadows .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['cloak drape around him as he delivers the mercy blow . the atmosphere is heavy with tragedy , lit by a pale , wintry light that casts long , somber shadows .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['sentinel trees loom under a heavy , overcast sky , with soft winter light filtering through the frost , creating a cold , hushed atmosphere .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['sentinel trees loom under a heavy , overcast sky , with soft winter light filtering through the frost , creating a cold , hushed atmosphere .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['thick furs . the scene is lit by a single flickering hearth , casting long , dancing shadows and a warm , orange glow against the cold , damp grey masonry .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['thick furs . the scene is lit by a single flickering hearth , casting long , dancing shadows and a warm , orange glow against the cold , damp grey masonry .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [". dust motes dance in shafts of pale sunlight piercing the gloom , highlighting the rough grain of the wood and arya 's simple linen tunic ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [". dust motes dance in shafts of pale sunlight piercing the gloom , highlighting the rough grain of the wood and arya 's simple linen tunic ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['serene , knowing expression . the golden hour light casts a warm , amber glow over the endless horizon , highlighting the soft textures of the grass and the intimate , tender bond between the two women .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['serene , knowing expression . the golden hour light casts a warm , amber glow over the endless horizon , highlighting the soft textures of the grass and the intimate , tender bond between the two women .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', once - fine linen . around them , dothraki warriors watch in silence . harsh midday sun casts sharp shadows across the arid plains , highlighting the tension in their standoff .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', once - fine linen . around them , dothraki warriors watch in silence . harsh midday sun casts sharp shadows across the arid plains , highlighting the tension in their standoff .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['shoulders , eyes wide with quiet longing . cold , grey morning light filters through a narrow slit window , casting long , pale shadows across the damp , grit - covered floor .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['shoulders , eyes wide with quiet longing . cold , grey morning light filters through a narrow slit window , casting long , pale shadows across the damp , grit - covered floor .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['gripping a heavy hammer . his blue eyes are sullen and guarded . around them , glowing forges cast harsh , flickering light and deep shadows across grime - covered anvils and piles of raw iron .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['gripping a heavy hammer . his blue eyes are sullen and guarded . around them , glowing forges cast harsh , flickering light and deep shadows across grime - covered anvils and piles of raw iron .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [", his eyes wide with terror . harsh sunlight cuts through narrow slits in the grey walls , illuminating dust motes and the stark contrast between the warrior 's power and the boy 's fear ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [", his eyes wide with terror . harsh sunlight cuts through narrow slits in the grey walls , illuminating dust motes and the stark contrast between the warrior 's power and the boy 's fear ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['; banners flutter in the wind , and the air is thick with kicked - up dirt and the scent of crushed grass and horse sweat .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['; banners flutter in the wind , and the air is thick with kicked - up dirt and the scent of crushed grass and horse sweat .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['tables . flickering orange torchlight casts long , dancing shadows across the stone walls and mud - streaked floor , heightening the sudden tension .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['tables . flickering orange torchlight casts long , dancing shadows across the stone walls and mud - streaked floor , heightening the sudden tension .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['ted frame . he is escorted by stern guards in mud - splattered leather and steel . grey mist clings to the jagged peaks above .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['ted frame . he is escorted by stern guards in mud - splattered leather and steel . grey mist clings to the jagged peaks above .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['pierces through swirling grey clouds , casting harsh shadows across the white stone of the seven towering spires .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['pierces through swirling grey clouds , casting harsh shadows across the white stone of the seven towering spires .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['. cold mountain light floods the white marble hall , casting sharp shadows . the atmosphere is tense , smelling of ozone and cold stone and desperation .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['. cold mountain light floods the white marble hall , casting sharp shadows . the atmosphere is tense , smelling of ozone and cold stone and desperation .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['flickering torchlight casts dancing , jagged shadows across the grime - streaked walls and muddy floor , illuminating the tension of their treasonous plot .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['flickering torchlight casts dancing , jagged shadows across the grime - streaked walls and muddy floor , illuminating the tension of their treasonous plot .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["the knight 's armpit . vardis , in dented plate armor , gasps in agony . cold , pale light filters through the high arches ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["the knight 's armpit . vardis , in dented plate armor , gasps in agony . cold , pale light filters through the high arches ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['throne . the cold , thin mountain air swirls around them , while pale , stark light filters through the high arches , casting long , oppressive shadows .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['throne . the cold , thin mountain air swirls around them , while pale , stark light filters through the high arches , casting long , oppressive shadows .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['with betrayal ; the lighting is stark , with cold shafts of daylight cutting through dust motes , casting deep shadows across the stone floor .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['with betrayal ; the lighting is stark , with cold shafts of daylight cutting through dust motes , casting deep shadows across the stone floor .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['. soft , golden sunlight filters through budding willow trees , casting a hopeful , ethereal glow over the sprawling tournament grounds .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['. soft , golden sunlight filters through budding willow trees , casting a hopeful , ethereal glow over the sprawling tournament grounds .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["the flickering orange glow of braziers that cast deep , dancing shadows . drogo 's expression is stern and dismissive as he prepares for the hunt , embodying the fierce stallion who mounts the world ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["the flickering orange glow of braziers that cast deep , dancing shadows . drogo 's expression is stern and dismissive as he prepares for the hunt , embodying the fierce stallion who mounts the world ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["others struggle to strip the boy 's garments . cold , grey light filters through skeletal trees , casting a bleak , oppressive atmosphere over the struggle ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["others struggle to strip the boy 's garments . cold , grey light filters through skeletal trees , casting a bleak , oppressive atmosphere over the struggle ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['pale light filtering through narrow slits , casting long shadows across the damp floor and the distant , sightless gaze of maester aemon .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['pale light filtering through narrow slits , casting long shadows across the damp floor and the distant , sightless gaze of maester aemon .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['en . splashes of crimson blood spray across the damp forest floor . dim , filtered sunlight pierces through a canopy of ancient , oppressive grey trees .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['en . splashes of crimson blood spray across the damp forest floor . dim , filtered sunlight pierces through a canopy of ancient , oppressive grey trees .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['athered parchment , his expression torn with guilt as he carefully writes " my heir " instead of " my son ." flickering orange candlelight casts long , dancing shadows .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['athered parchment , his expression torn with guilt as he carefully writes " my heir " instead of " my son ." flickering orange candlelight casts long , dancing shadows .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['dirt . cold , grey light filters through the towering stone walls , casting long shadows over the damp cobblestones and piles of refuse in the oppressive , silent atmosphere .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['dirt . cold , grey light filters through the towering stone walls , casting long shadows over the damp cobblestones and piles of refuse in the oppressive , silent atmosphere .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['beats down , casting sharp shadows on the scorched earth , while the merchant screams , dragged through the dirt by galloping horses .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['beats down , casting sharp shadows on the scorched earth , while the merchant screams , dragged through the dirt by galloping horses .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['wintry light filters through a leaden sky , casting a cold , grim atmosphere over the mud - splattered steel of gathered spears .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['wintry light filters through a leaden sky , casting a cold , grim atmosphere over the mud - splattered steel of gathered spears .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['splattered steel plate and boiled leather . a grey , oppressive sky casts a flat light over the rushing river , enhancing the grim , tense atmosphere of a standoff .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['splattered steel plate and boiled leather . a grey , oppressive sky casts a flat light over the rushing river , enhancing the grim , tense atmosphere of a standoff .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['canopy , illuminating the swirling snowflakes and the damp , frosted earth . the atmosphere is tense , smelling of pine and winter .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['canopy , illuminating the swirling snowflakes and the damp , frosted earth . the atmosphere is tense , smelling of pine and winter .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['rigid . the air is thick with tension and the scent of dust , while the stark light casts deep , jagged shadows across the cobblestones .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['rigid . the air is thick with tension and the scent of dust , while the stark light casts deep , jagged shadows across the cobblestones .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', his eyes vacant , wearing a stained leather vest . harsh , blinding sunlight creates shimmering heat waves , casting stark , oppressive shadows across the gritty earth .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', his eyes vacant , wearing a stained leather vest . harsh , blinding sunlight creates shimmering heat waves , casting stark , oppressive shadows across the gritty earth .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['an inner heat . daenerys , skin glistening with sweat and ash , is enveloped by the searing fire , her expression one of divine transcendence and raw power .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['an inner heat . daenerys , skin glistening with sweat and ash , is enveloped by the searing fire , her expression one of divine transcendence and raw power .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', grey daylight filters through the oppressive stone walls , casting long , melancholic shadows across the room where untouched silver platters of food sit abandoned .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', grey daylight filters through the oppressive stone walls , casting long , melancholic shadows across the room where untouched silver platters of food sit abandoned .']

  0%|          | 0/28 [00:00<?, ?it/s]

Metadata guardado en: /content/drive/MyDrive/Proyecto NLP y DL/Imagen_Generacion/generated_images_sd3/sd3_medium/prueba_500chars_sd3/metadata.json
Resumen: {'total_rows': 50, 'ok': 50, 'errors': 0, 'skipped_existing': 0}

================================================================================
Modelo: sd3_medium
Dataset: prueba_1013chars_sd3_inicial.jsonl
Prompt column: prompt_sd3_large
max_sequence_length: 256
Output dir: /content/drive/MyDrive/Proyecto NLP y DL/Imagen_Generacion/generated_images_sd3/sd3_medium/prueba_1013chars_sd3_inicial/images
================================================================================
Filas cargadas: 50

sd3_medium | prueba_1013chars_sd3_inicial.jsonl:   0%|          | 0/50 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["in the blood - stained snow , its size dwarfing a pony . eddard 's weathered hand reaches beneath the creature 's jaw , pulling out a jagged , blood - soaked shard of a stag 's antler . beside him , young bran clutches a tiny , shivering direwolf pup to his chest with fierce desperation , while theon greyjoy stands nearby , his steel sword half - drawn with a cold , arrogant expression . the lighting is a bleak , oppressive winter grey , with a pale sun struggling to pierce through heavy clouds , casting soft , muted shadows across the crimson - stained white terrain and the rough , boiled leather and fur textures of the stark party 's winter attire ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["in the blood - stained snow , its size dwarfing a pony . eddard 's weathered hand reaches beneath the creature 's jaw , pulling out a jagged , blood - soaked shard of a stag 's antler . beside him , young bran clutches a tiny , shivering direwolf pup to his chest with fierce desperation , while theon greyjoy stands nearby , his steel sword half - drawn with a cold , arrogant expression . the lighting is a bleak , oppressive winter grey , with a pale sun struggling to pierce through heavy clouds , casting soft , muted shadows across the crimson - stained white terrain and the rough , boiled leather and fur textures of the stark party 's winter attire ."]
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ["massive, dark carcass of a direwolf, an enormous beast semienterred in the blood-stained snow, its size dwarfing a pony. Eddard's weathered hand reaches beneath the creature's jaw, pulling out a jagged, blood-soaked shard of a stag's antler. Beside him, young Bran clutches a tiny, shivering direwolf pup to his chest with fierce desperation, while Theon Greyjoy stands nearby, his steel sword half-drawn with a cold, arrogant expression. The lighting is a bleak, oppressive winter grey, with a pale sun struggling to pierce through heavy clouds, casting soft, muted shadows across the crimson-stained white terrain and the rough, boiled leather and fur textures of the Stark party's winter attire."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['small , shivering grey pup , his face a mask of desperate protection , while robb stands beside him with a defiant , commanding gaze . jon snow stands slightly apart , cradling a sixth , smaller pup against his chest , his expression solemn and longing . around them , grim guards in interlocking steel ringmail and heavy grey wool look on with apprehension . the ground is a harsh mixture of frozen white snow and dark , blood - stained earth . a pale , wintry light filters through a heavy overcast sky , casting a cold , muted glow over the scene , emphasizing the stark contrast between the warmth of the pups and the freezing , oppressive atmosphere of the wilderness .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['small , shivering grey pup , his face a mask of desperate protection , while robb stands beside him with a defiant , commanding gaze . jon snow stands slightly apart , cradling a sixth , smaller pup against his chest , his expression solemn and longing . around them , grim guards in interlocking steel ringmail and heavy grey wool look on with apprehension . the ground is a harsh mixture of frozen white snow and dark , blood - stained earth . a pale , wintry light filters through a heavy overcast sky , casting a cold , muted glow over the scene , emphasizing the stark contrast between the warmth of the pups and the freezing , oppressive atmosphere of the wilderness .']
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ['together in the biting cold. Young Bran clings fiercely to a small, shivering grey pup, his face a mask of desperate protection, while Robb stands beside him with a defiant, commanding gaze. Jon Snow stands slightly apart, cradling a sixth, smaller pup against his chest, his expression solemn and longing. Around them, grim guards in interlocking steel ringmail and heavy grey wool look on with apprehension. The ground is a harsh mixture of frozen white snow and dark, blood-stained earth. A pale, wintry light filters through a heavy overcast sky, casting a cold, muted glow over the scene, emphasizing the stark contrast between the warmth of the pups and the freezing, oppressive atmosphere of the wilderness.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["delivers the devastating news of jon arryn 's death . ned 's expression is one of sudden , crushing loss , his eyes clouded with memory and shock . they are positioned beside the ancient heart tree , its ghostly white bark contrasting sharply with the deep , bleeding red of its carved face and sap - filled eyes . the atmosphere is heavy and oppressive , with a thin mist clinging to the damp earth . pale , diffused northern light filters through the skeletal branches of the godswood , casting soft , muted shadows that emphasize the grim solemnity of the encounter and the sudden weight of a dying era ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["delivers the devastating news of jon arryn 's death . ned 's expression is one of sudden , crushing loss , his eyes clouded with memory and shock . they are positioned beside the ancient heart tree , its ghostly white bark contrasting sharply with the deep , bleeding red of its carved face and sap - filled eyes . the atmosphere is heavy and oppressive , with a thin mist clinging to the damp earth . pale , diffused northern light filters through the skeletal branches of the godswood , casting soft , muted shadows that emphasize the grim solemnity of the encounter and the sudden weight of a dying era ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["beside him , his expression solemn and guarded , holding a flickering oil lamp that casts long , dancing shadows across the vaulted ceiling . they are dressed in heavy , travel - worn furs and thick wools ; robert 's royal velvet is dusted with grime , while ned wears a dark , rugged cloak of boiled leather and grey wool . around them , a silent procession of ancient stark ancestors sit carved in stone , their sightless eyes watching from the gloom . the atmosphere is thick with dampness and the scent of old earth . the singular , trembling orange light of the lamp creates a stark chiaroscuro , illuminating the pale , serene face of lyanna 's statue against the suffocating darkness ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["beside him , his expression solemn and guarded , holding a flickering oil lamp that casts long , dancing shadows across the vaulted ceiling . they are dressed in heavy , travel - worn furs and thick wools ; robert 's royal velvet is dusted with grime , while ned wears a dark , rugged cloak of boiled leather and grey wool . around them , a silent procession of ancient stark ancestors sit carved in stone , their sightless eyes watching from the gloom . the atmosphere is thick with dampness and the scent of old earth . the singular , trembling orange light of the lamp creates a stark chiaroscuro , illuminating the pale , serene face of lyanna 's statue against the suffocating darkness ."]
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ["aching longing, his hand hovering near the cold granite. Ned stands beside him, his expression solemn and guarded, holding a flickering oil lamp that casts long, dancing shadows across the vaulted ceiling. They are dressed in heavy, travel-worn furs and thick wools; Robert's royal velvet is dusted with grime, while Ned wears a dark, rugged cloak of boiled leather and grey wool. Around them, a silent procession of ancient Stark ancestors sit carved in stone, their sightless eyes watching from the gloom. The atmosphere is thick with dampness and the scent of old earth. The singular, trembling orange light of the lamp creates a stark chiaroscuro, illuminating the pale, serene face of Lyanna's statue against the suffocating darkness."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['trothal of sansa stark to prince joffrey . ned stands rigid , his face a mask of solemn hesitation , dressed in heavy , charcoal - grey wool and thick furs that smell of pine and cold rain . robert wears a rich , gold - embroidered velvet doublet , now stained and rumpled , reflecting his decadent decline . the room is illuminated by the orange flicker of massive hearths , casting long , dancing shadows across the rough - hewn stone walls . the air is thick with the scent of roasting meat and peat smoke , while the oppressive chill of the north clings to the edges of the warmth , mirroring the tension of a political bond forged in the shadow of old ghosts .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['trothal of sansa stark to prince joffrey . ned stands rigid , his face a mask of solemn hesitation , dressed in heavy , charcoal - grey wool and thick furs that smell of pine and cold rain . robert wears a rich , gold - embroidered velvet doublet , now stained and rumpled , reflecting his decadent decline . the room is illuminated by the orange flicker of massive hearths , casting long , dancing shadows across the rough - hewn stone walls . the air is thick with the scent of roasting meat and peat smoke , while the oppressive chill of the north clings to the edges of the warmth , mirroring the tension of a political bond forged in the shadow of old ghosts .']
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: [', his expression a mixture of desperation and nostalgic longing as he proposes the betrothal of Sansa Stark to Prince Joffrey. Ned stands rigid, his face a mask of solemn hesitation, dressed in heavy, charcoal-grey wool and thick furs that smell of pine and cold rain. Robert wears a rich, gold-embroidered velvet doublet, now stained and rumpled, reflecting his decadent decline. The room is illuminated by the orange flicker of massive hearths, casting long, dancing shadows across the rough-hewn stone walls. The air is thick with the scent of roasting meat and peat smoke, while the oppressive chill of the North clings to the edges of the warmth, mirroring the tension of a political bond forged in the shadow of old ghosts.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['goblet of deep red summer wine . behind him , the air is thick with the scent of roasted meats and hearth smoke . in the distant , elevated background , the high table is a scene of opulent rigidity ; lord and lady stark sit beside the king and queen , surrounded by the royal children . the queen is radiant in a gown of shimmering gold silk , a jeweled emerald diadem resting upon her golden hair . massive stone walls are draped with heavy wool banners of the direwolf , stag , and lion . warm , flickering orange light from towering fireplaces casts long , dancing shadows , contrasting the golden glow of the high table with the dim , gritty atmosphere of the lower benches .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['goblet of deep red summer wine . behind him , the air is thick with the scent of roasted meats and hearth smoke . in the distant , elevated background , the high table is a scene of opulent rigidity ; lord and lady stark sit beside the king and queen , surrounded by the royal children . the queen is radiant in a gown of shimmering gold silk , a jeweled emerald diadem resting upon her golden hair . massive stone walls are draped with heavy wool banners of the direwolf , stag , and lion . warm , flickering orange light from towering fireplaces casts long , dancing shadows , contrasting the golden glow of the high table with the dim , gritty atmosphere of the lower benches .']
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ['He wears a simple, dark wool tunic of coarse weave, clutching a pewter goblet of deep red summer wine. Behind him, the air is thick with the scent of roasted meats and hearth smoke. In the distant, elevated background, the high table is a scene of opulent rigidity; Lord and Lady Stark sit beside the King and Queen, surrounded by the royal children. The Queen is radiant in a gown of shimmering gold silk, a jeweled emerald diadem resting upon her golden hair. Massive stone walls are draped with heavy wool banners of the direwolf, stag, and lion. Warm, flickering orange light from towering fireplaces casts long, dancing shadows, contrasting the golden glow of the high table with the dim, gritty atmosphere of the lower benches.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["rion leans in with a knowing , cynical smirk , his mismatched eyes gleaming with sharp intelligence . tyrion is dressed in rich , crimson velvet and gold - threaded brocade that contrasts sharply with the bleak northern surroundings . he gestures with a small , ring - adorned hand , delivering his cold advice . the background is a blur of rough - hewn stone walls and flickering wall torches that cast long , dancing shadows and a warm , orange glow across the scene . the air is thick with the scent of roasted meat and old smoke . jon 's face is a mask of suppressed hurt and simmering anger , capturing a pivotal moment of psychological cruelty ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["rion leans in with a knowing , cynical smirk , his mismatched eyes gleaming with sharp intelligence . tyrion is dressed in rich , crimson velvet and gold - threaded brocade that contrasts sharply with the bleak northern surroundings . he gestures with a small , ring - adorned hand , delivering his cold advice . the background is a blur of rough - hewn stone walls and flickering wall torches that cast long , dancing shadows and a warm , orange glow across the scene . the air is thick with the scent of roasted meat and old smoke . jon 's face is a mask of suppressed hurt and simmering anger , capturing a pivotal moment of psychological cruelty ."]
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ["y wool tunic trimmed with coarse fur. Beside him, the diminutive Tyrion leans in with a knowing, cynical smirk, his mismatched eyes gleaming with sharp intelligence. Tyrion is dressed in rich, crimson velvet and gold-threaded brocade that contrasts sharply with the bleak Northern surroundings. He gestures with a small, ring-adorned hand, delivering his cold advice. The background is a blur of rough-hewn stone walls and flickering wall torches that cast long, dancing shadows and a warm, orange glow across the scene. The air is thick with the scent of roasted meat and old smoke. Jon's face is a mask of suppressed hurt and simmering anger, capturing a pivotal moment of psychological cruelty."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['the textures coarse and weathered , smelling of pine and old snow . around him , the room is swallowed by oppressive shadows , illuminated only by the flickering , amber glow of a few dying hearth fires that cast long , dancing silhouettes against the damp masonry . his eyes are narrow and haunted , reflecting the weight of a dangerous secret . through a narrow window , a bleak , overcast sky looms , hinting at the treacherous journey south . the atmosphere is thick with tension and paranoia , a silent battle between his loyalty to robert and the suffocating realization that he is stepping into a nest of vipers .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['the textures coarse and weathered , smelling of pine and old snow . around him , the room is swallowed by oppressive shadows , illuminated only by the flickering , amber glow of a few dying hearth fires that cast long , dancing silhouettes against the damp masonry . his eyes are narrow and haunted , reflecting the weight of a dangerous secret . through a narrow window , a bleak , overcast sky looms , hinting at the treacherous journey south . the atmosphere is thick with tension and paranoia , a silent battle between his loyalty to robert and the suffocating realization that he is stepping into a nest of vipers .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', his finger pointing toward the lethal , tapered tip of the blade . arya looks up at him with wide , intense eyes , her face a mask of fierce determination . jon wears a heavy , dark wool tunic and a weathered leather jerkin , while arya is dressed in a simple , rough - spun linen dress , slightly rumpled from her struggle with packing . beside them , the white wolf ghost and the grey wolf nymeria sit alert , their fur contrasting against the cold grey granite floor . soft , pale northern light filters through a narrow embrasure , casting long , cool shadows and highlighting the metallic sheen of the sword and the gritty texture of the ancient stone walls .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', his finger pointing toward the lethal , tapered tip of the blade . arya looks up at him with wide , intense eyes , her face a mask of fierce determination . jon wears a heavy , dark wool tunic and a weathered leather jerkin , while arya is dressed in a simple , rough - spun linen dress , slightly rumpled from her struggle with packing . beside them , the white wolf ghost and the grey wolf nymeria sit alert , their fur contrasting against the cold grey granite floor . soft , pale northern light filters through a narrow embrasure , casting long , cool shadows and highlighting the metallic sheen of the sword and the gritty texture of the ancient stone walls .']
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: [", trembling hand to grip the hilt. He is mid-sentence, demonstrating the weapon's purpose, his finger pointing toward the lethal, tapered tip of the blade. Arya looks up at him with wide, intense eyes, her face a mask of fierce determination. Jon wears a heavy, dark wool tunic and a weathered leather jerkin, while Arya is dressed in a simple, rough-spun linen dress, slightly rumpled from her struggle with packing. Beside them, the white wolf Ghost and the grey wolf Nymeria sit alert, their fur contrasting against the cold grey granite floor. Soft, pale northern light filters through a narrow embrasure, casting long, cool shadows and highlighting the metallic sheen of the sword and the gritty texture of the ancient stone walls."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['golden - haired man — her mirror image — are locked in a passionate , forbidden embrace against a cold stone wall . the room is cast in deep amber shadows and stark chiaroscuro , highlighting the pale skin of the lovers . outside , the air is freezing , with a light dusting of melting snow clinging to the grey masonry . bran ’ s small fingers grip the rough , abrasive rock , his simple wool tunic damp from the mist . the tension is palpable ; the boy is frozen in a moment of devastating discovery , the vast , dizzying drop to the wet courtyard below creating a sense of vertigo and impending doom .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['golden - haired man — her mirror image — are locked in a passionate , forbidden embrace against a cold stone wall . the room is cast in deep amber shadows and stark chiaroscuro , highlighting the pale skin of the lovers . outside , the air is freezing , with a light dusting of melting snow clinging to the grey masonry . bran ’ s small fingers grip the rough , abrasive rock , his simple wool tunic damp from the mist . the tension is palpable ; the boy is frozen in a moment of devastating discovery , the vast , dizzying drop to the wet courtyard below creating a sense of vertigo and impending doom .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["uselessly at the rough , grey masonry as he tips into the void . the man wears a rich , gold - threaded doublet of heavy crimson silk , now rumpled and stained . the architecture is oppressive , featuring weathered gargoyles and damp , lichen - covered granite . below , the dizzying drop reveals a courtyard of slick , slushy snow and grey cobblestones . the lighting is a bleak , oppressive overcast daylight , casting soft but dismal shadows that emphasize the grit of the stone . a chilling atmosphere of betrayal permeates the air , with the wind whipping the boy 's simple wool tunic as he begins his fatal descent ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["uselessly at the rough , grey masonry as he tips into the void . the man wears a rich , gold - threaded doublet of heavy crimson silk , now rumpled and stained . the architecture is oppressive , featuring weathered gargoyles and damp , lichen - covered granite . below , the dizzying drop reveals a courtyard of slick , slushy snow and grey cobblestones . the lighting is a bleak , oppressive overcast daylight , casting soft but dismal shadows that emphasize the grit of the stone . a chilling atmosphere of betrayal permeates the air , with the wind whipping the boy 's simple wool tunic as he begins his fatal descent ."]
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ["is a mask of pure shock and terror, his small hands clawing uselessly at the rough, grey masonry as he tips into the void. The man wears a rich, gold-threaded doublet of heavy crimson silk, now rumpled and stained. The architecture is oppressive, featuring weathered gargoyles and damp, lichen-covered granite. Below, the dizzying drop reveals a courtyard of slick, slushy snow and grey cobblestones. The lighting is a bleak, oppressive overcast daylight, casting soft but dismal shadows that emphasize the grit of the stone. A chilling atmosphere of betrayal permeates the air, with the wind whipping the boy's simple wool tunic as he begins his fatal descent."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', simmering hatred , turns sharply toward jon snow . jon stands near the heavy oak door , his posture rigid and pained , dressed in dark , travel - worn boiled leather and a heavy wool cloak . the air is thick with resentment . catelyn ’ s eyes are narrow and cruel as she delivers her biting words , her lip curling in disdain . beside jon , the white direwolf ghost watches with piercing red eyes , sensing the hostility . pale , wintry light filters through a narrow open window , illuminating dust motes and the stark contrast between the warm hearth - glow and the freezing draft . the atmosphere is suffocating , charged with familial tragedy and unspoken malice .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', simmering hatred , turns sharply toward jon snow . jon stands near the heavy oak door , his posture rigid and pained , dressed in dark , travel - worn boiled leather and a heavy wool cloak . the air is thick with resentment . catelyn ’ s eyes are narrow and cruel as she delivers her biting words , her lip curling in disdain . beside jon , the white direwolf ghost watches with piercing red eyes , sensing the hostility . pale , wintry light filters through a narrow open window , illuminating dust motes and the stark contrast between the warm hearth - glow and the freezing draft . the atmosphere is suffocating , charged with familial tragedy and unspoken malice .']
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ['burn hair matted and disheveled, her face etched with hollow exhaustion and a cold, simmering hatred, turns sharply toward Jon Snow. Jon stands near the heavy oak door, his posture rigid and pained, dressed in dark, travel-worn boiled leather and a heavy wool cloak. The air is thick with resentment. Catelyn’s eyes are narrow and cruel as she delivers her biting words, her lip curling in disdain. Beside Jon, the white direwolf Ghost watches with piercing red eyes, sensing the hostility. Pale, wintry light filters through a narrow open window, illuminating dust motes and the stark contrast between the warm hearth-glow and the freezing draft. The atmosphere is suffocating, charged with familial tragedy and unspoken malice.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["breathtaking creature , its coat a shimmering winter - sea grey and its flowing mane like swirling silver smoke , tossing its head with youthful energy . daenerys , dressed in delicate , flowing silks of pale cream and gold , reaches out with a mixture of trepidation and wonder , her small hand nearly touching the mare 's velvet muzzle . around them , the atmosphere is thick with the heat of the afternoon , the golden light casting long , soft shadows across the stone tiles . the tension is palpable as the proud dothraki bloodriders watch in silence , their bronze ornaments glinting under a harsh , brilliant sky ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["breathtaking creature , its coat a shimmering winter - sea grey and its flowing mane like swirling silver smoke , tossing its head with youthful energy . daenerys , dressed in delicate , flowing silks of pale cream and gold , reaches out with a mixture of trepidation and wonder , her small hand nearly touching the mare 's velvet muzzle . around them , the atmosphere is thick with the heat of the afternoon , the golden light casting long , soft shadows across the stone tiles . the tension is palpable as the proud dothraki bloodriders watch in silence , their bronze ornaments glinting under a harsh , brilliant sky ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['hall . ned stark stands his ground , his face a mask of frozen grief and moral indignation , his grey eyes piercing and filled with a quiet , simmering anger . ned wears a heavy , charcoal - grey wool doublet with a thick fur mantle draped over his shoulders , while robert is clad in rich , gold - embroidered crimson velvet that contrasts with the grim atmosphere . the room is illuminated by flickering orange torchlight that casts long , dancing shadows against the damp limestone walls . the air is thick with tension and the scent of old smoke , capturing a moment of profound ideological clash between two old friends .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['hall . ned stark stands his ground , his face a mask of frozen grief and moral indignation , his grey eyes piercing and filled with a quiet , simmering anger . ned wears a heavy , charcoal - grey wool doublet with a thick fur mantle draped over his shoulders , while robert is clad in rich , gold - embroidered crimson velvet that contrasts with the grim atmosphere . the room is illuminated by flickering orange torchlight that casts long , dancing shadows against the damp limestone walls . the air is thick with tension and the scent of old smoke , capturing a moment of profound ideological clash between two old friends .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['in a silent scream of agony as blood sprays across the cold floor . nearby , catelyn stark recoils in terror and relief , her fine velvet gown torn and stained , her auburn hair disheveled . beside her , young bran stark looks on with wide , trembling eyes , his small frame shivering in a linen tunic . the atmosphere is thick with tension and the smell of iron and wet fur . harsh , flickering torchlight casts long , dancing shadows against the damp granite walls , creating a stark chiaroscuro effect that emphasizes the raw , primal power of the beast protecting the children in the oppressive gloom of the north .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['in a silent scream of agony as blood sprays across the cold floor . nearby , catelyn stark recoils in terror and relief , her fine velvet gown torn and stained , her auburn hair disheveled . beside her , young bran stark looks on with wide , trembling eyes , his small frame shivering in a linen tunic . the atmosphere is thick with tension and the smell of iron and wet fur . harsh , flickering torchlight casts long , dancing shadows against the damp granite walls , creating a stark chiaroscuro effect that emphasizes the raw , primal power of the beast protecting the children in the oppressive gloom of the north .']
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ['assassin, dressed in rough, dark wool and weathered leather, is thrown backward, his face twisted in a silent scream of agony as blood sprays across the cold floor. Nearby, Catelyn Stark recoils in terror and relief, her fine velvet gown torn and stained, her auburn hair disheveled. Beside her, young Bran Stark looks on with wide, trembling eyes, his small frame shivering in a linen tunic. The atmosphere is thick with tension and the smell of iron and wet fur. Harsh, flickering torchlight casts long, dancing shadows against the damp granite walls, creating a stark chiaroscuro effect that emphasizes the raw, primal power of the beast protecting the children in the oppressive gloom of the North.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['metal that shimmer with a sinister , iridescent quality . beside the blade , a hand in a rough wool sleeve points toward the weapon , highlighting its unnatural sharpness . the room is cold , with frost creeping along the stone walls and a single flickering torch casting long , dancing shadows and a warm , orange glow that contrasts with the oppressive grey stone . the atmosphere is thick with dread and urgency . ser rodrik stands in the background , his face etched with grim determination , wearing heavy boiled leather and a weathered cloak of thick grey fur , his eyes fixed on the deadly instrument of the attempted assassination .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['metal that shimmer with a sinister , iridescent quality . beside the blade , a hand in a rough wool sleeve points toward the weapon , highlighting its unnatural sharpness . the room is cold , with frost creeping along the stone walls and a single flickering torch casting long , dancing shadows and a warm , orange glow that contrasts with the oppressive grey stone . the atmosphere is thick with dread and urgency . ser rodrik stands in the background , his face etched with grim determination , wearing heavy boiled leather and a weathered cloak of thick grey fur , his eyes fixed on the deadly instrument of the attempted assassination .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["firmly onto joffrey 's arm . the prince 's ornate crimson and gold velvet doublet is torn , and his polished leather boots kick frantically in the air . nearby , a young arya stark , dressed in mud - splattered brown leather and rough linen , stands with a defiant , tear - streaked face , clutching a wooden stick . the ground is a mess of trampled emerald grass and damp river silt . sunlight filters through the canopy of ancient , whispering trees , creating sharp contrasts of light and shadow . the atmosphere is thick with tension , the spray of river water and the dust kicked up by the panicked horse adding a gritty , visceral realism to the sudden attack ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["firmly onto joffrey 's arm . the prince 's ornate crimson and gold velvet doublet is torn , and his polished leather boots kick frantically in the air . nearby , a young arya stark , dressed in mud - splattered brown leather and rough linen , stands with a defiant , tear - streaked face , clutching a wooden stick . the ground is a mess of trampled emerald grass and damp river silt . sunlight filters through the canopy of ancient , whispering trees , creating sharp contrasts of light and shadow . the atmosphere is thick with tension , the spray of river water and the dust kicked up by the panicked horse adding a gritty , visceral realism to the sudden attack ."]
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ["eyes, is captured mid-leap, her powerful jaws clamped firmly onto Joffrey's arm. The prince's ornate crimson and gold velvet doublet is torn, and his polished leather boots kick frantically in the air. Nearby, a young Arya Stark, dressed in mud-splattered brown leather and rough linen, stands with a defiant, tear-streaked face, clutching a wooden stick. The ground is a mess of trampled emerald grass and damp river silt. Sunlight filters through the canopy of ancient, whispering trees, creating sharp contrasts of light and shadow. The atmosphere is thick with tension, the spray of river water and the dust kicked up by the panicked horse adding a gritty, visceral realism to the sudden attack."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["grey cobblestones . ned 's expression is shattered , eyes glistening with unshed tears as he leans close to the creature , his voice a silent whisper of apology . he wears a heavy , dark grey wool doublet with thick leather fastenings and a fur - lined cloak that clings to his broad shoulders . the atmosphere is oppressive and somber , lit by the pale , filtered light of a cloudy afternoon that casts soft , muted shadows across the scene . in the background , the towering red walls of the fortress loom , cold and indifferent . the air is thick with a sense of inevitable tragedy , capturing the precise moment of a father 's heartbreaking sacrifice ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["grey cobblestones . ned 's expression is shattered , eyes glistening with unshed tears as he leans close to the creature , his voice a silent whisper of apology . he wears a heavy , dark grey wool doublet with thick leather fastenings and a fur - lined cloak that clings to his broad shoulders . the atmosphere is oppressive and somber , lit by the pale , filtered light of a cloudy afternoon that casts soft , muted shadows across the scene . in the background , the towering red walls of the fortress loom , cold and indifferent . the air is thick with a sense of inevitable tragedy , capturing the precise moment of a father 's heartbreaking sacrifice ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["gently outstretched , touching the pup 's forehead as the creature leans in with curious trust . around them , the landscape is a stark wilderness of towering , frost - covered sentinel trees and a heavy , oppressive grey sky . the air is thick with a biting chill , visible as faint puffs of breath from both boy and wolf . soft , diffused winter light filters through the canopy , casting muted shadows across the pristine snow . the scene is one of quiet wonder and destiny , capturing the raw , gritty texture of the north , from the coarse weave of bran 's cloak to the wet , cold nose of the wolf ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["gently outstretched , touching the pup 's forehead as the creature leans in with curious trust . around them , the landscape is a stark wilderness of towering , frost - covered sentinel trees and a heavy , oppressive grey sky . the air is thick with a biting chill , visible as faint puffs of breath from both boy and wolf . soft , diffused winter light filters through the canopy , casting muted shadows across the pristine snow . the scene is one of quiet wonder and destiny , capturing the raw , gritty texture of the north , from the coarse weave of bran 's cloak to the wet , cold nose of the wolf ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["a silver direwolf brooch , and his weathered leather tunic shows the wear of the north . opposite him , the atmosphere is thick with accusation . the room is illuminated by a few flickering wall torches that cast long , dancing shadows across the rough - hewn granite walls and cold floor . dust motes dance in the orange light , highlighting the stark contrast between the shimmering , otherworldly metal of the blade and the gritty , muted tones of the room . ned 's brow is furrowed , his eyes piercing as he speaks of tyrion lannister , the air heavy with the weight of a betrayal that threatens the peace of his household ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["a silver direwolf brooch , and his weathered leather tunic shows the wear of the north . opposite him , the atmosphere is thick with accusation . the room is illuminated by a few flickering wall torches that cast long , dancing shadows across the rough - hewn granite walls and cold floor . dust motes dance in the orange light , highlighting the stark contrast between the shimmering , otherworldly metal of the blade and the gritty , muted tones of the room . ned 's brow is furrowed , his eyes piercing as he speaks of tyrion lannister , the air heavy with the weight of a betrayal that threatens the peace of his household ."]
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ["ilt, gripping it tightly as he presents the evidence. His heavy grey wool cloak is fastened with a silver direwolf brooch, and his weathered leather tunic shows the wear of the North. Opposite him, the atmosphere is thick with accusation. The room is illuminated by a few flickering wall torches that cast long, dancing shadows across the rough-hewn granite walls and cold floor. Dust motes dance in the orange light, highlighting the stark contrast between the shimmering, otherworldly metal of the blade and the gritty, muted tones of the room. Ned's brow is furrowed, his eyes piercing as he speaks of Tyrion Lannister, the air heavy with the weight of a betrayal that threatens the peace of his household."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['looking small and bony , stands sideways in a precise fencing stance , her face a mask of intense concentration and nervousness . she grips a heavy wooden practice sword — weighted with lead — in her left hand , her knuckles white . syrio is mid - motion , his hand adjusting the placement of her fingers on the hilt to ensure a perfect grip . the room is bathed in pale , dusty midday light filtering through high windows , casting long , soft shadows across the cold stone floor . arya wears simple , rough - spun linen clothes , slightly rumpled , contrasting with the disciplined , rhythmic atmosphere of the lethal dance .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['looking small and bony , stands sideways in a precise fencing stance , her face a mask of intense concentration and nervousness . she grips a heavy wooden practice sword — weighted with lead — in her left hand , her knuckles white . syrio is mid - motion , his hand adjusting the placement of her fingers on the hilt to ensure a perfect grip . the room is bathed in pale , dusty midday light filtering through high windows , casting long , soft shadows across the cold stone floor . arya wears simple , rough - spun linen clothes , slightly rumpled , contrasting with the disciplined , rhythmic atmosphere of the lethal dance .']
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ['a poised, fluid grace, his expression stern yet focused, as he guides Arya in the Water Dance. Arya, looking small and bony, stands sideways in a precise fencing stance, her face a mask of intense concentration and nervousness. She grips a heavy wooden practice sword—weighted with lead—in her left hand, her knuckles white. Syrio is mid-motion, his hand adjusting the placement of her fingers on the hilt to ensure a perfect grip. The room is bathed in pale, dusty midday light filtering through high windows, casting long, soft shadows across the cold stone floor. Arya wears simple, rough-spun linen clothes, slightly rumpled, contrasting with the disciplined, rhythmic atmosphere of the lethal dance.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["of gentle realization as she softly presses her fingers against daenerys 's lower abdomen . daenerys looks down at her own belly , her violet eyes shimmering with a mixture of shock and newfound strength , her lips parted in a silent , knowing breath . the surrounding landscape is an infinite horizon of waving green grasses that mimic the motion of ocean waves under a brilliant , searing sun . the lighting is golden and hazy , casting a soft glow over their skin and highlighting the intricate textures of the woven dothraki fabrics . the atmosphere is heavy with a sense of destiny and secret power , captured in a tender , hushed exchange amidst the wild openness of the plains ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["of gentle realization as she softly presses her fingers against daenerys 's lower abdomen . daenerys looks down at her own belly , her violet eyes shimmering with a mixture of shock and newfound strength , her lips parted in a silent , knowing breath . the surrounding landscape is an infinite horizon of waving green grasses that mimic the motion of ocean waves under a brilliant , searing sun . the lighting is golden and hazy , casting a soft glow over their skin and highlighting the intricate textures of the woven dothraki fabrics . the atmosphere is heavy with a sense of destiny and secret power , captured in a tender , hushed exchange amidst the wild openness of the plains ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', stained with the red dust of the plains , while viserys is clad in a faded , once - opulent silk tunic of pale gold , now frayed and soiled . around them , the khalasar watches in tense silence ; dothraki bloodriders on powerful horses loom in the background , their leather armor and bronze ornaments glinting . the scene is bathed in the harsh , oppressive glare of a midday sun , casting short , obsidian shadows across the parched earth . a swirling haze of golden dust clings to their clothes and hair , blurring the horizon of the vast , undulating grasslands , emphasizing the raw , gritty tension of a power shift .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', stained with the red dust of the plains , while viserys is clad in a faded , once - opulent silk tunic of pale gold , now frayed and soiled . around them , the khalasar watches in tense silence ; dothraki bloodriders on powerful horses loom in the background , their leather armor and bronze ornaments glinting . the scene is bathed in the harsh , oppressive glare of a midday sun , casting short , obsidian shadows across the parched earth . a swirling haze of golden dust clings to their clothes and hair , blurring the horizon of the vast , undulating grasslands , emphasizing the raw , gritty tension of a power shift .']
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ['a travel-worn Dothraki gown of rough-spun cream linen, stained with the red dust of the plains, while Viserys is clad in a faded, once-opulent silk tunic of pale gold, now frayed and soiled. Around them, the khalasar watches in tense silence; Dothraki bloodriders on powerful horses loom in the background, their leather armor and bronze ornaments glinting. The scene is bathed in the harsh, oppressive glare of a midday sun, casting short, obsidian shadows across the parched earth. A swirling haze of golden dust clings to their clothes and hair, blurring the horizon of the vast, undulating grasslands, emphasizing the raw, gritty tension of a power shift.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["he wears a coarse , oversized tunic of rough - spun grey wool and heavy , mud - caked leather boots that sink into the damp earth of winterfell . bran clings to him , his small hands gripping the rough fabric of hodor 's shoulder , his expression one of quiet trust . they move through a dim , stone corridor of the ancient fortress , where the air is thick with cold moisture . pale , wintry light filters through narrow arrow - slits , casting long , stark shadows across the uneven cobblestones . the atmosphere is somber and hushed , illuminated by the flickering , orange glow of a distant wall torch that highlights the gritty texture of the damp granite walls ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["he wears a coarse , oversized tunic of rough - spun grey wool and heavy , mud - caked leather boots that sink into the damp earth of winterfell . bran clings to him , his small hands gripping the rough fabric of hodor 's shoulder , his expression one of quiet trust . they move through a dim , stone corridor of the ancient fortress , where the air is thick with cold moisture . pale , wintry light filters through narrow arrow - slits , casting long , stark shadows across the uneven cobblestones . the atmosphere is somber and hushed , illuminated by the flickering , orange glow of a distant wall torch that highlights the gritty texture of the damp granite walls ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['. gendry , shirtless and glistening with perspiration , pauses mid - action , his powerful arms strained as he grips a heavy iron hammer . he looks toward eddard stark with sullen , brooding blue eyes , his jaw shadowed by a coarse , emerging beard . around them , the forge glows with an intense , oppressive orange heat , casting deep , flickering shadows against the soot - stained walls . other apprentices labor in the background , pumping massive leather bellows that breathe fire into the hearths . the lighting is a stark chiaroscuro , where the blinding white - hot glow of molten steel clashes with the oppressive darkness of the stone chamber , highlighting the grime and grit of the smithy .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['. gendry , shirtless and glistening with perspiration , pauses mid - action , his powerful arms strained as he grips a heavy iron hammer . he looks toward eddard stark with sullen , brooding blue eyes , his jaw shadowed by a coarse , emerging beard . around them , the forge glows with an intense , oppressive orange heat , casting deep , flickering shadows against the soot - stained walls . other apprentices labor in the background , pumping massive leather bellows that breathe fire into the hearths . the lighting is a stark chiaroscuro , where the blinding white - hot glow of molten steel clashes with the oppressive darkness of the stone chamber , highlighting the grime and grit of the smithy .']
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ['-black, unruly hair plastered to his forehead by sweat. Gendry, shirtless and glistening with perspiration, pauses mid-action, his powerful arms strained as he grips a heavy iron hammer. He looks toward Eddard Stark with sullen, brooding blue eyes, his jaw shadowed by a coarse, emerging beard. Around them, the forge glows with an intense, oppressive orange heat, casting deep, flickering shadows against the soot-stained walls. Other apprentices labor in the background, pumping massive leather bellows that breathe fire into the hearths. The lighting is a stark chiaroscuro, where the blinding white-hot glow of molten steel clashes with the oppressive darkness of the stone chamber, highlighting the grime and grit of the smithy.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["is soft - featured and overweight , his face wet with tears of desperation , dressed in fine but ill - fitting velvet doublets of house tarly . randyll ’ s expression is one of cold disgust and disappointment , his posture rigid as he forces his son toward a waiting escort . the room is dimly lit by flickering wall torches that cast long , oppressive shadows across the grey granite floors and heavy oak furniture . cold winter light filters through narrow slits in the masonry , illuminating dust motes in the air . the atmosphere is suffocating and cruel , capturing the moment of a father 's brutal rejection as he casts his son away to the wall ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["is soft - featured and overweight , his face wet with tears of desperation , dressed in fine but ill - fitting velvet doublets of house tarly . randyll ’ s expression is one of cold disgust and disappointment , his posture rigid as he forces his son toward a waiting escort . the room is dimly lit by flickering wall torches that cast long , oppressive shadows across the grey granite floors and heavy oak furniture . cold winter light filters through narrow slits in the masonry , illuminating dust motes in the air . the atmosphere is suffocating and cruel , capturing the moment of a father 's brutal rejection as he casts his son away to the wall ."]
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: [", Samwell Tarly, who is trembling and shrinking back in terror. Sam is soft-featured and overweight, his face wet with tears of desperation, dressed in fine but ill-fitting velvet doublets of House Tarly. Randyll’s expression is one of cold disgust and disappointment, his posture rigid as he forces his son toward a waiting escort. The room is dimly lit by flickering wall torches that cast long, oppressive shadows across the grey granite floors and heavy oak furniture. Cold winter light filters through narrow slits in the masonry, illuminating dust motes in the air. The atmosphere is suffocating and cruel, capturing the moment of a father's brutal rejection as he casts his son away to the Wall."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['blue silk , embroidered with delicate golden crescents , billows violently in the wind . his face is youthful and strikingly handsome , wearing a smirk of effortless confidence . around him , the tourney grounds are a chaos of churned brown earth and scattered straw . in the background , the blurred shapes of cheering crowds and colorful pavilions create a sense of scale . the lighting is a harsh , brilliant midday sun that creates sharp highlights on the steel and deep , dramatic shadows in the folds of his cloak , emphasizing the stark contrast between his pristine beauty and the gritty , dusty reality of the arena .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['blue silk , embroidered with delicate golden crescents , billows violently in the wind . his face is youthful and strikingly handsome , wearing a smirk of effortless confidence . around him , the tourney grounds are a chaos of churned brown earth and scattered straw . in the background , the blurred shapes of cheering crowds and colorful pavilions create a sense of scale . the lighting is a harsh , brilliant midday sun that creates sharp highlights on the steel and deep , dramatic shadows in the folds of his cloak , emphasizing the stark contrast between his pristine beauty and the gritty , dusty reality of the arena .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['by two burly guards . tyrion , small in stature with mismatched eyes and a scarred face , looks up with a mixture of shock and defiant amusement , his rich crimson velvet doublet rumpled and stained with spilled ale . around them , the common room is a chaos of overturned stools and startled peasants . the air is thick with the smell of roasting meat and damp wool . harsh , flickering orange light from a massive stone hearth casts long , dancing shadows across the timbered walls , while a cold , grey rain streaks the windowpanes , blurring the desolate landscape outside .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['by two burly guards . tyrion , small in stature with mismatched eyes and a scarred face , looks up with a mixture of shock and defiant amusement , his rich crimson velvet doublet rumpled and stained with spilled ale . around them , the common room is a chaos of overturned stools and startled peasants . the air is thick with the smell of roasting meat and damp wool . harsh , flickering orange light from a massive stone hearth casts long , dancing shadows across the timbered walls , while a cold , grey rain streaks the windowpanes , blurring the desolate landscape outside .']
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ['commanding finger at Tyrion Lannister, who is being violently hauled upward from a rough-hewn wooden table by two burly guards. Tyrion, small in stature with mismatched eyes and a scarred face, looks up with a mixture of shock and defiant amusement, his rich crimson velvet doublet rumpled and stained with spilled ale. Around them, the common room is a chaos of overturned stools and startled peasants. The air is thick with the smell of roasting meat and damp wool. Harsh, flickering orange light from a massive stone hearth casts long, dancing shadows across the timbered walls, while a cold, grey rain streaks the windowpanes, blurring the desolate landscape outside.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['wears a heavy , mud - splattered woolen cloak of deep grey over a sturdy travel dress , her auburn hair damp from the relentless drizzle . surrounding them , armored men - at - arms in weathered steel ringmail and boiled leather push the captives toward the jagged , towering peaks of the arryn mountains . the atmosphere is oppressive and bleak ; a thick , slate - grey mist clings to the steep cliffs , blurring the horizon . the lighting is a dim , diffused silver , casting soft , melancholy shadows across the wet stone and sodden earth , emphasizing the isolation and the growing tension of the kidnapping .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['wears a heavy , mud - splattered woolen cloak of deep grey over a sturdy travel dress , her auburn hair damp from the relentless drizzle . surrounding them , armored men - at - arms in weathered steel ringmail and boiled leather push the captives toward the jagged , towering peaks of the arryn mountains . the atmosphere is oppressive and bleak ; a thick , slate - grey mist clings to the steep cliffs , blurring the horizon . the lighting is a dim , diffused silver , casting soft , melancholy shadows across the wet stone and sodden earth , emphasizing the isolation and the growing tension of the kidnapping .']
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ['elyn Stark rides a powerful warhorse, her expression a mask of cold, unwavering determination. She wears a heavy, mud-splattered woolen cloak of deep grey over a sturdy travel dress, her auburn hair damp from the relentless drizzle. Surrounding them, armored men-at-arms in weathered steel ringmail and boiled leather push the captives toward the jagged, towering peaks of the Arryn mountains. The atmosphere is oppressive and bleak; a thick, slate-grey mist clings to the steep cliffs, blurring the horizon. The lighting is a dim, diffused silver, casting soft, melancholy shadows across the wet stone and sodden earth, emphasizing the isolation and the growing tension of the kidnapping.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["railing tightly , knuckles white , as she gazes down at the dizzying drop of the giant 's lance . around her , the air is thin and biting , with swirling mountain mists clinging to the jagged spires that pierce the sky like daggers . the lighting is a harsh , pale morning sun filtering through a veil of freezing fog , casting long , ghostly shadows across the courtyard below . the atmosphere is one of oppressive isolation and quiet tension , where the wind howls through the open arches , whipping her hair across a face marked by the grief and paranoia of a widow ruling a secluded kingdom ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["railing tightly , knuckles white , as she gazes down at the dizzying drop of the giant 's lance . around her , the air is thin and biting , with swirling mountain mists clinging to the jagged spires that pierce the sky like daggers . the lighting is a harsh , pale morning sun filtering through a veil of freezing fog , casting long , ghostly shadows across the courtyard below . the atmosphere is one of oppressive isolation and quiet tension , where the wind howls through the open arches , whipping her hair across a face marked by the grief and paranoia of a widow ruling a secluded kingdom ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['the hilt of a well - used steel longsword . opposite him , a knight of the vale in polished , interlocking steel ringmail and a heavy blue surcoat bristles with indignation . in the background , tyrion lannister watches with a mixture of anxiety and defiance , his small frame draped in a rich but travel - worn crimson velvet doublet . the architecture is cold and imposing , with towering white marble pillars and high vaulted ceilings . pale , wintry light filters through narrow slits in the stone , casting long , stark shadows across the polished floor , while the atmosphere is thick with the oppressive silence of the court and the scent of cold stone .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['the hilt of a well - used steel longsword . opposite him , a knight of the vale in polished , interlocking steel ringmail and a heavy blue surcoat bristles with indignation . in the background , tyrion lannister watches with a mixture of anxiety and defiance , his small frame draped in a rich but travel - worn crimson velvet doublet . the architecture is cold and imposing , with towering white marble pillars and high vaulted ceilings . pale , wintry light filters through narrow slits in the stone , casting long , stark shadows across the polished floor , while the atmosphere is thick with the oppressive silence of the court and the scent of cold stone .']
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ['s weathered, salt-stained boiled leather armor and a rough linen tunic, his hand gripping the hilt of a well-used steel longsword. Opposite him, a knight of the Vale in polished, interlocking steel ringmail and a heavy blue surcoat bristles with indignation. In the background, Tyrion Lannister watches with a mixture of anxiety and defiance, his small frame draped in a rich but travel-worn crimson velvet doublet. The architecture is cold and imposing, with towering white marble pillars and high vaulted ceilings. Pale, wintry light filters through narrow slits in the stone, casting long, stark shadows across the polished floor, while the atmosphere is thick with the oppressive silence of the court and the scent of cold stone.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['two conspirators . a few paces ahead , a portly man in a short , heavy leather cloak and a dull steel helmet leans in close to his companion . beside him stands a man with a distinctive , bifurcated yellow goatee , his expression cunning and low . the air is thick with moisture and the stench of decay . a single , flickering torch held by the men casts long , dancing shadows and a harsh orange glow that cuts through the suffocating darkness , highlighting the grime on their clothes and the tension in their hushed argument . the scene is a gritty tableau of secrecy , where the cold stone walls seem to close in around the hidden girl .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['two conspirators . a few paces ahead , a portly man in a short , heavy leather cloak and a dull steel helmet leans in close to his companion . beside him stands a man with a distinctive , bifurcated yellow goatee , his expression cunning and low . the air is thick with moisture and the stench of decay . a single , flickering torch held by the men casts long , dancing shadows and a harsh orange glow that cuts through the suffocating darkness , highlighting the grime on their clothes and the tension in their hushed argument . the scene is a gritty tableau of secrecy , where the cold stone walls seem to close in around the hidden girl .']
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ['of intense alertness, her wide eyes filled with fear and curiosity as she eavesdrops on two conspirators. A few paces ahead, a portly man in a short, heavy leather cloak and a dull steel helmet leans in close to his companion. Beside him stands a man with a distinctive, bifurcated yellow goatee, his expression cunning and low. The air is thick with moisture and the stench of decay. A single, flickering torch held by the men casts long, dancing shadows and a harsh orange glow that cuts through the suffocating darkness, highlighting the grime on their clothes and the tension in their hushed argument. The scene is a gritty tableau of secrecy, where the cold stone walls seem to close in around the hidden girl.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["smeared with grey stone dust . bronn is captured mid - action , gripping his longsword with both hands , driving the blade with his full body weight deep into the gap of the knight 's armpit , piercing the interlocking steel ringmail . the scene is thick with tension ; the air is cold and thin . high above , the pale , stark light of a mountain moon filters through the open architecture , casting long , harsh shadows across the pale stone floor . bronn wears weathered , blood - stained boiled leather and rough wool , his expression one of cold professionalism , contrasting with the wide - eyed terror and agony on ser vardis 's face ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["smeared with grey stone dust . bronn is captured mid - action , gripping his longsword with both hands , driving the blade with his full body weight deep into the gap of the knight 's armpit , piercing the interlocking steel ringmail . the scene is thick with tension ; the air is cold and thin . high above , the pale , stark light of a mountain moon filters through the open architecture , casting long , harsh shadows across the pale stone floor . bronn wears weathered , blood - stained boiled leather and rough wool , his expression one of cold professionalism , contrasting with the wide - eyed terror and agony on ser vardis 's face ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['thick cloak of sky - blue wool draped over his shoulders . opposite him , the small , battered figure of tyrion lannister stands defiant , his face bruised and swollen , wearing travel - worn crimson velvet and gold brocade that is stained with the grime of the dungeons . lady lysa arryn watches from her high throne of pale moonstone , her expression a mask of cold cruelty and twisted triumph . the hall is a cavern of white marble and soaring arches , illuminated by pale , wintry light filtering through high windows , casting long , stark shadows across the polished floor . the atmosphere is thick with hostility , the air cold and breathless as the court looks on in silence .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['thick cloak of sky - blue wool draped over his shoulders . opposite him , the small , battered figure of tyrion lannister stands defiant , his face bruised and swollen , wearing travel - worn crimson velvet and gold brocade that is stained with the grime of the dungeons . lady lysa arryn watches from her high throne of pale moonstone , her expression a mask of cold cruelty and twisted triumph . the hall is a cavern of white marble and soaring arches , illuminated by pale , wintry light filtering through high windows , casting long , stark shadows across the polished floor . the atmosphere is thick with hostility , the air cold and breathless as the court looks on in silence .']
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: [', etched with the falcon of House Arryn, with a thick cloak of sky-blue wool draped over his shoulders. Opposite him, the small, battered figure of Tyrion Lannister stands defiant, his face bruised and swollen, wearing travel-worn crimson velvet and gold brocade that is stained with the grime of the dungeons. Lady Lysa Arryn watches from her high throne of pale moonstone, her expression a mask of cold cruelty and twisted triumph. The hall is a cavern of white marble and soaring arches, illuminated by pale, wintry light filtering through high windows, casting long, stark shadows across the polished floor. The atmosphere is thick with hostility, the air cold and breathless as the court looks on in silence.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['grey wool doublet with a thick fur mantle draped over his shoulders , the fabric coarse and weathered . robert , bloated and flushed with rage , leans forward in his carved throne , his gold - embroidered crimson tunic strained . between them , the air is thick with tension . the room is illuminated by flickering orange torchlight that casts long , dancing shadows against the cold stone walls and towering tapestries . dust motes dance in the singular shafts of pale light filtering through high , narrow windows . the atmosphere is suffocating and grim , capturing the exact moment ned refuses to seal the death warrant of a young princess .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['grey wool doublet with a thick fur mantle draped over his shoulders , the fabric coarse and weathered . robert , bloated and flushed with rage , leans forward in his carved throne , his gold - embroidered crimson tunic strained . between them , the air is thick with tension . the room is illuminated by flickering orange torchlight that casts long , dancing shadows against the cold stone walls and towering tapestries . dust motes dance in the singular shafts of pale light filtering through high , narrow windows . the atmosphere is suffocating and grim , capturing the exact moment ned refuses to seal the death warrant of a young princess .']
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ['he stares down King Robert Baratheon. Ned wears a heavy, charcoal-grey wool doublet with a thick fur mantle draped over his shoulders, the fabric coarse and weathered. Robert, bloated and flushed with rage, leans forward in his carved throne, his gold-embroidered crimson tunic strained. Between them, the air is thick with tension. The room is illuminated by flickering orange torchlight that casts long, dancing shadows against the cold stone walls and towering tapestries. Dust motes dance in the singular shafts of pale light filtering through high, narrow windows. The atmosphere is suffocating and grim, capturing the exact moment Ned refuses to seal the death warrant of a young princess.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['a tunic of boiled leather and rough - spun linen . in the distance , the colossal , melted towers of harrenhal loom like blackened , twisted fingers against a pale , shimmering sky . the atmosphere is thick with the scent of damp earth and blooming wildflowers . soft , golden sunlight filters through a light haze , casting a nostalgic , ethereal glow over the landscape . ned ’ s expression is one of wide - eyed wonder and anticipation , his hand gripping the leather reins . the scene captures the transition from the cold north to the deceptive warmth of the south , blending the grit of medieval travel with the haunting , surreal beauty of a fever dream .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['a tunic of boiled leather and rough - spun linen . in the distance , the colossal , melted towers of harrenhal loom like blackened , twisted fingers against a pale , shimmering sky . the atmosphere is thick with the scent of damp earth and blooming wildflowers . soft , golden sunlight filters through a light haze , casting a nostalgic , ethereal glow over the landscape . ned ’ s expression is one of wide - eyed wonder and anticipation , his hand gripping the leather reins . the scene captures the transition from the cold north to the deceptive warmth of the south , blending the grit of medieval travel with the haunting , surreal beauty of a fever dream .']
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ['ak of charcoal wool fastened by a silver wolf-head brooch, over a tunic of boiled leather and rough-spun linen. In the distance, the colossal, melted towers of Harrenhal loom like blackened, twisted fingers against a pale, shimmering sky. The atmosphere is thick with the scent of damp earth and blooming wildflowers. Soft, golden sunlight filters through a light haze, casting a nostalgic, ethereal glow over the landscape. Ned’s expression is one of wide-eyed wonder and anticipation, his hand gripping the leather reins. The scene captures the transition from the cold North to the deceptive warmth of the south, blending the grit of medieval travel with the haunting, surreal beauty of a fever dream.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["legacy . he is mid - motion , fastening a wide , ornate belt crafted from heavy medallions of hammered gold , silver , and bronze over a painted leather vest . beside him , daenerys targaryen is propped up on one elbow atop a heap of rich , textured sleeping furs , her pale skin contrasting with the dark fabrics . her expression is one of yearning and intensity as she looks up at him , pleading for the conquest of the west . the atmosphere is charged with narrative tension ; drogo 's face is stern , his lips pursed beneath a long mustache , dismissing her talk of wooden horses . harsh chiaroscuro lighting casts long , dancing shadows against the canvas walls , emphasizing the raw power of the dothraki warlord ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["legacy . he is mid - motion , fastening a wide , ornate belt crafted from heavy medallions of hammered gold , silver , and bronze over a painted leather vest . beside him , daenerys targaryen is propped up on one elbow atop a heap of rich , textured sleeping furs , her pale skin contrasting with the dark fabrics . her expression is one of yearning and intensity as she looks up at him , pleading for the conquest of the west . the atmosphere is charged with narrative tension ; drogo 's face is stern , his lips pursed beneath a long mustache , dismissing her talk of wooden horses . harsh chiaroscuro lighting casts long , dancing shadows against the canvas walls , emphasizing the raw power of the dothraki warlord ."]
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ["heavy, uncut curtain past his waist, symbolizing his undefeated legacy. He is mid-motion, fastening a wide, ornate belt crafted from heavy medallions of hammered gold, silver, and bronze over a painted leather vest. Beside him, Daenerys Targaryen is propped up on one elbow atop a heap of rich, textured sleeping furs, her pale skin contrasting with the dark fabrics. Her expression is one of yearning and intensity as she looks up at him, pleading for the conquest of the West. The atmosphere is charged with narrative tension; Drogo's face is stern, his lips pursed beneath a long mustache, dismissing her talk of wooden horses. Harsh chiaroscuro lighting casts long, dancing shadows against the canvas walls, emphasizing the raw power of the Dothraki warlord."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["wool tunic , their expressions greedy and cruel . bran 's useless legs hang limp in the stirrups , his small hands frozen and trembling . the scene is set amidst a dense , oppressive forest where ancient , gnarled roots break through a thin , fresh layer of slushy snow . a heavy , grey mist clings to the towering pines , blurring the horizon . the lighting is dim and cold , with a pale , filtered winter light casting muted tones across the damp earth and mud - splattered boots of the attackers , creating an atmosphere of sudden , suffocating dread and vulnerability ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["wool tunic , their expressions greedy and cruel . bran 's useless legs hang limp in the stirrups , his small hands frozen and trembling . the scene is set amidst a dense , oppressive forest where ancient , gnarled roots break through a thin , fresh layer of slushy snow . a heavy , grey mist clings to the towering pines , blurring the horizon . the lighting is dim and cold , with a pale , filtered winter light casting muted tones across the damp earth and mud - splattered boots of the attackers , creating an atmosphere of sudden , suffocating dread and vulnerability ."]
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ["ly yanks at the horse's bridle, while another reaches up to tear at Bran's fine wool tunic, their expressions greedy and cruel. Bran's useless legs hang limp in the stirrups, his small hands frozen and trembling. The scene is set amidst a dense, oppressive forest where ancient, gnarled roots break through a thin, fresh layer of slushy snow. A heavy, grey mist clings to the towering pines, blurring the horizon. The lighting is dim and cold, with a pale, filtered winter light casting muted tones across the damp earth and mud-splattered boots of the attackers, creating an atmosphere of sudden, suffocating dread and vulnerability."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["knowing smile , delivers the humbling news of jon 's assignment . jon 's expression is one of quiet shock , his dark eyes wide and his jaw slightly slack as he realizes he has been relegated to a servant . in the background , the blurred figures of other recruits depart , while the blind maester aemon remains a ghostly , silent presence . the atmosphere is oppressive and damp , with grey light filtering through narrow slits in the thick granite walls . a single iron torch bracket casts flickering , orange light and long , dancing shadows across the floor , highlighting the gritty texture of the frost - covered stone and the stark , bleak reality of jon 's new life ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["knowing smile , delivers the humbling news of jon 's assignment . jon 's expression is one of quiet shock , his dark eyes wide and his jaw slightly slack as he realizes he has been relegated to a servant . in the background , the blurred figures of other recruits depart , while the blind maester aemon remains a ghostly , silent presence . the atmosphere is oppressive and damp , with grey light filtering through narrow slits in the thick granite walls . a single iron torch bracket casts flickering , orange light and long , dancing shadows across the floor , highlighting the gritty texture of the frost - covered stone and the stark , bleak reality of jon 's new life ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["caked hunting tunic of deep gold and crimson velvet , now torn and drenched in dark , visceral blood . the boar 's coarse , bristly black fur is matted with dirt and forest debris . they are surrounded by a claustrophobic woodland of gnarled oaks and damp ferns under a suffocating , grey overcast sky . shafts of pale , cold light filter through the canopy , illuminating the spray of blood and the churned - up earth beneath them . the atmosphere is heavy with the scent of pine and iron , capturing a moment of raw , violent desperation as the king collapses into the wet loam , his royal dignity shattered by the beast 's primal fury ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["caked hunting tunic of deep gold and crimson velvet , now torn and drenched in dark , visceral blood . the boar 's coarse , bristly black fur is matted with dirt and forest debris . they are surrounded by a claustrophobic woodland of gnarled oaks and damp ferns under a suffocating , grey overcast sky . shafts of pale , cold light filter through the canopy , illuminating the spray of blood and the churned - up earth beneath them . the atmosphere is heavy with the scent of pine and iron , capturing a moment of raw , violent desperation as the king collapses into the wet loam , his royal dignity shattered by the beast 's primal fury ."]
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ["and agony as a tusk rips deep into his abdomen. He wears a heavy, mud-caked hunting tunic of deep gold and crimson velvet, now torn and drenched in dark, visceral blood. The boar's coarse, bristly black fur is matted with dirt and forest debris. They are surrounded by a claustrophobic woodland of gnarled oaks and damp ferns under a suffocating, grey overcast sky. Shafts of pale, cold light filter through the canopy, illuminating the spray of blood and the churned-up earth beneath them. The atmosphere is heavy with the scent of pine and iron, capturing a moment of raw, violent desperation as the king collapses into the wet loam, his royal dignity shattered by the beast's primal fury."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['and moral agony , holds a piece of rough parchment across his knee . with a trembling hand , he grips a quill , the ink glistening black . the scene captures the precise moment of betrayal and love : ned is mid - stroke , carefully scratching the words " my heir " instead of " my son joffrey ." he wears a heavy , dark grey wool tunic with a fur mantle draped over his shoulders , the fabric coarse and worn . a single flickering candle on a nearby oak table casts long , dancing shadows and a harsh orange glow , highlighting the stark contrast between the king \'s decaying flesh and the cold , determined resolve in ned \'s eyes .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['and moral agony , holds a piece of rough parchment across his knee . with a trembling hand , he grips a quill , the ink glistening black . the scene captures the precise moment of betrayal and love : ned is mid - stroke , carefully scratching the words " my heir " instead of " my son joffrey ." he wears a heavy , dark grey wool tunic with a fur mantle draped over his shoulders , the fabric coarse and worn . a single flickering candle on a nearby oak table casts long , dancing shadows and a harsh orange glow , highlighting the stark contrast between the king \'s decaying flesh and the cold , determined resolve in ned \'s eyes .']
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ['rattling breaths. Ned, his face etched with profound grief and moral agony, holds a piece of rough parchment across his knee. With a trembling hand, he grips a quill, the ink glistening black. The scene captures the precise moment of betrayal and love: Ned is mid-stroke, carefully scratching the words "my heir" instead of "my son Joffrey." He wears a heavy, dark grey wool tunic with a fur mantle draped over his shoulders, the fabric coarse and worn. A single flickering candle on a nearby oak table casts long, dancing shadows and a harsh orange glow, highlighting the stark contrast between the king\'s decaying flesh and the cold, determined resolve in Ned\'s eyes.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['to the ground , mirroring the predatory stance of a mangy , one - eared black cat that arches its back and hisses at her from the shadows . the environment is a gritty labyrinth of grey limestone walls and oppressive architecture , with piles of refuse and damp moss clinging to the corners . harsh , slanted sunlight filters down from high ramparts , creating a stark contrast of blinding light and deep , ink - black shadows . the air is thick with the smell of salt and old stone . her hands are scarred with raw scratches and half - healed scabs , highlighting her desperation and the ruggedness of her secret training in the heart of the castle .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['to the ground , mirroring the predatory stance of a mangy , one - eared black cat that arches its back and hisses at her from the shadows . the environment is a gritty labyrinth of grey limestone walls and oppressive architecture , with piles of refuse and damp moss clinging to the corners . harsh , slanted sunlight filters down from high ramparts , creating a stark contrast of blinding light and deep , ink - black shadows . the air is thick with the smell of salt and old stone . her hands are scarred with raw scratches and half - healed scabs , highlighting her desperation and the ruggedness of her secret training in the heart of the castle .']
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ['concentration and fear. She is mid-stride, crouching low to the ground, mirroring the predatory stance of a mangy, one-eared black cat that arches its back and hisses at her from the shadows. The environment is a gritty labyrinth of grey limestone walls and oppressive architecture, with piles of refuse and damp moss clinging to the corners. Harsh, slanted sunlight filters down from high ramparts, creating a stark contrast of blinding light and deep, ink-black shadows. The air is thick with the smell of salt and old stone. Her hands are scarred with raw scratches and half-healed scabs, highlighting her desperation and the ruggedness of her secret training in the heart of the castle.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["stripped naked and trembling with terror , his limbs bound with rough hemp ropes to the back of a heavy wooden wagon . the wagon 's wheels churn through the dry , golden earth , kicking up clouds of grit . dothraki bloodriders on lean horses circle the procession , their curved arakhs gleaming under a harsh , oppressive sun . the atmosphere is thick with tension and the smell of sweat and dust . stark , high - contrast lighting creates deep shadows , emphasizing the raw muscles of the warriors and the desperate , strained muscles of the condemned man as he is dragged across the unforgiving terrain ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["stripped naked and trembling with terror , his limbs bound with rough hemp ropes to the back of a heavy wooden wagon . the wagon 's wheels churn through the dry , golden earth , kicking up clouds of grit . dothraki bloodriders on lean horses circle the procession , their curved arakhs gleaming under a harsh , oppressive sun . the atmosphere is thick with tension and the smell of sweat and dust . stark , high - contrast lighting creates deep shadows , emphasizing the raw muscles of the warriors and the desperate , strained muscles of the condemned man as he is dragged across the unforgiving terrain ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['wild hair , listen intently . robb wears a heavy cloak of grey wool fastened by a silver direwolf brooch , over a tunic of boiled leather and a gambeson of quilted linen . the karstarks are draped in massive , coarse furs of bear and wolf , their steel spear - tips glinting coldly . the atmosphere is heavy with the scent of wet earth and horse musk . a pale , wintry sun struggles to pierce through a slate - grey sky , casting a flat , oppressive light over the scene , while the distant sound of a deep war drum echoes against the ancient granite walls of the fortress .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['wild hair , listen intently . robb wears a heavy cloak of grey wool fastened by a silver direwolf brooch , over a tunic of boiled leather and a gambeson of quilted linen . the karstarks are draped in massive , coarse furs of bear and wolf , their steel spear - tips glinting coldly . the atmosphere is heavy with the scent of wet earth and horse musk . a pale , wintry sun struggles to pierce through a slate - grey sky , casting a flat , oppressive light over the scene , while the distant sound of a deep war drum echoes against the ancient granite walls of the fortress .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["studded oak gates that block the crossing . robb is clad in heavy , mud - splattered steel plate armor and a thick fur cloak that catches the damp wind . beside him , catelyn stark watches with a worried , piercing gaze , her velvet gown stained by the road . the atmosphere is oppressive and grey , with a churning , slate - colored river rushing violently beneath the towering stone bridge . a cold mist clings to the jagged fortifications , while the dim , overcast light casts deep shadows across the soldiers ' grim faces , emphasizing the suffocating tension of a diplomatic deadlock on the brink of war ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["studded oak gates that block the crossing . robb is clad in heavy , mud - splattered steel plate armor and a thick fur cloak that catches the damp wind . beside him , catelyn stark watches with a worried , piercing gaze , her velvet gown stained by the road . the atmosphere is oppressive and grey , with a churning , slate - colored river rushing violently beneath the towering stone bridge . a cold mist clings to the jagged fortifications , while the dim , overcast light casts deep shadows across the soldiers ' grim faces , emphasizing the suffocating tension of a diplomatic deadlock on the brink of war ."]
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ["appearing youthful yet burdened, gestures with a clenched fist toward the massive iron-studded oak gates that block the crossing. Robb is clad in heavy, mud-splattered steel plate armor and a thick fur cloak that catches the damp wind. Beside him, Catelyn Stark watches with a worried, piercing gaze, her velvet gown stained by the road. The atmosphere is oppressive and grey, with a churning, slate-colored river rushing violently beneath the towering stone bridge. A cold mist clings to the jagged fortifications, while the dim, overcast light casts deep shadows across the soldiers' grim faces, emphasizing the suffocating tension of a diplomatic deadlock on the brink of war."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['knees in the slushy snow . she wears rugged , interlocking furs and rough - hewn hides , her clothing stained with the grime of the wilderness . stark guards in iron - studded leather armor hold her arms firmly , their breath visible in the freezing air . around them , the ancient trees are draped in a thin shroud of white snow , their skeletal branches interlocking overhead . the lighting is a cold , oppressive grey , with a pale , wintry sun struggling to pierce through the thick canopy , casting soft , muted shadows across the frozen ground and highlighting the gritty texture of the mud and ice .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['knees in the slushy snow . she wears rugged , interlocking furs and rough - hewn hides , her clothing stained with the grime of the wilderness . stark guards in iron - studded leather armor hold her arms firmly , their breath visible in the freezing air . around them , the ancient trees are draped in a thin shroud of white snow , their skeletal branches interlocking overhead . the lighting is a cold , oppressive grey , with a pale , wintry sun struggling to pierce through the thick canopy , casting soft , muted shadows across the frozen ground and highlighting the gritty texture of the mud and ice .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["els in the dirt , his face weathered and exhausted , wearing a torn , grime - streaked linen tunic and heavy leather breeches . ned 's expression is one of grim acceptance , his eyes fixed forward . beside the throne , queen cersei and a weeping sansa stark are frozen in shock , their faces pale with desperation . a gold - cloaked guardsman stands poised with a heavy steel longsword , the blade reflecting the stark light . the atmosphere is thick with tension and the smell of dust and sweat , while the surrounding crowd is a blur of muted browns and greys , creating a sharp contrast with the royal gold and the impending violence ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["els in the dirt , his face weathered and exhausted , wearing a torn , grime - streaked linen tunic and heavy leather breeches . ned 's expression is one of grim acceptance , his eyes fixed forward . beside the throne , queen cersei and a weeping sansa stark are frozen in shock , their faces pale with desperation . a gold - cloaked guardsman stands poised with a heavy steel longsword , the blade reflecting the stark light . the atmosphere is thick with tension and the smell of dust and sweat , while the surrounding crowd is a blur of muted browns and greys , creating a sharp contrast with the royal gold and the impending violence ."]
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ["glints harshly under a blinding midday sun. Before him, Ned Stark kneels in the dirt, his face weathered and exhausted, wearing a torn, grime-streaked linen tunic and heavy leather breeches. Ned's expression is one of grim acceptance, his eyes fixed forward. Beside the throne, Queen Cersei and a weeping Sansa Stark are frozen in shock, their faces pale with desperation. A gold-cloaked guardsman stands poised with a heavy steel longsword, the blade reflecting the stark light. The atmosphere is thick with tension and the smell of dust and sweat, while the surrounding crowd is a blur of muted browns and greys, creating a sharp contrast with the royal gold and the impending violence."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['his lips before her expression hardens ; with a sudden , desperate motion , she grips a heavy fabric cushion and presses it firmly over his face to stifle his breath . she wears a sweat - stained , lightweight dothraki gown of pale silk that clings to her skin in the stifling air . drogo is clad in a weathered leather vest , his chest beneath it marked by a dried , crusty poultice of blue mud and fig leaves . the lighting is a harsh , blinding midday glare that creates shimmering heat waves across the horizon , while fat , reddish blood - flies buzz in oppressive circles around them , adding a visceral sense of decay to the silent , tragic scene .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['his lips before her expression hardens ; with a sudden , desperate motion , she grips a heavy fabric cushion and presses it firmly over his face to stifle his breath . she wears a sweat - stained , lightweight dothraki gown of pale silk that clings to her skin in the stifling air . drogo is clad in a weathered leather vest , his chest beneath it marked by a dried , crusty poultice of blue mud and fig leaves . the lighting is a harsh , blinding midday glare that creates shimmering heat waves across the horizon , while fat , reddish blood - flies buzz in oppressive circles around them , adding a visceral sense of decay to the silent , tragic scene .']
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ['former self. Daenerys presses a final, lingering kiss to his lips before her expression hardens; with a sudden, desperate motion, she grips a heavy fabric cushion and presses it firmly over his face to stifle his breath. She wears a sweat-stained, lightweight Dothraki gown of pale silk that clings to her skin in the stifling air. Drogo is clad in a weathered leather vest, his chest beneath it marked by a dried, crusty poultice of blue mud and fig leaves. The lighting is a harsh, blinding midday glare that creates shimmering heat waves across the horizon, while fat, reddish blood-flies buzz in oppressive circles around them, adding a visceral sense of decay to the silent, tragic scene.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['by his head amidst his long , braided hair , and the cream - and - gold egg placed between his legs . the air is thick with the scent of burning oil and scorched earth . as the towering inferno erupts , violent orange and crimson flames roar upward , swirling in a chaotic vortex of heat . daenerys steps into the heart of the fire , her skin glistening with oil , her simple linen gown catching fire . the lighting is a stark , blinding chiaroscuro of searing gold light and deep , soot - black shadows . the atmosphere is heavy with mystical tension , capturing the exact moment of a supernatural rebirth amidst the crackling roar of the pyre .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['by his head amidst his long , braided hair , and the cream - and - gold egg placed between his legs . the air is thick with the scent of burning oil and scorched earth . as the towering inferno erupts , violent orange and crimson flames roar upward , swirling in a chaotic vortex of heat . daenerys steps into the heart of the fire , her skin glistening with oil , her simple linen gown catching fire . the lighting is a stark , blinding chiaroscuro of searing gold light and deep , soot - black shadows . the atmosphere is heavy with mystical tension , capturing the exact moment of a supernatural rebirth amidst the crackling roar of the pyre .']
The following part of your input was truncated because `max_sequence_length` is set to  256 tokens: ['egg is pressed against his heart, the green egg nestled by his head amidst his long, braided hair, and the cream-and-gold egg placed between his legs. The air is thick with the scent of burning oil and scorched earth. As the towering inferno erupts, violent orange and crimson flames roar upward, swirling in a chaotic vortex of heat. Daenerys steps into the heart of the fire, her skin glistening with oil, her simple linen gown catching fire. The lighting is a stark, blinding chiaroscuro of searing gold light and deep, soot-black shadows. The atmosphere is heavy with mystical tension, capturing the exact moment of a supernatural rebirth amidst the crackling roar of the pyre.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', her knuckles white from gripping the cold masonry . her face is a mask of profound grief , eyes red - rimmed and brimming with tears , her expression flickering between utter despair and a haunting longing for release . the room is cluttered with untouched silver platters of food , casting dull reflections in the dim light . outside , the grey , forbidding walls of the red keep loom under a heavy , overcast sky . the atmosphere is suffocating and melancholic , lit only by the pale , filtered daylight of a winter afternoon , creating deep , moody shadows that emphasize her isolation and the crushing weight of her captivity .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', her knuckles white from gripping the cold masonry . her face is a mask of profound grief , eyes red - rimmed and brimming with tears , her expression flickering between utter despair and a haunting longing for release . the room is cluttered with untouched silver platters of food , casting dull reflections in the dim light . outside , the grey , forbidding walls of the red keep loom under a heavy , overcast sky . the atmosphere is suffocating and melancholic , lit only by the pale , filtered daylight of a winter afternoon , creating deep , moody shadows that emphasize her isolation and the crushing weight of her captivity .']

  0%|          | 0/28 [00:00<?, ?it/s]

Metadata guardado en: /content/drive/MyDrive/Proyecto NLP y DL/Imagen_Generacion/generated_images_sd3/sd3_medium/prueba_1013chars_sd3_inicial/metadata.json
Resumen: {'total_rows': 50, 'ok': 50, 'errors': 0, 'skipped_existing': 0}

================================================================================
Modelo: sd3_medium
Dataset: prueba_1960chars_sd3_conResumen.jsonl
Prompt column: prompt_sd3_large
max_sequence_length: 512
Output dir: /content/drive/MyDrive/Proyecto NLP y DL/Imagen_Generacion/generated_images_sd3/sd3_medium/prueba_1960chars_sd3_conResumen/images
================================================================================
Filas cargadas: 50

sd3_medium | prueba_1960chars_sd3_conResumen.jsonl:   0%|          | 0/50 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['of the worn pelt matted with frozen condensation . his face is a mask of stoic duty , though his eyes betray a flicker of heavy sorrow ; a slight furrow in his brow and a tight set to his jaw reveal the burden of the sentence he must carry out . before him kneels gared , the deserter . gared is a broken man , his salt - stained , tattered black wool cloak clinging to his shivering frame . his skin is a pallid , translucent grey , beaded with cold sweat and grime , his eyes wide with a primal , haunting terror that speaks of things seen beyond the wall . his breath emerges in jagged , frantic plumes of white steam . the tension is electric and suffocating . nearby , a young bran stark watches with wide , innocent eyes , his small hand clutching a thick wool tunic , while jon snow stands beside him , his expression stern , whispering a lesson on the necessity of looking upon death . theon greyjoy stands poised , his fingers gripping the hilt of ice — the massive greatsword of house stark . the blade is a terrifying marvel of valyrian steel , featuring smoky , rippling patterns etched into the dark metal , reflecting the dull , leaden sky . the lighting is oppressive and cold , a diffused , wintry luminescence that casts soft , smudge - like shadows across the frozen peat . the environment is framed by the skeletal , blackened branches of ancient weirwoods and jagged grey stones . as eddard raises the massive blade , the steel catches a sliver of pale light , creating a sharp , lethal contrast against the muted tones of the tundra . every detail is visceral : the crunch of frozen earth under boots , the metallic scent of the blade , and the heavy , rhythmic silence of the north .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['of the worn pelt matted with frozen condensation . his face is a mask of stoic duty , though his eyes betray a flicker of heavy sorrow ; a slight furrow in his brow and a tight set to his jaw reveal the burden of the sentence he must carry out . before him kneels gared , the deserter . gared is a broken man , his salt - stained , tattered black wool cloak clinging to his shivering frame . his skin is a pallid , translucent grey , beaded with cold sweat and grime , his eyes wide with a primal , haunting terror that speaks of things seen beyond the wall . his breath emerges in jagged , frantic plumes of white steam . the tension is electric and suffocating . nearby , a young bran stark watches with wide , innocent eyes , his small hand clutching a thick wool tunic , while jon snow stands beside him , his expression stern , whispering a lesson on the necessity of looking upon death . theon greyjoy stands poised , his fingers gripping the hilt of ice — the massive greatsword of house stark . the blade is a terrifying marvel of valyrian steel , featuring smoky , rippling patterns etched into the dark metal , reflecting the dull , leaden sky . the lighting is oppressive and cold , a diffused , wintry luminescence that casts soft , smudge - like shadows across the frozen peat . the environment is framed by the skeletal , blackened branches of ancient weirwoods and jagged grey stones . as eddard raises the massive blade , the steel catches a sliver of pale light , creating a sharp , lethal contrast against the muted tones of the tundra . every detail is visceral : the crunch of frozen earth under boots , the metallic scent of the blade , and the heavy , rhythmic silence of the north .']
[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (543 > 512). Running this sequence through the model will result in indexing errors
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ['d in heavy, charcoal-grey furs and boiled leather, the texture of the worn pelt matted with frozen condensation. His face is a mask of stoic duty, though his eyes betray a flicker of heavy sorrow; a slight furrow in his brow and a tight set to his jaw reveal the burden of the sentence he must carry out. Before him kneels Gared, the deserter. Gared is a broken man, his salt-stained, tattered black wool cloak clinging to his shivering frame. His skin is a pallid, translucent grey, beaded with cold sweat and grime, his eyes wide with a primal, haunting terror that speaks of things seen beyond the Wall. His breath emerges in jagged, frantic plumes of white steam. The tension is electric and suffocating. Nearby, a young Bran Stark watches with wide, innocent eyes, his small hand clutching a thick wool tunic, while Jon Snow stands beside him, his expression stern, whispering a lesson on the necessity of looking upon death. Theon Greyjoy stands poised, his fingers gripping the hilt of Ice—the massive greatsword of House Stark. The blade is a terrifying marvel of Valyrian steel, featuring smoky, rippling patterns etched into the dark metal, reflecting the dull, leaden sky. The lighting is oppressive and cold, a diffused, wintry luminescence that casts soft, smudge-like shadows across the frozen peat. The environment is framed by the skeletal, blackened branches of ancient weirwoods and jagged grey stones. As Eddard raises the massive blade, the steel catches a sliver of pale light, creating a sharp, lethal contrast against the muted tones of the tundra. Every detail is visceral: the crunch of frozen earth under boots, the metallic scent of the blade, and the heavy, rhythmic silence of the North.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["a nearby pony , her massive ribcage heaving one last time in a frozen stillness . embedded deep within her throat is a jagged , towering set of antlers , the bone bleached and splintered , locking her in a permanent , silent scream of agony . surrounding the beast are the stark children , their small figures dwarfed by the scale of the tragedy . robb stark , his face tight with a mixture of grief and protective instinct , cradles a tiny , shivering direwolf pup in his calloused hands , the pup 's fur a soft , smoky grey against the rough , salt - stained wool of robb 's heavy winter cloak . beside him , bran stands frozen , his wide eyes reflecting the horror and wonder of the scene , his small hand reaching out toward the mother 's coarse , frozen pelt . jon snow stands slightly apart , his expression brooding and observant , his dark eyes scanning the perimeter of the snowy clearing . the lighting is a harsh , oppressive winter grey ; a pale , filtered sun struggles to pierce through a thick veil of slate - colored clouds , casting soft , diffused shadows that blur the line between the white earth and the grey sky . tiny ice crystals dance in the frigid air , clinging to the children 's eyelashes and the woolen fibers of their tunics . the texture of the scene is visceral : the wet , glistening blood soaking into the porous snow , the rough grain of the antlers , and the contrast between the massive , cold corpse and the fragile , warm breath of the five tiny pups huddling together in a desperate pile of fur and whimpers . the atmosphere is heavy with the scent of iron and old frost , capturing a pivotal moment of innocence meeting the brutal reality of the north ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["a nearby pony , her massive ribcage heaving one last time in a frozen stillness . embedded deep within her throat is a jagged , towering set of antlers , the bone bleached and splintered , locking her in a permanent , silent scream of agony . surrounding the beast are the stark children , their small figures dwarfed by the scale of the tragedy . robb stark , his face tight with a mixture of grief and protective instinct , cradles a tiny , shivering direwolf pup in his calloused hands , the pup 's fur a soft , smoky grey against the rough , salt - stained wool of robb 's heavy winter cloak . beside him , bran stands frozen , his wide eyes reflecting the horror and wonder of the scene , his small hand reaching out toward the mother 's coarse , frozen pelt . jon snow stands slightly apart , his expression brooding and observant , his dark eyes scanning the perimeter of the snowy clearing . the lighting is a harsh , oppressive winter grey ; a pale , filtered sun struggles to pierce through a thick veil of slate - colored clouds , casting soft , diffused shadows that blur the line between the white earth and the grey sky . tiny ice crystals dance in the frigid air , clinging to the children 's eyelashes and the woolen fibers of their tunics . the texture of the scene is visceral : the wet , glistening blood soaking into the porous snow , the rough grain of the antlers , and the contrast between the massive , cold corpse and the fragile , warm breath of the five tiny pups huddling together in a desperate pile of fur and whimpers . the atmosphere is heavy with the scent of iron and old frost , capturing a pivotal moment of innocence meeting the brutal reality of the north ."]
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ["crimson blood. The wolf is monstrous in scale, dwarfing a nearby pony, her massive ribcage heaving one last time in a frozen stillness. Embedded deep within her throat is a jagged, towering set of antlers, the bone bleached and splintered, locking her in a permanent, silent scream of agony. Surrounding the beast are the Stark children, their small figures dwarfed by the scale of the tragedy. Robb Stark, his face tight with a mixture of grief and protective instinct, cradles a tiny, shivering direwolf pup in his calloused hands, the pup's fur a soft, smoky grey against the rough, salt-stained wool of Robb's heavy winter cloak. Beside him, Bran stands frozen, his wide eyes reflecting the horror and wonder of the scene, his small hand reaching out toward the mother's coarse, frozen pelt. Jon Snow stands slightly apart, his expression brooding and observant, his dark eyes scanning the perimeter of the snowy clearing. The lighting is a harsh, oppressive winter grey; a pale, filtered sun struggles to pierce through a thick veil of slate-colored clouds, casting soft, diffused shadows that blur the line between the white earth and the grey sky. Tiny ice crystals dance in the frigid air, clinging to the children's eyelashes and the woolen fibers of their tunics. The texture of the scene is visceral: the wet, glistening blood soaking into the porous snow, the rough grain of the antlers, and the contrast between the massive, cold corpse and the fragile, warm breath of the five tiny pups huddling together in a desperate pile of fur and whimpers. The atmosphere is heavy with the scent of iron and old frost, capturing a pivotal moment of innocence meeting the brutal reality of the North."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["by a pale , dying winter sun that casts long , ghostly blue shadows across the jagged , snow - covered terrain . robb stark , his face hardened by the sudden weight of leadership , cradles a small , shivering direwolf pup in his calloused hands . his fingers are red from the cold , gripping the pup 's thick , charcoal - colored fur . he is leaning toward bran , whose wide , innocent eyes are filled with a mixture of terror and wonder . bran ’ s breath forms thick white plumes in the freezing air , his small frame wrapped in heavy , salt - stained wool and thick furs that look coarse and heavy . beside them , jon snow stands slightly apart , his posture guarded , his dark eyes scanning the perimeter . his expression is one of quiet realization as he discovers the sixth pup , hidden beneath the flank of the dead mother . the pup is smaller , a ghostly white , its tiny claws digging into the frozen earth . the tension is palpable ; the contrast between the warmth of the pups and the lethal cold of the environment creates a visceral struggle for survival . the dead mother wolf lies in a gruesome heap , a massive , jagged antler protruding violently from her throat , the wound frozen in a crust of crimson ice . the texture of the antler is porous and weathered , contrasting with the sleek , blood - stained fur of the beast . in the background , theon greyjoy stands with a smirk of disdain , his hand resting on the hilt of a polished steel blade , his leather armor glistening with a thin layer of frost . the surrounding forest consists of towering , skeletal ironwood trees , their black bark peeling like burnt skin against the blinding white of the tundra ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["by a pale , dying winter sun that casts long , ghostly blue shadows across the jagged , snow - covered terrain . robb stark , his face hardened by the sudden weight of leadership , cradles a small , shivering direwolf pup in his calloused hands . his fingers are red from the cold , gripping the pup 's thick , charcoal - colored fur . he is leaning toward bran , whose wide , innocent eyes are filled with a mixture of terror and wonder . bran ’ s breath forms thick white plumes in the freezing air , his small frame wrapped in heavy , salt - stained wool and thick furs that look coarse and heavy . beside them , jon snow stands slightly apart , his posture guarded , his dark eyes scanning the perimeter . his expression is one of quiet realization as he discovers the sixth pup , hidden beneath the flank of the dead mother . the pup is smaller , a ghostly white , its tiny claws digging into the frozen earth . the tension is palpable ; the contrast between the warmth of the pups and the lethal cold of the environment creates a visceral struggle for survival . the dead mother wolf lies in a gruesome heap , a massive , jagged antler protruding violently from her throat , the wound frozen in a crust of crimson ice . the texture of the antler is porous and weathered , contrasting with the sleek , blood - stained fur of the beast . in the background , theon greyjoy stands with a smirk of disdain , his hand resting on the hilt of a polished steel blade , his leather armor glistening with a thin layer of frost . the surrounding forest consists of towering , skeletal ironwood trees , their black bark peeling like burnt skin against the blinding white of the tundra ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["ted and coarse , his eyes bloodshot yet gleaming with a desperate , nostalgic intensity . he is draped in heavy , gold - trimmed furs that seem to swallow his frame , the rich velvets stained with droplets of spilled arbor gold . opposite him , ned stark stands as a pillar of frozen granite . his posture is rigid , his grey eyes clouded with a mixture of loyalty and profound dread . a single bead of sweat tracks down his temple , contrasting with the pale , weathered skin of his face . he wears a heavy cloak of charcoal wool fastened by a silver direwolf brooch , the metal cold and matte . between them sits a massive oak table , its surface scarred by centuries of use , holding a heavy iron flagon and two mismatched goblets . the lighting is dramatic and oppressive ; a violent orange glow from the hearth casts long , dancing shadows that stretch across the rough - hewn stone walls , while a sliver of pale , wintry moonlight pierces through a narrow slit window , illuminating the swirling dust motes in the air . robert ’ s hand , thick - fingered and adorned with a heavy gold signet ring , slams onto the table , vibrating the wood . his expression is a raw plea , his mouth slightly agape , capturing the moment he demands ned become the hand of the king . the tension is palpable , a silent war between the king 's chaotic desire and the warden of the north 's stoic reluctance . in the background , the gothic arches of the room fade into a suffocating darkness , emphasizing the claustrophobic weight of the crown 's request . every texture is visceral : the coarse weave of the tapestries , the cold dampness of the stone floor , and the shimmering , oily reflection of the wine in the cup ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["ted and coarse , his eyes bloodshot yet gleaming with a desperate , nostalgic intensity . he is draped in heavy , gold - trimmed furs that seem to swallow his frame , the rich velvets stained with droplets of spilled arbor gold . opposite him , ned stark stands as a pillar of frozen granite . his posture is rigid , his grey eyes clouded with a mixture of loyalty and profound dread . a single bead of sweat tracks down his temple , contrasting with the pale , weathered skin of his face . he wears a heavy cloak of charcoal wool fastened by a silver direwolf brooch , the metal cold and matte . between them sits a massive oak table , its surface scarred by centuries of use , holding a heavy iron flagon and two mismatched goblets . the lighting is dramatic and oppressive ; a violent orange glow from the hearth casts long , dancing shadows that stretch across the rough - hewn stone walls , while a sliver of pale , wintry moonlight pierces through a narrow slit window , illuminating the swirling dust motes in the air . robert ’ s hand , thick - fingered and adorned with a heavy gold signet ring , slams onto the table , vibrating the wood . his expression is a raw plea , his mouth slightly agape , capturing the moment he demands ned become the hand of the king . the tension is palpable , a silent war between the king 's chaotic desire and the warden of the north 's stoic reluctance . in the background , the gothic arches of the room fade into a suffocating darkness , emphasizing the claustrophobic weight of the crown 's request . every texture is visceral : the coarse weave of the tapestries , the cold dampness of the stone floor , and the shimmering , oily reflection of the wine in the cup ."]
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ["deep, boozy crimson, his beard matted and coarse, his eyes bloodshot yet gleaming with a desperate, nostalgic intensity. He is draped in heavy, gold-trimmed furs that seem to swallow his frame, the rich velvets stained with droplets of spilled Arbor gold. Opposite him, Ned Stark stands as a pillar of frozen granite. His posture is rigid, his grey eyes clouded with a mixture of loyalty and profound dread. A single bead of sweat tracks down his temple, contrasting with the pale, weathered skin of his face. He wears a heavy cloak of charcoal wool fastened by a silver direwolf brooch, the metal cold and matte. Between them sits a massive oak table, its surface scarred by centuries of use, holding a heavy iron flagon and two mismatched goblets. The lighting is dramatic and oppressive; a violent orange glow from the hearth casts long, dancing shadows that stretch across the rough-hewn stone walls, while a sliver of pale, wintry moonlight pierces through a narrow slit window, illuminating the swirling dust motes in the air. Robert’s hand, thick-fingered and adorned with a heavy gold signet ring, slams onto the table, vibrating the wood. His expression is a raw plea, his mouth slightly agape, capturing the moment he demands Ned become the Hand of the King. The tension is palpable, a silent war between the King's chaotic desire and the Warden of the North's stoic reluctance. In the background, the Gothic arches of the room fade into a suffocating darkness, emphasizing the claustrophobic weight of the crown's request. Every texture is visceral: the coarse weave of the tapestries, the cold dampness of the stone floor, and the shimmering, oily reflection of the wine in the cup."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["tension . robert ’ s posture is slumped , his heavy velvet doublet stained with the grime of the road , his breathing audible in the stillness . he gazes down at the stone effigy of lyanna stark , his eyes glistening with a mixture of raw longing and a ghost of a smile . the lighting is stark and moody ; a few flickering torches cast dancing , amber light against the deep , obsidian shadows of the vaulted ceiling , creating violent contrasts that carve deep lines into the men 's weathered faces . the torchlight glints off the polished , cold marble of lyanna ’ s statue , highlighting the delicate , frozen curve of her cheek and the intricate , motionless folds of her stone gown . ned stands slightly behind the king , his shoulders rigid , his hands clasped tightly behind his back . his expression is one of quiet endurance , a micro - twitch of the jaw betraying the pain of reopened wounds . the texture of the scene is visceral : the rough , salt - stained wool of ned 's cloak , the sweat - beaded skin on robert 's forehead despite the chill , and the ancient , porous limestone of the crypts , slick with condensation . dust motes dance in the narrow shafts of orange light . the atmosphere is heavy with the weight of dead years and unspoken secrets . robert reaches out , his calloused finger almost touching the cold stone of the statue ’ s hand , the contrast between his living , flushed skin and the pale , lifeless marble emphasizing the permanence of loss . the surrounding darkness of the crypts feels like a physical presence , pressing in on them , isolating the two men in a sanctuary of grief and memory ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["tension . robert ’ s posture is slumped , his heavy velvet doublet stained with the grime of the road , his breathing audible in the stillness . he gazes down at the stone effigy of lyanna stark , his eyes glistening with a mixture of raw longing and a ghost of a smile . the lighting is stark and moody ; a few flickering torches cast dancing , amber light against the deep , obsidian shadows of the vaulted ceiling , creating violent contrasts that carve deep lines into the men 's weathered faces . the torchlight glints off the polished , cold marble of lyanna ’ s statue , highlighting the delicate , frozen curve of her cheek and the intricate , motionless folds of her stone gown . ned stands slightly behind the king , his shoulders rigid , his hands clasped tightly behind his back . his expression is one of quiet endurance , a micro - twitch of the jaw betraying the pain of reopened wounds . the texture of the scene is visceral : the rough , salt - stained wool of ned 's cloak , the sweat - beaded skin on robert 's forehead despite the chill , and the ancient , porous limestone of the crypts , slick with condensation . dust motes dance in the narrow shafts of orange light . the atmosphere is heavy with the weight of dead years and unspoken secrets . robert reaches out , his calloused finger almost touching the cold stone of the statue ’ s hand , the contrast between his living , flushed skin and the pale , lifeless marble emphasizing the permanence of loss . the surrounding darkness of the crypts feels like a physical presence , pressing in on them , isolating the two men in a sanctuary of grief and memory ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["olith of a man . he is an exiled knight , his presence a jarring contrast of westerosi nobility and dothraki ruggedness . he wears a travel - worn tunic of coarse , salt - stained linen and a heavy leather brigandine scarred by years of desert grit . his skin is leathered and bronze from the essosi sun , with deep - set eyes reflecting a mixture of weary melancholy and sudden , piercing intrigue . opposite him stands the young daenerys targaryen , fragile and trembling , her pale skin almost translucent against the vibrant silks of her gown . her eyes are rimmed with red from recent tears , her small shoulders hunched in a posture of profound vulnerability . beside her , viserys targaryen looms , his expression a mask of arrogant desperation , his fingers twitching with a nervous , predatory energy . the tension is palpable , a silent electric current between the exiled knight and the frightened princess . jorah ’ s posture is respectful yet observant , his gaze lingering on daenerys with a protective instinct he doesn 't yet understand . in the background , the imposing figure of khal drogo stands like a bronze panther , his long , unbroken braid draped over a shoulder of corded muscle , his dark eyes scanning the room with predatory indifference . the architecture is a blend of gothic grandeur and eastern decadence : towering marble columns etched with swirling floral motifs , polished mosaic floors reflecting the violent amber glow of the afternoon sun , and heavy velvet draperies in deep crimson that cast long , jagged shadows across the scene . every texture is vivid : the cold smoothness of the marble , the rough grain of jorah 's leather gear , and the shimmering , iridescent quality of the targaryen silks ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["olith of a man . he is an exiled knight , his presence a jarring contrast of westerosi nobility and dothraki ruggedness . he wears a travel - worn tunic of coarse , salt - stained linen and a heavy leather brigandine scarred by years of desert grit . his skin is leathered and bronze from the essosi sun , with deep - set eyes reflecting a mixture of weary melancholy and sudden , piercing intrigue . opposite him stands the young daenerys targaryen , fragile and trembling , her pale skin almost translucent against the vibrant silks of her gown . her eyes are rimmed with red from recent tears , her small shoulders hunched in a posture of profound vulnerability . beside her , viserys targaryen looms , his expression a mask of arrogant desperation , his fingers twitching with a nervous , predatory energy . the tension is palpable , a silent electric current between the exiled knight and the frightened princess . jorah ’ s posture is respectful yet observant , his gaze lingering on daenerys with a protective instinct he doesn 't yet understand . in the background , the imposing figure of khal drogo stands like a bronze panther , his long , unbroken braid draped over a shoulder of corded muscle , his dark eyes scanning the room with predatory indifference . the architecture is a blend of gothic grandeur and eastern decadence : towering marble columns etched with swirling floral motifs , polished mosaic floors reflecting the violent amber glow of the afternoon sun , and heavy velvet draperies in deep crimson that cast long , jagged shadows across the scene . every texture is vivid : the cold smoothness of the marble , the rough grain of jorah 's leather gear , and the shimmering , iridescent quality of the targaryen silks ."]
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ["frame, Ser Jorah Mormont stands as a weathered monolith of a man. He is an exiled knight, his presence a jarring contrast of Westerosi nobility and Dothraki ruggedness. He wears a travel-worn tunic of coarse, salt-stained linen and a heavy leather brigandine scarred by years of desert grit. His skin is leathered and bronze from the Essosi sun, with deep-set eyes reflecting a mixture of weary melancholy and sudden, piercing intrigue. Opposite him stands the young Daenerys Targaryen, fragile and trembling, her pale skin almost translucent against the vibrant silks of her gown. Her eyes are rimmed with red from recent tears, her small shoulders hunched in a posture of profound vulnerability. Beside her, Viserys Targaryen looms, his expression a mask of arrogant desperation, his fingers twitching with a nervous, predatory energy. The tension is palpable, a silent electric current between the exiled knight and the frightened princess. Jorah’s posture is respectful yet observant, his gaze lingering on Daenerys with a protective instinct he doesn't yet understand. In the background, the imposing figure of Khal Drogo stands like a bronze panther, his long, unbroken braid draped over a shoulder of corded muscle, his dark eyes scanning the room with predatory indifference. The architecture is a blend of Gothic grandeur and Eastern decadence: towering marble columns etched with swirling floral motifs, polished mosaic floors reflecting the violent amber glow of the afternoon sun, and heavy velvet draperies in deep crimson that cast long, jagged shadows across the scene. Every texture is vivid: the cold smoothness of the marble, the rough grain of Jorah's leather gear, and the shimmering, iridescent quality of the Targaryen silks."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["blue moonlight filtering through high , narrow slits in the stone walls , creating deep , oppressive shadows . in the foreground , jon snow sits far removed from the nobility , positioned among the squires and servants at a long , rough - hewn trestle table . his posture is a mix of isolation and quiet relief ; he leans back slightly , a pewter tankard of dark ale gripped in a calloused hand . his face is etched with a subtle , melancholic detachment , his dark eyes scanning the room with a piercing , observant intensity . he wears a heavy , charcoal - grey wool tunic with a coarse , salt - stained leather jerkin , the fabric pilling at the shoulders . in the blurred mid - ground , the high table is a tableau of tension . king robert is a mountain of a man , his face flushed a violent crimson from wine , his gold - threaded velvet doublet strained across a bloated chest . beside him , queen cersei sits with a rigid , porcelain posture , her lips curled into a thin , artificial smile that doesn 't reach her cold , emerald eyes . prince joffrey exudes a sneering arrogance , his golden curls shimmering under the torchlight , while jaime lannister leans back with a predatory , effortless grace , his golden armor reflecting the firelight in sharp , blinding glints . the environment is rich with texture : the grease - slicked surfaces of the wooden tables , the heavy furs draped over stone benches , and the distant , echoing roar of a hundred voices . the air is hazy with smoke from the central hearth , blurring the edges of the gothic arches and emphasizing the suffocating social divide between the royal blood and the bastard in the shadows ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["blue moonlight filtering through high , narrow slits in the stone walls , creating deep , oppressive shadows . in the foreground , jon snow sits far removed from the nobility , positioned among the squires and servants at a long , rough - hewn trestle table . his posture is a mix of isolation and quiet relief ; he leans back slightly , a pewter tankard of dark ale gripped in a calloused hand . his face is etched with a subtle , melancholic detachment , his dark eyes scanning the room with a piercing , observant intensity . he wears a heavy , charcoal - grey wool tunic with a coarse , salt - stained leather jerkin , the fabric pilling at the shoulders . in the blurred mid - ground , the high table is a tableau of tension . king robert is a mountain of a man , his face flushed a violent crimson from wine , his gold - threaded velvet doublet strained across a bloated chest . beside him , queen cersei sits with a rigid , porcelain posture , her lips curled into a thin , artificial smile that doesn 't reach her cold , emerald eyes . prince joffrey exudes a sneering arrogance , his golden curls shimmering under the torchlight , while jaime lannister leans back with a predatory , effortless grace , his golden armor reflecting the firelight in sharp , blinding glints . the environment is rich with texture : the grease - slicked surfaces of the wooden tables , the heavy furs draped over stone benches , and the distant , echoing roar of a hundred voices . the air is hazy with smoke from the central hearth , blurring the edges of the gothic arches and emphasizing the suffocating social divide between the royal blood and the bastard in the shadows ."]
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ["ering orange torchlight and the cold, pale blue moonlight filtering through high, narrow slits in the stone walls, creating deep, oppressive shadows. In the foreground, Jon Snow sits far removed from the nobility, positioned among the squires and servants at a long, rough-hewn trestle table. His posture is a mix of isolation and quiet relief; he leans back slightly, a pewter tankard of dark ale gripped in a calloused hand. His face is etched with a subtle, melancholic detachment, his dark eyes scanning the room with a piercing, observant intensity. He wears a heavy, charcoal-grey wool tunic with a coarse, salt-stained leather jerkin, the fabric pilling at the shoulders. In the blurred mid-ground, the high table is a tableau of tension. King Robert is a mountain of a man, his face flushed a violent crimson from wine, his gold-threaded velvet doublet strained across a bloated chest. Beside him, Queen Cersei sits with a rigid, porcelain posture, her lips curled into a thin, artificial smile that doesn't reach her cold, emerald eyes. Prince Joffrey exudes a sneering arrogance, his golden curls shimmering under the torchlight, while Jaime Lannister leans back with a predatory, effortless grace, his golden armor reflecting the firelight in sharp, blinding glints. The environment is rich with texture: the grease-slicked surfaces of the wooden tables, the heavy furs draped over stone benches, and the distant, echoing roar of a hundred voices. The air is hazy with smoke from the central hearth, blurring the edges of the Gothic arches and emphasizing the suffocating social divide between the royal blood and the bastard in the shadows."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["— a secret language shared only between sisters . her eyes , wide with a mixture of dread and sudden clarity , scan the jagged ink strokes . the revelation is a poison : lysa arryn , her sister , claims that jon arryn did not die of natural causes , but was murdered by the queen and the lannisters . catelyn ’ s face is a mask of pale tension ; a single bead of sweat clings to her temple despite the cold . her posture is rigid , her shoulders hunched as if shielding the secret from the very walls . beside her , the flickering orange glow of a dying hearth casts long , dancing shadows that stretch across the rough - hewn stone floor and the heavy , dark oak furniture . the lighting is moody and oppressive , with deep amber highlights clashing against the cold , blue moonlight filtering through a narrow slit window . the textures are visceral : the coarse , salt - stained wool of catelyn 's heavy gown , the grainy texture of the ancient parchment , and the glint of a silver seal partially melted . in the background , the gothic architecture of the keep looms , with heavy vaulted ceilings and iron sconces that drip black soot . the atmosphere is heavy with an invisible weight , the silent scream of a political conspiracy that threatens to ignite a war . every line of catelyn 's expression conveys a desperate urgency ; her lips are parted , her breath visible in the freezing air , as she realizes that eddard must travel to king 's landing to uncover a truth that could destroy them all . the scene is a study in intimacy and impending doom , capturing the exact moment a private letter transforms into a catalyst for continental chaos ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["— a secret language shared only between sisters . her eyes , wide with a mixture of dread and sudden clarity , scan the jagged ink strokes . the revelation is a poison : lysa arryn , her sister , claims that jon arryn did not die of natural causes , but was murdered by the queen and the lannisters . catelyn ’ s face is a mask of pale tension ; a single bead of sweat clings to her temple despite the cold . her posture is rigid , her shoulders hunched as if shielding the secret from the very walls . beside her , the flickering orange glow of a dying hearth casts long , dancing shadows that stretch across the rough - hewn stone floor and the heavy , dark oak furniture . the lighting is moody and oppressive , with deep amber highlights clashing against the cold , blue moonlight filtering through a narrow slit window . the textures are visceral : the coarse , salt - stained wool of catelyn 's heavy gown , the grainy texture of the ancient parchment , and the glint of a silver seal partially melted . in the background , the gothic architecture of the keep looms , with heavy vaulted ceilings and iron sconces that drip black soot . the atmosphere is heavy with an invisible weight , the silent scream of a political conspiracy that threatens to ignite a war . every line of catelyn 's expression conveys a desperate urgency ; her lips are parted , her breath visible in the freezing air , as she realizes that eddard must travel to king 's landing to uncover a truth that could destroy them all . the scene is a study in intimacy and impending doom , capturing the exact moment a private letter transforms into a catalyst for continental chaos ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["and rough - hewn leather , leans in with a secretive , knowing smile , his eyes reflecting a deep , protective kinship . his posture is slightly hunched , creating a private sanctuary between them . arya , small and spirited , looks up with wide , shimmering eyes , her face a mask of sudden wonder . her fingers are stained with the dust of her haphazardly packed trunks . between them , jon presents the gift : needle . the sword is a slender , elegant sliver of high - carbon steel , its blade polished to a mirror - sheen that catches the pale , wintry light filtering through a narrow gothic window . the hilt is wrapped in fine , weathered leather , showing the subtle grain of the hide . the lighting is moody and directional ; a soft , diffused silver light from the overcast northern sky illuminates the side of their faces , while deep , velvet shadows cling to the corners of the room and the heavy oak beams of the ceiling . in the background , nymeria , the direwolf , is a blur of grey - white fur , poised like a sentinel by the heavy iron - bound door , her amber eyes watchful . every texture is visceral : the coarse weave of the stark tapestries hanging on the walls , the cold dampness of the limestone floor , and the slight glint of sweat on jon 's brow . the focus is tight on the moment the steel passes from jon 's calloused hand to arya 's small , trembling grip . the air feels heavy with the unspoken promise of protection and the looming shadow of the north , capturing a fleeting instant of childhood innocence before the onset of war ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["and rough - hewn leather , leans in with a secretive , knowing smile , his eyes reflecting a deep , protective kinship . his posture is slightly hunched , creating a private sanctuary between them . arya , small and spirited , looks up with wide , shimmering eyes , her face a mask of sudden wonder . her fingers are stained with the dust of her haphazardly packed trunks . between them , jon presents the gift : needle . the sword is a slender , elegant sliver of high - carbon steel , its blade polished to a mirror - sheen that catches the pale , wintry light filtering through a narrow gothic window . the hilt is wrapped in fine , weathered leather , showing the subtle grain of the hide . the lighting is moody and directional ; a soft , diffused silver light from the overcast northern sky illuminates the side of their faces , while deep , velvet shadows cling to the corners of the room and the heavy oak beams of the ceiling . in the background , nymeria , the direwolf , is a blur of grey - white fur , poised like a sentinel by the heavy iron - bound door , her amber eyes watchful . every texture is visceral : the coarse weave of the stark tapestries hanging on the walls , the cold dampness of the limestone floor , and the slight glint of sweat on jon 's brow . the focus is tight on the moment the steel passes from jon 's calloused hand to arya 's small , trembling grip . the air feels heavy with the unspoken promise of protection and the looming shadow of the north , capturing a fleeting instant of childhood innocence before the onset of war ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['with a bittersweet smile and eyes reflecting a deep , fraternal bond . he holds out a slender , elegant blade — needle — its polished steel gleaming with a cold , silver luster that contrasts against the rough , charcoal - grey wool of his tunic . arya ’ s expression is one of pure , wide - eyed wonder , her small hands trembling slightly as she reaches for the hilt . her skin is flushed from the cold , with a few stray smudges of dirt on her cheek , her eyes locked on the weapon with an intensity that borders on obsession . the lighting is a moody , overcast northern afternoon ; soft , diffused light filters through a heavy ceiling of slate - grey clouds , casting gentle , muted shadows that cling to the crevices of the ancient , lichen - covered granite walls . in the background , the blurred silhouettes of soldiers and horses create a sense of impending separation . the textures are visceral : the cold , biting wind whipping through arya \'s salt - stained linen dress , the coarse grain of the wooden crates she was packing , and the lethal , mirror - like smoothness of the thin blade . jon ’ s voice is a whisper , his lips barely moving as he imparts the fundamental lesson : " stick them with the pointy end ." beside them , the direwolf nymeria stands as a silent sentinel , her thick , grey - white fur ruffled by the breeze , her amber eyes vigilant , guarding the entrance to their private sanctuary . the atmosphere is heavy with the tension of a childhood ending and the silent promise of survival in a world of steel and ice .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['with a bittersweet smile and eyes reflecting a deep , fraternal bond . he holds out a slender , elegant blade — needle — its polished steel gleaming with a cold , silver luster that contrasts against the rough , charcoal - grey wool of his tunic . arya ’ s expression is one of pure , wide - eyed wonder , her small hands trembling slightly as she reaches for the hilt . her skin is flushed from the cold , with a few stray smudges of dirt on her cheek , her eyes locked on the weapon with an intensity that borders on obsession . the lighting is a moody , overcast northern afternoon ; soft , diffused light filters through a heavy ceiling of slate - grey clouds , casting gentle , muted shadows that cling to the crevices of the ancient , lichen - covered granite walls . in the background , the blurred silhouettes of soldiers and horses create a sense of impending separation . the textures are visceral : the cold , biting wind whipping through arya \'s salt - stained linen dress , the coarse grain of the wooden crates she was packing , and the lethal , mirror - like smoothness of the thin blade . jon ’ s voice is a whisper , his lips barely moving as he imparts the fundamental lesson : " stick them with the pointy end ." beside them , the direwolf nymeria stands as a silent sentinel , her thick , grey - white fur ruffled by the breeze , her amber eyes vigilant , guarding the entrance to their private sanctuary . the atmosphere is heavy with the tension of a childhood ending and the silent promise of survival in a world of steel and ice .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['ped raw , digging into the porous stone . he peers through a narrow , arched window embrasure into a dim , candle - lit chamber . inside , the lighting is a warm , flickering amber that casts dancing , elongated shadows against the damp stone walls . cersei lannister and jaime lannister are entwined in a desperate , illicit embrace . cersei ’ s skin is a pale , luminous ivory , glistening with a thin sheen of sweat ; her golden hair is a chaotic spill across her shoulders . jaime , her mirror image with a sharp , arrogant jawline and golden stubble , holds her with a possessive grip . their expressions are a volatile mix of passion and sudden , piercing panic as they realize they are being watched . the camera captures the moment of sudden violence . bran has lost his balance , his small body dangling precariously over the abyss , one hand gripping the jagged edge of the window ledge . the texture of the worn , salt - stained linen of his tunic flutters in the cold northern wind . jaime ’ s face shifts from lust to a cold , calculating desperation . he reaches out , his hand gripping bran ’ s wrist — not in a gesture of rescue , but as a prelude to a crime . the contrast is stark : the warmth of the interior chamber versus the freezing , slate - grey exterior of the tower . the air is thick with the smell of old stone and ozone . as jaime prepares to heave the boy backward into the void , the focus tightens on the micro - expression of cersei ’ s face — a mask of sheer , wide - eyed terror and ruthless necessity . the background shows the sprawling , blurred courtyard of winterfell far below , a dizzying drop of grey stone and dead grass .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['ped raw , digging into the porous stone . he peers through a narrow , arched window embrasure into a dim , candle - lit chamber . inside , the lighting is a warm , flickering amber that casts dancing , elongated shadows against the damp stone walls . cersei lannister and jaime lannister are entwined in a desperate , illicit embrace . cersei ’ s skin is a pale , luminous ivory , glistening with a thin sheen of sweat ; her golden hair is a chaotic spill across her shoulders . jaime , her mirror image with a sharp , arrogant jawline and golden stubble , holds her with a possessive grip . their expressions are a volatile mix of passion and sudden , piercing panic as they realize they are being watched . the camera captures the moment of sudden violence . bran has lost his balance , his small body dangling precariously over the abyss , one hand gripping the jagged edge of the window ledge . the texture of the worn , salt - stained linen of his tunic flutters in the cold northern wind . jaime ’ s face shifts from lust to a cold , calculating desperation . he reaches out , his hand gripping bran ’ s wrist — not in a gesture of rescue , but as a prelude to a crime . the contrast is stark : the warmth of the interior chamber versus the freezing , slate - grey exterior of the tower . the air is thick with the smell of old stone and ozone . as jaime prepares to heave the boy backward into the void , the focus tightens on the micro - expression of cersei ’ s face — a mask of sheer , wide - eyed terror and ruthless necessity . the background shows the sprawling , blurred courtyard of winterfell far below , a dizzying drop of grey stone and dead grass .']
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ['the rough, lichen-covered grey granite. His small fingers are scraped raw, digging into the porous stone. He peers through a narrow, arched window embrasure into a dim, candle-lit chamber. Inside, the lighting is a warm, flickering amber that casts dancing, elongated shadows against the damp stone walls. Cersei Lannister and Jaime Lannister are entwined in a desperate, illicit embrace. Cersei’s skin is a pale, luminous ivory, glistening with a thin sheen of sweat; her golden hair is a chaotic spill across her shoulders. Jaime, her mirror image with a sharp, arrogant jawline and golden stubble, holds her with a possessive grip. Their expressions are a volatile mix of passion and sudden, piercing panic as they realize they are being watched. The camera captures the moment of sudden violence. Bran has lost his balance, his small body dangling precariously over the abyss, one hand gripping the jagged edge of the window ledge. The texture of the worn, salt-stained linen of his tunic flutters in the cold Northern wind. Jaime’s face shifts from lust to a cold, calculating desperation. He reaches out, his hand gripping Bran’s wrist—not in a gesture of rescue, but as a prelude to a crime. The contrast is stark: the warmth of the interior chamber versus the freezing, slate-grey exterior of the tower. The air is thick with the smell of old stone and ozone. As Jaime prepares to heave the boy backward into the void, the focus tightens on the micro-expression of Cersei’s face—a mask of sheer, wide-eyed terror and ruthless necessity. The background shows the sprawling, blurred courtyard of Winterfell far below, a dizzying drop of grey stone and dead grass.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["vivid , blooming crimson welt across joffrey ’ s pale , porcelain cheek . joffrey ’ s head is snapped to the side , his mouth agape in a mixture of shock and narcissistic rage , his golden curls disheveled . his eyes are wide , glistening with unshed tears of humiliation , while his posture is stiff , trembling with the impulse to scream . tyrion ’ s expression is one of cold , disciplined disgust ; his mismatched eyes narrow , his brow furrowed in a stern reprimand . he leans in , the fabric of his rich , crimson velvet doublet contrasting with the grey , oppressive stone of the walls . the texture of the velvet is heavy and plush , catching the dim light , while tyrion 's skin is weathered , with fine lines of stress and cynicism etched around his eyes . the lighting is oppressive and moody , provided by flickering iron wall sconces that cast long , dancing shadows and a warm , amber glow that fails to penetrate the deep , charcoal gloom of the vaulted ceiling . in the background , sandor clegane looms like a mountain of scarred flesh and blackened steel , his burned face partially obscured by the flickering light , his expression one of grim , silent amusement . the environment is damp and oppressive ; moisture clings to the rough - hewn granite blocks of the hallway , and a thin mist of cold northern air swirls around their boots . the air feels thick with the scent of old stone , torch smoke , and the metallic tang of tension . every detail is visceral : the gold embroidery on joffrey 's tunic fraying slightly at the collar , the glint of a signet ring on tyrion 's finger , and the heavy , rhythmic breathing of the hound echoing through the silent , gothic passage ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["vivid , blooming crimson welt across joffrey ’ s pale , porcelain cheek . joffrey ’ s head is snapped to the side , his mouth agape in a mixture of shock and narcissistic rage , his golden curls disheveled . his eyes are wide , glistening with unshed tears of humiliation , while his posture is stiff , trembling with the impulse to scream . tyrion ’ s expression is one of cold , disciplined disgust ; his mismatched eyes narrow , his brow furrowed in a stern reprimand . he leans in , the fabric of his rich , crimson velvet doublet contrasting with the grey , oppressive stone of the walls . the texture of the velvet is heavy and plush , catching the dim light , while tyrion 's skin is weathered , with fine lines of stress and cynicism etched around his eyes . the lighting is oppressive and moody , provided by flickering iron wall sconces that cast long , dancing shadows and a warm , amber glow that fails to penetrate the deep , charcoal gloom of the vaulted ceiling . in the background , sandor clegane looms like a mountain of scarred flesh and blackened steel , his burned face partially obscured by the flickering light , his expression one of grim , silent amusement . the environment is damp and oppressive ; moisture clings to the rough - hewn granite blocks of the hallway , and a thin mist of cold northern air swirls around their boots . the air feels thick with the scent of old stone , torch smoke , and the metallic tang of tension . every detail is visceral : the gold embroidery on joffrey 's tunic fraying slightly at the collar , the glint of a signet ring on tyrion 's finger , and the heavy , rhythmic breathing of the hound echoing through the silent , gothic passage ."]
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ["violent crack of a slap that has left a vivid, blooming crimson welt across Joffrey’s pale, porcelain cheek. Joffrey’s head is snapped to the side, his mouth agape in a mixture of shock and narcissistic rage, his golden curls disheveled. His eyes are wide, glistening with unshed tears of humiliation, while his posture is stiff, trembling with the impulse to scream. Tyrion’s expression is one of cold, disciplined disgust; his mismatched eyes narrow, his brow furrowed in a stern reprimand. He leans in, the fabric of his rich, crimson velvet doublet contrasting with the grey, oppressive stone of the walls. The texture of the velvet is heavy and plush, catching the dim light, while Tyrion's skin is weathered, with fine lines of stress and cynicism etched around his eyes. The lighting is oppressive and moody, provided by flickering iron wall sconces that cast long, dancing shadows and a warm, amber glow that fails to penetrate the deep, charcoal gloom of the vaulted ceiling. In the background, Sandor Clegane looms like a mountain of scarred flesh and blackened steel, his burned face partially obscured by the flickering light, his expression one of grim, silent amusement. The environment is damp and oppressive; moisture clings to the rough-hewn granite blocks of the hallway, and a thin mist of cold Northern air swirls around their boots. The air feels thick with the scent of old stone, torch smoke, and the metallic tang of tension. Every detail is visceral: the gold embroidery on Joffrey's tunic fraying slightly at the collar, the glint of a signet ring on Tyrion's finger, and the heavy, rhythmic breathing of the Hound echoing through the silent, Gothic passage."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['sweat - beads form in the humid heat . her expression is a complex mask of trepidation and burgeoning curiosity , her violet eyes wide and reflecting the dying light . standing before her is magister illyrio , a man of immense girth and opulent excess . his face is slick with oil , his skin glistening , wearing heavy brocade robes of deep crimson and gold that look suffocatingly thick . with a slow , theatrical gesture , he presents three massive , stone - like objects resting on a velvet cushion of midnight blue . these are the dragon eggs : one a deep , mossy green with organic , crystalline ridges ; one a pale , iridescent cream that glows like a dying star ; and one a matte , obsidian black , its surface etched with ancient , smoky ripples and fossilized scales . the lighting is dramatic , with the low - hanging sun casting long , jagged silhouettes across the mosaic floor of the courtyard . to the side , viserys targaryen watches with a predatory , hungry gaze , his posture rigid , his fingers twitching with an obsessive desire for the power these eggs represent . beside him , ser jorah mormont stands like a weathered monolith , his salt - stained leather armor contrasting with the luxury of the setting , his eyes softening with a protective , hidden longing as he looks at daenerys . the environment is a blend of gothic excess and essosi opulence ; towering marble columns are entwined with flowering vines , and the air is thick with the scent of roasting meats , exotic incense , and the salty breeze of the narrow sea . the tension is palpable , a silent electricity crackling between the fragile girl and the ancient , dormant power of the stone eggs .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['sweat - beads form in the humid heat . her expression is a complex mask of trepidation and burgeoning curiosity , her violet eyes wide and reflecting the dying light . standing before her is magister illyrio , a man of immense girth and opulent excess . his face is slick with oil , his skin glistening , wearing heavy brocade robes of deep crimson and gold that look suffocatingly thick . with a slow , theatrical gesture , he presents three massive , stone - like objects resting on a velvet cushion of midnight blue . these are the dragon eggs : one a deep , mossy green with organic , crystalline ridges ; one a pale , iridescent cream that glows like a dying star ; and one a matte , obsidian black , its surface etched with ancient , smoky ripples and fossilized scales . the lighting is dramatic , with the low - hanging sun casting long , jagged silhouettes across the mosaic floor of the courtyard . to the side , viserys targaryen watches with a predatory , hungry gaze , his posture rigid , his fingers twitching with an obsessive desire for the power these eggs represent . beside him , ser jorah mormont stands like a weathered monolith , his salt - stained leather armor contrasting with the luxury of the setting , his eyes softening with a protective , hidden longing as he looks at daenerys . the environment is a blend of gothic excess and essosi opulence ; towering marble columns are entwined with flowering vines , and the air is thick with the scent of roasting meats , exotic incense , and the salty breeze of the narrow sea . the tension is palpable , a silent electricity crackling between the fragile girl and the ancient , dormant power of the stone eggs .']
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ['ber sunset, the fabric clinging to her skin where sweat-beads form in the humid heat. Her expression is a complex mask of trepidation and burgeoning curiosity, her violet eyes wide and reflecting the dying light. Standing before her is Magister Illyrio, a man of immense girth and opulent excess. His face is slick with oil, his skin glistening, wearing heavy brocade robes of deep crimson and gold that look suffocatingly thick. With a slow, theatrical gesture, he presents three massive, stone-like objects resting on a velvet cushion of midnight blue. These are the dragon eggs: one a deep, mossy green with organic, crystalline ridges; one a pale, iridescent cream that glows like a dying star; and one a matte, obsidian black, its surface etched with ancient, smoky ripples and fossilized scales. The lighting is dramatic, with the low-hanging sun casting long, jagged silhouettes across the mosaic floor of the courtyard. To the side, Viserys Targaryen watches with a predatory, hungry gaze, his posture rigid, his fingers twitching with an obsessive desire for the power these eggs represent. Beside him, Ser Jorah Mormont stands like a weathered monolith, his salt-stained leather armor contrasting with the luxury of the setting, his eyes softening with a protective, hidden longing as he looks at Daenerys. The environment is a blend of Gothic excess and Essosi opulence; towering marble columns are entwined with flowering vines, and the air is thick with the scent of roasting meats, exotic incense, and the salty breeze of the Narrow Sea. The tension is palpable, a silent electricity crackling between the fragile girl and the ancient, dormant power of the stone eggs.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["sweat and dust . he holds the lead of a magnificent young mare , a creature of ethereal beauty with a coat the color of a winter sea — a shimmering , stormy grey that catches the dying light . the horse 's mane is a wild , flowing cascade of silver smoke , whipping in the warm wind . daenerys stands before him , her expression a fragile mixture of terror and burgeoning curiosity . her skin is pale , almost translucent against the heavy , ornate silks of her bridal attire , which are embroidered with intricate gold threads that shimmer with every shallow breath she takes . her small hands tremble slightly as she looks upon the animal . the tension between them is electric ; drogo ’ s dark , piercing eyes are fixed on her , not with cruelty , but with a possessive , simmering intensity . surrounding them , the atmosphere is thick with the scent of roasted meat , pungent horse sweat , and exotic spices . in the background , the blurred figures of the bloodriders stand like statues of iron and leather , their weathered faces scarred and stern . nearby , a pile of heavy , leather - bound books provided by jorah and the iridescent , stone - like dragon eggs — one deep emerald , one cream , one obsidian black — rest upon a table of rough - hewn wood , their surfaces matte and ancient . the lighting is dramatic , with the low - hanging sun creating a high - contrast rim light around the characters , while deep , velvet shadows swallow the edges of the encampment . every texture is palpable : the coarse grain of the dothraki leather , the delicate weave of the silks , and the powerful , rippling muscles of the grey mare ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["sweat and dust . he holds the lead of a magnificent young mare , a creature of ethereal beauty with a coat the color of a winter sea — a shimmering , stormy grey that catches the dying light . the horse 's mane is a wild , flowing cascade of silver smoke , whipping in the warm wind . daenerys stands before him , her expression a fragile mixture of terror and burgeoning curiosity . her skin is pale , almost translucent against the heavy , ornate silks of her bridal attire , which are embroidered with intricate gold threads that shimmer with every shallow breath she takes . her small hands tremble slightly as she looks upon the animal . the tension between them is electric ; drogo ’ s dark , piercing eyes are fixed on her , not with cruelty , but with a possessive , simmering intensity . surrounding them , the atmosphere is thick with the scent of roasted meat , pungent horse sweat , and exotic spices . in the background , the blurred figures of the bloodriders stand like statues of iron and leather , their weathered faces scarred and stern . nearby , a pile of heavy , leather - bound books provided by jorah and the iridescent , stone - like dragon eggs — one deep emerald , one cream , one obsidian black — rest upon a table of rough - hewn wood , their surfaces matte and ancient . the lighting is dramatic , with the low - hanging sun creating a high - contrast rim light around the characters , while deep , velvet shadows swallow the edges of the encampment . every texture is palpable : the coarse grain of the dothraki leather , the delicate weave of the silks , and the powerful , rippling muscles of the grey mare ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["him , her expression one of maternal agony and exhaustion , her fingers clutching the coarse , salt - stained linen of the bedsheets . the lighting is oppressive ; dim , flickering torchlight casts dancing , jagged shadows against the rough - hewn gothic masonry , while a distant , violent orange glow from a burning tower bleeds through the narrow window , painting the room in sickly amber streaks . suddenly , the silence is shattered . a hooded assassin bursts through the heavy wooden door , his movement a blur of lethal intent . he is a shadow draped in worn , dark leather that creaks with every stride . in his grip is a dagger of valyrian steel , its blade etched with smoky , undulating ripples that seem to swallow the light . as he lunges toward the unconscious boy , catelyn throws herself forward in a desperate , instinctive shield . the blade sinks into her flesh with a sickening slide ; her eyes widen in a shock of searing pain , a single droplet of crimson blood blooming across her gown . at the apex of the violence , a blur of grey fur erupts from the corner of the room . summer , the direwolf , launches himself with primal fury . the wolf 's massive jaws snap shut with a bone - crushing sound , tearing through the assassin 's throat . blood sprays in a violent arc , splashing across the cold stone floor and the white linens of the bed . the assassin 's eyes bulge , his hands clawing uselessly at the thick , coarse fur of the beast as he is dragged backward , his muffled gurgles lost to the guttural snarls of the wolf . the scene is a visceral contrast of fragile innocence , maternal sacrifice , and raw , animalistic savagery ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["him , her expression one of maternal agony and exhaustion , her fingers clutching the coarse , salt - stained linen of the bedsheets . the lighting is oppressive ; dim , flickering torchlight casts dancing , jagged shadows against the rough - hewn gothic masonry , while a distant , violent orange glow from a burning tower bleeds through the narrow window , painting the room in sickly amber streaks . suddenly , the silence is shattered . a hooded assassin bursts through the heavy wooden door , his movement a blur of lethal intent . he is a shadow draped in worn , dark leather that creaks with every stride . in his grip is a dagger of valyrian steel , its blade etched with smoky , undulating ripples that seem to swallow the light . as he lunges toward the unconscious boy , catelyn throws herself forward in a desperate , instinctive shield . the blade sinks into her flesh with a sickening slide ; her eyes widen in a shock of searing pain , a single droplet of crimson blood blooming across her gown . at the apex of the violence , a blur of grey fur erupts from the corner of the room . summer , the direwolf , launches himself with primal fury . the wolf 's massive jaws snap shut with a bone - crushing sound , tearing through the assassin 's throat . blood sprays in a violent arc , splashing across the cold stone floor and the white linens of the bed . the assassin 's eyes bulge , his hands clawing uselessly at the thick , coarse fur of the beast as he is dragged backward , his muffled gurgles lost to the guttural snarls of the wolf . the scene is a visceral contrast of fragile innocence , maternal sacrifice , and raw , animalistic savagery ."]
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ["ic. Catelyn Stark is slumped beside him, her expression one of maternal agony and exhaustion, her fingers clutching the coarse, salt-stained linen of the bedsheets. The lighting is oppressive; dim, flickering torchlight casts dancing, jagged shadows against the rough-hewn Gothic masonry, while a distant, violent orange glow from a burning tower bleeds through the narrow window, painting the room in sickly amber streaks. Suddenly, the silence is shattered. A hooded assassin bursts through the heavy wooden door, his movement a blur of lethal intent. He is a shadow draped in worn, dark leather that creaks with every stride. In his grip is a dagger of Valyrian steel, its blade etched with smoky, undulating ripples that seem to swallow the light. As he lunges toward the unconscious boy, Catelyn throws herself forward in a desperate, instinctive shield. The blade sinks into her flesh with a sickening slide; her eyes widen in a shock of searing pain, a single droplet of crimson blood blooming across her gown. At the apex of the violence, a blur of grey fur erupts from the corner of the room. Summer, the direwolf, launches himself with primal fury. The wolf's massive jaws snap shut with a bone-crushing sound, tearing through the assassin's throat. Blood sprays in a violent arc, splashing across the cold stone floor and the white linens of the bed. The assassin's eyes bulge, his hands clawing uselessly at the thick, coarse fur of the beast as he is dragged backward, his muffled gurgles lost to the guttural snarls of the wolf. The scene is a visceral contrast of fragile innocence, maternal sacrifice, and raw, animalistic savagery."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["a mask of sheer terror and maternal agony , her breath coming in ragged gasps . a jagged wound on her arm seeps crimson , staining the fine , salt - stained linen of her gown . beside her , bran lies motionless on a heavy oak bed , his pale skin waxy and sweat - beaded , eyes closed in an unconscious stupor . the scene is frozen in a moment of violent intervention . a lean , sinister assassin , dressed in muted , charcoal - grey leathers that blend into the shadows , is being violently thrown backward . his expression is one of sudden , jarring shock , eyes wide with disbelief as his grip on a slender , rippled valyrian steel dagger slips . the blade , etched with smoky , swirling patterns , glints under the dim light . latching onto the assassin 's throat with primal ferocity is bran ’ s direwolf . the beast is a colossal shadow of grey and white fur , muscles rippling beneath a thick , coarse coat . its powerful jaws are clamped shut around the man 's neck , tearing through skin and sinew in a spray of vivid scarlet . the wolf 's eyes are amber slits of protective rage , its paws digging deep into the stone floor , claws scratching the grit . shadows stretch long and jagged across the room , cast by the dying embers of the hearth and the violent light from the window . the gothic architecture of the room — heavy vaulted ceilings and thick , oppressive pillars — frames the chaos . every texture is visceral : the rough grain of the wooden bedframe , the cold dampness of the limestone walls , and the wet , glistening gore of the assassin 's shredded throat . the atmosphere is heavy with the sudden transition from silent grief to explosive , animalistic violence ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["a mask of sheer terror and maternal agony , her breath coming in ragged gasps . a jagged wound on her arm seeps crimson , staining the fine , salt - stained linen of her gown . beside her , bran lies motionless on a heavy oak bed , his pale skin waxy and sweat - beaded , eyes closed in an unconscious stupor . the scene is frozen in a moment of violent intervention . a lean , sinister assassin , dressed in muted , charcoal - grey leathers that blend into the shadows , is being violently thrown backward . his expression is one of sudden , jarring shock , eyes wide with disbelief as his grip on a slender , rippled valyrian steel dagger slips . the blade , etched with smoky , swirling patterns , glints under the dim light . latching onto the assassin 's throat with primal ferocity is bran ’ s direwolf . the beast is a colossal shadow of grey and white fur , muscles rippling beneath a thick , coarse coat . its powerful jaws are clamped shut around the man 's neck , tearing through skin and sinew in a spray of vivid scarlet . the wolf 's eyes are amber slits of protective rage , its paws digging deep into the stone floor , claws scratching the grit . shadows stretch long and jagged across the room , cast by the dying embers of the hearth and the violent light from the window . the gothic architecture of the room — heavy vaulted ceilings and thick , oppressive pillars — frames the chaos . every texture is visceral : the rough grain of the wooden bedframe , the cold dampness of the limestone walls , and the wet , glistening gore of the assassin 's shredded throat . the atmosphere is heavy with the sudden transition from silent grief to explosive , animalistic violence ."]
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ["k is collapsed on the cold floor, her face a mask of sheer terror and maternal agony, her breath coming in ragged gasps. A jagged wound on her arm seeps crimson, staining the fine, salt-stained linen of her gown. Beside her, Bran lies motionless on a heavy oak bed, his pale skin waxy and sweat-beaded, eyes closed in an unconscious stupor. The scene is frozen in a moment of violent intervention. A lean, sinister assassin, dressed in muted, charcoal-grey leathers that blend into the shadows, is being violently thrown backward. His expression is one of sudden, jarring shock, eyes wide with disbelief as his grip on a slender, rippled Valyrian steel dagger slips. The blade, etched with smoky, swirling patterns, glints under the dim light. Latching onto the assassin's throat with primal ferocity is Bran’s direwolf. The beast is a colossal shadow of grey and white fur, muscles rippling beneath a thick, coarse coat. Its powerful jaws are clamped shut around the man's neck, tearing through skin and sinew in a spray of vivid scarlet. The wolf's eyes are amber slits of protective rage, its paws digging deep into the stone floor, claws scratching the grit. Shadows stretch long and jagged across the room, cast by the dying embers of the hearth and the violent light from the window. The Gothic architecture of the room—heavy vaulted ceilings and thick, oppressive pillars—frames the chaos. Every texture is visceral: the rough grain of the wooden bedframe, the cold dampness of the limestone walls, and the wet, glistening gore of the assassin's shredded throat. The atmosphere is heavy with the sudden transition from silent grief to explosive, animalistic violence."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [", a single streak of crimson blood blooming across her salt - stained linen gown where the blade has sliced through . opposite her , a hooded assassin looms , his posture coiled and predatory , his face obscured by a coarse , dark wool cowl that casts a deep shadow over his features . in the assassin 's grip is a slender , lethal dagger . the blade is forged from valyrian steel , characterized by its distinct , smoky ripples and dark , swirling patterns etched into the metal , shimmering with a cold , unnatural luster . the hilt is ornate , crafted from polished bone and dark leather , gripped by a hand with knuckles white from tension . the scene is violently interrupted by the sudden , explosive surge of summer , bran 's direwolf . the massive beast is a blur of grey - white fur and raw power , captured mid - leap , his jaws wide and teeth bared in a primal snarl . the wolf 's claws dig into the wooden floorboards , sending splinters flying . the composition focuses on the precise moment of impact : the wolf 's teeth sinking deep into the assassin 's throat , a spray of hot , bright blood painting the cold grey stone . lighting is dramatic and oppressive ; the room is dim , illuminated only by a flickering hearth and the distant , violent orange glow of a burning tower filtering through a narrow window , casting long , jagged silhouettes across the floor . dust motes dance in the shafts of amber light . in the background , bran lies motionless on his bed , his pale , sweat - beaded skin contrasting with the heavy , dark furs of his blankets , his expression one of haunting stillness amidst the chaos ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [", a single streak of crimson blood blooming across her salt - stained linen gown where the blade has sliced through . opposite her , a hooded assassin looms , his posture coiled and predatory , his face obscured by a coarse , dark wool cowl that casts a deep shadow over his features . in the assassin 's grip is a slender , lethal dagger . the blade is forged from valyrian steel , characterized by its distinct , smoky ripples and dark , swirling patterns etched into the metal , shimmering with a cold , unnatural luster . the hilt is ornate , crafted from polished bone and dark leather , gripped by a hand with knuckles white from tension . the scene is violently interrupted by the sudden , explosive surge of summer , bran 's direwolf . the massive beast is a blur of grey - white fur and raw power , captured mid - leap , his jaws wide and teeth bared in a primal snarl . the wolf 's claws dig into the wooden floorboards , sending splinters flying . the composition focuses on the precise moment of impact : the wolf 's teeth sinking deep into the assassin 's throat , a spray of hot , bright blood painting the cold grey stone . lighting is dramatic and oppressive ; the room is dim , illuminated only by a flickering hearth and the distant , violent orange glow of a burning tower filtering through a narrow window , casting long , jagged silhouettes across the floor . dust motes dance in the shafts of amber light . in the background , bran lies motionless on his bed , his pale , sweat - beaded skin contrasting with the heavy , dark furs of his blankets , his expression one of haunting stillness amidst the chaos ."]
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ["mask of shock, eyes wide and pupils dilated, a single streak of crimson blood blooming across her salt-stained linen gown where the blade has sliced through. Opposite her, a hooded assassin looms, his posture coiled and predatory, his face obscured by a coarse, dark wool cowl that casts a deep shadow over his features. In the assassin's grip is a slender, lethal dagger. The blade is forged from Valyrian steel, characterized by its distinct, smoky ripples and dark, swirling patterns etched into the metal, shimmering with a cold, unnatural luster. The hilt is ornate, crafted from polished bone and dark leather, gripped by a hand with knuckles white from tension. The scene is violently interrupted by the sudden, explosive surge of Summer, Bran's direwolf. The massive beast is a blur of grey-white fur and raw power, captured mid-leap, his jaws wide and teeth bared in a primal snarl. The wolf's claws dig into the wooden floorboards, sending splinters flying. The composition focuses on the precise moment of impact: the wolf's teeth sinking deep into the assassin's throat, a spray of hot, bright blood painting the cold grey stone. Lighting is dramatic and oppressive; the room is dim, illuminated only by a flickering hearth and the distant, violent orange glow of a burning tower filtering through a narrow window, casting long, jagged silhouettes across the floor. Dust motes dance in the shafts of amber light. In the background, Bran lies motionless on his bed, his pale, sweat-beaded skin contrasting with the heavy, dark furs of his blankets, his expression one of haunting stillness amidst the chaos."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["center of the frame , young arya stark stands with a fierce , protective intensity . her small frame is taut , shoulders squared , and her face is a mask of righteous fury . her skin is smudged with river silt and grime , with a single streak of mud crossing her cheek . she has just snatched ' lion 's tooth ,' joffrey ’ s ornate sword , from the ground . she grips the hilt with both hands , her knuckles white from the pressure , the blade angled defensively . the sword is a piece of arrogant craftsmanship : polished steel reflecting the grey sky , with a gold - filigreed pommel and a hilt wrapped in pristine , cream - colored leather that contrasts sharply with arya 's worn , dirt - stained linen tunic . opposite her , prince joffrey stands in a posture of wounded pride and simmering malice . he is dressed in rich , crimson velvets and gold embroidery , his clothes jarringly opulent against the wild , rugged backdrop . his lips are curled in a sneer of disbelief , his pale skin flushed with anger , and his eyes narrow with a cruel , entitled spark . between them , the butcher 's boy , mycah , cringes in terror . he is trembling , his breathing shallow , with a small , glistening bead of blood where the sword tip recently pricked his cheek . he is dressed in rough , salt - stained burlap , his posture collapsed and defeated . in the background , sansa stark watches with a look of horrified apprehension , her hands clasped tightly to her chest , her silk gown dragging in the mire . the environment is a graveyard of history , with the distant , skeletal remains of ancient battlements looming through the river mist , evoking the ghosts of the clash between robert baratheon and rhaegar targaryen ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["center of the frame , young arya stark stands with a fierce , protective intensity . her small frame is taut , shoulders squared , and her face is a mask of righteous fury . her skin is smudged with river silt and grime , with a single streak of mud crossing her cheek . she has just snatched ' lion 's tooth ,' joffrey ’ s ornate sword , from the ground . she grips the hilt with both hands , her knuckles white from the pressure , the blade angled defensively . the sword is a piece of arrogant craftsmanship : polished steel reflecting the grey sky , with a gold - filigreed pommel and a hilt wrapped in pristine , cream - colored leather that contrasts sharply with arya 's worn , dirt - stained linen tunic . opposite her , prince joffrey stands in a posture of wounded pride and simmering malice . he is dressed in rich , crimson velvets and gold embroidery , his clothes jarringly opulent against the wild , rugged backdrop . his lips are curled in a sneer of disbelief , his pale skin flushed with anger , and his eyes narrow with a cruel , entitled spark . between them , the butcher 's boy , mycah , cringes in terror . he is trembling , his breathing shallow , with a small , glistening bead of blood where the sword tip recently pricked his cheek . he is dressed in rough , salt - stained burlap , his posture collapsed and defeated . in the background , sansa stark watches with a look of horrified apprehension , her hands clasped tightly to her chest , her silk gown dragging in the mire . the environment is a graveyard of history , with the distant , skeletal remains of ancient battlements looming through the river mist , evoking the ghosts of the clash between robert baratheon and rhaegar targaryen ."]
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ["to the tall, swaying reeds. In the center of the frame, young Arya Stark stands with a fierce, protective intensity. Her small frame is taut, shoulders squared, and her face is a mask of righteous fury. Her skin is smudged with river silt and grime, with a single streak of mud crossing her cheek. She has just snatched 'Lion's Tooth,' Joffrey’s ornate sword, from the ground. She grips the hilt with both hands, her knuckles white from the pressure, the blade angled defensively. The sword is a piece of arrogant craftsmanship: polished steel reflecting the grey sky, with a gold-filigreed pommel and a hilt wrapped in pristine, cream-colored leather that contrasts sharply with Arya's worn, dirt-stained linen tunic. Opposite her, Prince Joffrey stands in a posture of wounded pride and simmering malice. He is dressed in rich, crimson velvets and gold embroidery, his clothes jarringly opulent against the wild, rugged backdrop. His lips are curled in a sneer of disbelief, his pale skin flushed with anger, and his eyes narrow with a cruel, entitled spark. Between them, the butcher's boy, Mycah, cringes in terror. He is trembling, his breathing shallow, with a small, glistening bead of blood where the sword tip recently pricked his cheek. He is dressed in rough, salt-stained burlap, his posture collapsed and defeated. In the background, Sansa Stark watches with a look of horrified apprehension, her hands clasped tightly to her chest, her silk gown dragging in the mire. The environment is a graveyard of history, with the distant, skeletal remains of ancient battlements looming through the river mist, evoking the ghosts of the clash between Robert Baratheon and Rhaegar Targaryen."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["inging to his forehead . hovering inches from his face is the three - eyed raven , a creature of unsettling intelligence . the raven 's feathers are not merely black , but a deep , iridescent void that absorbs the surrounding light , with three piercing , milky - white eyes that glow with an ancient , predatory wisdom . the bird 's beak is parted in a silent , commanding scream , its posture aggressive and urgent . the perspective is a dizzying , vertical plunge . below bran , the world unfolds like a living , breathing tapestry of gold , emerald , and slate grey . the architecture of winterfell is visible in miniature , the grey granite walls etched with frost , the godswood a splash of deep crimson leaves against a stark white snowfield . tiny , flickering figures of robb , hodor , and maester luwin move like ghosts through the courtyards . further south , the golden spires of king 's landing glint under a harsh , oppressive sun , where the figures of ned and the royal family are engulfed by creeping , ink - like shadows that coil around their ankles like serpents . to the east , the deep cerulean of the narrow sea is sliced by the sharp prow of a galley , while the distant , shimmering heat haze of the dothraki sea and the obsidian towers of asshai flicker on the horizon . to the far north , the colossal , translucent blue wall of ice looms , a jagged monolith of frozen history , with the solitary , dark silhouette of jon snow standing guard . the lighting is otherworldly ; a celestial , pale moonlight clashes with violent streaks of violet and gold nebula gas , casting long , distorted shadows across the floating fragments of the world . every texture is hyper - defined : the coarse , oily sheen of the raven 's plumage , the crystalline structure of the wall 's ice , and the fragile , trembling fabric of bran 's linen tunic ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["inging to his forehead . hovering inches from his face is the three - eyed raven , a creature of unsettling intelligence . the raven 's feathers are not merely black , but a deep , iridescent void that absorbs the surrounding light , with three piercing , milky - white eyes that glow with an ancient , predatory wisdom . the bird 's beak is parted in a silent , commanding scream , its posture aggressive and urgent . the perspective is a dizzying , vertical plunge . below bran , the world unfolds like a living , breathing tapestry of gold , emerald , and slate grey . the architecture of winterfell is visible in miniature , the grey granite walls etched with frost , the godswood a splash of deep crimson leaves against a stark white snowfield . tiny , flickering figures of robb , hodor , and maester luwin move like ghosts through the courtyards . further south , the golden spires of king 's landing glint under a harsh , oppressive sun , where the figures of ned and the royal family are engulfed by creeping , ink - like shadows that coil around their ankles like serpents . to the east , the deep cerulean of the narrow sea is sliced by the sharp prow of a galley , while the distant , shimmering heat haze of the dothraki sea and the obsidian towers of asshai flicker on the horizon . to the far north , the colossal , translucent blue wall of ice looms , a jagged monolith of frozen history , with the solitary , dark silhouette of jon snow standing guard . the lighting is otherworldly ; a celestial , pale moonlight clashes with violent streaks of violet and gold nebula gas , casting long , distorted shadows across the floating fragments of the world . every texture is hyper - defined : the coarse , oily sheen of the raven 's plumage , the crystalline structure of the wall 's ice , and the fragile , trembling fabric of bran 's linen tunic ."]
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ["awe. His skin is pale, almost translucent, with fine beads of cold sweat clinging to his forehead. Hovering inches from his face is the Three-Eyed Raven, a creature of unsettling intelligence. The raven's feathers are not merely black, but a deep, iridescent void that absorbs the surrounding light, with three piercing, milky-white eyes that glow with an ancient, predatory wisdom. The bird's beak is parted in a silent, commanding scream, its posture aggressive and urgent. The perspective is a dizzying, vertical plunge. Below Bran, the world unfolds like a living, breathing tapestry of gold, emerald, and slate grey. The architecture of Winterfell is visible in miniature, the grey granite walls etched with frost, the Godswood a splash of deep crimson leaves against a stark white snowfield. Tiny, flickering figures of Robb, Hodor, and Maester Luwin move like ghosts through the courtyards. Further south, the golden spires of King's Landing glint under a harsh, oppressive sun, where the figures of Ned and the royal family are engulfed by creeping, ink-like shadows that coil around their ankles like serpents. To the east, the deep cerulean of the Narrow Sea is sliced by the sharp prow of a galley, while the distant, shimmering heat haze of the Dothraki Sea and the obsidian towers of Asshai flicker on the horizon. To the far north, the colossal, translucent blue wall of ice looms, a jagged monolith of frozen history, with the solitary, dark silhouette of Jon Snow standing guard. The lighting is otherworldly; a celestial, pale moonlight clashes with violent streaks of violet and gold nebula gas, casting long, distorted shadows across the floating fragments of the world. Every texture is hyper-defined: the coarse, oily sheen of the raven's plumage, the crystalline structure of the Wall's ice, and the fragile, trembling fabric of Bran's linen tunic."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["strand of auburn hair clinging to her damp cheek . she wears a heavy , travel - worn cloak of deep charcoal wool , the fabric coarse and salt - stained , fastened by a simple silver brooch . beside her stands ser rodrik cassel , his presence a stark contrast of seasoned martial discipline and physical fragility . his face is raw and slightly reddened from the sea wind , notably missing his signature thick mustache — the skin above his lip is smooth and irritated , a pragmatic sacrifice to avoid the grime of his recent seasickness . he leans slightly against the salt - crusted mahogany railing , his knuckles white , his eyes scanning the horizon with a mixture of relief and apprehension . his leather brigandine is scuffed , showing the wear of a long voyage , with dull brass rivets catching the pale light . the lighting is oppressive and moody ; a heavy , overcast sky casts a diffused , cold silver light over the scene , creating deep , soft shadows in the folds of their garments . in the distance , the sprawling , jagged silhouette of king 's landing emerges through a veil of coastal mist , the red keep looming like a blood - stained monolith atop aegon 's hill . the architecture of the city is a dense , chaotic sprawl of terracotta roofs and limestone walls . the atmosphere is thick with unspoken dread . catelyn ’ s gaze is fixed on the city , her lips pressed thin , imagining the gaze of littlefinger and the dangers of the court . the deck of the ship is slick with seawater , reflecting the gloomy sky , while the rigging overhead snaps violently in the wind , adding a sense of urgency to their arrival ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["strand of auburn hair clinging to her damp cheek . she wears a heavy , travel - worn cloak of deep charcoal wool , the fabric coarse and salt - stained , fastened by a simple silver brooch . beside her stands ser rodrik cassel , his presence a stark contrast of seasoned martial discipline and physical fragility . his face is raw and slightly reddened from the sea wind , notably missing his signature thick mustache — the skin above his lip is smooth and irritated , a pragmatic sacrifice to avoid the grime of his recent seasickness . he leans slightly against the salt - crusted mahogany railing , his knuckles white , his eyes scanning the horizon with a mixture of relief and apprehension . his leather brigandine is scuffed , showing the wear of a long voyage , with dull brass rivets catching the pale light . the lighting is oppressive and moody ; a heavy , overcast sky casts a diffused , cold silver light over the scene , creating deep , soft shadows in the folds of their garments . in the distance , the sprawling , jagged silhouette of king 's landing emerges through a veil of coastal mist , the red keep looming like a blood - stained monolith atop aegon 's hill . the architecture of the city is a dense , chaotic sprawl of terracotta roofs and limestone walls . the atmosphere is thick with unspoken dread . catelyn ’ s gaze is fixed on the city , her lips pressed thin , imagining the gaze of littlefinger and the dangers of the court . the deck of the ship is slick with seawater , reflecting the gloomy sky , while the rigging overhead snaps violently in the wind , adding a sense of urgency to their arrival ."]
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ["on etched around her eyes and a single, stray strand of auburn hair clinging to her damp cheek. She wears a heavy, travel-worn cloak of deep charcoal wool, the fabric coarse and salt-stained, fastened by a simple silver brooch. Beside her stands Ser Rodrik Cassel, his presence a stark contrast of seasoned martial discipline and physical fragility. His face is raw and slightly reddened from the sea wind, notably missing his signature thick mustache—the skin above his lip is smooth and irritated, a pragmatic sacrifice to avoid the grime of his recent seasickness. He leans slightly against the salt-crusted mahogany railing, his knuckles white, his eyes scanning the horizon with a mixture of relief and apprehension. His leather brigandine is scuffed, showing the wear of a long voyage, with dull brass rivets catching the pale light. The lighting is oppressive and moody; a heavy, overcast sky casts a diffused, cold silver light over the scene, creating deep, soft shadows in the folds of their garments. In the distance, the sprawling, jagged silhouette of King's Landing emerges through a veil of coastal mist, the Red Keep looming like a blood-stained monolith atop Aegon's Hill. The architecture of the city is a dense, chaotic sprawl of terracotta roofs and limestone walls. The atmosphere is thick with unspoken dread. Catelyn’s gaze is fixed on the city, her lips pressed thin, imagining the gaze of Littlefinger and the dangers of the court. The deck of the ship is slick with seawater, reflecting the gloomy sky, while the rigging overhead snaps violently in the wind, adding a sense of urgency to their arrival."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [". he is dressed in simple , lightweight linens of a pale cream hue , the fabric clinging to his thin frame , smelling of salt and distant shores . his expression is one of playful yet piercing intensity , a slight , knowing smirk tugging at the corner of his mouth as he holds a wooden practice sword with an effortless , fluid grace . opposite him stands young arya stark , her small frame tense and vibrating with a mixture of defiance and curiosity . she wears a rough , salt - stained tunic of muted grey , her dark hair escaping a messy braid in wild strands that stick to her sweat - beaded forehead . her knuckles are white as she grips her own wooden sword , her wide , grey eyes locked onto syrio ’ s with a fierce , untamed determination . the tension between them is electric — a clash between the disciplined , rhythmic dance of braavos and the raw , unrefined spirit of the north . the surrounding architecture is oppressive ; massive , soot - stained limestone pillars rise toward a vaulted ceiling lost in deep , velvet shadows . the floor is composed of oversized , uneven flagstones , worn smooth by centuries of footsteps , reflecting the amber glow of the sun . in the background , the heavy oak doors of the small hall stand slightly ajar , casting a long , jagged silhouette across the floor . every detail is tactile : the rough grain of the practice swords , the dampness of the humid air , and the subtle ripple of syrio 's muscles as he shifts his weight , preparing to teach the girl that the sword is not a weapon , but a dance of survival ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [". he is dressed in simple , lightweight linens of a pale cream hue , the fabric clinging to his thin frame , smelling of salt and distant shores . his expression is one of playful yet piercing intensity , a slight , knowing smirk tugging at the corner of his mouth as he holds a wooden practice sword with an effortless , fluid grace . opposite him stands young arya stark , her small frame tense and vibrating with a mixture of defiance and curiosity . she wears a rough , salt - stained tunic of muted grey , her dark hair escaping a messy braid in wild strands that stick to her sweat - beaded forehead . her knuckles are white as she grips her own wooden sword , her wide , grey eyes locked onto syrio ’ s with a fierce , untamed determination . the tension between them is electric — a clash between the disciplined , rhythmic dance of braavos and the raw , unrefined spirit of the north . the surrounding architecture is oppressive ; massive , soot - stained limestone pillars rise toward a vaulted ceiling lost in deep , velvet shadows . the floor is composed of oversized , uneven flagstones , worn smooth by centuries of footsteps , reflecting the amber glow of the sun . in the background , the heavy oak doors of the small hall stand slightly ajar , casting a long , jagged silhouette across the floor . every detail is tactile : the rough grain of the practice swords , the dampness of the humid air , and the subtle ripple of syrio 's muscles as he shifts his weight , preparing to teach the girl that the sword is not a weapon , but a dance of survival ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["cream hue , the fabric clinging to his frame with salt - stained creases . his expression is one of playful yet piercing intensity , his dark eyes locked onto arya stark . arya , small and fierce , holds a blunt practice sword with white - knuckled intensity . her face is smudged with grime , a single bead of sweat tracing a path through the dust on her cheek . her posture is rigid , reflecting the clumsy strength of the west , contrasting sharply with syrio 's ethereal grace . he moves not like a soldier , but like a ripple in a pond , his wooden blade flickering in a blur of motion . the lighting is harsh and vertical , casting short , ink - black shadows that anchor the figures to the scorched earth . in the background , the gothic arches of the small hall loom , their intricate carvings weathered by centuries of salt air and neglect . the air is thick with floating motes of gold dust , illuminated by shafts of light piercing through the overhead colonnades . the tension is palpable — a clash of philosophies . syrio ’ s wooden sword barely touches arya ’ s , a series of rapid , sudden taps that mimic the flow of water , while arya lunges with heavy , desperate strikes . the texture of the scene is visceral : the rough grain of the practice swords , the coarse grit of the courtyard sand kicking up around their boots , and the shimmering heat haze distorting the distant red stone towers . syrio ’ s lips are curled in a knowing , enigmatic smile , his body coiled like a spring , embodying the water dance — a lethal , liquid elegance that makes the heavy iron of the westerosi knights seem archaic and slow ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["cream hue , the fabric clinging to his frame with salt - stained creases . his expression is one of playful yet piercing intensity , his dark eyes locked onto arya stark . arya , small and fierce , holds a blunt practice sword with white - knuckled intensity . her face is smudged with grime , a single bead of sweat tracing a path through the dust on her cheek . her posture is rigid , reflecting the clumsy strength of the west , contrasting sharply with syrio 's ethereal grace . he moves not like a soldier , but like a ripple in a pond , his wooden blade flickering in a blur of motion . the lighting is harsh and vertical , casting short , ink - black shadows that anchor the figures to the scorched earth . in the background , the gothic arches of the small hall loom , their intricate carvings weathered by centuries of salt air and neglect . the air is thick with floating motes of gold dust , illuminated by shafts of light piercing through the overhead colonnades . the tension is palpable — a clash of philosophies . syrio ’ s wooden sword barely touches arya ’ s , a series of rapid , sudden taps that mimic the flow of water , while arya lunges with heavy , desperate strikes . the texture of the scene is visceral : the rough grain of the practice swords , the coarse grit of the courtyard sand kicking up around their boots , and the shimmering heat haze distorting the distant red stone towers . syrio ’ s lips are curled in a knowing , enigmatic smile , his body coiled like a spring , embodying the water dance — a lethal , liquid elegance that makes the heavy iron of the westerosi knights seem archaic and slow ."]
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ["a poised, fluid stance. He is dressed in light, breathable linens of a pale cream hue, the fabric clinging to his frame with salt-stained creases. His expression is one of playful yet piercing intensity, his dark eyes locked onto Arya Stark. Arya, small and fierce, holds a blunt practice sword with white-knuckled intensity. Her face is smudged with grime, a single bead of sweat tracing a path through the dust on her cheek. Her posture is rigid, reflecting the clumsy strength of the West, contrasting sharply with Syrio's ethereal grace. He moves not like a soldier, but like a ripple in a pond, his wooden blade flickering in a blur of motion. The lighting is harsh and vertical, casting short, ink-black shadows that anchor the figures to the scorched earth. In the background, the Gothic arches of the Small Hall loom, their intricate carvings weathered by centuries of salt air and neglect. The air is thick with floating motes of gold dust, illuminated by shafts of light piercing through the overhead colonnades. The tension is palpable—a clash of philosophies. Syrio’s wooden sword barely touches Arya’s, a series of rapid, sudden taps that mimic the flow of water, while Arya lunges with heavy, desperate strikes. The texture of the scene is visceral: the rough grain of the practice swords, the coarse grit of the courtyard sand kicking up around their boots, and the shimmering heat haze distorting the distant red stone towers. Syrio’s lips are curled in a knowing, enigmatic smile, his body coiled like a spring, embodying the Water Dance—a lethal, liquid elegance that makes the heavy iron of the Westerosi knights seem archaic and slow."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['a captive to the quiet strength of a mother . she is dressed in worn , salt - stained linen and rough - spun silks of pale cream , the fabric clinging to her skin , damp with a fine sheen of sweat that beads on her collarbone and forehead . beside her , jhiqui leans in , her expression a mixture of reverence and knowing . the tension between them is palpable — a shared secret in a world of warriors . jhiqui ’ s hand hovers inches from daenerys ’ s abdomen , her dark eyes searching daenerys ’ s face . daenerys ’ s expression is a complex tapestry of shock and sudden , fierce clarity ; her lips are slightly parted , her silver - gold hair whipping across her face in the dry wind , some strands catching in the coarse weave of her tunic . the lighting is dramatic and directional , with the dying sun casting long , jagged silhouettes across the parched earth . a deep , amber glow illuminates the side of daenerys ’ s face , leaving the other half in a soft , velvet shadow , symbolizing her dual nature as a frightened girl and a rising queen . in the background , the blurred shapes of the khalasar are visible : the flickering orange embers of distant campfires , the silhouettes of horses with braided manes , and the distant , imposing figure of khal drogo , a mountain of muscle and leather , watching from afar . the ground is a texture of crushed yellow grass and grey dust that clings to the hem of her skirts . every detail is visceral : the cracked leather of the saddles , the glint of bronze ornaments , and the raw , organic intensity of a woman discovering a new life stirring within her amidst a wasteland of war .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['a captive to the quiet strength of a mother . she is dressed in worn , salt - stained linen and rough - spun silks of pale cream , the fabric clinging to her skin , damp with a fine sheen of sweat that beads on her collarbone and forehead . beside her , jhiqui leans in , her expression a mixture of reverence and knowing . the tension between them is palpable — a shared secret in a world of warriors . jhiqui ’ s hand hovers inches from daenerys ’ s abdomen , her dark eyes searching daenerys ’ s face . daenerys ’ s expression is a complex tapestry of shock and sudden , fierce clarity ; her lips are slightly parted , her silver - gold hair whipping across her face in the dry wind , some strands catching in the coarse weave of her tunic . the lighting is dramatic and directional , with the dying sun casting long , jagged silhouettes across the parched earth . a deep , amber glow illuminates the side of daenerys ’ s face , leaving the other half in a soft , velvet shadow , symbolizing her dual nature as a frightened girl and a rising queen . in the background , the blurred shapes of the khalasar are visible : the flickering orange embers of distant campfires , the silhouettes of horses with braided manes , and the distant , imposing figure of khal drogo , a mountain of muscle and leather , watching from afar . the ground is a texture of crushed yellow grass and grey dust that clings to the hem of her skirts . every detail is visceral : the cracked leather of the saddles , the glint of bronze ornaments , and the raw , organic intensity of a woman discovering a new life stirring within her amidst a wasteland of war .']
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ['a moment of profound, silent revelation, her posture shifting from the fragility of a captive to the quiet strength of a mother. She is dressed in worn, salt-stained linen and rough-spun silks of pale cream, the fabric clinging to her skin, damp with a fine sheen of sweat that beads on her collarbone and forehead. Beside her, Jhiqui leans in, her expression a mixture of reverence and knowing. The tension between them is palpable—a shared secret in a world of warriors. Jhiqui’s hand hovers inches from Daenerys’s abdomen, her dark eyes searching Daenerys’s face. Daenerys’s expression is a complex tapestry of shock and sudden, fierce clarity; her lips are slightly parted, her silver-gold hair whipping across her face in the dry wind, some strands catching in the coarse weave of her tunic. The lighting is dramatic and directional, with the dying sun casting long, jagged silhouettes across the parched earth. A deep, amber glow illuminates the side of Daenerys’s face, leaving the other half in a soft, velvet shadow, symbolizing her dual nature as a frightened girl and a rising queen. In the background, the blurred shapes of the khalasar are visible: the flickering orange embers of distant campfires, the silhouettes of horses with braided manes, and the distant, imposing figure of Khal Drogo, a mountain of muscle and leather, watching from afar. The ground is a texture of crushed yellow grass and grey dust that clings to the hem of her skirts. Every detail is visceral: the cracked leather of the saddles, the glint of bronze ornaments, and the raw, organic intensity of a woman discovering a new life stirring within her amidst a wasteland of war.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["grey wool and worn linen . his face is a mask of fragile defiance , eyes wide and searching , while his posture is stiff , held upright by the effort of his will . beside him , robb stark stands like a sentinel , his brow furrowed in deep suspicion , hand resting instinctively on the hilt of his sword , his gaze sharp and protective . tyrion lannister stands opposite them , a striking contrast in his rich , crimson velvet doublet with gold embroidery that catches the flickering light of nearby tallow candles . his expression is one of calculated empathy , a slight , knowing smirk playing on his lips , while his mismatched eyes glint with an intellect that borders on arrogance . he holds a piece of yellowed vellum — the blueprints for a specialized saddle — extending it toward the maester . the paper is crisp , with precise , ink - drawn diagrams of leather straps and reinforced supports . the lighting is dramatic and moody ; a single high window allows a shaft of pale , wintry sunlight to pierce the gloom , illuminating dust motes dancing in the air and casting long , jagged shadows across the uneven flagstone floor . the texture of the room is palpable : the rough - hewn granite of the walls , the polished dark oak of the furniture , and the sweat - beaded skin on bran ’ s forehead . the tension is a physical presence , a silent clash between the lannister ’ s unexpected generosity and the starks ' ingrained distrust . every micro - expression is captured — the maester ’ s squint of professional curiosity as he examines the plans , and the subtle flicker of resentment in robb 's jaw ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["grey wool and worn linen . his face is a mask of fragile defiance , eyes wide and searching , while his posture is stiff , held upright by the effort of his will . beside him , robb stark stands like a sentinel , his brow furrowed in deep suspicion , hand resting instinctively on the hilt of his sword , his gaze sharp and protective . tyrion lannister stands opposite them , a striking contrast in his rich , crimson velvet doublet with gold embroidery that catches the flickering light of nearby tallow candles . his expression is one of calculated empathy , a slight , knowing smirk playing on his lips , while his mismatched eyes glint with an intellect that borders on arrogance . he holds a piece of yellowed vellum — the blueprints for a specialized saddle — extending it toward the maester . the paper is crisp , with precise , ink - drawn diagrams of leather straps and reinforced supports . the lighting is dramatic and moody ; a single high window allows a shaft of pale , wintry sunlight to pierce the gloom , illuminating dust motes dancing in the air and casting long , jagged shadows across the uneven flagstone floor . the texture of the room is palpable : the rough - hewn granite of the walls , the polished dark oak of the furniture , and the sweat - beaded skin on bran ’ s forehead . the tension is a physical presence , a silent clash between the lannister ’ s unexpected generosity and the starks ' ingrained distrust . every micro - expression is captured — the maester ’ s squint of professional curiosity as he examines the plans , and the subtle flicker of resentment in robb 's jaw ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['parchment color , beaded with cold sweat that glitters under the flickering amber light of a dying tallow candle . his fingers , gnarled and trembling , claw desperately at the surface of a massive , leather - bound tome : " the lineages and histories of the great houses of the seven kingdoms ." the book is splayed open , its vellum pages yellowed and brittle , covered in dense , handwritten genealogical charts and ink - stained annotations that hint at a forbidden discovery . standing over him is grand maester pycelle , his posture a study in calculated indifference . pycelle ’ s heavy , velvet robes of deep crimson swallow his frail frame , the fabric thick and dusty . his long , white beard is meticulously groomed , contrasting with the predatory , calculating glint in his watery eyes . he watches arryn ’ s struggle not with urgency , but with a cold , clinical curiosity , his hands tucked hidden within his wide sleeves . the lighting is oppressive ; a single high , narrow gothic window allows a sliver of bruised purple twilight to pierce the gloom , casting a long , jagged shadow of pycelle across the dying man . the environment is cluttered with the tools of a maester : glass vials filled with iridescent liquids , bundles of dried herbs hanging from the rafters , and stacks of scrolls tied with frayed twine . the texture of the scene is visceral — the rough grain of the oak desk , the embossed gold leaf peeling off the book \'s spine , and the visible tension in arryn \'s neck tendons as he gasps for air , his eyes wide with the terror of a man who has uncovered a secret that has now become his death sentence .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['parchment color , beaded with cold sweat that glitters under the flickering amber light of a dying tallow candle . his fingers , gnarled and trembling , claw desperately at the surface of a massive , leather - bound tome : " the lineages and histories of the great houses of the seven kingdoms ." the book is splayed open , its vellum pages yellowed and brittle , covered in dense , handwritten genealogical charts and ink - stained annotations that hint at a forbidden discovery . standing over him is grand maester pycelle , his posture a study in calculated indifference . pycelle ’ s heavy , velvet robes of deep crimson swallow his frail frame , the fabric thick and dusty . his long , white beard is meticulously groomed , contrasting with the predatory , calculating glint in his watery eyes . he watches arryn ’ s struggle not with urgency , but with a cold , clinical curiosity , his hands tucked hidden within his wide sleeves . the lighting is oppressive ; a single high , narrow gothic window allows a sliver of bruised purple twilight to pierce the gloom , casting a long , jagged shadow of pycelle across the dying man . the environment is cluttered with the tools of a maester : glass vials filled with iridescent liquids , bundles of dried herbs hanging from the rafters , and stacks of scrolls tied with frayed twine . the texture of the scene is visceral — the rough grain of the oak desk , the embossed gold leaf peeling off the book \'s spine , and the visible tension in arryn \'s neck tendons as he gasps for air , his eyes wide with the terror of a man who has uncovered a secret that has now become his death sentence .']
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ['His skin is a sickly, translucent parchment color, beaded with cold sweat that glitters under the flickering amber light of a dying tallow candle. His fingers, gnarled and trembling, claw desperately at the surface of a massive, leather-bound tome: "The Lineages and Histories of the Great Houses of the Seven Kingdoms." The book is splayed open, its vellum pages yellowed and brittle, covered in dense, handwritten genealogical charts and ink-stained annotations that hint at a forbidden discovery. Standing over him is Grand Maester Pycelle, his posture a study in calculated indifference. Pycelle’s heavy, velvet robes of deep crimson swallow his frail frame, the fabric thick and dusty. His long, white beard is meticulously groomed, contrasting with the predatory, calculating glint in his watery eyes. He watches Arryn’s struggle not with urgency, but with a cold, clinical curiosity, his hands tucked hidden within his wide sleeves. The lighting is oppressive; a single high, narrow Gothic window allows a sliver of bruised purple twilight to pierce the gloom, casting a long, jagged shadow of Pycelle across the dying man. The environment is cluttered with the tools of a Maester: glass vials filled with iridescent liquids, bundles of dried herbs hanging from the rafters, and stacks of scrolls tied with frayed twine. The texture of the scene is visceral—the rough grain of the oak desk, the embossed gold leaf peeling off the book\'s spine, and the visible tension in Arryn\'s neck tendons as he gasps for air, his eyes wide with the terror of a man who has uncovered a secret that has now become his death sentence.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["cold , northern determination . beside him , ghost is a spectral presence , a massive white direwolf with piercing red eyes , his teeth bared in a silent , menacing snarl , muscles rippling beneath thick , snow - white fur . rast is recoiling into his rough , straw - filled cot , his face contorted in a mixture of sudden terror and disbelief . sweat beads on his forehead , glistening under the flickering , amber light of a distant torch that casts long , jagged silhouettes across the frost - covered stone walls . the lighting is chiaroscuro , with deep , ink - black shadows swallowing the corners of the room , emphasizing the isolation of the encounter . in the background , samwell tarly is visible , huddled in a heavy , oversized black cloak of coarse , salt - stained wool . his expression is one of fragile hope and profound vulnerability , his wide eyes reflecting the torchlight as he watches jon ’ s unexpected defense . the textures are visceral : the rough - hewn granite of the walls , the frayed edges of the black uniforms , and the cold , metallic glint of a training sword leaning against a wooden pillar . the atmosphere is heavy with the unspoken brotherhood of outcasts . jon ’ s hand rests firmly on ghost ’ s neck , the contrast between the pale fur and the dark leather of jon 's glove highlighting the bond between them . the scene is a study in power dynamics — the physical intimidation of the wolf and the moral strength of jon snow , set against the bleak , gothic austerity of the wall 's interior , where the cold seems to seep through the very image ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["cold , northern determination . beside him , ghost is a spectral presence , a massive white direwolf with piercing red eyes , his teeth bared in a silent , menacing snarl , muscles rippling beneath thick , snow - white fur . rast is recoiling into his rough , straw - filled cot , his face contorted in a mixture of sudden terror and disbelief . sweat beads on his forehead , glistening under the flickering , amber light of a distant torch that casts long , jagged silhouettes across the frost - covered stone walls . the lighting is chiaroscuro , with deep , ink - black shadows swallowing the corners of the room , emphasizing the isolation of the encounter . in the background , samwell tarly is visible , huddled in a heavy , oversized black cloak of coarse , salt - stained wool . his expression is one of fragile hope and profound vulnerability , his wide eyes reflecting the torchlight as he watches jon ’ s unexpected defense . the textures are visceral : the rough - hewn granite of the walls , the frayed edges of the black uniforms , and the cold , metallic glint of a training sword leaning against a wooden pillar . the atmosphere is heavy with the unspoken brotherhood of outcasts . jon ’ s hand rests firmly on ghost ’ s neck , the contrast between the pale fur and the dark leather of jon 's glove highlighting the bond between them . the scene is a study in power dynamics — the physical intimidation of the wolf and the moral strength of jon snow , set against the bleak , gothic austerity of the wall 's interior , where the cold seems to seep through the very image ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [", whose face is twisted in a sudden , waking mask of sheer terror . beside jon , ghost , the direwolf , is a spectral presence of blinding white fur and piercing red eyes , his massive head inches from rast ’ s throat , a low , guttural snarl vibrating through his chest . the lighting is visceral ; flickering orange torchlight casts dancing , jagged shadows against the rough - hewn granite walls , while a pale , freezing moonlight spills through a narrow arrow - slit , illuminating the frost clinging to the iron bedframes . jon ’ s expression is a study in controlled menace ; his dark brows are furrowed , and his eyes are cold , reflecting the hardness of the wall . he wears a heavy , salt - stained black cloak of thick , coarse wool with a leather strap crossing his chest . his hand rests firmly on the hilt of his sword , the pommel worn from use . rast is sprawled back against a thin , grey linen mattress , his skin beaded with cold sweat , his eyes wide and pupils dilated in panic . in the blurred background , samwell tarly is visible , huddled in a thick , oversized fur mantle that swallows his soft frame . his expression is one of profound relief and tentative hope , his eyes shimmering with unshed tears as he watches jon ’ s protective stance . the textures are tactile : the grit of the stone floor , the frayed edges of the wool blankets , and the crystalline frost forming on the edges of the room . the tension is palpable , a silent vow of brotherhood forged in the oppressive darkness of the night 's watch ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [", whose face is twisted in a sudden , waking mask of sheer terror . beside jon , ghost , the direwolf , is a spectral presence of blinding white fur and piercing red eyes , his massive head inches from rast ’ s throat , a low , guttural snarl vibrating through his chest . the lighting is visceral ; flickering orange torchlight casts dancing , jagged shadows against the rough - hewn granite walls , while a pale , freezing moonlight spills through a narrow arrow - slit , illuminating the frost clinging to the iron bedframes . jon ’ s expression is a study in controlled menace ; his dark brows are furrowed , and his eyes are cold , reflecting the hardness of the wall . he wears a heavy , salt - stained black cloak of thick , coarse wool with a leather strap crossing his chest . his hand rests firmly on the hilt of his sword , the pommel worn from use . rast is sprawled back against a thin , grey linen mattress , his skin beaded with cold sweat , his eyes wide and pupils dilated in panic . in the blurred background , samwell tarly is visible , huddled in a thick , oversized fur mantle that swallows his soft frame . his expression is one of profound relief and tentative hope , his eyes shimmering with unshed tears as he watches jon ’ s protective stance . the textures are tactile : the grit of the stone floor , the frayed edges of the wool blankets , and the crystalline frost forming on the edges of the room . the tension is palpable , a silent vow of brotherhood forged in the oppressive darkness of the night 's watch ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["yet dangerous . opposite him stands sansa stark , small and fragile , her face a mask of terrified curiosity and suppressed horror . the tension between them is electric , a collision of raw brutality and aristocratic innocence . the lighting is visceral ; a single , flickering torch on the wall casts a violent , orange glow that dances across the scene , leaving deep , cavernous shadows in the corners of the room . the light catches the sweat - beaded skin of sandor 's forehead and the glint of a half - empty wine skin clutched in his calloused , scarred hand . sandor slowly turns his head , forcing sansa to look directly at the ruin of his face . the detail is harrowing : the skin on the left side of his face is a landscape of puckered , glossy scar tissue , melted and fused into a permanent , twisted grimace . the texture is a mix of waxy , pale ridges and deep , angry crimson furrows where the flesh once bubbled . he describes the memory with a low , guttural rasp — the sensation of his brother gregor ’ s massive hand crushing his skull downward , the searing , blinding heat of the red - hot coals in the brazier , and the smell of his own burning skin . sansa ’ s expression is one of visceral shock ; her pupils are dilated , her lips slightly parted , a single tear tracing a path through the fine powder on her cheek . she wears a gown of pale , heavy silk , the fabric shimmering faintly in the torchlight , contrasting sharply with sandor 's worn , salt - stained leather armor and the rough , coarse wool of his cloak . the environment is claustrophobic , with heavy gothic arches overhead and the distant , muffled sounds of the city echoing through the cold stone corridors ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["yet dangerous . opposite him stands sansa stark , small and fragile , her face a mask of terrified curiosity and suppressed horror . the tension between them is electric , a collision of raw brutality and aristocratic innocence . the lighting is visceral ; a single , flickering torch on the wall casts a violent , orange glow that dances across the scene , leaving deep , cavernous shadows in the corners of the room . the light catches the sweat - beaded skin of sandor 's forehead and the glint of a half - empty wine skin clutched in his calloused , scarred hand . sandor slowly turns his head , forcing sansa to look directly at the ruin of his face . the detail is harrowing : the skin on the left side of his face is a landscape of puckered , glossy scar tissue , melted and fused into a permanent , twisted grimace . the texture is a mix of waxy , pale ridges and deep , angry crimson furrows where the flesh once bubbled . he describes the memory with a low , guttural rasp — the sensation of his brother gregor ’ s massive hand crushing his skull downward , the searing , blinding heat of the red - hot coals in the brazier , and the smell of his own burning skin . sansa ’ s expression is one of visceral shock ; her pupils are dilated , her lips slightly parted , a single tear tracing a path through the fine powder on her cheek . she wears a gown of pale , heavy silk , the fabric shimmering faintly in the torchlight , contrasting sharply with sandor 's worn , salt - stained leather armor and the rough , coarse wool of his cloak . the environment is claustrophobic , with heavy gothic arches overhead and the distant , muffled sounds of the city echoing through the cold stone corridors ."]
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ["drunken, bitter intensity, his posture slumped yet dangerous. Opposite him stands Sansa Stark, small and fragile, her face a mask of terrified curiosity and suppressed horror. The tension between them is electric, a collision of raw brutality and aristocratic innocence. The lighting is visceral; a single, flickering torch on the wall casts a violent, orange glow that dances across the scene, leaving deep, cavernous shadows in the corners of the room. The light catches the sweat-beaded skin of Sandor's forehead and the glint of a half-empty wine skin clutched in his calloused, scarred hand. Sandor slowly turns his head, forcing Sansa to look directly at the ruin of his face. The detail is harrowing: the skin on the left side of his face is a landscape of puckered, glossy scar tissue, melted and fused into a permanent, twisted grimace. The texture is a mix of waxy, pale ridges and deep, angry crimson furrows where the flesh once bubbled. He describes the memory with a low, guttural rasp—the sensation of his brother Gregor’s massive hand crushing his skull downward, the searing, blinding heat of the red-hot coals in the brazier, and the smell of his own burning skin. Sansa’s expression is one of visceral shock; her pupils are dilated, her lips slightly parted, a single tear tracing a path through the fine powder on her cheek. She wears a gown of pale, heavy silk, the fabric shimmering faintly in the torchlight, contrasting sharply with Sandor's worn, salt-stained leather armor and the rough, coarse wool of his cloak. The environment is claustrophobic, with heavy Gothic arches overhead and the distant, muffled sounds of the city echoing through the cold stone corridors."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["and unwavering , are locked onto tyrion lannister . she wears a heavy , travel - worn cloak of deep charcoal wool , the fabric coarse and pilled from leagues of riding , fastened by a silver brooch . tyrion is caught mid - gesture , a goblet of wine frozen in his hand , his small frame dwarfed by the looming threat around him . his expression is a complex blend of genuine shock and a flickering , calculating wit ; a single bead of sweat rolls down his temple , glistening under the flickering orange glow of the hearth . he is dressed in rich , crimson velvet that looks garish and out of place in the rustic , grime - streaked interior of the inn . surrounding them , a dozen men - at - arms erupt into motion . the sound is a synchronized metallic shriek as longswords are unsheathed from leather scabbards . the blades are polished steel , reflecting the violent , dancing flames of the fireplace , casting jagged , elongated shadows across the uneven stone floor and the rough - hewn timber beams of the ceiling . the lighting is chiaroscuro ; deep , oppressive blacks in the corners of the room contrasted with the harsh , warm amber light hitting the characters ' faces . dust motes dance in the shafts of light piercing through the grime - coated windows . the texture of the room is visceral : the greasy sheen on the wooden tables , the salt - stained linen of the peasants ' tunics , and the cold , damp grey of the stone walls . catelyn ’ s hand is clenched tight , her knuckles white , embodying the absolute authority of the north , while the air vibrates with the unspoken threat of violence and the sudden collapse of hospitality ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["and unwavering , are locked onto tyrion lannister . she wears a heavy , travel - worn cloak of deep charcoal wool , the fabric coarse and pilled from leagues of riding , fastened by a silver brooch . tyrion is caught mid - gesture , a goblet of wine frozen in his hand , his small frame dwarfed by the looming threat around him . his expression is a complex blend of genuine shock and a flickering , calculating wit ; a single bead of sweat rolls down his temple , glistening under the flickering orange glow of the hearth . he is dressed in rich , crimson velvet that looks garish and out of place in the rustic , grime - streaked interior of the inn . surrounding them , a dozen men - at - arms erupt into motion . the sound is a synchronized metallic shriek as longswords are unsheathed from leather scabbards . the blades are polished steel , reflecting the violent , dancing flames of the fireplace , casting jagged , elongated shadows across the uneven stone floor and the rough - hewn timber beams of the ceiling . the lighting is chiaroscuro ; deep , oppressive blacks in the corners of the room contrasted with the harsh , warm amber light hitting the characters ' faces . dust motes dance in the shafts of light piercing through the grime - coated windows . the texture of the room is visceral : the greasy sheen on the wooden tables , the salt - stained linen of the peasants ' tunics , and the cold , damp grey of the stone walls . catelyn ’ s hand is clenched tight , her knuckles white , embodying the absolute authority of the north , while the air vibrates with the unspoken threat of violence and the sudden collapse of hospitality ."]
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ["ing, her face a mask of cold, maternal fury. Her eyes, sharp and unwavering, are locked onto Tyrion Lannister. She wears a heavy, travel-worn cloak of deep charcoal wool, the fabric coarse and pilled from leagues of riding, fastened by a silver brooch. Tyrion is caught mid-gesture, a goblet of wine frozen in his hand, his small frame dwarfed by the looming threat around him. His expression is a complex blend of genuine shock and a flickering, calculating wit; a single bead of sweat rolls down his temple, glistening under the flickering orange glow of the hearth. He is dressed in rich, crimson velvet that looks garish and out of place in the rustic, grime-streaked interior of the inn. Surrounding them, a dozen men-at-arms erupt into motion. The sound is a synchronized metallic shriek as longswords are unsheathed from leather scabbards. The blades are polished steel, reflecting the violent, dancing flames of the fireplace, casting jagged, elongated shadows across the uneven stone floor and the rough-hewn timber beams of the ceiling. The lighting is chiaroscuro; deep, oppressive blacks in the corners of the room contrasted with the harsh, warm amber light hitting the characters' faces. Dust motes dance in the shafts of light piercing through the grime-coated windows. The texture of the room is visceral: the greasy sheen on the wooden tables, the salt-stained linen of the peasants' tunics, and the cold, damp grey of the stone walls. Catelyn’s hand is clenched tight, her knuckles white, embodying the absolute authority of the North, while the air vibrates with the unspoken threat of violence and the sudden collapse of hospitality."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["cloak of deep charcoal grey is whipped violently by a freezing gale , the fabric frayed and salt - stained from the journey . her knuckles are white as she grips the lead rope , her eyes cold and piercing , reflecting a mother 's vengeful resolve . tyrion , dwarfed by the towering limestone cliffs , stumbles on the uneven shale . his expensive crimson doublet is torn and coated in a layer of grey dust and dried mud ; the fine velvet is matted and worn . his expression is a complex mixture of intellectual defiance and genuine fear , a slight , sardonic smirk twitching at the corner of his mouth despite the sweat - beaded skin of his forehead and the bruising around his wrists where the rough hemp rope bites deep into his flesh . the lighting is oppressive : a bruised , purple - grey twilight descends , with a pale , dying sun casting long , distorted shadows that stretch like fingers across the rocky terrain . the air is thick with a swirling mist that clings to the damp , lichen - covered stone walls of the gorge . in the background , the oppressive gothic silhouette of the eyrie looms far above , a precarious spire of white stone clinging to the mountain peak , barely visible through the haze . every detail is tactile : the gritty texture of the sliding scree beneath their boots , the metallic scent of incoming snow , and the rhythmic , heavy breathing of the guards flanking them . the tension is palpable , a silent war of wills between the high - born lady and the imp , framed by the indifferent , monolithic cruelty of the westerosi highlands ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["cloak of deep charcoal grey is whipped violently by a freezing gale , the fabric frayed and salt - stained from the journey . her knuckles are white as she grips the lead rope , her eyes cold and piercing , reflecting a mother 's vengeful resolve . tyrion , dwarfed by the towering limestone cliffs , stumbles on the uneven shale . his expensive crimson doublet is torn and coated in a layer of grey dust and dried mud ; the fine velvet is matted and worn . his expression is a complex mixture of intellectual defiance and genuine fear , a slight , sardonic smirk twitching at the corner of his mouth despite the sweat - beaded skin of his forehead and the bruising around his wrists where the rough hemp rope bites deep into his flesh . the lighting is oppressive : a bruised , purple - grey twilight descends , with a pale , dying sun casting long , distorted shadows that stretch like fingers across the rocky terrain . the air is thick with a swirling mist that clings to the damp , lichen - covered stone walls of the gorge . in the background , the oppressive gothic silhouette of the eyrie looms far above , a precarious spire of white stone clinging to the mountain peak , barely visible through the haze . every detail is tactile : the gritty texture of the sliding scree beneath their boots , the metallic scent of incoming snow , and the rhythmic , heavy breathing of the guards flanking them . the tension is palpable , a silent war of wills between the high - born lady and the imp , framed by the indifferent , monolithic cruelty of the westerosi highlands ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["elements , stripped of a ceiling , allowing the oppressive , slate - grey clouds of the vale to swirl violently overhead . tyrion is huddled against the rear wall , his small frame trembling . his skin is sallow , beaded with cold sweat , and his velvet doublet is stained with grime and salt . his expression is one of raw , wide - eyed insomnia ; his pupils are dilated with the primal fear of rolling an inch too far in his sleep and plummeting to his death . standing over him is mord , the jailer , a man of grotesque cruelty . mord ’ s face is a map of pockmarks and sneers , his eyes glinting with sadistic pleasure . he holds a wooden platter of meager food , gripping it with calloused , dirt - caked fingers . the tension is electric as mord deliberately lifts the plate just out of tyrion ’ s reach , a slow , mocking gesture of power . tyrion ’ s hand is outstretched , fingers trembling , his posture desperate and diminished . the lighting is a harsh , diffused alpine glare , casting cold , blue - toned shadows that cling to the crevices of the rock . the air is thick with a visible , freezing mist that clings to the characters ' clothes . every texture is visceral : the rough , abrasive grain of the limestone , the coarse wool of mord 's tunic , and the damp , glistening moisture on the slanted floor . in the background , the dizzying drop of the mountain peaks stretches infinitely downward , a void of swirling white fog and sharp , obsidian crags , emphasizing the lethal fragility of the ledge ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["elements , stripped of a ceiling , allowing the oppressive , slate - grey clouds of the vale to swirl violently overhead . tyrion is huddled against the rear wall , his small frame trembling . his skin is sallow , beaded with cold sweat , and his velvet doublet is stained with grime and salt . his expression is one of raw , wide - eyed insomnia ; his pupils are dilated with the primal fear of rolling an inch too far in his sleep and plummeting to his death . standing over him is mord , the jailer , a man of grotesque cruelty . mord ’ s face is a map of pockmarks and sneers , his eyes glinting with sadistic pleasure . he holds a wooden platter of meager food , gripping it with calloused , dirt - caked fingers . the tension is electric as mord deliberately lifts the plate just out of tyrion ’ s reach , a slow , mocking gesture of power . tyrion ’ s hand is outstretched , fingers trembling , his posture desperate and diminished . the lighting is a harsh , diffused alpine glare , casting cold , blue - toned shadows that cling to the crevices of the rock . the air is thick with a visible , freezing mist that clings to the characters ' clothes . every texture is visceral : the rough , abrasive grain of the limestone , the coarse wool of mord 's tunic , and the damp , glistening moisture on the slanted floor . in the background , the dizzying drop of the mountain peaks stretches infinitely downward , a void of swirling white fog and sharp , obsidian crags , emphasizing the lethal fragility of the ledge ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["oppressive grey , with pale sunlight filtering through high , narrow slits , casting long , skeletal shadows across the polished stone floor . in the center of the frame , the chaos of the fight has reached its zenith . ser vardis egen , a mountain of a man encased in heavy , ornate plate armor of polished steel , is pinned helplessly beneath the massive , shattered torso of the weeping woman statue . the stone is porous and weathered , with cracks spider - webbing through the sculpture 's frozen , grieving face . vardis 's armor is scuffed and dented , the metal reflecting the dim light in dull , metallic streaks , his breathing heavy and panicked , visible as a faint mist in the chilling mountain air . standing over him is bronn , the mercenary . his posture is a contrast of lean agility and lethal intent . he wears light , worn leather brigandine and salt - stained linen that clings to his sweat - beaded skin . his face is a mask of cold , pragmatic calculation ; there is no honor in his eyes , only the professional focus of a killer . bronn grips his longsword with both hands , the steel blade shimmering with a sharp , lethal edge . he is captured in the moment of the killing blow , leaning his entire body weight forward , driving the blade downward with visceral force . the sword pierces through the gap in the armor , sliding under the knight 's arm and plunging deep into the ribs . in the background , the court watches in stunned silence . lady lysa arryn stands frozen , her face a pale mask of horror and disbelief , her fingers clutching the velvet of her gown . the atmosphere is thick with the smell of ozone , cold stone , and the metallic tang of fresh blood spilling onto the pale marble ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["oppressive grey , with pale sunlight filtering through high , narrow slits , casting long , skeletal shadows across the polished stone floor . in the center of the frame , the chaos of the fight has reached its zenith . ser vardis egen , a mountain of a man encased in heavy , ornate plate armor of polished steel , is pinned helplessly beneath the massive , shattered torso of the weeping woman statue . the stone is porous and weathered , with cracks spider - webbing through the sculpture 's frozen , grieving face . vardis 's armor is scuffed and dented , the metal reflecting the dim light in dull , metallic streaks , his breathing heavy and panicked , visible as a faint mist in the chilling mountain air . standing over him is bronn , the mercenary . his posture is a contrast of lean agility and lethal intent . he wears light , worn leather brigandine and salt - stained linen that clings to his sweat - beaded skin . his face is a mask of cold , pragmatic calculation ; there is no honor in his eyes , only the professional focus of a killer . bronn grips his longsword with both hands , the steel blade shimmering with a sharp , lethal edge . he is captured in the moment of the killing blow , leaning his entire body weight forward , driving the blade downward with visceral force . the sword pierces through the gap in the armor , sliding under the knight 's arm and plunging deep into the ribs . in the background , the court watches in stunned silence . lady lysa arryn stands frozen , her face a pale mask of horror and disbelief , her fingers clutching the velvet of her gown . the atmosphere is thick with the smell of ozone , cold stone , and the metallic tang of fresh blood spilling onto the pale marble ."]
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ["s of clouds and mountain peaks. The lighting is a cold, oppressive grey, with pale sunlight filtering through high, narrow slits, casting long, skeletal shadows across the polished stone floor. In the center of the frame, the chaos of the fight has reached its zenith. Ser Vardis Egen, a mountain of a man encased in heavy, ornate plate armor of polished steel, is pinned helplessly beneath the massive, shattered torso of the Weeping Woman statue. The stone is porous and weathered, with cracks spider-webbing through the sculpture's frozen, grieving face. Vardis's armor is scuffed and dented, the metal reflecting the dim light in dull, metallic streaks, his breathing heavy and panicked, visible as a faint mist in the chilling mountain air. Standing over him is Bronn, the mercenary. His posture is a contrast of lean agility and lethal intent. He wears light, worn leather brigandine and salt-stained linen that clings to his sweat-beaded skin. His face is a mask of cold, pragmatic calculation; there is no honor in his eyes, only the professional focus of a killer. Bronn grips his longsword with both hands, the steel blade shimmering with a sharp, lethal edge. He is captured in the moment of the killing blow, leaning his entire body weight forward, driving the blade downward with visceral force. The sword pierces through the gap in the armor, sliding under the knight's arm and plunging deep into the ribs. In the background, the court watches in stunned silence. Lady Lysa Arryn stands frozen, her face a pale mask of horror and disbelief, her fingers clutching the velvet of her gown. The atmosphere is thick with the smell of ozone, cold stone, and the metallic tang of fresh blood spilling onto the pale marble."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["the pale , oppressive light filtering through the high , narrow gothic windows . every rivet and etched groove of his cuirass is visible , catching the glint of the torchlight . opposite him , the tension is a physical weight , the silence broken only by the distant whistle of the mountain wind howling through the peaks of the vale . lysa arryn watches from her high seat , her fingers gripping the carved stone armrests until her knuckles are white . her expression is a mask of frantic desperation and maternal obsession , her eyes wide and darting , her lips pressed into a thin , trembling line . the shadows of the hall are long and jagged , stretching across the cold , grey flagstone floor which is worn smooth by centuries of footsteps . the lighting is stark and directional , a cold , wintry blue light clashing with the warm , flickering orange of the wall - mounted braziers , creating a chiaroscuro effect that deepens the hollows of the knights ' faces . ser vardis ’ s cloak , a heavy wool of deep navy , is salt - stained and frayed at the edges , contrasting with the pristine brilliance of his sword . the blade is held steady , but a single bead of sweat rolls down his temple , carving a path through the fine dust of the hall . the architecture surrounding them is oppressive ; soaring ribbed vaults and pointed arches of pale limestone that seem to lean inward , amplifying the claustrophobia of the trial . every detail , from the intricate heraldry embroidered on the banners to the microscopic cracks in the stone pillars , vibrates with the high - stakes dread of a life hanging in the balance ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["the pale , oppressive light filtering through the high , narrow gothic windows . every rivet and etched groove of his cuirass is visible , catching the glint of the torchlight . opposite him , the tension is a physical weight , the silence broken only by the distant whistle of the mountain wind howling through the peaks of the vale . lysa arryn watches from her high seat , her fingers gripping the carved stone armrests until her knuckles are white . her expression is a mask of frantic desperation and maternal obsession , her eyes wide and darting , her lips pressed into a thin , trembling line . the shadows of the hall are long and jagged , stretching across the cold , grey flagstone floor which is worn smooth by centuries of footsteps . the lighting is stark and directional , a cold , wintry blue light clashing with the warm , flickering orange of the wall - mounted braziers , creating a chiaroscuro effect that deepens the hollows of the knights ' faces . ser vardis ’ s cloak , a heavy wool of deep navy , is salt - stained and frayed at the edges , contrasting with the pristine brilliance of his sword . the blade is held steady , but a single bead of sweat rolls down his temple , carving a path through the fine dust of the hall . the architecture surrounding them is oppressive ; soaring ribbed vaults and pointed arches of pale limestone that seem to lean inward , amplifying the claustrophobia of the trial . every detail , from the intricate heraldry embroidered on the banners to the microscopic cracks in the stone pillars , vibrates with the high - stakes dread of a life hanging in the balance ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["ary work , gripping a well - used longsword with a worn leather hilt . opposite him , the opposing champion looms , clad in polished , oppressive steel that glints blindingly under the oppressive midday sun . the lighting is a harsh , vertical glare , creating deep , ink - black shadows beneath the brows and chin of the fighters , emphasizing the grit and sweat beading on bronn 's tanned skin . in the background , the towering gothic spires of the red keep loom like jagged teeth against a bleached , pale blue sky . the arena is a circle of packed ochre earth , littered with fine dust that swirls around the combatants ' boots with every subtle shift in weight . high above in the royal gallery , tyrion lannister watches with a mixture of desperation and calculated hope . his small frame is draped in heavy , crimson velvet robes that seem to swallow him , his fingers gripping the stone railing until his knuckles are white . his eyes are wide , reflecting the violent tension of the pit below , while beside him , the court nobility watches with cold , judgmental expressions , their silk garments shimmering in the heat . the air is thick with the smell of hot iron and dry earth . every detail is visceral : the etched ripples of the steel blades , the coarse weave of the linen tunics , and the micro - expressions of lethal intent on bronn 's face . the composition captures the immense scale of the architecture contrasted with the intimate , deadly proximity of the two warriors , frozen in the heartbeat before the clash ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["ary work , gripping a well - used longsword with a worn leather hilt . opposite him , the opposing champion looms , clad in polished , oppressive steel that glints blindingly under the oppressive midday sun . the lighting is a harsh , vertical glare , creating deep , ink - black shadows beneath the brows and chin of the fighters , emphasizing the grit and sweat beading on bronn 's tanned skin . in the background , the towering gothic spires of the red keep loom like jagged teeth against a bleached , pale blue sky . the arena is a circle of packed ochre earth , littered with fine dust that swirls around the combatants ' boots with every subtle shift in weight . high above in the royal gallery , tyrion lannister watches with a mixture of desperation and calculated hope . his small frame is draped in heavy , crimson velvet robes that seem to swallow him , his fingers gripping the stone railing until his knuckles are white . his eyes are wide , reflecting the violent tension of the pit below , while beside him , the court nobility watches with cold , judgmental expressions , their silk garments shimmering in the heat . the air is thick with the smell of hot iron and dry earth . every detail is visceral : the etched ripples of the steel blades , the coarse weave of the linen tunics , and the micro - expressions of lethal intent on bronn 's face . the composition captures the immense scale of the architecture contrasted with the intimate , deadly proximity of the two warriors , frozen in the heartbeat before the clash ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['young arya stark is a ghost in the dark ; her small frame is pressed tight against the cold , sweating rock , her breath held in a trembling chest . her eyes , wide and amber - dark , are fixed with intense focus on two men whispering just a few feet away . the first man is obese , his girth straining against a short , oil - slicked leather cape that smells of old sweat and cured hide . he wears a heavy steel helmet that reflects the flickering , sickly orange light of a distant torch , the metal pitted with rust and scratches . beside him stands a leaner man with a distinctive , bifurcated yellow beard that splits sharply at the chin , his expression one of predatory anticipation . the tension is palpable , a suffocating weight between them as they discuss the imminent clash between the wolf and the lion . the yellow - bearded man leans in , his voice a low , gravelly hiss , gesturing with a calloused hand as he questions why one hand of the king cannot fall if another already has . their faces are etched with malice , illuminated by a single , guttering torch that casts long , dancing silhouettes against the ribbed vaulting of the tunnel . the lighting is chiaroscuro , with violent contrasts between the deep , ink - black voids of the tunnel and the harsh , amber glow hitting the textures of the scene : the coarse weave of their woolen tunics , the glint of the steel helm , and the glistening moisture on the cavern walls . in the background , the faint , haunting silhouette of the dragon skull chamber looms , where the bleached , porous bone of ancient behemoths catches the stray light , adding a macabre , skeletal atmosphere to this nest of treason .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['young arya stark is a ghost in the dark ; her small frame is pressed tight against the cold , sweating rock , her breath held in a trembling chest . her eyes , wide and amber - dark , are fixed with intense focus on two men whispering just a few feet away . the first man is obese , his girth straining against a short , oil - slicked leather cape that smells of old sweat and cured hide . he wears a heavy steel helmet that reflects the flickering , sickly orange light of a distant torch , the metal pitted with rust and scratches . beside him stands a leaner man with a distinctive , bifurcated yellow beard that splits sharply at the chin , his expression one of predatory anticipation . the tension is palpable , a suffocating weight between them as they discuss the imminent clash between the wolf and the lion . the yellow - bearded man leans in , his voice a low , gravelly hiss , gesturing with a calloused hand as he questions why one hand of the king cannot fall if another already has . their faces are etched with malice , illuminated by a single , guttering torch that casts long , dancing silhouettes against the ribbed vaulting of the tunnel . the lighting is chiaroscuro , with violent contrasts between the deep , ink - black voids of the tunnel and the harsh , amber glow hitting the textures of the scene : the coarse weave of their woolen tunics , the glint of the steel helm , and the glistening moisture on the cavern walls . in the background , the faint , haunting silhouette of the dragon skull chamber looms , where the bleached , porous bone of ancient behemoths catches the stray light , adding a macabre , skeletal atmosphere to this nest of treason .']
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ['shadows of a narrow alcove, young Arya Stark is a ghost in the dark; her small frame is pressed tight against the cold, sweating rock, her breath held in a trembling chest. Her eyes, wide and amber-dark, are fixed with intense focus on two men whispering just a few feet away. The first man is obese, his girth straining against a short, oil-slicked leather cape that smells of old sweat and cured hide. He wears a heavy steel helmet that reflects the flickering, sickly orange light of a distant torch, the metal pitted with rust and scratches. Beside him stands a leaner man with a distinctive, bifurcated yellow beard that splits sharply at the chin, his expression one of predatory anticipation. The tension is palpable, a suffocating weight between them as they discuss the imminent clash between the Wolf and the Lion. The yellow-bearded man leans in, his voice a low, gravelly hiss, gesturing with a calloused hand as he questions why one Hand of the King cannot fall if another already has. Their faces are etched with malice, illuminated by a single, guttering torch that casts long, dancing silhouettes against the ribbed vaulting of the tunnel. The lighting is chiaroscuro, with violent contrasts between the deep, ink-black voids of the tunnel and the harsh, amber glow hitting the textures of the scene: the coarse weave of their woolen tunics, the glint of the steel helm, and the glistening moisture on the cavern walls. In the background, the faint, haunting silhouette of the dragon skull chamber looms, where the bleached, porous bone of ancient behemoths catches the stray light, adding a macabre, skeletal atmosphere to this nest of treason.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["at the edges . opposite him , a phalanx of gold cloaks — the city watch — closes in , their armor a tarnished , scratched gold that reflects the oppressive midday sun . the soldiers ' expressions are predatory , their lips curled in sneers , eyes glinting with a mixture of greed and malice . the lighting is harsh and vertical , creating deep , ink - black shadows beneath the eaves of the leaning timber - frame houses that crowd the street . shafts of blinding white light cut through the haze of floating dust and urban grime , highlighting the sweat - beaded skin on the soldiers ' foreheads and the grit embedded in the cracks of the limestone walls . ned ’ s hand rests on the pommel of his sword , the leather grip worn smooth by years of use . the tension is palpable , a vibrating silence broken only by the distant screams of the city . one guard steps forward , his breath visible as a faint mist , his hand gripping a spear with a shaft of polished ash and a tip of cold , pitted iron . the contrast is stark : ned ’ s stoic , honor - bound stillness against the jagged , aggressive energy of the city 's corruption . in the background , the red keep looms like a jagged tooth of pale red stone against a bleached , pale blue sky , its towering spires casting long , ominous shadows that seem to swallow the alleyway . every texture is visceral — the slime of the gutter , the rough grain of the wooden shutters , and the cold , metallic scent of steel and old blood hanging in the stagnant air ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["at the edges . opposite him , a phalanx of gold cloaks — the city watch — closes in , their armor a tarnished , scratched gold that reflects the oppressive midday sun . the soldiers ' expressions are predatory , their lips curled in sneers , eyes glinting with a mixture of greed and malice . the lighting is harsh and vertical , creating deep , ink - black shadows beneath the eaves of the leaning timber - frame houses that crowd the street . shafts of blinding white light cut through the haze of floating dust and urban grime , highlighting the sweat - beaded skin on the soldiers ' foreheads and the grit embedded in the cracks of the limestone walls . ned ’ s hand rests on the pommel of his sword , the leather grip worn smooth by years of use . the tension is palpable , a vibrating silence broken only by the distant screams of the city . one guard steps forward , his breath visible as a faint mist , his hand gripping a spear with a shaft of polished ash and a tip of cold , pitted iron . the contrast is stark : ned ’ s stoic , honor - bound stillness against the jagged , aggressive energy of the city 's corruption . in the background , the red keep looms like a jagged tooth of pale red stone against a bleached , pale blue sky , its towering spires casting long , ominous shadows that seem to swallow the alleyway . every texture is visceral — the slime of the gutter , the rough grain of the wooden shutters , and the cold , metallic scent of steel and old blood hanging in the stagnant air ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['sweat . in her trembling hands , she holds the massive , glistening heart of a wild stallion , still steaming in the arid heat . the organ is a deep , bruised crimson , its surface slick with thick , viscous blood that drips slowly down her wrists and stains her fingertips a dark , metallic red . her face is a mask of primal struggle ; her jaw is clenched , her eyes wide and watering from the metallic scent of raw gore , yet there is a fierce , burning determination in her gaze . beside her stands khal drogo , a towering presence of bronze skin and braided hair . his expression is initially a wall of stony indifference , his arms crossed over a chest adorned with leather and bone . however , as daenerys forces herself to consume the raw flesh , a subtle shift occurs in his micro - expressions — a softening of the brow and a glimmer of profound , unexpected pride sparking in his dark eyes . in the background , the dosh khaleen — the withered , ancient witches of the city — watch with predatory stillness . their skin is like parched parchment , draped in heavy , dust - caked silks , their eyes clouded by cataracts but sharp with judgment . they sit in the shadow of a crumbling , ancient stone archway , the gothic architecture of the city blending with the wild , untamed nature of the grasslands . the air is thick with the smell of horse sweat , dry grass , and iron . the lighting is a violent , high - contrast gold , highlighting the contrast between the raw , bloody heart and the pale , ethereal beauty of the khaleesi , capturing the exact moment of her transformation from a frightened girl into a mother of strength .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['sweat . in her trembling hands , she holds the massive , glistening heart of a wild stallion , still steaming in the arid heat . the organ is a deep , bruised crimson , its surface slick with thick , viscous blood that drips slowly down her wrists and stains her fingertips a dark , metallic red . her face is a mask of primal struggle ; her jaw is clenched , her eyes wide and watering from the metallic scent of raw gore , yet there is a fierce , burning determination in her gaze . beside her stands khal drogo , a towering presence of bronze skin and braided hair . his expression is initially a wall of stony indifference , his arms crossed over a chest adorned with leather and bone . however , as daenerys forces herself to consume the raw flesh , a subtle shift occurs in his micro - expressions — a softening of the brow and a glimmer of profound , unexpected pride sparking in his dark eyes . in the background , the dosh khaleen — the withered , ancient witches of the city — watch with predatory stillness . their skin is like parched parchment , draped in heavy , dust - caked silks , their eyes clouded by cataracts but sharp with judgment . they sit in the shadow of a crumbling , ancient stone archway , the gothic architecture of the city blending with the wild , untamed nature of the grasslands . the air is thick with the smell of horse sweat , dry grass , and iron . the lighting is a violent , high - contrast gold , highlighting the contrast between the raw , bloody heart and the pale , ethereal beauty of the khaleesi , capturing the exact moment of her transformation from a frightened girl into a mother of strength .']
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ['pale linen that clings to her skin, her forehead beaded with sweat. In her trembling hands, she holds the massive, glistening heart of a wild stallion, still steaming in the arid heat. The organ is a deep, bruised crimson, its surface slick with thick, viscous blood that drips slowly down her wrists and stains her fingertips a dark, metallic red. Her face is a mask of primal struggle; her jaw is clenched, her eyes wide and watering from the metallic scent of raw gore, yet there is a fierce, burning determination in her gaze. Beside her stands Khal Drogo, a towering presence of bronze skin and braided hair. His expression is initially a wall of stony indifference, his arms crossed over a chest adorned with leather and bone. However, as Daenerys forces herself to consume the raw flesh, a subtle shift occurs in his micro-expressions—a softening of the brow and a glimmer of profound, unexpected pride sparking in his dark eyes. In the background, the Dosh Khaleen—the withered, ancient witches of the city—watch with predatory stillness. Their skin is like parched parchment, draped in heavy, dust-caked silks, their eyes clouded by cataracts but sharp with judgment. They sit in the shadow of a crumbling, ancient stone archway, the Gothic architecture of the city blending with the wild, untamed nature of the grasslands. The air is thick with the smell of horse sweat, dry grass, and iron. The lighting is a violent, high-contrast gold, highlighting the contrast between the raw, bloody heart and the pale, ethereal beauty of the Khaleesi, capturing the exact moment of her transformation from a frightened girl into a mother of strength.']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["posture broken and desperate . his face is a mask of raw terror , eyes wide and bloodshot , skin beaded with cold sweat and grime . his fine , salt - stained linen tunic is torn , exposing a bruised shoulder where his arm hangs at an unnatural angle . standing over him is khal drogo , a towering figure of bronze skin and braided hair , his expression one of cold , detached judgment . drogo holds a heavy iron pot , the metal glowing a dull , menacing red from the intense heat of the surrounding braziers . inside the pot , a belt of golden medallions has transformed into a swirling , viscous pool of molten gold , shimmering with a violent , blinding luminosity . the lighting is dominated by the fierce orange glow of the fire , casting long , jagged silhouettes across the packed dirt . the light catches the liquid gold , creating a harsh contrast against the deepening purple of the evening sky . nearby , daenerys stands motionless , her gaze unwavering and hauntingly calm , her pale skin illuminated by the flickering flames . ser jorah stands beside her , his hand gripping her shoulder , his face etched with a mixture of pity and grim necessity . the climax captures the exact moment of execution : drogo tilts the pot with a slow , deliberate motion . a thick , glowing stream of liquid gold cascades downward , striking the crown of viserys 's head . the molten metal clings to his skin , flowing like lava over his forehead and eyes , searing the flesh instantly . there is no blood , only the hiss of evaporating moisture and the blinding brilliance of the gold hardening into a grotesque , permanent mask . the texture of the cooling metal is pitted and iridescent , fusing with the charred remnants of his hair ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["posture broken and desperate . his face is a mask of raw terror , eyes wide and bloodshot , skin beaded with cold sweat and grime . his fine , salt - stained linen tunic is torn , exposing a bruised shoulder where his arm hangs at an unnatural angle . standing over him is khal drogo , a towering figure of bronze skin and braided hair , his expression one of cold , detached judgment . drogo holds a heavy iron pot , the metal glowing a dull , menacing red from the intense heat of the surrounding braziers . inside the pot , a belt of golden medallions has transformed into a swirling , viscous pool of molten gold , shimmering with a violent , blinding luminosity . the lighting is dominated by the fierce orange glow of the fire , casting long , jagged silhouettes across the packed dirt . the light catches the liquid gold , creating a harsh contrast against the deepening purple of the evening sky . nearby , daenerys stands motionless , her gaze unwavering and hauntingly calm , her pale skin illuminated by the flickering flames . ser jorah stands beside her , his hand gripping her shoulder , his face etched with a mixture of pity and grim necessity . the climax captures the exact moment of execution : drogo tilts the pot with a slow , deliberate motion . a thick , glowing stream of liquid gold cascades downward , striking the crown of viserys 's head . the molten metal clings to his skin , flowing like lava over his forehead and eyes , searing the flesh instantly . there is no blood , only the hiss of evaporating moisture and the blinding brilliance of the gold hardening into a grotesque , permanent mask . the texture of the cooling metal is pitted and iridescent , fusing with the charred remnants of his hair ."]
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ["erys Targaryen is pinned to the scorched earth, his posture broken and desperate. His face is a mask of raw terror, eyes wide and bloodshot, skin beaded with cold sweat and grime. His fine, salt-stained linen tunic is torn, exposing a bruised shoulder where his arm hangs at an unnatural angle. Standing over him is Khal Drogo, a towering figure of bronze skin and braided hair, his expression one of cold, detached judgment. Drogo holds a heavy iron pot, the metal glowing a dull, menacing red from the intense heat of the surrounding braziers. Inside the pot, a belt of golden medallions has transformed into a swirling, viscous pool of molten gold, shimmering with a violent, blinding luminosity. The lighting is dominated by the fierce orange glow of the fire, casting long, jagged silhouettes across the packed dirt. The light catches the liquid gold, creating a harsh contrast against the deepening purple of the evening sky. Nearby, Daenerys stands motionless, her gaze unwavering and hauntingly calm, her pale skin illuminated by the flickering flames. Ser Jorah stands beside her, his hand gripping her shoulder, his face etched with a mixture of pity and grim necessity. The climax captures the exact moment of execution: Drogo tilts the pot with a slow, deliberate motion. A thick, glowing stream of liquid gold cascades downward, striking the crown of Viserys's head. The molten metal clings to his skin, flowing like lava over his forehead and eyes, searing the flesh instantly. There is no blood, only the hiss of evaporating moisture and the blinding brilliance of the gold hardening into a grotesque, permanent mask. The texture of the cooling metal is pitted and iridescent, fusing with the charred remnants of his hair."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["glows against the deepening gloom . the trees ' leaves are a violent , bleeding crimson , contrasting sharply with the obsidian - black soil and the pale frost coating the gnarled roots . jon snow and samwell tarly stand side - by - side , their figures small and fragile against the towering , sentient architecture of the grove . jon ’ s posture is rigid , his jaw clenched with a solemn , ancestral weight , his dark eyes reflecting the haunting red of the leaves . his skin is weathered , beaded with cold sweat and dusted with frost . beside him , samwell is trembling , his breath emerging in heavy , ragged plumes of white vapor ; his expression is a mixture of sheer terror and desperate resolve , his oversized black cloak swallowing his frame . they are draped in the heavy , coarse wool of the night 's watch — thick , salt - stained black linen and boiled leather that looks worn and oppressive . the texture of the fabric is rough and tactile , capturing the grime of the north . facing them is the septon , his robes a muted charcoal , his face etched with deep , parchment - like wrinkles . the lighting is ethereal and directional , with the dying light of a winter sun casting long , jagged silhouettes across the snow . the red sap of the weirwood trees looks like fresh blood weeping from the carved , screaming faces in the white bark . the atmosphere is heavy with a suffocating silence , broken only by the distant , mournful howl of a wolf , emphasizing the isolation of the wall and the permanence of the oath they are swearing ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["glows against the deepening gloom . the trees ' leaves are a violent , bleeding crimson , contrasting sharply with the obsidian - black soil and the pale frost coating the gnarled roots . jon snow and samwell tarly stand side - by - side , their figures small and fragile against the towering , sentient architecture of the grove . jon ’ s posture is rigid , his jaw clenched with a solemn , ancestral weight , his dark eyes reflecting the haunting red of the leaves . his skin is weathered , beaded with cold sweat and dusted with frost . beside him , samwell is trembling , his breath emerging in heavy , ragged plumes of white vapor ; his expression is a mixture of sheer terror and desperate resolve , his oversized black cloak swallowing his frame . they are draped in the heavy , coarse wool of the night 's watch — thick , salt - stained black linen and boiled leather that looks worn and oppressive . the texture of the fabric is rough and tactile , capturing the grime of the north . facing them is the septon , his robes a muted charcoal , his face etched with deep , parchment - like wrinkles . the lighting is ethereal and directional , with the dying light of a winter sun casting long , jagged silhouettes across the snow . the red sap of the weirwood trees looks like fresh blood weeping from the carved , screaming faces in the white bark . the atmosphere is heavy with a suffocating silence , broken only by the distant , mournful howl of a wolf , emphasizing the isolation of the wall and the permanence of the oath they are swearing ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['wn oak table : a bastard sword encased in a sheath of matte black metal , intricately inlaid with thin , shimmering veins of silver . jon snow , his skin pale and beaded with a light sweat of anxiety , reaches out with his left hand . as he draws the blade , the steel sings — a low , lethal hum . the blade of longclaw is a marvel of valyrian steel , characterized by those signature smoky , rippling patterns that look like frozen currents of dark water . three deep , precise blood - grooves run the length of the steel , designed to lighten the heavy blade for both lethal thrusts and devastating cleaves . the focus tightens on the hilt : a stark , white stone pommel carved into the snarling head of a wolf , its jaws agape in a silent howl , with tiny , jagged shards of deep crimson garnet embedded as eyes that catch the flickering torchlight . the grip is wrapped in fresh , tight leather , contrasting with the ancient , otherworldly metal of the blade . the lighting is moody and directional ; a single , guttering hearth casts long , dancing shadows against the gothic arches of the room , bathing the scene in amber and deep charcoal tones . jon ’ s expression is a complex mixture of profound gratitude and haunting guilt , his brow furrowed , his eyes reflecting the glint of the steel . mormont watches him with a stern , fatherly gaze , the tension between them vibrating with the weight of a legacy passed from one warrior to another . dust motes dance in the shafts of dim light , highlighting the worn , salt - stained wool of their black cloaks .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['wn oak table : a bastard sword encased in a sheath of matte black metal , intricately inlaid with thin , shimmering veins of silver . jon snow , his skin pale and beaded with a light sweat of anxiety , reaches out with his left hand . as he draws the blade , the steel sings — a low , lethal hum . the blade of longclaw is a marvel of valyrian steel , characterized by those signature smoky , rippling patterns that look like frozen currents of dark water . three deep , precise blood - grooves run the length of the steel , designed to lighten the heavy blade for both lethal thrusts and devastating cleaves . the focus tightens on the hilt : a stark , white stone pommel carved into the snarling head of a wolf , its jaws agape in a silent howl , with tiny , jagged shards of deep crimson garnet embedded as eyes that catch the flickering torchlight . the grip is wrapped in fresh , tight leather , contrasting with the ancient , otherworldly metal of the blade . the lighting is moody and directional ; a single , guttering hearth casts long , dancing shadows against the gothic arches of the room , bathing the scene in amber and deep charcoal tones . jon ’ s expression is a complex mixture of profound gratitude and haunting guilt , his brow furrowed , his eyes reflecting the glint of the steel . mormont watches him with a stern , fatherly gaze , the tension between them vibrating with the weight of a legacy passed from one warrior to another . dust motes dance in the shafts of dim light , highlighting the worn , salt - stained wool of their black cloaks .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [", cavernous wound tears across his torso — the brutal work of a giant boar — where the skin is puckered , bruised in deep purples and sickly yellows , and seeped with dried , crusty gore . his skin is a pale , sweat - beaded parchment , clinging to his hollowed cheeks . lord eddard stark leans over him , his face a mask of grief and suppressed turmoil . ned ’ s fingers , calloused and trembling slightly , grip the edge of a heavy parchment . his grey eyes are clouded with a devastating secret , his brow furrowed in a micro - expression of agony as he looks upon his dying friend . robert ’ s hand , shaking and clumsy , reaches out to clutch ned ’ s forearm , the grip weak and desperate . in the periphery , the shadows are inhabited by vultures . grand maester pycelle stands stiffly , his long , bleached beard contrasting with the deep crimson of his robes , his eyes blinking with a calculating slowness . lord renly baratheon lingers in the dim light , his posture poised and detached , his polished leather boots reflecting the flickering orange glow of the hearth . ser barristan selmy stands like a sentinel of sorrow , his white cloak draped heavily over his shoulders , his gaze fixed on the floor in profound failure . the lighting is oppressive ; singular , guttering tallow candles cast long , dancing silhouettes against the gothic stone walls and heavy velvet tapestries . a single shaft of moonlight pierces through a high , narrow window , illuminating the floating dust motes and the cold , etched silver of the royal seal resting on a side table . the tension is a physical weight , a silent scream between the dying king 's trust and the silent betrayal of the truth ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [", cavernous wound tears across his torso — the brutal work of a giant boar — where the skin is puckered , bruised in deep purples and sickly yellows , and seeped with dried , crusty gore . his skin is a pale , sweat - beaded parchment , clinging to his hollowed cheeks . lord eddard stark leans over him , his face a mask of grief and suppressed turmoil . ned ’ s fingers , calloused and trembling slightly , grip the edge of a heavy parchment . his grey eyes are clouded with a devastating secret , his brow furrowed in a micro - expression of agony as he looks upon his dying friend . robert ’ s hand , shaking and clumsy , reaches out to clutch ned ’ s forearm , the grip weak and desperate . in the periphery , the shadows are inhabited by vultures . grand maester pycelle stands stiffly , his long , bleached beard contrasting with the deep crimson of his robes , his eyes blinking with a calculating slowness . lord renly baratheon lingers in the dim light , his posture poised and detached , his polished leather boots reflecting the flickering orange glow of the hearth . ser barristan selmy stands like a sentinel of sorrow , his white cloak draped heavily over his shoulders , his gaze fixed on the floor in profound failure . the lighting is oppressive ; singular , guttering tallow candles cast long , dancing silhouettes against the gothic stone walls and heavy velvet tapestries . a single shaft of moonlight pierces through a high , narrow window , illuminating the floating dust motes and the cold , etched silver of the royal seal resting on a side table . the tension is a physical weight , a silent scream between the dying king 's trust and the silent betrayal of the truth ."]
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ["a ruin of flesh. A jagged, cavernous wound tears across his torso—the brutal work of a giant boar—where the skin is puckered, bruised in deep purples and sickly yellows, and seeped with dried, crusty gore. His skin is a pale, sweat-beaded parchment, clinging to his hollowed cheeks. Lord Eddard Stark leans over him, his face a mask of grief and suppressed turmoil. Ned’s fingers, calloused and trembling slightly, grip the edge of a heavy parchment. His grey eyes are clouded with a devastating secret, his brow furrowed in a micro-expression of agony as he looks upon his dying friend. Robert’s hand, shaking and clumsy, reaches out to clutch Ned’s forearm, the grip weak and desperate. In the periphery, the shadows are inhabited by vultures. Grand Maester Pycelle stands stiffly, his long, bleached beard contrasting with the deep crimson of his robes, his eyes blinking with a calculating slowness. Lord Renly Baratheon lingers in the dim light, his posture poised and detached, his polished leather boots reflecting the flickering orange glow of the hearth. Ser Barristan Selmy stands like a sentinel of sorrow, his white cloak draped heavily over his shoulders, his gaze fixed on the floor in profound failure. The lighting is oppressive; singular, guttering tallow candles cast long, dancing silhouettes against the Gothic stone walls and heavy velvet tapestries. A single shaft of moonlight pierces through a high, narrow window, illuminating the floating dust motes and the cold, etched silver of the royal seal resting on a side table. The tension is a physical weight, a silent scream between the dying king's trust and the silent betrayal of the truth."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["ts of pale sunlight piercing through high , narrow gothic windows , illuminating swirling dust motes and the shimmering gold embroidery of the lannister guards ' tabards . in the center of the hall , lord eddard stark stands isolated , his face a mask of weathered nobility and sudden , crushing realization . his skin is sweat - beaded , his grey eyes wide with a mixture of betrayal and disbelief . surrounding him is a tightening ring of gold cloaks , their armor clashing with a harsh , metallic ring , their faces grim and opportunistic . janos slynt stands at the forefront , his expression one of smug , bureaucratic cruelty , his hand gesturing coldly to seal the perimeter . the tension peaks as petyr baelish leans in close to ned ’ s ear . littlefinger ’ s posture is feline and predatory , a sharp contrast to ned ’ s rigid , honorable stance . baelish holds a slender , polished steel dagger pressed firmly against the soft skin beneath ned ’ s jawline , forcing his head upward . the blade reflects a sliver of cold light , contrasting with the rich , velvet textures of baelish 's doublet . baelish ’ s lips are curled into a faint , mocking smile , his eyes gleaming with a calculated malice . in the background , queen cersei stands beside the throne , her posture regal and triumphant , her emerald green gown flowing like a river of silk over the cold granite . the massive pillars of the hall loom like silent giants , their intricate carvings obscured by deep , moody shadows , while the distant sound of steel clashing echoes as ned 's few remaining loyalists are cut down , their blood staining the pale grey flagstones in violent , spreading blooms of crimson ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["ts of pale sunlight piercing through high , narrow gothic windows , illuminating swirling dust motes and the shimmering gold embroidery of the lannister guards ' tabards . in the center of the hall , lord eddard stark stands isolated , his face a mask of weathered nobility and sudden , crushing realization . his skin is sweat - beaded , his grey eyes wide with a mixture of betrayal and disbelief . surrounding him is a tightening ring of gold cloaks , their armor clashing with a harsh , metallic ring , their faces grim and opportunistic . janos slynt stands at the forefront , his expression one of smug , bureaucratic cruelty , his hand gesturing coldly to seal the perimeter . the tension peaks as petyr baelish leans in close to ned ’ s ear . littlefinger ’ s posture is feline and predatory , a sharp contrast to ned ’ s rigid , honorable stance . baelish holds a slender , polished steel dagger pressed firmly against the soft skin beneath ned ’ s jawline , forcing his head upward . the blade reflects a sliver of cold light , contrasting with the rich , velvet textures of baelish 's doublet . baelish ’ s lips are curled into a faint , mocking smile , his eyes gleaming with a calculated malice . in the background , queen cersei stands beside the throne , her posture regal and triumphant , her emerald green gown flowing like a river of silk over the cold granite . the massive pillars of the hall loom like silent giants , their intricate carvings obscured by deep , moody shadows , while the distant sound of steel clashing echoes as ned 's few remaining loyalists are cut down , their blood staining the pale grey flagstones in violent , spreading blooms of crimson ."]
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ["the stone floor. The lighting is dramatic and cold, with shafts of pale sunlight piercing through high, narrow Gothic windows, illuminating swirling dust motes and the shimmering gold embroidery of the Lannister guards' tabards. In the center of the hall, Lord Eddard Stark stands isolated, his face a mask of weathered nobility and sudden, crushing realization. His skin is sweat-beaded, his grey eyes wide with a mixture of betrayal and disbelief. Surrounding him is a tightening ring of Gold Cloaks, their armor clashing with a harsh, metallic ring, their faces grim and opportunistic. Janos Slynt stands at the forefront, his expression one of smug, bureaucratic cruelty, his hand gesturing coldly to seal the perimeter. The tension peaks as Petyr Baelish leans in close to Ned’s ear. Littlefinger’s posture is feline and predatory, a sharp contrast to Ned’s rigid, honorable stance. Baelish holds a slender, polished steel dagger pressed firmly against the soft skin beneath Ned’s jawline, forcing his head upward. The blade reflects a sliver of cold light, contrasting with the rich, velvet textures of Baelish's doublet. Baelish’s lips are curled into a faint, mocking smile, his eyes gleaming with a calculated malice. In the background, Queen Cersei stands beside the throne, her posture regal and triumphant, her emerald green gown flowing like a river of silk over the cold granite. The massive pillars of the hall loom like silent giants, their intricate carvings obscured by deep, moody shadows, while the distant sound of steel clashing echoes as Ned's few remaining loyalists are cut down, their blood staining the pale grey flagstones in violent, spreading blooms of crimson."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["that cling to her skin , her silver - gold hair shimmering under the harsh zenith light . her expression is one of innocent curiosity , her violet eyes wide as she looks at a crystal goblet of deep , ruby - red wine held by a sweating , nervous merchant . beside her , ser jorah mormont is a pillar of weathered steel and vigilance . his posture is rigid , his hand resting instinctively on the pommel of his sword . his brow is furrowed , eyes narrowed in a piercing , suspicious gaze directed not at the princess , but at the merchant ’ s twitching fingers and darting eyes . the tension is palpable ; a silent , electric charge between the protector and the predator . the merchant , a gaunt man in salt - stained linens and greasy furs , wears a mask of forced hospitality , but a bead of sweat rolls down his temple , carving a path through the grime on his skin . as jorah steps forward , his voice a low rumble , demanding the merchant taste the vintage first , the man 's face contorts into a mask of sudden panic . the background is a blur of dothraki warriors in leather armor and ornate jewelry , their bronze skin glistening with sweat . to the side , the heavy , braided whip of jhogo is captured mid - snap , frozen in a blur of motion as it lashes out to ensnare the fleeing merchant . the architecture consists of sprawling , open - air pavilions with weathered canvas awnings that cast jagged , amber - hued shadows across the packed earth . the lighting is a violent , saturated gold , creating high contrast between the brilliant highlights of the targaryen silver and the deep , ink - black shadows of the market stalls . every texture is visceral : the grit of the sand , the shimmer of the poisoned wine , and the coarse weave of the dothraki fabrics ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["that cling to her skin , her silver - gold hair shimmering under the harsh zenith light . her expression is one of innocent curiosity , her violet eyes wide as she looks at a crystal goblet of deep , ruby - red wine held by a sweating , nervous merchant . beside her , ser jorah mormont is a pillar of weathered steel and vigilance . his posture is rigid , his hand resting instinctively on the pommel of his sword . his brow is furrowed , eyes narrowed in a piercing , suspicious gaze directed not at the princess , but at the merchant ’ s twitching fingers and darting eyes . the tension is palpable ; a silent , electric charge between the protector and the predator . the merchant , a gaunt man in salt - stained linens and greasy furs , wears a mask of forced hospitality , but a bead of sweat rolls down his temple , carving a path through the grime on his skin . as jorah steps forward , his voice a low rumble , demanding the merchant taste the vintage first , the man 's face contorts into a mask of sudden panic . the background is a blur of dothraki warriors in leather armor and ornate jewelry , their bronze skin glistening with sweat . to the side , the heavy , braided whip of jhogo is captured mid - snap , frozen in a blur of motion as it lashes out to ensnare the fleeing merchant . the architecture consists of sprawling , open - air pavilions with weathered canvas awnings that cast jagged , amber - hued shadows across the packed earth . the lighting is a violent , saturated gold , creating high contrast between the brilliant highlights of the targaryen silver and the deep , ink - black shadows of the market stalls . every texture is visceral : the grit of the sand , the shimmer of the poisoned wine , and the coarse weave of the dothraki fabrics ."]
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ["ar. She is dressed in flowing, sun-bleached silks that cling to her skin, her silver-gold hair shimmering under the harsh zenith light. Her expression is one of innocent curiosity, her violet eyes wide as she looks at a crystal goblet of deep, ruby-red wine held by a sweating, nervous merchant. Beside her, Ser Jorah Mormont is a pillar of weathered steel and vigilance. His posture is rigid, his hand resting instinctively on the pommel of his sword. His brow is furrowed, eyes narrowed in a piercing, suspicious gaze directed not at the princess, but at the merchant’s twitching fingers and darting eyes. The tension is palpable; a silent, electric charge between the protector and the predator. The merchant, a gaunt man in salt-stained linens and greasy furs, wears a mask of forced hospitality, but a bead of sweat rolls down his temple, carving a path through the grime on his skin. As Jorah steps forward, his voice a low rumble, demanding the merchant taste the vintage first, the man's face contorts into a mask of sudden panic. The background is a blur of Dothraki warriors in leather armor and ornate jewelry, their bronze skin glistening with sweat. To the side, the heavy, braided whip of Jhogo is captured mid-snap, frozen in a blur of motion as it lashes out to ensnare the fleeing merchant. The architecture consists of sprawling, open-air pavilions with weathered canvas awnings that cast jagged, amber-hued shadows across the packed earth. The lighting is a violent, saturated gold, creating high contrast between the brilliant highlights of the Targaryen silver and the deep, ink-black shadows of the market stalls. Every texture is visceral: the grit of the sand, the shimmer of the poisoned wine, and the coarse weave of the Dothraki fabrics."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [", lethal fury , his dark eyes narrowed and fixed on the trembling wretch before him . the wine merchant , stripped naked and shivering , is bound with coarse , salt - stained hemp ropes to the ornate , gilded wheel of daenerys ’ s heavy wooden carriage . the merchant 's skin is pale , slick with a mixture of cold sweat and filth , his face contorted in a silent , wide - mouthed scream of terror . beside drogo stands daenerys , her posture shifting from the fragile girl she once was to a poised khaleesi . she wears a gown of sheer , flowing cream silk that flutters in the arid breeze , the fabric clinging to her skin . her violet eyes are wide , reflecting the flickering orange glow of nearby braziers , her lips parted in a mixture of shock and newfound empowerment . the tension between them is electric ; drogo ’ s hand rests heavily on the hilt of his arakh , the curved blade ’ s steel reflecting the dying light with a sharp , silver glint . the environment is a chaotic tapestry of the great grass sea : towering , golden stalks of grass sway violently in the background , while the distant silhouettes of thousands of dothraki screamers on horseback create a jagged horizon . the lighting is dramatic and high - contrast , with the deep crimson of the setting sun casting long , distorted shadows across the dusty earth . every detail is tactile : the rough grain of the carriage 's weathered wood , the intricate leather braiding of drogo 's chest harness , and the fine , shimmering dust motes dancing in the air . the scene captures the exact moment of a vow — the air thick with the scent of horse sweat and ozone — as drogo declares his intent to cross the salt sea and conquer the seven kingdoms ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [", lethal fury , his dark eyes narrowed and fixed on the trembling wretch before him . the wine merchant , stripped naked and shivering , is bound with coarse , salt - stained hemp ropes to the ornate , gilded wheel of daenerys ’ s heavy wooden carriage . the merchant 's skin is pale , slick with a mixture of cold sweat and filth , his face contorted in a silent , wide - mouthed scream of terror . beside drogo stands daenerys , her posture shifting from the fragile girl she once was to a poised khaleesi . she wears a gown of sheer , flowing cream silk that flutters in the arid breeze , the fabric clinging to her skin . her violet eyes are wide , reflecting the flickering orange glow of nearby braziers , her lips parted in a mixture of shock and newfound empowerment . the tension between them is electric ; drogo ’ s hand rests heavily on the hilt of his arakh , the curved blade ’ s steel reflecting the dying light with a sharp , silver glint . the environment is a chaotic tapestry of the great grass sea : towering , golden stalks of grass sway violently in the background , while the distant silhouettes of thousands of dothraki screamers on horseback create a jagged horizon . the lighting is dramatic and high - contrast , with the deep crimson of the setting sun casting long , distorted shadows across the dusty earth . every detail is tactile : the rough grain of the carriage 's weathered wood , the intricate leather braiding of drogo 's chest harness , and the fine , shimmering dust motes dancing in the air . the scene captures the exact moment of a vow — the air thick with the scent of horse sweat and ozone — as drogo declares his intent to cross the salt sea and conquer the seven kingdoms ."]
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ["—cascading down his back. His expression is a mask of cold, lethal fury, his dark eyes narrowed and fixed on the trembling wretch before him. The wine merchant, stripped naked and shivering, is bound with coarse, salt-stained hemp ropes to the ornate, gilded wheel of Daenerys’s heavy wooden carriage. The merchant's skin is pale, slick with a mixture of cold sweat and filth, his face contorted in a silent, wide-mouthed scream of terror. Beside Drogo stands Daenerys, her posture shifting from the fragile girl she once was to a poised Khaleesi. She wears a gown of sheer, flowing cream silk that flutters in the arid breeze, the fabric clinging to her skin. Her violet eyes are wide, reflecting the flickering orange glow of nearby braziers, her lips parted in a mixture of shock and newfound empowerment. The tension between them is electric; Drogo’s hand rests heavily on the hilt of his arakh, the curved blade’s steel reflecting the dying light with a sharp, silver glint. The environment is a chaotic tapestry of the Great Grass Sea: towering, golden stalks of grass sway violently in the background, while the distant silhouettes of thousands of Dothraki screamers on horseback create a jagged horizon. The lighting is dramatic and high-contrast, with the deep crimson of the setting sun casting long, distorted shadows across the dusty earth. Every detail is tactile: the rough grain of the carriage's weathered wood, the intricate leather braiding of Drogo's chest harness, and the fine, shimmering dust motes dancing in the air. The scene captures the exact moment of a vow—the air thick with the scent of horse sweat and ozone—as Drogo declares his intent to cross the salt sea and conquer the Seven Kingdoms."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["ces through a high window , illuminating swirling dust motes and the frost - rimed breath of the gathered lords . at the center of the chaos , great jon umber stands as a mountain of a man , his face a mask of weathered leather and booming arrogance . his massive hand grips the hilt of a colossal greatsword , the steel singing as it is ripped from its scabbard in a blur of polished silver . he looms over robb stark , who stands rigid , his young face pale but his jaw locked in a desperate imitation of his father 's resolve . robb 's fingers clutch the hilt of his own blade , his knuckles white , sweat beading on his forehead despite the biting chill . in a sudden , explosive blur of silver - grey fur , grey wind lunges . the direwolf is a streak of primal fury , his muscles rippling beneath a thick , coarse coat . the wolf 's jaws snap shut with a sickening , wet crunch on great jon 's hand . blood , a vivid and shocking crimson , sprays across the grey stone floor , splashing against the worn , salt - stained leather of the lords ' boots . great jon 's expression shifts instantly from dominance to a wide - eyed , guttural shock , his mouth open in a silent roar of agony as two fingers are torn clean away . in the periphery , roose bolton watches with a predatory stillness , his pale , colorless eyes devoid of emotion , his posture unnervingly limp . the contrast is stark : the visceral violence of the wolf , the raw pain of the umber , and the cold , calculating silence of the bolton . the lighting casts long , jagged silhouettes across the hall , framing the scene in a chiaroscuro of power , blood , and the brutal law of the north ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["ces through a high window , illuminating swirling dust motes and the frost - rimed breath of the gathered lords . at the center of the chaos , great jon umber stands as a mountain of a man , his face a mask of weathered leather and booming arrogance . his massive hand grips the hilt of a colossal greatsword , the steel singing as it is ripped from its scabbard in a blur of polished silver . he looms over robb stark , who stands rigid , his young face pale but his jaw locked in a desperate imitation of his father 's resolve . robb 's fingers clutch the hilt of his own blade , his knuckles white , sweat beading on his forehead despite the biting chill . in a sudden , explosive blur of silver - grey fur , grey wind lunges . the direwolf is a streak of primal fury , his muscles rippling beneath a thick , coarse coat . the wolf 's jaws snap shut with a sickening , wet crunch on great jon 's hand . blood , a vivid and shocking crimson , sprays across the grey stone floor , splashing against the worn , salt - stained leather of the lords ' boots . great jon 's expression shifts instantly from dominance to a wide - eyed , guttural shock , his mouth open in a silent roar of agony as two fingers are torn clean away . in the periphery , roose bolton watches with a predatory stillness , his pale , colorless eyes devoid of emotion , his posture unnervingly limp . the contrast is stark : the visceral violence of the wolf , the raw pain of the umber , and the cold , calculating silence of the bolton . the lighting casts long , jagged silhouettes across the hall , framing the scene in a chiaroscuro of power , blood , and the brutal law of the north ."]
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ["s. A single, violent shaft of pale northern light pierces through a high window, illuminating swirling dust motes and the frost-rimed breath of the gathered lords. At the center of the chaos, Great Jon Umber stands as a mountain of a man, his face a mask of weathered leather and booming arrogance. His massive hand grips the hilt of a colossal greatsword, the steel singing as it is ripped from its scabbard in a blur of polished silver. He looms over Robb Stark, who stands rigid, his young face pale but his jaw locked in a desperate imitation of his father's resolve. Robb's fingers clutch the hilt of his own blade, his knuckles white, sweat beading on his forehead despite the biting chill. In a sudden, explosive blur of silver-grey fur, Grey Wind lunges. The direwolf is a streak of primal fury, his muscles rippling beneath a thick, coarse coat. The wolf's jaws snap shut with a sickening, wet crunch on Great Jon's hand. Blood, a vivid and shocking crimson, sprays across the grey stone floor, splashing against the worn, salt-stained leather of the lords' boots. Great Jon's expression shifts instantly from dominance to a wide-eyed, guttural shock, his mouth open in a silent roar of agony as two fingers are torn clean away. In the periphery, Roose Bolton watches with a predatory stillness, his pale, colorless eyes devoid of emotion, his posture unnervingly limp. The contrast is stark: the visceral violence of the wolf, the raw pain of the Umber, and the cold, calculating silence of the Bolton. The lighting casts long, jagged silhouettes across the hall, framing the scene in a chiaroscuro of power, blood, and the brutal law of the North."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["the heavy velvet fabric now sodden and clinging to his small frame . his face is a mask of grime and sweat , a jagged , raw wound weeping blood across his cheek , his eyes wide with a mixture of adrenaline - fueled terror and a sharp , intellectual realization of the trap . he is flanked by the rugged , feral warriors of the mountain clans ; these men are towering , wild - eyed brutes clad in cured furs and rusted chainmail , their skin weathered like old leather , shouting guttural war cries . beside tyrion , bronn stands with a predatory grace , his worn leather armor splattered with gore , a cynical , half - smirk playing on his lips as he pivots his blade to deflect a northern strike . the environment is a nightmare of gothic brutality : the ground is a churned slurry of black peat and crimson pools , littered with shattered ash - wood shields and the corpses of fallen horses . in the distance , the lannister banners — the golden lion on a field of crimson — snap violently in the wind , partially obscured by the thick , acrid smoke of burning encampments . the lighting is oppressive and cold , a diffused , pale light filtering through heavy storm clouds , creating deep , charcoal shadows in the folds of the soldiers ' cloaks . every texture is magnified : the cold glint of etched steel , the coarse weave of salt - stained linen , and the glistening , wet sheen of the mud . the tension is palpable , a snapshot of the moment tyrion realizes he and his vanguard were merely bait in his father 's cold , calculated game of war ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["the heavy velvet fabric now sodden and clinging to his small frame . his face is a mask of grime and sweat , a jagged , raw wound weeping blood across his cheek , his eyes wide with a mixture of adrenaline - fueled terror and a sharp , intellectual realization of the trap . he is flanked by the rugged , feral warriors of the mountain clans ; these men are towering , wild - eyed brutes clad in cured furs and rusted chainmail , their skin weathered like old leather , shouting guttural war cries . beside tyrion , bronn stands with a predatory grace , his worn leather armor splattered with gore , a cynical , half - smirk playing on his lips as he pivots his blade to deflect a northern strike . the environment is a nightmare of gothic brutality : the ground is a churned slurry of black peat and crimson pools , littered with shattered ash - wood shields and the corpses of fallen horses . in the distance , the lannister banners — the golden lion on a field of crimson — snap violently in the wind , partially obscured by the thick , acrid smoke of burning encampments . the lighting is oppressive and cold , a diffused , pale light filtering through heavy storm clouds , creating deep , charcoal shadows in the folds of the soldiers ' cloaks . every texture is magnified : the cold glint of etched steel , the coarse weave of salt - stained linen , and the glistening , wet sheen of the mud . the tension is palpable , a snapshot of the moment tyrion realizes he and his vanguard were merely bait in his father 's cold , calculated game of war ."]
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ["that stains his ornate, crimson-and-gold doublet, the heavy velvet fabric now sodden and clinging to his small frame. His face is a mask of grime and sweat, a jagged, raw wound weeping blood across his cheek, his eyes wide with a mixture of adrenaline-fueled terror and a sharp, intellectual realization of the trap. He is flanked by the rugged, feral warriors of the Mountain Clans; these men are towering, wild-eyed brutes clad in cured furs and rusted chainmail, their skin weathered like old leather, shouting guttural war cries. Beside Tyrion, Bronn stands with a predatory grace, his worn leather armor splattered with gore, a cynical, half-smirk playing on his lips as he pivots his blade to deflect a Northern strike. The environment is a nightmare of Gothic brutality: the ground is a churned slurry of black peat and crimson pools, littered with shattered ash-wood shields and the corpses of fallen horses. In the distance, the Lannister banners—the golden lion on a field of crimson—snap violently in the wind, partially obscured by the thick, acrid smoke of burning encampments. The lighting is oppressive and cold, a diffused, pale light filtering through heavy storm clouds, creating deep, charcoal shadows in the folds of the soldiers' cloaks. Every texture is magnified: the cold glint of etched steel, the coarse weave of salt-stained linen, and the glistening, wet sheen of the mud. The tension is palpable, a snapshot of the moment Tyrion realizes he and his vanguard were merely bait in his father's cold, calculated game of war."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["of rime ice clinging to his auburn beard and eyelashes . opposite him , osha is forced to her knees , her breath blooming in thick , white plumes in the frigid air . her expression is a volatile mix of feral defiance and calculated fear , her eyes darting between the circle of steel surrounding her . the environment is a suffocating expanse of towering sentinel trees , their bark gnarled and silver - grey , draped in heavy , sagging blankets of snow . the lighting is a cold , oppressive twilight ; a pale , filtered blue light seeps through the dense canopy , creating deep , ink - black shadows that swallow the forest floor . high - contrast lighting catches the glint of polished steel from the surrounding stark guards , whose armor is etched with the wear of travel , showing scratches and salt - stains . extreme detail is focused on the textures : the coarse , woven grain of osha 's rough - hewn furs , the intricate , hammered rivets of the soldiers ' leather bracers , and the crystalline structure of the fresh snow being crushed under heavy leather boots . a single , stray droplet of blood stains the pristine white snow near osha 's knee , a vivid , visceral crimson . the air feels heavy and damp , almost tangible , with a light flurry of snowflakes drifting slowly through the scene , some landing and melting on the sweat - beaded skin of the soldiers ' foreheads . the tension is electric , a silent war of wills played out in the oppressive silence of the north , where the only sound is the distant , haunting moan of the wind through the frozen pines ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["of rime ice clinging to his auburn beard and eyelashes . opposite him , osha is forced to her knees , her breath blooming in thick , white plumes in the frigid air . her expression is a volatile mix of feral defiance and calculated fear , her eyes darting between the circle of steel surrounding her . the environment is a suffocating expanse of towering sentinel trees , their bark gnarled and silver - grey , draped in heavy , sagging blankets of snow . the lighting is a cold , oppressive twilight ; a pale , filtered blue light seeps through the dense canopy , creating deep , ink - black shadows that swallow the forest floor . high - contrast lighting catches the glint of polished steel from the surrounding stark guards , whose armor is etched with the wear of travel , showing scratches and salt - stains . extreme detail is focused on the textures : the coarse , woven grain of osha 's rough - hewn furs , the intricate , hammered rivets of the soldiers ' leather bracers , and the crystalline structure of the fresh snow being crushed under heavy leather boots . a single , stray droplet of blood stains the pristine white snow near osha 's knee , a vivid , visceral crimson . the air feels heavy and damp , almost tangible , with a light flurry of snowflakes drifting slowly through the scene , some landing and melting on the sweat - beaded skin of the soldiers ' foreheads . the tension is electric , a silent war of wills played out in the oppressive silence of the north , where the only sound is the distant , haunting moan of the wind through the frozen pines ."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["tes and the frantic movements of a macabre ritual . at the center of the scene , khal drogo lies prone and broken , his bronze skin now a sickly , pallid grey , sweat - beaded and glistening under the oppressive heat . he is partially submerged in a shallow , crimson pool of horse 's blood , the liquid reflecting the violent orange hues of the tent 's interior . mirri maz duur , the maegi , leans over him with a predatory intensity . her weathered , parchment - like skin is etched with deep wrinkles , and her eyes are wide with a terrifying , occult focus . her hands , stained dark with gore , gesture wildly as she chants , her lips curled in a sneer of arcane power . daenerys targaryen is collapsed on the dirt floor , her posture one of utter devastation . her silver - gold hair is matted with dust and sweat , clinging to her pale , tear - streaked cheeks . her eyes are wide , pupils dilated in a mixture of horror and desperate hope , her small hands clutching the coarse , salt - stained linen of her gown . beside her , ser jorah mormont stands as a battered sentinel ; his leather armor is scuffed and splattered with blood , his expression a grim mask of protective agony . his hand grips the hilt of his sword , knuckles white , as he glances warily toward the tent entrance where the shadows of terrified bloodriders flicker . the environment is a clash of textures : the rough , woven hemp of the tent walls , the slick , viscous surface of the blood - bath , and the jagged edges of ceremonial bone charms hanging from the ceiling . ethereal , ink - black shadows dance unnaturally across the canvas , twisting into distorted shapes that defy the laws of light , signaling the arrival of the dark magic of asshai ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ["tes and the frantic movements of a macabre ritual . at the center of the scene , khal drogo lies prone and broken , his bronze skin now a sickly , pallid grey , sweat - beaded and glistening under the oppressive heat . he is partially submerged in a shallow , crimson pool of horse 's blood , the liquid reflecting the violent orange hues of the tent 's interior . mirri maz duur , the maegi , leans over him with a predatory intensity . her weathered , parchment - like skin is etched with deep wrinkles , and her eyes are wide with a terrifying , occult focus . her hands , stained dark with gore , gesture wildly as she chants , her lips curled in a sneer of arcane power . daenerys targaryen is collapsed on the dirt floor , her posture one of utter devastation . her silver - gold hair is matted with dust and sweat , clinging to her pale , tear - streaked cheeks . her eyes are wide , pupils dilated in a mixture of horror and desperate hope , her small hands clutching the coarse , salt - stained linen of her gown . beside her , ser jorah mormont stands as a battered sentinel ; his leather armor is scuffed and splattered with blood , his expression a grim mask of protective agony . his hand grips the hilt of his sword , knuckles white , as he glances warily toward the tent entrance where the shadows of terrified bloodriders flicker . the environment is a clash of textures : the rough , woven hemp of the tent walls , the slick , viscous surface of the blood - bath , and the jagged edges of ceremonial bone charms hanging from the ceiling . ethereal , ink - black shadows dance unnaturally across the canvas , twisting into distorted shapes that defy the laws of light , signaling the arrival of the dark magic of asshai ."]
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ["of swirling incense to illuminate floating dust motes and the frantic movements of a macabre ritual. At the center of the scene, Khal Drogo lies prone and broken, his bronze skin now a sickly, pallid grey, sweat-beaded and glistening under the oppressive heat. He is partially submerged in a shallow, crimson pool of horse's blood, the liquid reflecting the violent orange hues of the tent's interior. Mirri Maz Duur, the maegi, leans over him with a predatory intensity. Her weathered, parchment-like skin is etched with deep wrinkles, and her eyes are wide with a terrifying, occult focus. Her hands, stained dark with gore, gesture wildly as she chants, her lips curled in a sneer of arcane power. Daenerys Targaryen is collapsed on the dirt floor, her posture one of utter devastation. Her silver-gold hair is matted with dust and sweat, clinging to her pale, tear-streaked cheeks. Her eyes are wide, pupils dilated in a mixture of horror and desperate hope, her small hands clutching the coarse, salt-stained linen of her gown. Beside her, Ser Jorah Mormont stands as a battered sentinel; his leather armor is scuffed and splattered with blood, his expression a grim mask of protective agony. His hand grips the hilt of his sword, knuckles white, as he glances warily toward the tent entrance where the shadows of terrified bloodriders flicker. The environment is a clash of textures: the rough, woven hemp of the tent walls, the slick, viscous surface of the blood-bath, and the jagged edges of ceremonial bone charms hanging from the ceiling. Ethereal, ink-black shadows dance unnaturally across the canvas, twisting into distorted shapes that defy the laws of light, signaling the arrival of the dark magic of Asshai."]

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['the textures worn and salt - stained from the march . his auburn hair is damp with sweat , clinging to a forehead furrowed in hesitation . around him , the air vibrates with the roar of northern lords . the lighting is dramatic and directional ; massive iron braziers cast violent , dancing orange glows that carve deep , jagged shadows into the gothic arches of the hall . the flickering light catches the smoky ripples of valyrian steel and the cold glint of iron as weapons are drawn . great jon umber , a mountain of a man in rough - hewn furs and rusted mail , crashes to one knee . the sound of his heavy broadsword clattering against the cold , grey flagstones echoes like a thunderclap . the tension is palpable in the micro - expressions : the fierce , unwavering loyalty in the eyes of rickard karstark , the stern resolve of maege mormont , and the wide - eyed , hopeful desperation of the river lords . catelyn stark stands in the periphery , her face a mask of maternal terror and pride , her fingers gripping the fabric of her gown so tightly her knuckles are white . as the chorus of " the king in the north !" erupts , the sound becomes a physical force . dust motes dance in the shafts of dim light piercing through high , narrow windows . the scene is a collision of raw emotion and cold steel , capturing the exact heartbeat where a son becomes a sovereign , framed by the oppressive , ancient architecture of the tully stronghold and the suffocating heat of a hundred shouting men .']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['the textures worn and salt - stained from the march . his auburn hair is damp with sweat , clinging to a forehead furrowed in hesitation . around him , the air vibrates with the roar of northern lords . the lighting is dramatic and directional ; massive iron braziers cast violent , dancing orange glows that carve deep , jagged shadows into the gothic arches of the hall . the flickering light catches the smoky ripples of valyrian steel and the cold glint of iron as weapons are drawn . great jon umber , a mountain of a man in rough - hewn furs and rusted mail , crashes to one knee . the sound of his heavy broadsword clattering against the cold , grey flagstones echoes like a thunderclap . the tension is palpable in the micro - expressions : the fierce , unwavering loyalty in the eyes of rickard karstark , the stern resolve of maege mormont , and the wide - eyed , hopeful desperation of the river lords . catelyn stark stands in the periphery , her face a mask of maternal terror and pride , her fingers gripping the fabric of her gown so tightly her knuckles are white . as the chorus of " the king in the north !" erupts , the sound becomes a physical force . dust motes dance in the shafts of dim light piercing through high , narrow windows . the scene is a collision of raw emotion and cold steel , capturing the exact heartbeat where a son becomes a sovereign , framed by the oppressive , ancient architecture of the tully stronghold and the suffocating heat of a hundred shouting men .']

  0%|          | 0/28 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [", blood - red comet streaks across the charcoal sky , casting a sinister , crimson luminescence that carves deep , jagged shadows across the wasteland . daenerys targaryen emerges from the cooling white ash , her skin glistening with a mixture of sweat and soot , miraculously unburned . she is nude , her vulnerability contrasting with her newfound power . her iconic platinum hair is gone , leaving her scalp exposed and raw . she stands with a regal , primal posture , her chest heaving with slow , rhythmic breaths . clinging to her skin are three newborn dragons : one a deep , obsidian black with scales like polished onyx , another a vibrant , emerald green , and the third a shimmering cream - and - gold . their tiny , translucent wings flutter , and their needle - like claws grip her damp skin , leaving faint red marks . their eyes are slits of molten gold , blinking with ancient intelligence . surrounding the pyre , the remnants of the khalasar — gaunt elders , weeping women , and freed slaves in salt - stained , tattered linens — are frozen in collective awe . ser jorah mormont , his leather armor dusted in grey soot and his face etched with disbelief , is captured mid - motion , sinking to one knee . his expression is a complex blend of terror and religious devotion . the background is a desolate dothraki sea , the grass burnt to a crisp , under the oppressive glow of the red star . the lighting is high - contrast , with the orange glow of the remaining embers illuminating the underside of the dragons ' wings and the determined , ethereal gaze of the mother of dragons ."]
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [", blood - red comet streaks across the charcoal sky , casting a sinister , crimson luminescence that carves deep , jagged shadows across the wasteland . daenerys targaryen emerges from the cooling white ash , her skin glistening with a mixture of sweat and soot , miraculously unburned . she is nude , her vulnerability contrasting with her newfound power . her iconic platinum hair is gone , leaving her scalp exposed and raw . she stands with a regal , primal posture , her chest heaving with slow , rhythmic breaths . clinging to her skin are three newborn dragons : one a deep , obsidian black with scales like polished onyx , another a vibrant , emerald green , and the third a shimmering cream - and - gold . their tiny , translucent wings flutter , and their needle - like claws grip her damp skin , leaving faint red marks . their eyes are slits of molten gold , blinking with ancient intelligence . surrounding the pyre , the remnants of the khalasar — gaunt elders , weeping women , and freed slaves in salt - stained , tattered linens — are frozen in collective awe . ser jorah mormont , his leather armor dusted in grey soot and his face etched with disbelief , is captured mid - motion , sinking to one knee . his expression is a complex blend of terror and religious devotion . the background is a desolate dothraki sea , the grass burnt to a crisp , under the oppressive glow of the red star . the lighting is high - contrast , with the orange glow of the remaining embers illuminating the underside of the dragons ' wings and the determined , ethereal gaze of the mother of dragons ."]
The following part of your input was truncated because `max_sequence_length` is set to  512 tokens: ["e smolder, the embers glowing like dying stars in the dim, oppressive light. A violent, blood-red comet streaks across the charcoal sky, casting a sinister, crimson luminescence that carves deep, jagged shadows across the wasteland. Daenerys Targaryen emerges from the cooling white ash, her skin glistening with a mixture of sweat and soot, miraculously unburned. She is nude, her vulnerability contrasting with her newfound power. Her iconic platinum hair is gone, leaving her scalp exposed and raw. She stands with a regal, primal posture, her chest heaving with slow, rhythmic breaths. Clinging to her skin are three newborn dragons: one a deep, obsidian black with scales like polished onyx, another a vibrant, emerald green, and the third a shimmering cream-and-gold. Their tiny, translucent wings flutter, and their needle-like claws grip her damp skin, leaving faint red marks. Their eyes are slits of molten gold, blinking with ancient intelligence. Surrounding the pyre, the remnants of the khalasar—gaunt elders, weeping women, and freed slaves in salt-stained, tattered linens—are frozen in collective awe. Ser Jorah Mormont, his leather armor dusted in grey soot and his face etched with disbelief, is captured mid-motion, sinking to one knee. His expression is a complex blend of terror and religious devotion. The background is a desolate Dothraki sea, the grass burnt to a crisp, under the oppressive glow of the red star. The lighting is high-contrast, with the orange glow of the remaining embers illuminating the underside of the dragons' wings and the determined, ethereal gaze of the Mother of Dragons."]

  0%|          | 0/28 [00:00<?, ?it/s]

Metadata guardado en: /content/drive/MyDrive/Proyecto NLP y DL/Imagen_Generacion/generated_images_sd3/sd3_medium/prueba_1960chars_sd3_conResumen/metadata.json
Resumen: {'total_rows': 50, 'ok': 50, 'errors': 0, 'skipped_existing': 0}

Liberando modelo: sd3_medium

====================================================================================================
GENERACIÓN COMPLETA
Resumen guardado en: /content/drive/MyDrive/Proyecto NLP y DL/Imagen_Generacion/generated_images_sd3/run_summary.json
====================================================================================================

,model_alias,model_id,source_file,total_rows,ok,errors,skipped_existing,metadata_path
0,sd35_large,stabilityai/stable-diffusion-3.5-large,prueba_500chars_sd3.jsonl,50,50,0,0,/content/drive/MyDrive/Proyecto NLP y DL/Image...
1,sd35_large,stabilityai/stable-diffusion-3.5-large,prueba_1013chars_sd3_inicial.jsonl,50,50,0,0,/content/drive/MyDrive/Proyecto NLP y DL/Image...
2,sd35_large,stabilityai/stable-diffusion-3.5-large,prueba_1960chars_sd3_conResumen.jsonl,50,50,0,0,/content/drive/MyDrive/Proyecto NLP y DL/Image...
3,sd3_medium,stabilityai/stable-diffusion-3-medium-diffusers,prueba_500chars_sd3.jsonl,50,50,0,0,/content/drive/MyDrive/Proyecto NLP y DL/Image...
4,sd3_medium,stabilityai/stable-diffusion-3-medium-diffusers,prueba_1013chars_sd3_inicial.jsonl,50,50,0,0,/content/drive/MyDrive/Proyecto NLP y DL/Image...
5,sd3_medium,stabilityai/stable-diffusion-3-medium-diffusers,prueba_1960chars_sd3_conResumen.jsonl,50,50,0,0,/content/drive/MyDrive/Proyecto NLP y DL/Image...

In [8]:
# ============================================================
# OPTIONAL: VIEW SUMMARY
# ============================================================

summary_df = pd.DataFrame(summary)
display(summary_df)

,model_alias,model_id,source_file,total_rows,ok,errors,skipped_existing,metadata_path
0,sd35_large,stabilityai/stable-diffusion-3.5-large,prueba_500chars_sd3.jsonl,50,50,0,0,/content/drive/MyDrive/Proyecto NLP y DL/Image...
1,sd35_large,stabilityai/stable-diffusion-3.5-large,prueba_1013chars_sd3_inicial.jsonl,50,50,0,0,/content/drive/MyDrive/Proyecto NLP y DL/Image...
2,sd35_large,stabilityai/stable-diffusion-3.5-large,prueba_1960chars_sd3_conResumen.jsonl,50,50,0,0,/content/drive/MyDrive/Proyecto NLP y DL/Image...
3,sd3_medium,stabilityai/stable-diffusion-3-medium-diffusers,prueba_500chars_sd3.jsonl,50,50,0,0,/content/drive/MyDrive/Proyecto NLP y DL/Image...
4,sd3_medium,stabilityai/stable-diffusion-3-medium-diffusers,prueba_1013chars_sd3_inicial.jsonl,50,50,0,0,/content/drive/MyDrive/Proyecto NLP y DL/Image...
5,sd3_medium,stabilityai/stable-diffusion-3-medium-diffusers,prueba_1960chars_sd3_conResumen.jsonl,50,50,0,0,/content/drive/MyDrive/Proyecto NLP y DL/Image...